fix: fixes an a11y bug in Alert component
Codecademy/client-modules pull request #1117
Opened 2020-11-01 13:29 UTC by saghdaey

## Overview

The Alert component's "TypeIcon" is purely decorative so this PR handles hiding the icon from screen readers.

This work is done as part of a ticket on the EGG board https://codecademy.atlassian.net/browse/EGG-168 which relates to https://codecademy.atlassian.net/browse/TR2-328 which mirror's this ticket: https://codecademy.atlassian.net/browse/A11Y-428

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: A11Y-428
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description
This bug came up in a11y testing for the "Linked Accounts" page in the monolith. Screen readers picked up the Icon in confirmation box, which is purely decorative. To fix, I've added the aria-hidden attribute to the icon in the Alert component. 

Note: this should fix other recorded a11y bugs that relate to the alert component and screen readers since the "TypeIcon" can be a checkmark for confirmation, an exclamation point for an error, etc..

2020-11-02 17:55 UTC, jcenglish approved these changes
Yaaay, I'm excited for this fix!

2020-11-02 17:58 UTC, JoshuaKGoldberg commented on packages/gamut/src/Alert/index.tsx
> +            <TypeIcon size={24} aria-hidden />
Is this icon not actually informative? I thought we'd want to include the _type_ of error (notice, warning, success, error, etc.) with the alert?

@jcenglish

2020-11-02 18:31 UTC, jcenglish commented on packages/gamut/src/Alert/index.tsx
> +            <TypeIcon size={24} aria-hidden />
Ooh, good point. I think it would be useful to do that, although it's not strictly necessary. Alternatively, we could change our alert text to be more informative in that way.

2020-11-02 18:52 UTC, JoshuaKGoldberg requested changes
My vote would be to make the aria label text for the image a readable prefix for the type of alert, such as `"Warning: "`.

2020-11-03 15:26 UTC, saghdaey commented
> My vote would be to make the aria label text for the image a readable prefix for the type of alert, such as `"Warning: "`.
these are the type options provided to the Alert --> 

 "BannerType {
  Notice = 'notice',
  Announcement = 'announcement',
  Error = 'error',
  Info = 'info',
  Success = 'success',
}" 

does that work? @JoshuaKGoldberg

2020-11-03 16:34 UTC, JoshuaKGoldberg commented
@saghdaey sounds good to me!

2020-11-03 19:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.7.1-alpha.fa9405.0<br/>@codecademy/gamut@16.4.1-alpha.fa9405.0<br/>@codecademy/styleguide@17.11.1-alpha.fa9405.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-03 19:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa1ae2bd21aa40c5b834db6--gamut-preview.netlify.app>https://5fa1ae2bd21aa40c5b834db6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa1ae2bd21aa40c5b834db6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-03 19:29 UTC, JoshuaKGoldberg approved these changes
Thanks!

2020-11-04 16:38 UTC, merged