[WIP] Start of base landing page component
Codecademy/client-modules pull request #1118
Opened 2020-11-02 14:16 UTC by judahtanthony

## Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description

2020-11-02 14:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1118) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1118) before we can accept your contribution.<br/><hr/>**Judah Anthony** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/client-modules?pullRequest=1118) it.</sub>

2020-11-04 23:03 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LPSection/Title.tsx
> +// Heading seems to not take className.
Err, it does: `HeadingProps` takes it from `ContainerElementProps`. What odd behavior are you seeing?

2020-11-04 23:03 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LPSection/Title.tsx
> +export const LPSectionTitle: React.FC<LPSectionTitleProps> = ({
I'm averse to including abbreviations that aren't super duper common across the industry, as they can make the code harder to read for people not already immersed in our particular structures. Can section be `LandingPage*` instead of `LP*`, please?

2020-11-04 23:04 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LPSection/Title.tsx
> +    }}
Oh man @codecaaron this is, like, a perfect example of a variant like your system is trying to solve, at the props level 😄

2020-11-04 23:06 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LPSection/CTA.tsx
> +  <CTA theme="hyper" href={href}>{children}</CTA>
Yeah the `theme` prop is a tricky one: it's somewhat reserved by Emotion. Hence this very bizarre [CI error](https://app.circleci.com/pipelines/github/Codecademy/client-modules/7636/workflows/c6fb3e3f-c021-47b4-a02c-27d3f2316542/jobs/44438):

```
$ tsc --emitDeclarationOnly
src/brand/LPSection/CTA.tsx(18,8): error TS2322: Type 'string' is not assignable to type 'undefined'.
```

You'll want to use some other name instead. `variant` is what I've been suggesting to folks.

2020-11-04 23:08 UTC, JoshuaKGoldberg requested changes
Glorious start! Nice to see usage of the new styled components and mdx stuff. I can take a deeper look once it builds 👍

2020-11-05 16:41 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LPSection/CTA.tsx
> +  <CTA theme="hyper" href={href}>{children}</CTA>
Oooohhh.  Thanks.  Should we update [Button](https://gamut.codecademy.com/storybook/?path=/docs/atoms-button--button) (which uses theme) to alias that prop?  I'm currently just letting Emotion to proxy all the props through.

2020-11-05 17:19 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LPSection/Title.tsx
> +// Heading seems to not take className.
Hmmm.  I don't know why I thought that.  It is not true.  I will remove this comment.

2020-11-05 17:19 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LPSection/Title.tsx
> +export const LPSectionTitle: React.FC<LPSectionTitleProps> = ({
Will do.

2020-11-05 17:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.6.3-alpha.462e37.0<br/>@codecademy/styleguide@17.10.4-alpha.462e37.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-05 17:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa438475d566e0a86eeaa91--gamut-preview.netlify.app>https://5fa438475d566e0a86eeaa91--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa438475d566e0a86eeaa91>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-05 17:43 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LPSection/CTA.tsx
> +  <CTA theme="hyper" href={href}>{children}</CTA>
Yeah I was thinking about doing that... we're about to deprecate it (https://github.com/codecademy-engineering/Codecademy/pull/20004 -> https://github.com/Codecademy/client-modules/pull/1069) so after that goes in I can send a `variant` prop alias.

2020-11-05 17:44 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LandingPageSection/CTA.tsx
> +const CTA = styled('div')`
⛳ ✨ 

```suggestion
const CTA = styled.div`
```

2020-11-05 17:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.6.3-alpha.ad8961.0<br/>@codecademy/styleguide@17.10.4-alpha.ad8961.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-05 17:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa43a5c23b839009f8de849--gamut-preview.netlify.app>https://5fa43a5c23b839009f8de849--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa43a5c23b839009f8de849>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-05 18:04 UTC, rogervera commented on packages/gamut-labs/src/brand/LandingPageSection/CTA.tsx
> +const CTA = styled('div')`
@JoshuaKGoldberg Birdie!

2020-11-05 18:15 UTC, rogervera commented on packages/gamut-labs/src/brand/LandingPageSection/Description.tsx
> +const Description = styled('div')`
Suggestion for `styled.div` same as https://github.com/Codecademy/client-modules/pull/1118/files#r518240948

2020-11-05 18:28 UTC, rogervera approved these changes
LGTM!
Per your post in Slack, I do agree that I see these more as atoms than organisms however.

2020-11-05 18:29 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LPSection/Title.tsx
> +// Heading seems to not take className.
removed.

2020-11-05 18:29 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LPSection/Title.tsx
> +export const LPSectionTitle: React.FC<LPSectionTitleProps> = ({
updated.

2020-11-05 18:30 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LPSection/CTA.tsx
> +  <CTA theme="hyper" href={href}>{children}</CTA>
For now I just wrapped the raw button.  So far we just need simple layout-y things.

2020-11-05 18:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.6.3-alpha.3789e0.0<br/>@codecademy/styleguide@17.10.4-alpha.3789e0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-05 18:31 UTC, judahtanthony commented
> Glorious start! Nice to see usage of the new styled components and mdx stuff. I can take a deeper look once it builds 👍

I think I have addressed all your concerns.

2020-11-05 18:31 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LandingPageSection/CTA.tsx
> +const CTA = styled('div')`
Updated.

2020-11-05 18:32 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LandingPageSection/Description.tsx
> +const Description = styled('div')`
Thanks.  Fixed.

2020-11-05 18:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa4452e662f63111b4c35c6--gamut-preview.netlify.app>https://5fa4452e662f63111b4c35c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa4452e662f63111b4c35c6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-05 18:33 UTC, judahtanthony commented
> LGTM!
> Per your post in Slack, I do agree that I see these more as atoms than organisms however.

100%
I ultimately would just like a LandingPageSection "gallery" for our marketers, so the shouldn't even see thing like "title" which they cannot directly choose.

2020-11-05 18:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.6.3-alpha.bb1432.0<br/>@codecademy/styleguide@17.10.4-alpha.bb1432.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-05 18:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa44855ccaccc104fc90c66--gamut-preview.netlify.app>https://5fa44855ccaccc104fc90c66--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa44855ccaccc104fc90c66>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-05 18:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.8.0-alpha.21fc6d.0<br/>@codecademy/styleguide@17.12.0-alpha.21fc6d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-05 18:52 UTC, JoshuaKGoldberg approved these changes
LGTM, with the caveats requested :)

2020-11-05 18:52 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LandingPageSection/CTA.tsx
> +    <Button theme="hyper" href={href}>
Just confirming: this is a _start_, right? Because this button is kind of useless without an `onClick` 😄 .

2020-11-05 18:52 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LandingPageSection/CTA.tsx
> +const CTA = styled.div`
Could you put the margin on the button? `styled(Button)`?

2020-11-05 18:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Brand/Organisms/LandingPageSectionTitle.stories.mdx
> +  title="Labs/Brand/Organisms/LandingPageSectionTitle"
I agree, these should really be atoms. You could always add an organism section afterwards for things that contain them, but these aren't it.

2020-11-05 18:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa44a12d9e83810d0af06e0--gamut-preview.netlify.app>https://5fa44a12d9e83810d0af06e0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa44a12d9e83810d0af06e0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-05 18:59 UTC, merged