REACH-377 add landing page hero gamut component
Codecademy/client-modules pull request #1161
Opened 2020-11-17 17:52 UTC by christian-dinh

## Overview

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/2aBlW1pgFt5PT6soRu1HXy/%E2%9C%8F%EF%B8%8F-Landing-Page-Templates---Unification?node-id=1%3A43
- [x] Related to JIRA ticket: REACH-377
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### Description
The designs use the shiny new `CTAButton`, and `ButtonDeprecated` has "deprecated" in the name so the first commit refactors `LandingPageSection/CTA` to use `CTAButton`. If that's out of scope for this ticket then nbd I can just remove the commit. The second commit makes the thing:

#### Screen size sm and above:
<img width="1141" alt="Screen Shot 2020-11-17 at 11 26 05 AM" src="https://user-images.githubusercontent.com/19958143/99426054-a9624e00-28d1-11eb-945c-0289f5eb52e7.png">

#### Screen size below sm:
<img width="580" alt="Screen Shot 2020-11-17 at 12 49 11 PM" src="https://user-images.githubusercontent.com/19958143/99427364-54273c00-28d3-11eb-8ca9-281becb42f83.png">

The storybook can be found in `lab/brand/molecules/LandingPageHero`

2020-11-17 17:55 UTC, christian-dinh commented on packages/gamut-labs/src/brand/LandingPageSection/CTA.tsx
> +    <CTAButton onClick={() => (window.location.href = href)}>
Storybook doesn't like this since it loads the component in an iframe. Not sure of a better way to do a redirect if we want to continue using a button (semantically this would actually be a link)

2020-11-17 17:57 UTC, christian-dinh commented on packages/gamut-labs/src/brand/LandingPageSection/Title.tsx
> +  margin: 0;
The title appears at the top in all the components that will use it, so I got rid of the top margin

2020-11-17 17:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.4.0-alpha.64a4cc.0<br/>@codecademy/styleguide@18.6.0-alpha.64a4cc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-17 18:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb4102c202e6f74feeca380--gamut-preview.netlify.app>https://5fb4102c202e6f74feeca380--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb4102c202e6f74feeca380>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-17 18:22 UTC, rogervera commented on packages/gamut-labs/src/brand/LandingPageSection/CTA.tsx
> +    <CTAButton onClick={() => (window.location.href = href)}>
Tagging @JoshuaKGoldberg, author of https://github.com/Codecademy/client-modules/pull/1119 👋 

What's the new API to get the desired behavior like the old `href` prop?

https://github.com/Codecademy/client-modules/blob/b0e7c81dbf9ad29a5cccedb2798fa5105c49bff7/packages/gamut/src/ButtonDeprecatedBase/index.tsx#L73-L86

2020-11-17 19:15 UTC, rogervera commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +  width: 16.6%; // 2 columns in a 12 column layout
**Strong Suggestion**: I think I'd prefer having this component composed using `LayoutGrid`

On 
XL to M: left is 9 col, right is 3


Might be more power than it's worth, but at least it allows us to more easily layout the future "short" version, and if we ever add more to the Hero

2020-11-17 19:27 UTC, rogervera commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +
**Nit**: Figured why not add a `showCTA` var, and renamed for consistency. 

```suggestion
  const showImage = !!imgSrc;
  const showCTA = cta && ctaHref;
```

2020-11-17 19:33 UTC, christian-dinh commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +
`hasImg` was actually leftover from an earlier iteration, I can add `showCTA` and drop `hasImg` altogether since besides the cta everything else is just testing one prop if that looks ok:

<img width="694" alt="Screen Shot 2020-11-17 at 2 33 07 PM" src="https://user-images.githubusercontent.com/19958143/99438457-d4549e00-28e1-11eb-8724-10bee46614c0.png">

2020-11-17 19:42 UTC, rogervera commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +
>I can add showCTA and drop hasImg altogether since besides the cta everything else is just testing one prop (if that looks ok):

SGTM!

2020-11-17 19:58 UTC, rogervera reviewed
Looks good. I'd get Dev's eyes to look this over https://5fb4102c202e6f74feeca380--gamut-preview.netlify.app/storybook/?path=/story/labs-brand-molecules-landingpagehero--landing-page-hero if you haven't already!

2020-11-17 20:14 UTC, christian-dinh commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +
ok wow so there was actually a reason for doing `showCTA` inline. `href` is a required prop for `LandingPageSectionCTA` but it is optional in `LandingPageHero`. Typescript is not smart enough to realize that `LandingPageSectionCTA` will not be rendered without an `href` when `ctaHref` is used in a `const` 🤦‍♀️ 

That was probably a horrible explanation sorry lol, lmk if that makes sense

2020-11-17 20:15 UTC, rogervera requested changes
I'd like to hear from @Codecademy/web-platform regarding https://github.com/Codecademy/client-modules/pull/1161/files#r525386765. 🤔

I wouldn't want to set the standard for:
```tsx
onClick={() => (window.location.href = href)}
```
In practice, we typically like to use the onClick prop to fire data tracking.

2020-11-17 20:16 UTC, christian-dinh commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +
it makes sense to me that that behavior would exist with a `let` or `var` but I'm surprised it's also an issue with `const`

2020-11-17 20:17 UTC, rogervera commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +
I got what you meant. _But_, what about an FU to the compiler and do `href={ctaHref!}`?

2020-11-17 20:29 UTC, christian-dinh commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +
I'm newish to typescript and had to look up what that means 😅 

Personally since the expression is so short I'd probably rather just inline it. Even though that's totally a safe assertion it feels a lil naughty to me 😯

2020-11-17 20:31 UTC, rogervera commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +
Hehehe, good point. Resolved 👍

2020-11-17 20:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.4.0-alpha.34f2b4.0<br/>@codecademy/styleguide@18.6.0-alpha.34f2b4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-17 20:51 UTC, christian-dinh commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +  margin: 2rem 0;
oh one more thing to point out, I split up `margin` and `padding` here under the assumption that [margin collapse](https://www.w3schools.com/css/css_margin_collapse.asp) will be desirable, though relying on collapses can be a bit of a code smell. Not necessarily something that needs to be addressed now, taking it back is an easy fix and we'll know more as more components get added.

2020-11-17 20:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb437e87e2c83013e81d714--gamut-preview.netlify.app>https://5fb437e87e2c83013e81d714--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb437e87e2c83013e81d714>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-17 21:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.4.0-alpha.4f0577.0<br/>@codecademy/styleguide@18.6.0-alpha.4f0577.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-17 21:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb43ac4930a390153130905--gamut-preview.netlify.app>https://5fb43ac4930a390153130905--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb43ac4930a390153130905>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-18 19:32 UTC, judahtanthony commented on packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx
> +  <Layout>
Does Layout take `testId`?  It would be nice to have the wrapper use testId directly.

2020-11-19 15:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.5.0-alpha.4cd0f3.0<br/>@codecademy/styleguide@18.6.0-alpha.4cd0f3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-19 15:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb691993821c649291aded4--gamut-preview.netlify.app>https://5fb691993821c649291aded4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb691993821c649291aded4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-19 16:58 UTC, rogervera approved these changes
LGTM. Good point made in Slack about using ` ts-expect-error` to track down later. :shipit:

2020-11-19 17:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.5.0-alpha.7d7829.0<br/>@codecademy/styleguide@18.8.0-alpha.7d7829.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-19 17:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb6a90ad60af90c33c9f5b6--gamut-preview.netlify.app>https://5fb6a90ad60af90c33c9f5b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb6a90ad60af90c33c9f5b6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-19 17:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.5.0-alpha.b3c742.0<br/>@codecademy/styleguide@18.8.0-alpha.b3c742.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-19 17:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb6aa6ef864870ae555e058--gamut-preview.netlify.app>https://5fb6aa6ef864870ae555e058--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb6aa6ef864870ae555e058>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-19 18:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.5.0-alpha.ac5975.0<br/>@codecademy/styleguide@18.8.0-alpha.ac5975.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-19 18:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fb6b4c216741b17318e4809--gamut-preview.netlify.app>https://5fb6b4c216741b17318e4809--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fb6b4c216741b17318e4809>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-19 18:20 UTC, merged

2020-11-19 18:30 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/LandingPageSection/__tests__/LandingPageHero-test.tsx
> +    const wrapperNoHref = shallow(<LandingPageHero cta="test" />);
Heya @christian-dinh a couple of notes on this, sorry for not getting to the PR review in time 😞:
* We've been trying to use `mount` instead of `shallow` (or just RTL), since it's closer to RTL's behavior and better simulates the full component:
* Could you have one general area of assertions per unit test? Splitting them up gives us better granular indications of what's failing when something does.

https://www.notion.so/codecademy/JavaScript-Unit-Tests-6ccd870e0b1c4caea8ae6e07e088c9f9

2020-11-20 21:01 UTC, christian-dinh commented on packages/gamut-labs/src/brand/LandingPageSection/__tests__/LandingPageHero-test.tsx
> +    const wrapperNoHref = shallow(<LandingPageHero cta="test" />);
no worries, posthumous PR here: https://github.com/Codecademy/client-modules/pull/1177