fix: prevent VO from saying "group" for ProgressBar
Codecademy/client-modules pull request #1184
Opened 2020-11-23 20:28 UTC by natalieweesh

## Overview
previously the VoiceOver would say "Progress: 100%, group" on the progress bar, but this PR changes it to say "Progress: 100%" (without the "group")

it also needs the eslint-ignore because "text" is not officially an allowed aria role type -- even though it was proposed it was not accepted, but people use it for this workaround

see article:
https://blog.chrisworfolk.com/how-to-stop-voiceover-saying-the-word-group
and issue:
https://www.w3.org/WAI/ARIA/track/issues/435

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: EGG-487
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description

2020-11-23 20:31 UTC, JoshuaKGoldberg requested changes
If this doesn't fix it for all browsers, maybe there's another workaround?

2020-11-23 20:31 UTC, JoshuaKGoldberg commented on packages/gamut/src/ProgressBar/index.tsx
> +      role="text"
From the [linked article]():

> But it won’t fix it in some other browsers.

Have you investigated other things, like `aria-hidden`?

cc @jcenglish who probably has a more informed opinion than me 😄

2020-11-23 21:08 UTC, natalieweesh commented on packages/gamut/src/ProgressBar/index.tsx
> +      role="text"
would a better solution be to say "Progress: 100%, banner" or "figure" ? just use some other proper role other than "text" ?
i don't think using aria-hidden would work because we still need the voiceover to say "Progress: 100%"

2020-11-23 21:13 UTC, JoshuaKGoldberg commented on packages/gamut/src/ProgressBar/index.tsx
> +      role="text"
Ooh, `figure` does sound good... that's kind of what it is, I think?

For `hidden`, I meant a container element could have the label, then all its children that have text would be marked as hidden.

2020-11-24 16:26 UTC, natalieweesh commented on packages/gamut/src/ProgressBar/index.tsx
> +      role="text"
👌  updated to use role="figure" instead

2020-11-24 16:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.7.3-alpha.6fb463.0<br/>@codecademy/gamut@17.4.1-alpha.6fb463.0<br/>@codecademy/styleguide@18.10.2-alpha.6fb463.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-24 16:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fbd356c321ef334dbe4371e--gamut-preview.netlify.app>https://5fbd356c321ef334dbe4371e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fbd356c321ef334dbe4371e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-24 16:37 UTC, JoshuaKGoldberg approved these changes

2020-11-24 17:29 UTC, merged