feat(Styleguide): Add grid docs to storybook GM-118
Codecademy/client-modules pull request #1221
Opened 2020-12-08 14:43 UTC by codecaaron

### Overview

Adds a Foundations page specifically for grid.

* Adds a specific page for grid documentation on storybook and links back to figma.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/ZUJ7cfVgyoh1kiQYNN8Hbt/Grid-%E2%9C%85?node-id=307%3A4
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2020-12-08 14:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@21.1.1-alpha.e644c5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-12-08 14:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fcf924145a30de44a7a865a--gamut-preview.netlify.app>https://5fcf924145a30de44a7a865a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fcf924145a30de44a7a865a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-12-08 15:43 UTC, JoshuaKGoldberg commented on packages/styleguide/.storybook/components/FigmaLink.tsx
> +export const FigmaLink = ({ href }) => {
👀 ... nice.

2020-12-08 16:17 UTC, JoshuaKGoldberg requested changes
Great start! Just requesting clarification for the start of the page / major summary.

2020-12-08 16:17 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Core/Foundations/Grids/Grids.stories.mdx
> +These are the grids we use for all the screen sizes we design for. We use a 12-column grid approach, meaning every layout can be divided in sections of 2 or 3. It’s important to design with the in mi
```suggestion
These are the grids we use for all the screen sizes we design for.
We use a 12-column grid approach, meaning every layout can be divided in sections of 2 or 3.
It’s important to design with the grid in mind to create structured and consistent experiences.
On smaller screen sizes try to avoid using smaller components while using the grid as a guide.
```

2020-12-08 16:17 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Core/Foundations/Grids/Grids.stories.mdx
> +These are the grids we use for all the screen sizes we design for. We use a 12-column grid approach, meaning every layout can be divided in sections of 2 or 3. It’s important to design with the in mi
Also, I'm not understanding what that last sentence means. Could we remove it? Seems rather specific for an opening summary.

2020-12-08 16:17 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Core/Foundations/Grids/Grids.stories.mdx
> +### Screen sizes
Reading through this doc, I think it's missing a major summary of what a "Grid" actually _is_ before it goes into specifics of screen sizes, viewports, etc. Do you think you could post some high-level code samples with visualizations to start? Maybe even moving the last image in the page up here, with an explanation of how the grid is used in it?

2020-12-08 16:52 UTC, codecaaron commented on packages/styleguide/stories/Core/Foundations/Grids/Grids.stories.mdx
> +These are the grids we use for all the screen sizes we design for. We use a 12-column grid approach, meaning every layout can be divided in sections of 2 or 3. It’s important to design with the in mi
Should have mentioned that this is not purely just copy pasta of what is in figma. Let's ping Yassine to get some copy edits.

2021-01-19 18:25 UTC, codecaaron commented
Closing this in favor of a less customized approach.

2021-01-19 18:25 UTC, closed without merging