add beakPosition prop to Popover
Codecademy/client-modules pull request #1226
Opened 2020-12-10 07:23 UTC by sylvanasantos

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2020-12-10 07:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1226) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1226) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/client-modules?pullRequest=1226) it.</sub>

2020-12-10 07:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.1.5-alpha.a45bab.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-12-10 07:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd1ce7753c4b2903ce362d2--gamut-preview.netlify.app>https://5fd1ce7753c4b2903ce362d2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd1ce7753c4b2903ce362d2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-12-10 16:00 UTC, hmafzal approved these changes
LGTM!

2020-12-10 16:10 UTC, JoshuaKGoldberg requested changes
LGTM in general, but I think we can make the props interface a little cleaner. ✨

2020-12-10 16:10 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/Popover/index.tsx
> +  beakPosition?: 'left' | 'right';
In the current form, `beakPosition` is a "dependent" prop in that it can only exist if `showBeak` is true. That's a little redundant. How about removing `showBeak` as a prop altogether and only showing a beak if `beakPosition` is provided?

2020-12-10 16:16 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/Popover/index.tsx
> +  beakPosition?: 'left' | 'right';
Ooh, and how about just calling it `beak`?

2020-12-10 19:26 UTC, sylvanasantos commented on packages/gamut-labs/src/experimental/Popover/index.tsx
> +  beakPosition?: 'left' | 'right';
yes! this sounds great, i felt like it wasn't optimal but wasn't sure how to make it cleaner, thanks for the suggestion!

2020-12-10 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.2.1-alpha.c6fee0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-12-10 19:50 UTC, JoshuaKGoldberg approved these changes
Super! 😄

2020-12-10 19:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fd27c6c53c4b26e22e363cc--gamut-preview.netlify.app>https://5fd27c6c53c4b26e22e363cc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fd27c6c53c4b26e22e363cc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-12-10 20:44 UTC, merged

2020-12-11 00:16 UTC, sooinc commented
This is great, thanks Sylvana!