Ar theme system docs
Codecademy/client-modules pull request #1260
Opened 2020-12-28 00:24 UTC by codecaaron

### Overview

Storybook Block:
* Adds `DataTable` storybook block for configurable dynamic tables in MDX.
* Adds `ColorScale` block for a more compact and readable color scale to be used in `DataTable`.
* Adds `Box` and `Code` blocks for minor formatting.

Pages: 
* Removes `Layout` and `Typography` pages from foundations.
* Adds `Theme` page with all theme keys and scales documented.
* Adds Design Guidelines under Foundations.

System Props:
* Adds MDN link to all system properties.
* Adds link to `Theme` page for properties with a scale.

## Screenshots
<img width="1130" alt="Screen Shot 2020-12-27 at 6 50 07 PM" src="https://user-images.githubusercontent.com/52927224/103181940-be3ce480-4874-11eb-902b-77876d95a17a.png">
<img width="1082" alt="Screen Shot 2020-12-27 at 6 50 20 PM" src="https://user-images.githubusercontent.com/52927224/103181941-bed57b00-4874-11eb-90bc-ac7946baa7d3.png">
<img width="1153" alt="Screen Shot 2020-12-27 at 6 50 41 PM" src="https://user-images.githubusercontent.com/52927224/103181942-bed57b00-4874-11eb-8e1a-b9e66e62604f.png">
<img width="1049" alt="Screen Shot 2020-12-27 at 6 51 02 PM" src="https://user-images.githubusercontent.com/52927224/103181943-bf6e1180-4874-11eb-8a34-b6a6d352486a.png">

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2020-12-28 17:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.8-alpha.a4506c.0<br/>@codecademy/gamut-labs@7.6.4-alpha.a4506c.0<br/>@codecademy/gamut-styles@7.6.3-alpha.a4506c.0<br/>@codecademy/gamut@19.8.1-alpha.a4506c.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.a4506c.0<br/>@codecademy/styleguide@21.6.6-alpha.a4506c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-12-28 17:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fea17f911f328a030c9cd3f--gamut-preview.netlify.app>https://5fea17f911f328a030c9cd3f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fea17f911f328a030c9cd3f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-12-29 19:22 UTC, JoshuaKGoldberg requested changes
TBH I'm not a huge fan of the new colors format. It's not very visually dense so it's hard to scan through and see all the colors together. As you noted, it's also got less information in it, and you can't shortcut find through it. Maybe we can work together on a happy medium?

2020-12-29 19:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Core/Foundations/Legacy/Colors/Colors.stories.mdx
> +<Meta title="Foundations/Legacy/Colors" component="Colors" />
If these are now Legacy, should they be marked as Deprecated?

2020-12-29 19:24 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Core/Foundations/Legacy/Colors/Colors.stories.mdx
> +<Meta title="Foundations/Legacy/Colors" component="Colors" />
Oh, and the root-level About page's link will need to be updated.

2021-01-04 16:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.8-alpha.047891.0<br/>@codecademy/gamut-labs@7.6.4-alpha.047891.0<br/>@codecademy/gamut-styles@7.6.3-alpha.047891.0<br/>@codecademy/gamut@19.8.1-alpha.047891.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.047891.0<br/>@codecademy/styleguide@21.7.1-alpha.047891.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-04 16:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.8-alpha.60a67d.0<br/>@codecademy/gamut-labs@7.6.4-alpha.60a67d.0<br/>@codecademy/gamut-styles@7.6.3-alpha.60a67d.0<br/>@codecademy/gamut@19.8.1-alpha.60a67d.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.60a67d.0<br/>@codecademy/styleguide@21.7.1-alpha.60a67d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-04 17:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff349f06d36d868cbbbf68c--gamut-preview.netlify.app>https://5ff349f06d36d868cbbbf68c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff349f06d36d868cbbbf68c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-04 17:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.8-alpha.d7ced6.0<br/>@codecademy/gamut-labs@7.6.4-alpha.d7ced6.0<br/>@codecademy/gamut-styles@7.6.3-alpha.d7ced6.0<br/>@codecademy/gamut@19.8.1-alpha.d7ced6.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.d7ced6.0<br/>@codecademy/styleguide@21.7.1-alpha.d7ced6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-04 17:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff34d6f2b1aba545c00d3c2--gamut-preview.netlify.app>https://5ff34d6f2b1aba545c00d3c2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff34d6f2b1aba545c00d3c2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-04 17:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.8-alpha.ff1084.0<br/>@codecademy/gamut-labs@7.6.4-alpha.ff1084.0<br/>@codecademy/gamut-styles@7.6.3-alpha.ff1084.0<br/>@codecademy/gamut@19.8.1-alpha.ff1084.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.ff1084.0<br/>@codecademy/styleguide@21.7.1-alpha.ff1084.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-04 17:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff350d50bb4806dcc57ef57--gamut-preview.netlify.app>https://5ff350d50bb4806dcc57ef57--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff350d50bb4806dcc57ef57>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-06 17:18 UTC, codecaaron commented on packages/styleguide/stories/Core/Foundations/Theme/tables.tsx
> +      render: ({ id }: any) => <Code>theme.colors.{id}</Code>,
Good call, I added some styling the `Code` element to account for the space and persist an X scroll bar that is transparent, but will have a thumb if there is overflow.

2021-01-06 17:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.8-alpha.c58f86.0<br/>@codecademy/gamut-labs@7.6.4-alpha.c58f86.0<br/>@codecademy/gamut-styles@7.6.3-alpha.c58f86.0<br/>@codecademy/gamut@19.8.1-alpha.c58f86.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.c58f86.0<br/>@codecademy/styleguide@21.7.1-alpha.c58f86.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-06 17:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff5f1e035901d008796fe7f--gamut-preview.netlify.app>https://5ff5f1e035901d008796fe7f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff5f1e035901d008796fe7f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-06 18:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.8-alpha.ad3dfb.0<br/>@codecademy/gamut-labs@7.6.4-alpha.ad3dfb.0<br/>@codecademy/gamut-styles@7.6.3-alpha.ad3dfb.0<br/>@codecademy/gamut@19.8.1-alpha.ad3dfb.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.ad3dfb.0<br/>@codecademy/styleguide@21.7.1-alpha.ad3dfb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-06 18:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff5fd7735901d08919709cd--gamut-preview.netlify.app>https://5ff5fd7735901d08919709cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff5fd7735901d08919709cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-07 15:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.8-alpha.f40fee.0<br/>@codecademy/gamut-labs@7.6.4-alpha.f40fee.0<br/>@codecademy/gamut-styles@7.6.3-alpha.f40fee.0<br/>@codecademy/gamut@19.8.1-alpha.f40fee.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.f40fee.0<br/>@codecademy/styleguide@21.7.1-alpha.f40fee.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-07 15:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff727b20f0cb91b4327beee--gamut-preview.netlify.app>https://5ff727b20f0cb91b4327beee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff727b20f0cb91b4327beee>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-11 19:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.13-alpha.059ace.0<br/>@codecademy/gamut-labs@7.7.3-alpha.059ace.0<br/>@codecademy/gamut-styles@7.6.3-alpha.059ace.0<br/>@codecademy/gamut@19.9.3-alpha.059ace.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.059ace.0<br/>@codecademy/styleguide@21.9.1-alpha.059ace.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-11 19:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffca5873fbaad18f53b56b6--gamut-preview.netlify.app>https://5ffca5873fbaad18f53b56b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffca5873fbaad18f53b56b6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-11 19:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.13-alpha.2588de.0<br/>@codecademy/gamut-labs@7.7.3-alpha.2588de.0<br/>@codecademy/gamut-styles@7.6.3-alpha.2588de.0<br/>@codecademy/gamut@19.9.3-alpha.2588de.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.2588de.0<br/>@codecademy/styleguide@21.9.1-alpha.2588de.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-11 19:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffca8537cfa2d169a8557fe--gamut-preview.netlify.app>https://5ffca8537cfa2d169a8557fe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffca8537cfa2d169a8557fe>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-19 21:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.6-alpha.4081d4.0<br/>@codecademy/gamut-labs@7.10.6-alpha.4081d4.0<br/>@codecademy/gamut-styles@7.6.3-alpha.4081d4.0<br/>@codecademy/gamut@19.11.2-alpha.4081d4.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.4081d4.0<br/>@codecademy/styleguide@21.15.3-alpha.4081d4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-19 21:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.6-alpha.f30ed1.0<br/>@codecademy/gamut-labs@7.10.6-alpha.f30ed1.0<br/>@codecademy/gamut-styles@7.6.3-alpha.f30ed1.0<br/>@codecademy/gamut@19.11.2-alpha.f30ed1.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.f30ed1.0<br/>@codecademy/styleguide@21.15.3-alpha.f30ed1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-19 21:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60074e61158b491acbcabb1a--gamut-preview.netlify.app>https://60074e61158b491acbcabb1a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60074e61158b491acbcabb1a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-19 22:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.6-alpha.06378b.0<br/>@codecademy/gamut-labs@7.10.6-alpha.06378b.0<br/>@codecademy/gamut-styles@7.6.3-alpha.06378b.0<br/>@codecademy/gamut@19.11.2-alpha.06378b.0<br/>@codecademy/markdown-overrides@0.4.3-alpha.06378b.0<br/>@codecademy/styleguide@21.15.3-alpha.06378b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-19 22:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600759cb3089c71f77b2260f--gamut-preview.netlify.app>https://600759cb3089c71f77b2260f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600759cb3089c71f77b2260f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-22 23:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.8-alpha.15ff4d.0<br/>@codecademy/gamut-labs@7.13.2-alpha.15ff4d.0<br/>@codecademy/gamut-styles@7.6.4-alpha.15ff4d.0<br/>@codecademy/gamut@19.11.4-alpha.15ff4d.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.15ff4d.0<br/>@codecademy/styleguide@21.18.2-alpha.15ff4d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-22 23:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600b632de75f9a5967a887ab--gamut-preview.netlify.app>https://600b632de75f9a5967a887ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600b632de75f9a5967a887ab>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-25 19:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.9-alpha.1fab3e.0<br/>@codecademy/gamut-labs@7.13.3-alpha.1fab3e.0<br/>@codecademy/gamut-styles@7.6.4-alpha.1fab3e.0<br/>@codecademy/gamut@19.11.5-alpha.1fab3e.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.1fab3e.0<br/>@codecademy/styleguide@21.20.1-alpha.1fab3e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-25 19:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600f1701a63a210b9f7fc2dc--gamut-preview.netlify.app>https://600f1701a63a210b9f7fc2dc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600f1701a63a210b9f7fc2dc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-25 19:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600f1d0675c5af122233464a--gamut-preview.netlify.app>https://600f1d0675c5af122233464a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600f1d0675c5af122233464a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-25 19:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.9-alpha.359b3b.0<br/>@codecademy/gamut-labs@7.13.3-alpha.359b3b.0<br/>@codecademy/gamut-styles@7.6.4-alpha.359b3b.0<br/>@codecademy/gamut@19.11.5-alpha.359b3b.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.359b3b.0<br/>@codecademy/styleguide@21.20.1-alpha.359b3b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-26 16:13 UTC, dreamwasp approved these changes
so cool, and definitely serves as a good intro to our design system + gamut in general! ✨

2021-01-26 16:13 UTC, dreamwasp commented on packages/styleguide/stories/Foundations/Theme/index.stories.mdx
> +All current visual identity colors are available on the `colors` key on the Theme object, this includes named standard colors and their respective swatches. This object will not include older or more
*access

2021-01-26 16:13 UTC, dreamwasp commented on packages/styleguide/stories/Foundations/Theme/index.stories.mdx
> +### Spacing
this may be only tangentially related to this PR, but is there a way to get these sub-categories to show up on search?

2021-01-27 16:45 UTC, codecaaron commented on packages/styleguide/stories/Foundations/Theme/index.stories.mdx
> +### Spacing
I'm not sure if this is possible :(

Base line we would need to add a separate story for `Theme/spacing` and then reference the stories on the index page by ID.  I think what would happen is the links would go to the sub page rather than the reference in the main page.

2021-01-27 16:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.10-alpha.01d888.0<br/>@codecademy/gamut-labs@7.14.1-alpha.01d888.0<br/>@codecademy/gamut-styles@7.6.4-alpha.01d888.0<br/>@codecademy/gamut@19.11.6-alpha.01d888.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.01d888.0<br/>@codecademy/styleguide@21.21.1-alpha.01d888.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 16:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60119a69101bb484f92adf54--gamut-preview.netlify.app>https://60119a69101bb484f92adf54--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60119a69101bb484f92adf54>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 17:41 UTC, jakemhiller approved these changes
This is a huge improvement, nice work!

2021-01-27 18:40 UTC, codecaaron commented on packages/styleguide/stories/Core/Foundations/Legacy/Colors/Colors.stories.mdx
> +<Meta title="Foundations/Legacy/Colors" component="Colors" />
This change as been removed.

2021-01-27 18:47 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/Theme/tables.tsx
> +    VALUE_COLUMN,
There's a good bit of extra space to the right despite this column getting scrunched. Maybe it'd be good to expand it a bit? Make it fill remaining width, even?

![Screenshot of the Family table with the Value column squished](https://user-images.githubusercontent.com/3335181/106038505-08003100-60a6-11eb-9452-7dd270843187.png)

2021-01-27 18:51 UTC, JoshuaKGoldberg requested changes
I've warmed up to the single color per row approach 😄 , especially since the swatches look really nice on their rows as-is... This mostly looks fantastic to me, just requesting changes on clarifying the two color docs pages?

2021-01-27 18:51 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/Theme/tables.tsx
> +    VALUE_COLUMN,
There's a good bit of extra space to the right despite this column getting scrunched. Maybe it'd be good to expand it a bit? Make it fill remaining width, even?

![Screenshot of the Family table with the Value column squished](https://user-images.githubusercontent.com/3335181/106038505-08003100-60a6-11eb-9452-7dd270843187.png)

2021-01-27 18:51 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/Theme/index.stories.mdx
> +    subtitle: 'The emotion theme for codecademy',
Nittiest of the nits: here and elsewhere? 

```suggestion
    subtitle: 'The Emotion theme for codecademy',
```

2021-01-27 18:51 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/Theme/index.stories.mdx
> +Or by importing the object from "gamut-styles" if you are not using a `ThemeProvider` in your app.
```suggestion
Or by importing the object from `@codecademy/gamut-styles` if you are not using a `ThemeProvider` in your app.
```

2021-01-27 18:51 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/Theme/index.stories.mdx
> +All current visual identity colors are available on the `colors` key on the Theme object, this includes named standard colors and their respective swatches. This object will not include older or more
```suggestion
All current visual identity colors are available on the `colors` key on the Theme object, this includes named standard colors and their respective swatches. This object will not include older or more specific design tokens; if you need to access these color variables please check out the [full colors documentation](/?path=/docs/foundations-colors--standard)
```

2021-01-27 18:51 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/Theme/index.stories.mdx
> +    status: 'volatile',
It feels like this page is stable, and the old Colors one is now deprecated. I think it'd be confusing to have both exist and the newer one be marked as volatile. Could you add a deprecation notice & explanation in the old Colors.mdx as part of this PR?

![Screenshot of the Volatile notice on top of the Theme story page](https://user-images.githubusercontent.com/3335181/106039054-a68c9200-60a6-11eb-9677-89537459b58e.png)

2021-01-27 20:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.12-alpha.7d5943.0<br/>@codecademy/gamut-labs@7.14.3-alpha.7d5943.0<br/>@codecademy/gamut-styles@7.6.4-alpha.7d5943.0<br/>@codecademy/gamut@19.11.8-alpha.7d5943.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.7d5943.0<br/>@codecademy/styleguide@21.22.2-alpha.7d5943.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 20:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011c7f393030b9d87615539--gamut-preview.netlify.app>https://6011c7f393030b9d87615539--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011c7f393030b9d87615539>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-28 22:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.17-alpha.6b42b2.0<br/>@codecademy/gamut-labs@7.16.5-alpha.6b42b2.0<br/>@codecademy/gamut-styles@7.6.4-alpha.6b42b2.0<br/>@codecademy/gamut@20.0.4-alpha.6b42b2.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.6b42b2.0<br/>@codecademy/styleguide@22.0.4-alpha.6b42b2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-28 22:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60133e49362e6b0bdf4a7d3c--gamut-preview.netlify.app>https://60133e49362e6b0bdf4a7d3c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60133e49362e6b0bdf4a7d3c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-28 22:54 UTC, JoshuaKGoldberg approved these changes
Love it. Ship!! 🌮 🚀

2021-01-28 22:54 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/Colors/index.stories.mdx
> +**Deprecation Notice** These variables and access patterns are now deprecated please refer to [Theme](?path=/docs/foundations-theme--colors) for the most up to date documentation when using the new v
```suggestion
**Deprecation Notice** These variables and access patterns are now deprecated. Please refer to [Theme](?path=/docs/foundations-theme--colors) for the most up to date documentation when using the new visual identity.
```

2021-01-28 23:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601344981171eb0ddc1165a1--gamut-preview.netlify.app>https://601344981171eb0ddc1165a1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601344981171eb0ddc1165a1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-28 23:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.17-alpha.647d8a.0<br/>@codecademy/gamut-labs@7.16.5-alpha.647d8a.0<br/>@codecademy/gamut-styles@7.6.4-alpha.647d8a.0<br/>@codecademy/gamut@20.0.4-alpha.647d8a.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.647d8a.0<br/>@codecademy/styleguide@22.0.4-alpha.647d8a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-29 18:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.18-alpha.864121.0<br/>@codecademy/gamut-labs@8.0.2-alpha.864121.0<br/>@codecademy/gamut-styles@7.6.4-alpha.864121.0<br/>@codecademy/gamut@20.0.5-alpha.864121.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.864121.0<br/>@codecademy/styleguide@23.0.2-alpha.864121.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-29 18:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601459f92f73a900b3dc801c--gamut-preview.netlify.app>https://601459f92f73a900b3dc801c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601459f92f73a900b3dc801c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-29 18:56 UTC, merged