POC: SVG Patterns
Codecademy/client-modules pull request #1271
Opened 2021-01-07 16:25 UTC by natalieweesh

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-01-07 19:00 UTC, JoshuaKGoldberg commented on packages/gamut/src/ProgressBar/index.tsx
> +          height={36}
Doesn't look like these sizes are adaptive the way the rest of the progress bar is. 

I can review more deeply once the deploy is going through, just a hunch for now. 😄

2021-01-08 22:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.13-alpha.268e62.0<br/>@codecademy/gamut-labs@7.7.3-alpha.268e62.0<br/>@codecademy/gamut@19.9.3-alpha.268e62.0<br/>@codecademy/styleguide@21.8.3-alpha.268e62.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-08 22:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff8dd84e0e7ce1ef14abb2a--gamut-preview.netlify.app>https://5ff8dd84e0e7ce1ef14abb2a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff8dd84e0e7ce1ef14abb2a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-08 22:36 UTC, JoshuaKGoldberg requested changes

2021-01-08 22:36 UTC, JoshuaKGoldberg commented on packages/gamut/src/Pattern/index.tsx
> +        <pattern
So right now this component declares all the possible patterns it could use, then tells itself to render a single one by `id`. Can it only render what it needs based on the `name` prop?

2021-01-08 22:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.13-alpha.324c48.0<br/>@codecademy/gamut-labs@7.7.3-alpha.324c48.0<br/>@codecademy/gamut@19.9.3-alpha.324c48.0<br/>@codecademy/styleguide@21.8.3-alpha.324c48.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-08 22:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff8df93c3e2a81ccdbbf8fc--gamut-preview.netlify.app>https://5ff8df93c3e2a81ccdbbf8fc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff8df93c3e2a81ccdbbf8fc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-09 03:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ff922eb0b76293dab030bae--gamut-preview.netlify.app>https://5ff922eb0b76293dab030bae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ff922eb0b76293dab030bae>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-09 03:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.13-alpha.4e8058.0<br/>@codecademy/gamut-labs@7.7.3-alpha.4e8058.0<br/>@codecademy/gamut@19.9.3-alpha.4e8058.0<br/>@codecademy/styleguide@21.8.3-alpha.4e8058.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-11 19:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.13-alpha.0b848c.0<br/>@codecademy/gamut-labs@7.7.3-alpha.0b848c.0<br/>@codecademy/gamut@19.9.3-alpha.0b848c.0<br/>@codecademy/styleguide@21.9.1-alpha.0b848c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-11 19:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffcab7a012c2e00c40a176a--gamut-preview.netlify.app>https://5ffcab7a012c2e00c40a176a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffcab7a012c2e00c40a176a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-12 15:31 UTC, JoshuaKGoldberg approved these changes
Great, lgtm!

2021-01-12 15:31 UTC, JoshuaKGoldberg commented on packages/gamut/src/Pattern/index.tsx
> +  </div>
This component is a little large; you might consider moving the pattern definitions to separate component? Definitely a preference choice and non-blocking 😄.

2021-01-12 15:32 UTC, JoshuaKGoldberg commented on packages/gamut/src/ProgressBar/index.tsx
> +          height={36}
Amusing that it works as expected right now, but this feels reasonable?

```suggestion
          height={height}
```

2021-01-12 15:32 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Core/Atoms/ProgressBar/ProgressBar.stories.mdx
> +Using the new SVG Pattern component for a striped background. Here we are using the DiagonalStripesRegular Pattern in \$color-navy.
![Screenshot of storybook with \$color-navy](https://user-images.githubusercontent.com/3335181/104335574-7e573d80-54c1-11eb-8481-d3e72032f934.png)

```suggestion
Using the new SVG Pattern component for a striped background. Here we are using the DiagonalStripesRegular Pattern in navy.
```

2021-01-12 15:41 UTC, codecaaron reviewed
This looks great, but I'd love to utilize some of the building blocks with this to make it even more flexible.

Let me know if you have time today and we can pair to get it done!

2021-01-12 15:41 UTC, codecaaron commented on packages/gamut/src/Pattern/index.tsx
> +  <div className={className}>
Could we use `Box` as the wrapper for this with some configurations and have the props be forwarded to this?

https://gamut.codecademy.com/storybook/?path=/docs/layouts-box--box

Im more than happy to pair on that today!

2021-01-12 17:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.13-alpha.76c5e2.0<br/>@codecademy/gamut-labs@7.7.3-alpha.76c5e2.0<br/>@codecademy/gamut@19.9.3-alpha.76c5e2.0<br/>@codecademy/styleguide@21.9.1-alpha.76c5e2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-12 17:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffdd7b7790ebf409d3b2d12--gamut-preview.netlify.app>https://5ffdd7b7790ebf409d3b2d12--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffdd7b7790ebf409d3b2d12>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-12 17:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.3.13-alpha.5be5d1.0<br/>@codecademy/gamut-labs@7.7.3-alpha.5be5d1.0<br/>@codecademy/gamut@19.9.3-alpha.5be5d1.0<br/>@codecademy/styleguide@21.9.1-alpha.5be5d1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-12 17:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffddc2859dbe94d0059aad4--gamut-preview.netlify.app>https://5ffddc2859dbe94d0059aad4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffddc2859dbe94d0059aad4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-12 17:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.1-alpha.6c0de2.0<br/>@codecademy/gamut-labs@7.7.4-alpha.6c0de2.0<br/>@codecademy/gamut@19.9.4-alpha.6c0de2.0<br/>@codecademy/styleguide@21.9.2-alpha.6c0de2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-12 17:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffde3408355f00098d7b4ff--gamut-preview.netlify.app>https://5ffde3408355f00098d7b4ff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffde3408355f00098d7b4ff>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-12 18:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.1-alpha.747536.0<br/>@codecademy/gamut-labs@7.7.4-alpha.747536.0<br/>@codecademy/gamut@19.9.4-alpha.747536.0<br/>@codecademy/styleguide@21.9.2-alpha.747536.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-12 18:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffdef39479ce408114d9f21--gamut-preview.netlify.app>https://5ffdef39479ce408114d9f21--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffdef39479ce408114d9f21>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-12 20:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.1-alpha.e8f921.0<br/>@codecademy/gamut-labs@7.7.4-alpha.e8f921.0<br/>@codecademy/gamut@19.9.4-alpha.e8f921.0<br/>@codecademy/styleguide@21.9.2-alpha.e8f921.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-12 20:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5ffe038489b09a0d0225d5cd--gamut-preview.netlify.app>https://5ffe038489b09a0d0225d5cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5ffe038489b09a0d0225d5cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-12 22:40 UTC, codecaaron approved these changes

2021-01-13 13:49 UTC, merged