Cs jg jn ms form scss
Codecademy/client-modules pull request #1280
Opened 2021-01-14 14:54 UTC by jenesh

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-01-14 14:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1280) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1280) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: JoshuaKGoldberg<br/>:white_check_mark: dreamwasp<br/>:white_check_mark: jenesh<br/>:x: MattSchiller<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/client-modules?pullRequest=1280) it.</sub>

2021-01-14 18:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.2-alpha.d17f7e.0<br/>@codecademy/gamut-labs@7.7.5-alpha.d17f7e.0<br/>@codecademy/gamut@19.10.1-alpha.d17f7e.0<br/>@codecademy/styleguide@21.10.1-alpha.d17f7e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-14 18:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60008d16d8ba8a262faa85cf--gamut-preview.netlify.app>https://60008d16d8ba8a262faa85cf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60008d16d8ba8a262faa85cf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-14 18:47 UTC, codecaaron commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> +`;
```suggestion
const StyledFormGroup = styled(FormGroup)`
  margin-bottom: 0;
  
  // This is always the input
  > *:last-child {
   width: 100%;
  }
  
  ${FormGroupLabel} {
    display: inline-block;
    margin-right: 0.5rem;
   }
`;
```
Since these components are not used outside of this content it may make sense for us to let this wrapper instruct its direct descendant to be 100%.

2021-01-14 18:47 UTC, codecaaron commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +`;
Nice!  We actually have a utility for this through gamut-styles: 
```tsx
import { grid } from '@codecademy/gamut-styles';

const StyledColumn = styled(Column)(grid);
```

If you've got time I'd love to pair on refactoring it or maybe just adding it directly to `Column`!

2021-01-14 18:47 UTC, codecaaron commented on packages/gamut/src/HiddenText/index.tsx
> +export const HiddenText = styled.span<{ htmlFor?: string }>`
I think this probably isn't doing anything semantically for a span element.  Using `as="label"` on the hidden text component should let it pass through. 

Also I'm not sure that the prop will get correctly forwarded as `for`, since the prop forwarding for emotion is a bit different.

2021-01-14 21:00 UTC, jenesh commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +`;
Seems to be giving an error.

<img width="612" alt="Screen Shot 2021-01-14 at 4 00 05 PM" src="https://user-images.githubusercontent.com/47792836/104648734-92e23400-5681-11eb-8fd5-534f35b8952b.png">

2021-01-14 21:03 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> +`;
Haha I was actually going to suggest a different approach:

```suggestion
const StyledFormGroup = styled(FormGroup)`
  margin-bottom: 0;
`;

const inputStyles = `width: 100%`;

const StyledGridFormCheckboxInput = styled(GridFormCheckboxInput)(inputStyles)(inputStyles);
const StyledGridFormCustomInput = styled(GridFormCustomInput)(inputStyles);
const StyledGridFormFileInput = styled(GridFormFileInput)(inputStyles);
const StyledGridFormRadioGroupInput = styled(GridFormRadioGroupInput)(inputStyles);
const StyledGridFormSelectInput = styled(GridFormSelectInput)(inputStyles);
const StyledGridFormTextArea = styled(GridFormTextArea)(inputStyles);
const StyledGridFormTextInput = styled(GridFormTextInput)(inputStyles);

const StyledFormGroupLabel = styled(FormGroupLabel)`
  display: inline-block;
  margin-right: 0.5rem;
`;
```

...no preference from me.

2021-01-14 21:12 UTC, jenesh commented on packages/gamut/src/HiddenText/index.tsx
> +export const HiddenText = styled.span<{ htmlFor?: string }>`
Hmm so you're saying it's safe to remove `htmlFor` from the component itself? 

```
<HiddenText as="label">
    {props.field.label}
</HiddenText>
```

2021-01-14 21:18 UTC, jenesh commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> +`;
ooh that looks clean but went with the fancy css selector instead this time around.

2021-01-14 21:26 UTC, codecaaron commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +`;
Have you run `yarn build-all` recently?

2021-01-14 23:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.2-alpha.321174.0<br/>@codecademy/gamut-labs@7.7.5-alpha.321174.0<br/>@codecademy/gamut@19.10.1-alpha.321174.0<br/>@codecademy/styleguide@21.10.1-alpha.321174.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-14 23:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6000d39b1287b90c7b7b05ec--gamut-preview.netlify.app>https://6000d39b1287b90c7b7b05ec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6000d39b1287b90c7b7b05ec>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-15 17:58 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/styles/Checkbox.module.scss
>      left: -2px;
This file is unused now, 🔪 ❓

2021-01-15 17:58 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Checkbox.tsx
> +// Maybe ScreenReaderFocusable
So this ended up being just `screenReaderOnly`?

2021-01-15 18:18 UTC, jenesh commented on packages/gamut/src/Form/styles/Checkbox.module.scss
>      left: -2px;
That file is now in a happier place.

2021-01-15 18:22 UTC, JoshuaKGoldberg requested changes
LGTM, thanks for taking this on! I played with the storybook and they're just as snazzy as before. Just requesting  changes on file deletion :)

2021-01-15 18:22 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/__tests__/Checkbox-test.tsx
> +    const onChangeCallback = jest.fn();
Teeny tiny non-blocking nit: "callback" is implied by the "on change" name, type being a function, and its usage as a function prop.

```suggestion
    const onChange = jest.fn();
```

2021-01-15 18:22 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/__tests__/Checkbox-test.tsx
> -    expect(wrapper.find('input[type="checkbox"]').prop('checked')).toEqual(
Haha, this is why we've moved away from `shallow`... switching the tests to `mount` would be nice, but definitely not required in this PR.

2021-01-15 18:49 UTC, jenesh commented on packages/gamut/src/Form/Checkbox.tsx
> +// Maybe ScreenReaderFocusable
Not sure how to test/confirm this but should I keep it as is?

2021-01-15 18:56 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Checkbox.tsx
> +// Maybe ScreenReaderFocusable
https://www.notion.so/codecademy/Accessibility-b0984f0b97a640bc80b7365037d3044e#a12d8b37b7c44b4e9629436bb559dc48 might be what you're looking for? If not, let me know where you're stuck and I can help :)

2021-01-15 19:38 UTC, JoshuaKGoldberg approved these changes
🌮

2021-01-15 19:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.2-alpha.dc2908.0<br/>@codecademy/gamut-labs@7.7.5-alpha.dc2908.0<br/>@codecademy/gamut@19.10.1-alpha.dc2908.0<br/>@codecademy/styleguide@21.10.1-alpha.dc2908.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-15 19:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6001f03741da72010fcb84a9--gamut-preview.netlify.app>https://6001f03741da72010fcb84a9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6001f03741da72010fcb84a9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-15 20:36 UTC, jenesh commented on packages/gamut/src/Form/Checkbox.tsx
> +      ${Polyline} {
I tried messing around but I would think if someone wrote all this out it might have been needed. 🤷

2021-01-15 20:38 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Checkbox.tsx
> +      ${Polyline} {
It might have previously been necessary, maybe with SCSS, or maybe just temporarily when it was originally written (and not in the final product). Or maybe it was a style preference on their end that we no longer agree with. Its existence does not guarantee necessity 😄

2021-01-15 20:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.2-alpha.788dca.0<br/>@codecademy/gamut-labs@7.10.1-alpha.788dca.0<br/>@codecademy/gamut@19.10.1-alpha.788dca.0<br/>@codecademy/styleguide@21.13.1-alpha.788dca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-15 20:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6001ff1f258b5f0d6a6d0226--gamut-preview.netlify.app>https://6001ff1f258b5f0d6a6d0226--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6001ff1f258b5f0d6a6d0226>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-18 23:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.3-alpha.3e4637.0<br/>@codecademy/gamut-labs@7.10.3-alpha.3e4637.0<br/>@codecademy/gamut@19.10.2-alpha.3e4637.0<br/>@codecademy/styleguide@21.14.1-alpha.3e4637.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-18 23:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600613d19d07520f0f2e9d48--gamut-preview.netlify.app>https://600613d19d07520f0f2e9d48--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600613d19d07520f0f2e9d48>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-18 23:10 UTC, merged