feat(AppHeader): add AppHeader component
Codecademy/client-modules pull request #1300
Opened 2021-01-20 14:53 UTC by katiezutter

### Overview

Create AppHeaderDropdown component to be part of AppHeaderElements.

![image](https://user-images.githubusercontent.com/14988121/105191153-60f72480-5afc-11eb-9434-0f5605d5ccef.png)

Part of the [Global Nav Unification](https://codecademy.atlassian.net/browse/EGG-642) project.

This PR comes after [EGG-539](https://codecademy.atlassian.net/browse/EGG-539) and [EGG-540](https://codecademy.atlassian.net/browse/EGG-540), work done with @saghdaey which resulted in a [draft PR combining all GlobalHeader work](https://github.com/Codecademy/client-modules/pull/1265). We are now breaking up this branch to merge the following pieces separately:

1. [EGG-643](https://codecademy.atlassian.net/browse/EGG-643): AppHeaderLogo (#1277)
2. [EGG-644](https://codecademy.atlassian.net/browse/EGG-644): AppHeaderLink (#1278)
3. [EGG-645](https://codecademy.atlassian.net/browse/EGG-645): AppHeaderDropdown (#1279)
4. [EGG-646](https://codecademy.atlassian.net/browse/EGG-646): AppHeader
5. [EGG-647](https://codecademy.atlassian.net/browse/EGG-647): GlobalHeader

This PR adds unit tests to AppHeaderDropdown.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EGG-646](https://codecademy.atlassian.net/browse/EGG-646)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

2021-01-20 14:56 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +  color: ${({ theme }) => theme.colors.navy};
I had to change the way we were passing in `theme` here to get the focus outline the way we wanted it to be. Anyone know why the new focus styles were being overridden until we passed `theme` in inline?

2021-01-20 14:57 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/types.tsx
> +  newTab?: boolean;
Adding in the functionality here to be able to open a link in a new tab (I missed this in a previous PR).

2021-01-20 14:59 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/__tests__/AppHeader-test.tsx
> +describe('AppHeader', () => {
Here I was trying to put some checks around the big switch statement in `AppHeader`. Please let me know if these tests are unnecessary though!

2021-01-20 15:06 UTC, JoshuaKGoldberg requested changes
The code generally looks good to me. Could you please write a little more on the story to explain how the header works overall? I think it'll be important that folks can read that to understand.

I don't know why the preview environment isn't loading, but I just reran the checks and got it running locally... 🤷

2021-01-20 15:06 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/__tests__/AppHeader-test.tsx
> +describe('AppHeader', () => {
I think these are very excellent 😄,  and necessary.

2021-01-20 15:07 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/index.tsx
> +  className = '',
```suggestion
  className,
```

2021-01-20 15:07 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/index.tsx
> +    <AppBar className={className}>
Is it intentional that there is no background on this `AppBar` by default? That seems reasonable to me if you want it to inherit the surrounding background color, just checking...

2021-01-20 15:08 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLogo/index.tsx
> +      onClick={(event: React.MouseEvent) => onClick(event, item)}
On it!

2021-01-20 15:09 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/__tests__/AppHeader-test.tsx
> +  it('TextButton calls onClick() when clicked', () => {
Nit: I think the "it('X when Y')" format is a little easier to skim through for figuring out what tests do. What do you think?

```suggestion
  it('calls onClick when a TextButton is clicked', () => {
```

...and above, for example, `it('renders an AppHeaderLink when the type is link'`)

2021-01-20 15:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60084785ed39541f947181e2--gamut-preview.netlify.app>https://60084785ed39541f947181e2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60084785ed39541f947181e2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-20 15:15 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
> +      onClick={(event: React.MouseEvent) => onClick(event, item)}
In the places in `AppHeader/index.tsx`, when I try to remove, it yells at me:

<img width="606" alt="Screen Shot 2021-01-20 at 9 11 10 AM" src="https://user-images.githubusercontent.com/14988121/105195106-e4fedb80-5aff-11eb-9caf-abd1ca38ed36.png">

Was able to get rid of it in `AppHeaderLink` and `AppHeaderLogo` though.

2021-01-20 15:17 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
> +      onClick={(event: React.MouseEvent) => onClick(event, item)}
Huh, weird, that send like a bug in the typings. Thanks for pointing out!

2021-01-20 15:18 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/__tests__/AppHeader-test.tsx
> +  it('TextButton calls onClick() when clicked', () => {
More readable - I like these suggestions!

2021-01-20 15:21 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/index.tsx
> +    <AppBar className={className}>
Yes! We want to inherit the background color - thanks for checking :)

2021-01-20 15:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.10.6-alpha.dfd3f5.0<br/>@codecademy/styleguide@21.15.4-alpha.dfd3f5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-20 15:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60084ba084a96b24378e7d14--gamut-preview.netlify.app>https://60084ba084a96b24378e7d14--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60084ba084a96b24378e7d14>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-20 15:37 UTC, katiezutter commented
@JoshuaKGoldberg you're right, I'll fill in the story with more details! Weird that the preview environment isn't loading...

2021-01-20 15:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.10.6-alpha.89bbc2.0<br/>@codecademy/styleguide@21.15.4-alpha.89bbc2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-20 15:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60084e628fb8ac2cdd854381--gamut-preview.netlify.app>https://60084e628fb8ac2cdd854381--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60084e628fb8ac2cdd854381>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-20 19:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.10.7-alpha.e29458.0<br/>@codecademy/styleguide@21.15.7-alpha.e29458.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-20 19:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600887c0c5722f008df99cc1--gamut-preview.netlify.app>https://600887c0c5722f008df99cc1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600887c0c5722f008df99cc1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-20 22:09 UTC, saghdaey commented
This looks great, well done Katie!!!
I'm looking at the preview now - https://600887c0c5722f008df99cc1--gamut-preview.netlify.app/storybook/?path=/docs/labs-experimental-molecules-appheaderdropdown--app-header-dropdown

i think we may have talked about this before but I'm noticing that the drop down target (which is clickable) doesn't have cursor pointer on hover. maybe we can fix that in this PR?

2021-01-20 22:15 UTC, katiezutter commented
@saghdaey great catch - thought I was going crazy because I thought I had fixed this, but turns out I can't spell https://github.com/Codecademy/client-modules/pull/1300/files#diff-da6e62ca12094f8efb8c2d8d4302f7c252d2732769a564ee94f1603f059b3c6bL27
`cursor: ponter` lol...

2021-01-20 22:21 UTC, saghdaey approved these changes
love

2021-01-20 22:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.10.8-alpha.ea5c1a.0<br/>@codecademy/styleguide@21.15.7-alpha.ea5c1a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-20 22:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6008ad1a1747eb15e2a4a033--gamut-preview.netlify.app>https://6008ad1a1747eb15e2a4a033--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6008ad1a1747eb15e2a4a033>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-22 19:24 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLogo/__tests__/AppHeaderLogo-test.tsx
> +    onClick: onClick,
Very teeny nonblocking nit: we'll lint for this eventually, but just to show off cool JS features, this is equivalent:

```suggestion
    onClick,
```

2021-01-22 19:28 UTC, JoshuaKGoldberg approved these changes
Looks great! Some comments around docs but I trust you enough on filling them out or deciding I'm incorrect. 😄

2021-01-22 19:28 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeader.stories.mdx
> +AppHeader component for use in GlobalHeader. Uses AppBar to arrange items to the left or right side of the navigation bar. These items are passed in as objects of type AppHeaderItem, and map to AppHe
Rhetorically: what is "GlobalHeader"? Not all app that uses this might call it that, so you'd probably want to refer to it as something like:

```diff
- AppHeader component for use in GlobalHeader.
+ App header component for use as the top bar of pages.
```

2021-01-22 19:28 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeader.stories.mdx
> +AppHeader is not intended to be used alone, but rather by GlobalHeader which determines the composition of each of the Pro, Free, and Anon versions of Codecademy's global navigation header and passes
...and here, you'd probably want to generally abstract this to the idea that it receives information on this stuff from its parent. Gatsby.js static-sites, for example, needs to async load that.

2021-01-22 19:32 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLogo/__tests__/AppHeaderLogo-test.tsx
> +    onClick: onClick,
Updated in all the test files - thanks!

2021-01-22 19:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.10.8-alpha.5280fd.0<br/>@codecademy/styleguide@21.15.7-alpha.5280fd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-22 19:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600b29a0ad07d40dc7cec116--gamut-preview.netlify.app>https://600b29a0ad07d40dc7cec116--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600b29a0ad07d40dc7cec116>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-22 19:54 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeader.stories.mdx
> +AppHeader component for use in GlobalHeader. Uses AppBar to arrange items to the left or right side of the navigation bar. These items are passed in as objects of type AppHeaderItem, and map to AppHe
OH wait this is in the other PR! #1306

Never mind!!

2021-01-22 19:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.11.2-alpha.c25b14.0<br/>@codecademy/styleguide@21.16.2-alpha.c25b14.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-22 19:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600b2d86ad07d418cdcebe70--gamut-preview.netlify.app>https://600b2d86ad07d418cdcebe70--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600b2d86ad07d418cdcebe70>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-22 19:58 UTC, katiezutter commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeader.stories.mdx
> +AppHeader is not intended to be used alone, but rather by GlobalHeader which determines the composition of each of the Pro, Free, and Anon versions of Codecademy's global navigation header and passes
I was trying to get across that AppHeader would not be used in the monolith, static-sites, but rather is a component that the GlobalHeader component uses (PR for GlobalHeader: https://github.com/Codecademy/client-modules/pull/1306). And GlobalHeader is the one consumed by the monolith, not AppHeader. So maybe once the GlobalHeader changes are in, I can provide a link to the GlobalHeader storybook from the AppHeader storybook? And maybe these names are too confusing in and of themselves

2021-01-22 20:31 UTC, merged