Allow the PageFeatures component to render in a grid
Codecademy/client-modules pull request #1312
Opened 2021-01-22 22:11 UTC by judahtanthony

### Overview

Allow the PageFeatures component to render in a grid.

### PR Checklist
- [x] Related to designs: https://www.figma.com/file/EDtIzUHehl8njnjPStWtYR/Careers-Page---Refresh---1.19.21?node-id=139%3A736
- [x] Related to JIRA ticket: REACH-557
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

2021-01-22 22:12 UTC, judahtanthony commented on packages/gamut-labs/src/landingPage/Feature.tsx
> +  imgSrc?: string;
Now that we have "stat" and "none" features, we shouldn't require this.

2021-01-22 22:13 UTC, judahtanthony commented on packages/gamut-labs/src/landingPage/Feature.tsx
> +        fontWeight="title"
Correction in font-weight.

2021-01-22 22:14 UTC, judahtanthony commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +    {renderEach(maxCols, features, (feature) => (
Let me know if you think I over engineered this.  The idea is the renderEach and figure out how to render this layout.  This keep the messy logic out of here.

2021-01-22 22:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.11.1-alpha.5e0a7a.0<br/>@codecademy/styleguide@21.16.1-alpha.5e0a7a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-22 22:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://600b4ee95e57f1469e5b3110--gamut-preview.netlify.app>https://600b4ee95e57f1469e5b3110--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/600b4ee95e57f1469e5b3110>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-22 22:58 UTC, aionate0812 commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  itemRenderer: (item: any) => ReactNode
Is this a specific case where `any` can be set as the type?. I believe it's encouraged to use `any` as little as possible

2021-01-22 23:09 UTC, JoshuaKGoldberg requested changes
+1 to Alex's comment on the better types :)

2021-01-22 23:09 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/Feature.tsx
> +  imgSrc?: string;
Should this be a union of more specific types, then? `typeFeatureMediaProps = FeaturedImageProps | FeaturedIconProps | ...`?

2021-01-22 23:09 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
Generally, you don't want to use `as`: it can hide small but important differences in types. It's meant to be the _"I know it's slightly off, just let me do it"_ operator. Instead, how about inlining this object into the `size=`?

2021-01-22 23:22 UTC, rogervera commented on packages/gamut-labs/src/landingPage/Feature.tsx
> +  imgSrc?: string;
Ooo Alex and I were just pairing on something related for updating the Hero component to allow Videos.

```ts
type MediaProps = 
| {
    type: 'image'
  } & ImageProps
| {
    type: 'video
} & VideoProps
```

2021-01-22 23:25 UTC, codecaaron commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
We'd have to also specify the result of `12 / maxCols` IIRC since it won't infer the literal `12 | 6 | 4 | 3` and only `number`.

2021-01-22 23:54 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
Aha, right! I forgot about that. What an irksome lack of feature, TypeScript really should be be able to deduce that here since `maxCols` is a union type... ah well.

2021-01-23 00:05 UTC, codecaaron commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
Do you know if there are plans to implement something like that?  Seems like integer arithmetic within a limited set would be fairly low overhead?

2021-01-23 00:11 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
I'm skimming through their issue tracker and don't see it. You could always request it 😄

2021-01-23 00:15 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
Oh actually, I'm finding some references to the TS team not wanting it. The hard part would probably be around edge cases _(as always with adding to the type system)_. An example that would get brought up:

```
function takesOnePointFive(value: 1.5) { }

const two = 2;
const three = 3;

takesOnePointFive(three / two);
```

Should that work? If you're saying _yes, of course, it would be confusing for users to see division not work_, then how does the type system deal with the various quirks of IEEE 754? Is TypeScript going to have to implement a full math engine in the type system, as in https://github.com/microsoft/TypeScript/issues/26382 <- https://github.com/microsoft/TypeScript/issues/15645

2021-01-23 19:30 UTC, codecaaron commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
This makes sense, greatt find :D  Outside of whole numbers this is pretty gnar.

2021-01-27 17:05 UTC, judahtanthony commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
Sorry, so did we decide to inline it, or is the arithmetic going to require a cast anyhow, so might as well cast the whole thing?

2021-01-27 17:12 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  } as ResponsiveProperty<ColumnSizes>;
@judahtanthony you can do nothing I think 😄 . Up to you.

2021-01-27 19:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.15.0-alpha.33901f.0<br/>@codecademy/styleguide@21.23.0-alpha.33901f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 19:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011c08426a1e7a77bff86d6--gamut-preview.netlify.app>https://6011c08426a1e7a77bff86d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011c08426a1e7a77bff86d6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 19:39 UTC, judahtanthony commented on packages/gamut-labs/src/landingPage/PageFeatures.tsx
> +  itemRenderer: (item: any) => ReactNode
I have removed the any and replaced with an explicit type.

2021-01-27 19:41 UTC, judahtanthony commented
> +1 to Alex's comment on the stricter types :)
@JoshuaKGoldberg I think I have addressed all your concerns.

2021-01-27 20:05 UTC, JoshuaKGoldberg approved these changes

2021-01-27 20:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.15.0-alpha.c6841d.0<br/>@codecademy/styleguide@21.23.0-alpha.c6841d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 20:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011c93f1872b482ca38abf6--gamut-preview.netlify.app>https://6011c93f1872b482ca38abf6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011c93f1872b482ca38abf6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 20:15 UTC, merged