feat(PageHero): added functionality for PageHero to take images or videos as props
Codecademy/client-modules pull request #1323
Opened 2021-01-26 18:02 UTC by aionate0812

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-01-26 18:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1323) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1323) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/client-modules?pullRequest=1323) it.</sub>

2021-01-26 18:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.13.1-alpha.493478.0<br/>@codecademy/styleguide@21.18.1-alpha.493478.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-26 18:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60105badf8344f00ad9e49eb--gamut-preview.netlify.app>https://60105badf8344f00ad9e49eb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60105badf8344f00ad9e49eb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-26 19:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.13.5-alpha.0555ca.0<br/>@codecademy/styleguide@21.20.3-alpha.0555ca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-26 19:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601069d9b50a4514219f37ba--gamut-preview.netlify.app>https://601069d9b50a4514219f37ba--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601069d9b50a4514219f37ba>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-26 19:17 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +  const columSize = () => {
```suggestion
  const columnSize = () => {
```

2021-01-26 19:24 UTC, JoshuaKGoldberg requested changes
A good start! Requesting changes around a few small cleanups.

2021-01-26 19:24 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +      const videoArgs = omit({ ...media }, 'type');
`omit` doesn't modify its parameter, so this should be fine:

```suggestion
      const videoArgs = omit(media, 'type');
```

2021-01-26 19:24 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +    if (media && media.type === 'image') {
TypeScript doesn't have any way of knowing that the `renderMedia` function would only be called when `media` exists, so it's forcing you to add these unnecessary `media &&` checks, right?

In general, having a `const render* = ...` method with hard-to-describe logic is a potential indicator that it might be a good idea to split the code out into a separate function. Maybe a `<MediaHero media={media} />` or something like that?

Alternately, I suppose you could move this function outside of the component and have it take in `media` as a parameter... if so:

```suggestion
    if (media?.type === 'image') {
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2021-01-26 19:24 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/__tests__/Hero-test.tsx
> +  it('should render a video with videoTitle="" when media prop with type="video" is provided', () => {
Inaccurate, no?

```suggestion
  it('should render a video when media prop with type="video" is provided', () => {
```

2021-01-26 19:24 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/__tests__/Hero-test.tsx
> +  it('should render a video with videoTitle="" when media prop with type="video" is provided', () => {
(here and in other titles)

2021-01-26 20:47 UTC, aionate0812 commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +    if (media && media.type === 'image') {
I'm going to opt for the first solution, I believe that will make the component more flexible when adding other types of media. I will move the `columnSize` function outside of the component

2021-01-27 16:20 UTC, JoshuaKGoldberg approved these changes
Very close! A few unused pieces of code; otherwise this is looking great. I trust you to clean them up 😛

2021-01-27 16:20 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +const VideoColumn = styled(Column)`
🔪

2021-01-27 16:20 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  } else return null;
This case can never be hit because the media always is either image or video, right?

```suggestion
  }
```

2021-01-27 16:20 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  } else if (media && media.type === 'video') {
This check is unnecessary because the prop declares it must exist, right?

```suggestion
  } else if (media.type === 'video') {
```

2021-01-27 16:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.13.5-alpha.ad5e7b.0<br/>@codecademy/styleguide@21.20.3-alpha.ad5e7b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 16:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60119592bf936b6100317357--gamut-preview.netlify.app>https://60119592bf936b6100317357--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60119592bf936b6100317357>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 16:38 UTC, aionate0812 commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  } else return null;
![Screen Shot 2021-01-27 at 11 37 10 AM](https://user-images.githubusercontent.com/22219812/106022648-12b1ca80-6094-11eb-9390-8be507dd70ff.png)

I was getting this typescript error, returning `null` fixed. But maybe there is a better way to fix it?

2021-01-27 16:39 UTC, aionate0812 commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  } else if (media && media.type === 'video') {
true I missed that when cleaning up

2021-01-27 16:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.14.1-alpha.c983bd.0<br/>@codecademy/styleguide@21.21.1-alpha.c983bd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 16:45 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  } else return null;
Heh, annoying. Looks like TypeScript doesn't have this particular situation memorized as one where it can ignore that last case... If you change to a `switch (media.type) {` it does. 🤷

2021-01-27 16:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60119904dc571c5a8d5f89ea--gamut-preview.netlify.app>https://60119904dc571c5a8d5f89ea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60119904dc571c5a8d5f89ea>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 16:48 UTC, christian-dinh approved these changes
sorry I was late to the party on this one, looks good! one small nit to go along with Josh's feedback

2021-01-27 16:48 UTC, christian-dinh commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +      {media && <PageHeroMedia {...media} />}
I don't think the spread is necessary here, `media={media}` should do the trick

2021-01-27 17:00 UTC, aionate0812 commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +      {media && <PageHeroMedia {...media} />}
`PageHeroMedia` takes `MediaProps` as props. Should I make the component take a `media` prop of type `MediaProps`?

2021-01-27 17:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.7dd5a2.0<br/>@codecademy/gamut-labs@7.14.1-alpha.7dd5a2.0<br/>@codecademy/styleguide@21.21.1-alpha.7dd5a2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 17:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.5-alpha.a17b47.0<br/>@codecademy/gamut-labs@7.14.1-alpha.a17b47.0<br/>@codecademy/styleguide@21.21.1-alpha.a17b47.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 17:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011a1cb3317e45566238329--gamut-preview.netlify.app>https://6011a1cb3317e45566238329--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011a1cb3317e45566238329>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 17:27 UTC, aionate0812 commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  } else return null;
I `switch`ed the if statement for a `switch` instead

2021-01-27 17:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.5-alpha.eea649.0<br/>@codecademy/gamut-labs@7.14.1-alpha.eea649.0<br/>@codecademy/styleguide@21.21.1-alpha.eea649.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 17:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011a39c132aa2752e1de5bb--gamut-preview.netlify.app>https://6011a39c132aa2752e1de5bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011a39c132aa2752e1de5bb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 18:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.14.1-alpha.af500e.0<br/>@codecademy/styleguide@21.21.1-alpha.af500e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 18:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011aacfaa429d971a189030--gamut-preview.netlify.app>https://6011aacfaa429d971a189030--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011aacfaa429d971a189030>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 18:13 UTC, christian-dinh commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +      {media && <PageHeroMedia {...media} />}
woops missed that, yeah I think that would be a little more clear 👍

2021-01-27 22:50 UTC, aresnik11 commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +      {media && <PageHeroMedia {...media} />}
+1

2021-01-27 23:00 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  @media only screen and (max-width: ${breakpoints.sm}) {
Oh and we have a thing for this: https://gamut.codecademy.com/storybook/?path=/docs/foundations-layout--page#usage-typescript

```suggestion
  ${mediaQueries.sm} {
```

2021-01-27 23:03 UTC, christian-dinh commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  @media only screen and (max-width: ${breakpoints.sm}) {
just a heads up, `mediaQueries.sm` uses `min-width` instead of `max-width` so you would need to reverse the styling

2021-01-28 18:09 UTC, aionate0812 commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  @media only screen and (max-width: ${breakpoints.sm}) {
is this a blocker?

2021-01-28 18:10 UTC, aionate0812 commented on packages/gamut-labs/src/landingPage/PageHero.tsx
> +      {media && <PageHeroMedia {...media} />}
made the change

2021-01-28 18:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.16.1-alpha.50db04.0<br/>@codecademy/styleguide@21.24.2-alpha.50db04.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-28 18:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6012fffcebf8ff1d4acb268f--gamut-preview.netlify.app>https://6012fffcebf8ff1d4acb268f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6012fffcebf8ff1d4acb268f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-28 18:34 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  @media only screen and (max-width: ${breakpoints.sm}) {
Not IMO :)

2021-01-28 18:34 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
> +  @media only screen and (max-width: ${breakpoints.sm}) {
and oh didn't notice the change, good call @christian-dinh !

2021-01-28 19:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.16.2-alpha.750dde.0<br/>@codecademy/styleguide@22.0.1-alpha.750dde.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-28 19:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6013106dce29f359cb6b3198--gamut-preview.netlify.app>https://6013106dce29f359cb6b3198--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6013106dce29f359cb6b3198>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-29 15:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.16.6-alpha.34c24e.0<br/>@codecademy/styleguide@22.0.5-alpha.34c24e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-29 15:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60142518422b9b28f79e915f--gamut-preview.netlify.app>https://60142518422b9b28f79e915f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60142518422b9b28f79e915f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-29 15:14 UTC, merged