feat(Mobile Menu contd): interactions
Codecademy/client-modules pull request #1324
Opened 2021-01-26 18:49 UTC by saghdaey

- add icon as optional prop
- include icons in global header items
- set up app header story

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-01-26 18:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.9-alpha.bfcfc4.0<br/>@codecademy/gamut-labs@7.13.4-alpha.bfcfc4.0<br/>@codecademy/gamut@19.11.5-alpha.bfcfc4.0<br/>@codecademy/styleguide@21.20.2-alpha.bfcfc4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-26 18:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601065e208dbfa0a999fa353--gamut-preview.netlify.app>https://601065e208dbfa0a999fa353--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601065e208dbfa0a999fa353>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-26 22:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.9-alpha.90c224.0<br/>@codecademy/gamut-labs@7.13.4-alpha.90c224.0<br/>@codecademy/gamut@19.11.5-alpha.90c224.0<br/>@codecademy/styleguide@21.20.2-alpha.90c224.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-26 22:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6010983a93030b16aa61641c--gamut-preview.netlify.app>https://6010983a93030b16aa61641c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6010983a93030b16aa61641c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 02:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.14.1-alpha.cf1fbf.0<br/>@codecademy/styleguide@21.21.1-alpha.cf1fbf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 02:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6010d69d38b5ef7387a11088--gamut-preview.netlify.app>https://6010d69d38b5ef7387a11088--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6010d69d38b5ef7387a11088>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-01 20:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60185fd287cedf01392bb834--gamut-preview.netlify.app>https://60185fd287cedf01392bb834--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60185fd287cedf01392bb834>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-01 20:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.14.1-alpha.4b3fec.0<br/>@codecademy/styleguide@21.21.1-alpha.4b3fec.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 15:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.9a85b6.0<br/>@codecademy/styleguide@23.2.1-alpha.9a85b6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 15:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60196e3cceec99b30a5cd1ce--gamut-preview.netlify.app>https://60196e3cceec99b30a5cd1ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60196e3cceec99b30a5cd1ce>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 15:47 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> -  cursor: pointer;
moved this css to shared styles

2021-02-02 15:48 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
> +        );
loops through elements and maps links to the basic AppHeaderLinkMobile component; maps the 'dropdown' (and eventually 'profile-dropdown') to AppHeaderSubMenuTarget components

2021-02-02 15:49 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
> +  const [subMenuItem, setSubMenuItem] = useState<AppHeaderDropdownItem>();
controls whether the submenu is open (the submenu = for ex, the Resources sub menu, what would in the desktop version of the app appear in a popover or dropdown)

2021-02-02 15:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.9816f5.0<br/>@codecademy/styleguide@23.2.1-alpha.9816f5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 15:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60197531d2c78900bbc9ac8f--gamut-preview.netlify.app>https://60197531d2c78900bbc9ac8f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60197531d2c78900bbc9ac8f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 16:01 UTC, JoshuaKGoldberg requested changes
Love the direction this is heading! A main request around deduplicating state.

2021-02-02 16:01 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderMainMenuMobile.stories.mdx
> +The AppHeaderMainMenuMobile component is used in the mobile version of the AppHeader.
Do you think you could elaborate just a little bit here on how it opens & closes a sub menu? It's good that the individual stories explain it in detail, but I got confused reading through this main one.

2021-02-02 16:03 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
> +// will likely move from here --
removed this file from this PR :) you mustve been reviewing before I pushed the latest!!

2021-02-02 16:05 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
> +// will likely move from here --
oh nooo

2021-02-02 16:08 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
> +    action(event, item); // handles the tracking
this is the action that's being passed from the monolith (to handle tracking for ex) all the way through to the gamut components. I believe it was previously called onClick and then @katiezutter  implemented feedback to rename to action

2021-02-02 16:08 UTC, saghdaey commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderMainMenuMobile.stories.mdx
> +The AppHeaderMainMenuMobile component is used in the mobile version of the AppHeader.
yes def

2021-02-02 16:15 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
> +    action(event, item); // handles the tracking
In that case, ignore me 😄

2021-02-02 16:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.53e4e6.0<br/>@codecademy/styleguide@23.2.1-alpha.53e4e6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 16:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60197eb7709efe0f3e6d6292--gamut-preview.netlify.app>https://60197eb7709efe0f3e6d6292--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60197eb7709efe0f3e6d6292>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 16:37 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +  padding: 2px 0;
👌 nice simplification removing `AppHeaderAvatarTarget`

2021-02-02 16:41 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
> +  handleClose?: () => void;
Shouldn't `handleClose` be required here?

2021-02-02 16:46 UTC, katiezutter commented on packages/gamut-labs/src/experimental/GlobalHeader/styles.module.scss
> +  z-index: 14; // does this need to be 14
Nope, definitely just copied over from the monolith 😅

2021-02-02 16:48 UTC, katiezutter commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderSubMenuMobile.stories.mdx
> -<Props of={AppHeaderSubMenuMobile} />
Should this be `PropsTable` now instead of being removed?

2021-02-02 16:48 UTC, katiezutter commented on packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
> +<PropsTable story="GlobalHeader" />
Thank you for changing all these!

2021-02-02 16:55 UTC, saghdaey commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderSubMenuMobile.stories.mdx
> -<Props of={AppHeaderSubMenuMobile} />
oh oops did i not include :) my b. will add!

2021-02-02 17:12 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
> +    action(event, item); // handles the tracking
Oh I still think the comment isn't necessary. But not a blocking issue :)

2021-02-02 17:13 UTC, JoshuaKGoldberg approved these changes
🌮

2021-02-02 17:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.75fcef.0<br/>@codecademy/styleguide@23.2.1-alpha.75fcef.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 17:14 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
> +  handleClose?: () => void;
yep, fixed. thanks!

2021-02-02 17:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.372931.0<br/>@codecademy/styleguide@23.2.1-alpha.372931.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 17:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601989f36fde5216821ed4f7--gamut-preview.netlify.app>https://601989f36fde5216821ed4f7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601989f36fde5216821ed4f7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 19:02 UTC, katiezutter approved these changes
LGTM!

2021-02-02 19:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.07e491.0<br/>@codecademy/styleguide@23.2.1-alpha.07e491.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 19:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6019a95eb355d600c0acc18e--gamut-preview.netlify.app>https://6019a95eb355d600c0acc18e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6019a95eb355d600c0acc18e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 20:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.dfb90f.0<br/>@codecademy/styleguide@23.2.1-alpha.dfb90f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 20:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6019b359b355d60f77acc101--gamut-preview.netlify.app>https://6019b359b355d60f77acc101--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6019b359b355d60f77acc101>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 20:22 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/AppHeaderMainMenuMobile-test.tsx
> +    expect(targetButton).toHaveTextContent('resources target');
wrote these to "test" the mapItemToElement" function in the component

2021-02-02 21:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.8abfae.0<br/>@codecademy/styleguide@23.2.1-alpha.8abfae.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 21:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6019bf09fa41e61ac8cf11dc--gamut-preview.netlify.app>https://6019bf09fa41e61ac8cf11dc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6019bf09fa41e61ac8cf11dc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 21:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.325ccf.0<br/>@codecademy/styleguide@23.2.1-alpha.325ccf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 21:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6019c1814d70071b79b68101--gamut-preview.netlify.app>https://6019c1814d70071b79b68101--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6019c1814d70071b79b68101>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 21:21 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/AppHeaderMainMenuMobile-test.tsx
> +const sublink2TestId = 'sublink-2';
oops will fix these to be sublink1Id & sublink2Id 
took a look at our helper function createMockApHeaderLinkItem and expects id here then creates a data test id for the element in this format "app-header-link-{id}"

2021-02-02 21:31 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/AppHeaderMainMenuMobile-test.tsx
> +  it('calls the action function when the target button is clicked & renders the submenu with the appropriate links', () => {
```suggestion
  it('renders a submenu when its target button is clicked', () => {
```

2021-02-02 21:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.1-alpha.3c63a6.0<br/>@codecademy/styleguide@23.2.1-alpha.3c63a6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 21:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6019c7a7e9aefc1d2b644826--gamut-preview.netlify.app>https://6019c7a7e9aefc1d2b644826--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6019c7a7e9aefc1d2b644826>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-02 21:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.1.7-alpha.42e64b.0<br/>@codecademy/styleguide@24.1.1-alpha.42e64b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-02 21:55 UTC, merged