feat!: bumped ESLint packages to latest and added recommended, Jest linting
Codecademy/client-modules pull request #1326
Opened 2021-01-26 23:57 UTC by JoshuaKGoldberg

### Overview

Adds a couple new packages:

* https://www.npmjs.com/package/eslint-plugin-jest: The standard community Jest lint rule set
* https://www.npmjs.com/package/eslint-plugin-jest-react: Nascent little one we're creating (https://github.com/codecademy-engineering/Codecademy/pull/21529)

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-01-27 00:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.30079d.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.30079d.0<br/>@codecademy/gamut-labs@7.13.5-alpha.30079d.0<br/>@codecademy/gamut-styles@7.6.4-alpha.30079d.0<br/>@codecademy/gamut-system@0.2.2-alpha.30079d.0<br/>@codecademy/gamut@19.11.6-alpha.30079d.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.30079d.0<br/>@codecademy/styleguide@21.20.3-alpha.30079d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 00:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6010ae8993030b2deb615894--gamut-preview.netlify.app>https://6010ae8993030b2deb615894--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6010ae8993030b2deb615894>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 03:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6010d76228223f73d6833a8c--gamut-preview.netlify.app>https://6010d76228223f73d6833a8c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6010d76228223f73d6833a8c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 03:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.998fb0.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.998fb0.0<br/>@codecademy/gamut-labs@7.13.5-alpha.998fb0.0<br/>@codecademy/gamut-styles@7.6.4-alpha.998fb0.0<br/>@codecademy/gamut-system@0.2.2-alpha.998fb0.0<br/>@codecademy/gamut@19.11.6-alpha.998fb0.0<br/>@codecademy/macros@1.1.3-alpha.998fb0.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.998fb0.0<br/>@codecademy/styleguide@21.20.3-alpha.998fb0.0<br/>@codecademy/webpack-config@5.2.2-alpha.998fb0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 03:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6010dc0593030b7a92615323--gamut-preview.netlify.app>https://6010dc0593030b7a92615323--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6010dc0593030b7a92615323>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 03:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.41cb0e.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.41cb0e.0<br/>@codecademy/gamut-labs@7.13.5-alpha.41cb0e.0<br/>@codecademy/gamut-styles@7.6.4-alpha.41cb0e.0<br/>@codecademy/gamut-system@0.2.2-alpha.41cb0e.0<br/>@codecademy/gamut@19.11.6-alpha.41cb0e.0<br/>@codecademy/macros@1.1.3-alpha.41cb0e.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.41cb0e.0<br/>@codecademy/styleguide@21.20.3-alpha.41cb0e.0<br/>@codecademy/webpack-config@5.2.2-alpha.41cb0e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 15:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.e5c55f.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.e5c55f.0<br/>@codecademy/gamut-labs@7.13.5-alpha.e5c55f.0<br/>@codecademy/gamut-styles@7.6.4-alpha.e5c55f.0<br/>@codecademy/gamut-system@0.2.2-alpha.e5c55f.0<br/>@codecademy/gamut@19.11.6-alpha.e5c55f.0<br/>@codecademy/macros@1.1.3-alpha.e5c55f.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.e5c55f.0<br/>@codecademy/styleguide@21.20.3-alpha.e5c55f.0<br/>@codecademy/webpack-config@5.2.2-alpha.e5c55f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 15:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601181c42a7ccf89c5c012da--gamut-preview.netlify.app>https://601181c42a7ccf89c5c012da--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601181c42a7ccf89c5c012da>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 17:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011a1b438b5ef780fa1112f--gamut-preview.netlify.app>https://6011a1b438b5ef780fa1112f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011a1b438b5ef780fa1112f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 17:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.fb611d.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.fb611d.0<br/>@codecademy/gamut-labs@7.13.5-alpha.fb611d.0<br/>@codecademy/gamut-styles@7.6.4-alpha.fb611d.0<br/>@codecademy/gamut-system@0.2.2-alpha.fb611d.0<br/>@codecademy/gamut@19.11.6-alpha.fb611d.0<br/>@codecademy/macros@1.1.3-alpha.fb611d.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.fb611d.0<br/>@codecademy/styleguide@21.20.3-alpha.fb611d.0<br/>@codecademy/webpack-config@5.2.2-alpha.fb611d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 17:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.e4923c.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.e4923c.0<br/>@codecademy/gamut-labs@7.13.5-alpha.e4923c.0<br/>@codecademy/gamut-styles@7.6.4-alpha.e4923c.0<br/>@codecademy/gamut-system@0.2.2-alpha.e4923c.0<br/>@codecademy/gamut@19.11.6-alpha.e4923c.0<br/>@codecademy/macros@1.1.3-alpha.e4923c.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.e4923c.0<br/>@codecademy/styleguide@21.20.3-alpha.e4923c.0<br/>@codecademy/webpack-config@5.2.2-alpha.e4923c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 17:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011a60c4e99467813d7daf2--gamut-preview.netlify.app>https://6011a60c4e99467813d7daf2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011a60c4e99467813d7daf2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 17:59 UTC, codecaaron approved these changes
Nice!

Lots of great rules that make my heart sing!

2021-01-27 17:59 UTC, codecaaron commented on packages/eslint-config/index.js
> +        'no-undef': 'off',
Just curious was this turned off through an extension before?  Or is this net new?

2021-01-27 17:59 UTC, codecaaron commented on packages/gamut/src/FlexBox/Item.tsx
> +Item.displayName = 'Item';
Is this not getting covered by the babel plugin?  Just curious.

2021-01-27 17:59 UTC, codecaaron commented on packages/gamut/src/FlexBox/Container.tsx
> +Container.displayName = 'Container';
Was this broken before?

2021-01-27 17:59 UTC, codecaaron commented on packages/gamut/src/InputStepper/index.tsx
> +    const normalizedValue = normalize(parseInt(rawValue, 10));
Yay radix enforcement

2021-01-27 18:00 UTC, JoshuaKGoldberg commented on packages/gamut/src/FlexBox/Item.tsx
> +Item.displayName = 'Item';
Oh yeah we can remove these now.

2021-01-27 18:05 UTC, JoshuaKGoldberg commented on packages/eslint-config/index.js
> +        'no-undef': 'off',
I want to say it was turned off through extensions before, and now isn't. It was a little irksome playing around trying to find where they came from...

2021-01-27 18:08 UTC, jakemhiller commented on packages/eslint-config/index.js
> +    'airbnb',
Hello old friend

2021-01-27 18:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.d0ce1d.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.d0ce1d.0<br/>@codecademy/gamut-labs@7.13.5-alpha.d0ce1d.0<br/>@codecademy/gamut-styles@7.6.4-alpha.d0ce1d.0<br/>@codecademy/gamut-system@0.2.2-alpha.d0ce1d.0<br/>@codecademy/gamut@19.11.6-alpha.d0ce1d.0<br/>@codecademy/macros@1.1.3-alpha.d0ce1d.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.d0ce1d.0<br/>@codecademy/styleguide@21.20.3-alpha.d0ce1d.0<br/>@codecademy/webpack-config@5.2.2-alpha.d0ce1d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 18:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011acaedc571c6dec5f8a0a--gamut-preview.netlify.app>https://6011acaedc571c6dec5f8a0a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011acaedc571c6dec5f8a0a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 19:25 UTC, jakemhiller requested changes
Would prefer to merge this when we have autofixing enabled on commit. Based on the changes in this PR it seems like there are numerous style-based lint rules that we normally don't block PRs on because things are fixed automatically.

2021-02-01 19:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.4-alpha.3b9d29.0<br/>@codecademy/gamut-illustrations@0.4.10-alpha.3b9d29.0<br/>@codecademy/gamut-labs@7.13.5-alpha.3b9d29.0<br/>@codecademy/gamut-styles@7.6.4-alpha.3b9d29.0<br/>@codecademy/gamut-system@0.2.2-alpha.3b9d29.0<br/>@codecademy/gamut@19.11.6-alpha.3b9d29.0<br/>@codecademy/macros@1.1.3-alpha.3b9d29.0<br/>@codecademy/markdown-overrides@0.4.4-alpha.3b9d29.0<br/>@codecademy/styleguide@21.20.3-alpha.3b9d29.0<br/>@codecademy/webpack-config@5.2.2-alpha.3b9d29.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-01 19:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.7-alpha.d9e545.0<br/>@codecademy/gamut-illustrations@0.4.19-alpha.d9e545.0<br/>@codecademy/gamut-labs@8.0.3-alpha.d9e545.0<br/>@codecademy/gamut-styles@7.7.1-alpha.d9e545.0<br/>@codecademy/gamut-system@0.2.2-alpha.d9e545.0<br/>@codecademy/gamut@20.0.6-alpha.d9e545.0<br/>@codecademy/macros@1.1.3-alpha.d9e545.0<br/>@codecademy/markdown-overrides@0.4.5-alpha.d9e545.0<br/>@codecademy/styleguide@23.1.2-alpha.d9e545.0<br/>@codecademy/webpack-config@5.2.2-alpha.d9e545.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-01 19:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6018567f2827571194943cca--gamut-preview.netlify.app>https://6018567f2827571194943cca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6018567f2827571194943cca>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-01 19:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.7-alpha.a8a6bf.0<br/>@codecademy/gamut-illustrations@0.4.19-alpha.a8a6bf.0<br/>@codecademy/gamut-labs@8.0.3-alpha.a8a6bf.0<br/>@codecademy/gamut-styles@7.7.1-alpha.a8a6bf.0<br/>@codecademy/gamut-system@0.2.2-alpha.a8a6bf.0<br/>@codecademy/gamut@20.0.6-alpha.a8a6bf.0<br/>@codecademy/macros@1.1.3-alpha.a8a6bf.0<br/>@codecademy/markdown-overrides@0.4.5-alpha.a8a6bf.0<br/>@codecademy/styleguide@23.1.2-alpha.a8a6bf.0<br/>@codecademy/webpack-config@5.2.2-alpha.a8a6bf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-01 19:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60185c2cd1b0941c4ec33460--gamut-preview.netlify.app>https://60185c2cd1b0941c4ec33460--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60185c2cd1b0941c4ec33460>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-05 22:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.7-alpha.c96de7.0<br/>@codecademy/gamut-illustrations@0.4.19-alpha.c96de7.0<br/>@codecademy/gamut-labs@8.0.3-alpha.c96de7.0<br/>@codecademy/gamut-styles@7.7.1-alpha.c96de7.0<br/>@codecademy/gamut-system@0.2.2-alpha.c96de7.0<br/>@codecademy/gamut@20.0.6-alpha.c96de7.0<br/>@codecademy/macros@1.1.3-alpha.c96de7.0<br/>@codecademy/markdown-overrides@0.4.5-alpha.c96de7.0<br/>@codecademy/styleguide@23.1.2-alpha.c96de7.0<br/>@codecademy/webpack-config@5.2.2-alpha.c96de7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-05 22:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601dcab23966b268d406bc81--gamut-preview.netlify.app>https://601dcab23966b268d406bc81--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601dcab23966b268d406bc81>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-08 18:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.2.0-alpha.f966ff.0<br/>@codecademy/gamut-illustrations@0.4.19-alpha.f966ff.0<br/>@codecademy/gamut-labs@8.0.3-alpha.f966ff.0<br/>@codecademy/gamut-styles@7.7.1-alpha.f966ff.0<br/>@codecademy/gamut-system@0.2.2-alpha.f966ff.0<br/>@codecademy/gamut@20.0.6-alpha.f966ff.0<br/>@codecademy/macros@1.1.3-alpha.f966ff.0<br/>@codecademy/markdown-overrides@0.4.5-alpha.f966ff.0<br/>@codecademy/styleguide@23.1.2-alpha.f966ff.0<br/>@codecademy/webpack-config@5.2.2-alpha.f966ff.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-08 18:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60218439b3a45c008deea67f--gamut-preview.netlify.app>https://60218439b3a45c008deea67f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60218439b3a45c008deea67f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-08 19:09 UTC, jakemhiller approved these changes

2021-02-08 19:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.2.0-alpha.9686fe.0<br/>@codecademy/gamut-illustrations@0.4.30-alpha.9686fe.0<br/>@codecademy/gamut-labs@9.2.5-alpha.9686fe.0<br/>@codecademy/gamut-styles@7.7.4-alpha.9686fe.0<br/>@codecademy/gamut-system@0.3.1-alpha.9686fe.0<br/>@codecademy/gamut-tests@1.1.2-alpha.9686fe.0<br/>@codecademy/gamut@21.3.3-alpha.9686fe.0<br/>@codecademy/macros@1.1.3-alpha.9686fe.0<br/>@codecademy/markdown-overrides@0.4.8-alpha.9686fe.0<br/>@codecademy/styleguide@25.1.6-alpha.9686fe.0<br/>@codecademy/webpack-config@5.2.4-alpha.9686fe.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-08 19:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60218ddcfdd9fd0a44c31551--gamut-preview.netlify.app>https://60218ddcfdd9fd0a44c31551--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60218ddcfdd9fd0a44c31551>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-10 14:17 UTC, hmafzal approved these changes
LGTM! +1 to Jake

2021-02-10 15:59 UTC, MattSchiller approved these changes
Awesome & all about this =)

2021-02-12 19:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.2.0-alpha.1242cd.0<br/>@codecademy/gamut-illustrations@0.4.36-alpha.1242cd.0<br/>@codecademy/gamut-labs@9.3.8-alpha.1242cd.0<br/>@codecademy/gamut-styles@7.7.4-alpha.1242cd.0<br/>@codecademy/gamut-system@0.3.1-alpha.1242cd.0<br/>@codecademy/gamut-tests@1.1.3-alpha.1242cd.0<br/>@codecademy/gamut@21.3.9-alpha.1242cd.0<br/>@codecademy/macros@1.1.3-alpha.1242cd.0<br/>@codecademy/markdown-overrides@0.4.8-alpha.1242cd.0<br/>@codecademy/styleguide@25.2.8-alpha.1242cd.0<br/>@codecademy/webpack-config@5.2.4-alpha.1242cd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-12 19:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6026d94e11829739d289572c--gamut-preview.netlify.app>https://6026d94e11829739d289572c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6026d94e11829739d289572c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-12 19:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>babel-preset-codecademy@3.1.1-alpha.efb7d6.0<br/>@codecademy/eslint-config@3.2.0-alpha.efb7d6.0<br/>@codecademy/gamut-illustrations@0.4.36-alpha.efb7d6.0<br/>@codecademy/gamut-labs@9.3.8-alpha.efb7d6.0<br/>@codecademy/gamut-styles@7.7.4-alpha.efb7d6.0<br/>@codecademy/gamut-system@0.3.1-alpha.efb7d6.0<br/>@codecademy/gamut-tests@1.1.3-alpha.efb7d6.0<br/>@codecademy/gamut@21.3.9-alpha.efb7d6.0<br/>@codecademy/macros@1.1.3-alpha.efb7d6.0<br/>@codecademy/markdown-overrides@0.4.8-alpha.efb7d6.0<br/>@codecademy/styleguide@25.2.8-alpha.efb7d6.0<br/>@codecademy/webpack-config@5.2.4-alpha.efb7d6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-12 19:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6026dae67c6b9f312d923658--gamut-preview.netlify.app>https://6026dae67c6b9f312d923658--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6026dae67c6b9f312d923658>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-12 19:46 UTC, merged