feat(AppHeaderProfileDropdown): Pass through user avatar and display name
Codecademy/client-modules pull request #1330
Opened 2021-01-27 21:58 UTC by katiezutter

### Overview

Adds AppHeaderProfileDropdown component and sets up mobile menu for account sub-menu.

This PR was initially meant to set up the App Header items that we needed for the account sub-menu for the mobile header:

<img width="506" alt="Screen Shot 2021-01-27 at 3 50 46 PM" src="https://user-images.githubusercontent.com/14988121/106058920-887b5d80-60b7-11eb-95c9-7cdfb5f32708.png">

While doing this, I realized that since we now have the avatar, the user's display name, and all of the links that we needed for the mobile account sub-menu, we might as well have the desktop profile dropdown on the Gamut side as well (`AppHeaderProfileDropdown`). You can see this in the preview storybook for `GlobalHeader`:

<img width="462" alt="Screen Shot 2021-01-27 at 3 58 11 PM" src="https://user-images.githubusercontent.com/14988121/106059541-78b04900-60b8-11eb-9a34-451eeb42cf99.png">

This PR also addresses a z-index issue where the profile dropdown content was appearing underneath other content on the page. To address this, we now have an optional parameter for the consumer of `GlobalHeader` to pass in a base z-index.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EGG-663](https://codecademy.atlassian.net/browse/EGG-663)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

2021-01-27 22:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.16.1-alpha.183f34.0<br/>@codecademy/styleguide@21.24.1-alpha.183f34.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-27 22:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6011e401d8fb091058a1bb98--gamut-preview.netlify.app>https://6011e401d8fb091058a1bb98--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6011e401d8fb091058a1bb98>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-27 22:11 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
> +  | AppHeaderProfileDropdownProps
nice

2021-01-27 22:13 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
> +  arrowButton?: boolean;
did you just add this in preparation for this being able to open a submenu? I don't see arrowButton being used in the component (yet?)

2021-01-27 22:14 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
> +    </SeparatorOuter>
This whole deal of having a bunch of styled components here isn't my favorite, so suggestions are welcome! This is the way I could figure it out so that the styling for the horizontal separators looked right.

2021-01-27 22:16 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
> +  arrowButton?: boolean;
Oh I didn't add this in, it must've been from your other branch that I started with! I can take it out if you want, but maybe it's fine if you'll need it for your next PR?

2021-01-27 22:19 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
> +  arrowButton?: boolean;
oh haha yep must be thats funny:) 
i can handle it np!!

2021-01-27 22:20 UTC, saghdaey commented
I think we may need to add an admin variant to the pro dropdown to handle these other options --> 
<img width="398" alt="Screen Shot 2021-01-27 at 5 20 08 PM" src="https://user-images.githubusercontent.com/9753446/106061823-ed3cb500-60c3-11eb-9dc6-9ced75319c69.png">

2021-01-28 05:05 UTC, JoshuaKGoldberg requested changes
This is looking visually beautiful, mostly non-blocking nits! Just the one blocker IMO from the story having the dropdown float off to the right.

2021-01-28 05:05 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderProfileDropdown.stories.mdx
> +    item: {
Oof, https://github.com/storybookjs/storybook/pull/12824 would be really nice here...
![Screenshot of a bunch of raw text for a JSON 'item' prop in Storybook](https://user-images.githubusercontent.com/3335181/106092045-90f58780-60fb-11eb-82db-2979f593e99f.png)

2021-01-28 05:05 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderProfileDropdown.stories.mdx
> +  component={AppHeaderProfileDropdown}
Looks like there's a CSS bug with this in at least the story?

![Screenshot of the profile dropdown floating weirdly to the right](https://user-images.githubusercontent.com/3335181/106092301-ff3a4a00-60fb-11eb-9158-09f8ff58a052.png)

2021-01-28 05:05 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderProfileDropdown/__tests__/AppHeaderProfileDropdown-test.tsx
> +        type: 'link',
You might consider making a `createMockAppHeaderLinkItem` function to reduce duplication in all of these 😉 

![Screenshot of four test files with popover data](https://user-images.githubusercontent.com/3335181/106092434-4aecf380-60fc-11eb-805c-897614fbc552.png)

2021-01-28 05:05 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderProfileDropdown/__tests__/AppHeaderProfileDropdown-test.tsx
> +    expect(screen.getAllByRole('link')[0].getAttribute('href')).toEqual(
Up for using a `expect(....map(node => node.getAttribute('href'))).toEqual(...)` to make this all into one assertion?

2021-01-28 05:06 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderProfileDropdown/index.tsx
> +        isOpen={isOpen}
Hmm, this code looks really similar to `AppHeaderDropdown`... is there some DRYing that should happen?

2021-01-28 16:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.16.1-alpha.06724e.0<br/>@codecademy/styleguide@21.24.1-alpha.06724e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-28 16:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6012eac023448f35df30cc64--gamut-preview.netlify.app>https://6012eac023448f35df30cc64--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6012eac023448f35df30cc64>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-28 17:28 UTC, katiezutter commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderProfileDropdown.stories.mdx
> +  component={AppHeaderProfileDropdown}
Ahh yes, noticed this and then forgot to circle back! I think it's a storybook thing, looking into it.

2021-01-28 17:29 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderProfileDropdown/__tests__/AppHeaderProfileDropdown-test.tsx
> +    expect(screen.getAllByRole('link')[0].getAttribute('href')).toEqual(
Yes!! Thanks for these great improvements

2021-01-28 17:29 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderProfileDropdown/index.tsx
> +        isOpen={isOpen}
That's the path I was originally going down, but then once the file started looking convoluted I split it up - I'll take another stab at it!

2021-01-28 17:33 UTC, katiezutter commented
@saghdaey there is that admin functionality in this PR!

you can see it here for admin: https://6012eac023448f35df30cc64--gamut-preview.netlify.app/storybook/?path=/docs/labs-experimental-molecules-globalheader--pro-user-global-header-admin

and here for CS: https://6012eac023448f35df30cc64--gamut-preview.netlify.app/storybook/?path=/docs/labs-experimental-molecules-globalheader--pro-user-global-header-customer-support

2021-01-28 17:41 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderProfileDropdown/index.tsx
> +        isOpen={isOpen}
Update: oh wow this was _much_ easier now after the types `profile-dropdown` and `dropdown` are in order!

2021-01-28 19:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601312411768fe4ff35925f0--gamut-preview.netlify.app>https://601312411768fe4ff35925f0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601312411768fe4ff35925f0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-28 21:33 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderProfileDropdown/index.tsx
> +      style={{ paddingTop: pxRem(2), paddingBottom: pxRem(2) }}
No good reason - changed!

2021-01-28 21:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.16.5-alpha.f88d81.0<br/>@codecademy/styleguide@22.0.4-alpha.f88d81.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-28 21:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60132f6fce29f3809c6b3208--gamut-preview.netlify.app>https://60132f6fce29f3809c6b3208--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60132f6fce29f3809c6b3208>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-28 21:47 UTC, katiezutter commented
I addressed all of the feedback - thanks y'all! 😊 @JoshuaKGoldberg @saghdaey I'm re-requesting review because I made some pretty major refactors to this work! Also, thanks goodness commits will be squashed...yikes.

2021-01-28 21:58 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderDropdown.stories.mdx
> +<!-- These breaks are to allow room on the page for the Profile dropdown above -->
You could do this a teeny bit more elegantly with some `min-height` and/or `margin-bottom` in CSS 😉

2021-01-28 22:15 UTC, dreamwasp reviewed
LGTM, just have a couple questions above + am curious about the preexisting conditions that led to needing to define the z-index in this way

2021-01-28 22:15 UTC, dreamwasp commented on packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderDropdown.stories.mdx
> +      <Box height="50">
maybe you can add `margin`'s to this `Box` instead of the `<br />`s below?

2021-01-28 22:15 UTC, dreamwasp commented on packages/gamut-labs/src/experimental/AppHeader/index.tsx
> +        {items.left.map((item) => mapItemToElement(baseZIndex, item, onClick))}
just out of curiosity, when you one need to pass an onClick that applied to the entire Header? tracking?

2021-01-29 05:42 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/index.tsx
> +        {items.left.map((item) => mapItemToElement(baseZIndex, item, onClick))}
yep! tracking 
& and then hopefully in the future we can add routing via redux-first-router as well

2021-01-29 05:48 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
> -import { AppHeaderLink } from '../../AppHeader/AppHeaderElements/AppHeaderLink';
I had intentionally used the AppHeaderLink component here instead of the AppHeaderLinkMobile, is there a reason you switched it? 
My thought was the former never shows an icon (which is the behavior we want in the AppHeaderSubMenuMobile why use the component (AppHeaderLinkMobile) that will always check for something that's false?

2021-01-29 05:50 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
> +  topSeparator: true,
I don't love that we're adding specific styling properties to the AppHeaderItems; I wonder if there's a way of around this that's still easy to read

2021-01-29 14:38 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
> +    {(args) => <GlobalHeader onClick={() => {}} type="anon" />}
You might consider using `action('...')` to be a little more informative than `onClick` for these handlers. Search `action('` to see other examples.

2021-01-29 14:59 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
> -import { AppHeaderLink } from '../../AppHeader/AppHeaderElements/AppHeaderLink';
It's because we'll be reusing this component for the Profile sub-menu which does have icons, unlike the other sub-menus!

2021-01-29 15:05 UTC, katiezutter commented on packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
> +  topSeparator: true,
Another option would be to do an array of an array for profile dropdown items, so for an admin the profile dropdown would be something like [[profile, account, etc], [admin, cs, reportBug], [logout]] and then the dropdown could add a top separator to the first element of each array (except the first) - do you think that would be the better way to go?

2021-01-29 15:53 UTC, katiezutter commented on packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
> +### Anonymous User
Yeah, can't figure out why that's happening in the Storybook. @saghdaey and I spent a deal of time trying to figure out how to make it appear better on the Docs page but didn't figure it out! If you toggle to Canvas instead of Docs in Storybook after selecting each variant in the left-hand sidebar, that's more what it looks like 😊

2021-01-29 16:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@7.16.5-alpha.b7f370.0<br/>@codecademy/styleguide@22.0.4-alpha.b7f370.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-29 16:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60143deb237e6e66885b982b--gamut-preview.netlify.app>https://60143deb237e6e66885b982b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60143deb237e6e66885b982b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-29 18:34 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
> -import { AppHeaderLink } from '../../AppHeader/AppHeaderElements/AppHeaderLink';
oooo nice nice forgot that one had icons

2021-01-29 21:57 UTC, katiezutter commented
@dreamwasp glad you asked about the z-index thing - we've been through a little bit of an adventure with that, and just paired with Aaron earlier this afternoon! Took it out of this PR and we talked through some changes within static-sites/monolith that need to happen when we switch over to the new components! So now there are no z-index changes here. It was looking funky in Storybook though so we made Canvases have a height of 500px in the GlobalHeader story.

2021-01-29 22:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.0.3-alpha.114ea8.0<br/>@codecademy/styleguide@23.1.1-alpha.114ea8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-29 22:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601488f6fff37452dde582db--gamut-preview.netlify.app>https://601488f6fff37452dde582db--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601488f6fff37452dde582db>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-29 22:16 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +};
@saghdaey this is the component I added after revamping the way we're passing in link sections to the profile dropdown!

2021-01-29 22:17 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/types.tsx
> +  popover: AppHeaderLinkItem[][];
@saghdaey and here I changed it to a 2D array for the links, vs that `topSeparator` stuff

2021-01-29 22:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.0.3-alpha.46a47e.0<br/>@codecademy/styleguide@23.1.1-alpha.46a47e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-29 22:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60148ced34cec90090e08bbe--gamut-preview.netlify.app>https://60148ced34cec90090e08bbe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60148ced34cec90090e08bbe>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-29 23:03 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderAvatar/index.tsx
> +  imageUrl?: string;
do we have a default imageUrl? why is this optional?

2021-01-29 23:05 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderAvatar/index.tsx
> +`;
maybe we can use box but non-blocking!

2021-01-29 23:05 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderAvatar/index.tsx
> +  imageUrl?: string;
Good catch - shouldn't be!

2021-01-29 23:05 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/__tests__/AppHeaderDropdown-test.tsx
> +    ).toStrictEqual(testDropdownUrls);
nice:)

2021-01-29 23:09 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +        <span title={item.text} className={styles.copy}>
how come this span has a title? I think I had this in one of my PR's and josh or aaron asked me... and I didnt know and deleted lol

2021-01-29 23:10 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +        <span title={item.text} className={styles.copy}>
Really I'm just trying to secretly work back in all the unnecessary code that you deleted haha

2021-01-29 23:15 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +                </Box>
is the only difference between these two returns, the topSeparator true?  That's all i'm seeing but I dont trust my eyes rn. 
 I wonder if we could make this a little shorter and do --
`
                return (
                  <Box key={link.id} paddingX={16}>
                    <AppHeaderLinkMobile
                      action={action}
                      item={link}
                      key={link.id}
                      topSeparator={showTopSeparator(sectionIndex, linkIndex)}
                    />
                  </Box>

`

2021-01-29 23:15 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +                </Box>
ok sorry that formatting did not work lol

2021-01-29 23:16 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +                </Box>
& we can define showTopSeparator outside of the return

2021-01-29 23:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.0.3-alpha.27313d.0<br/>@codecademy/styleguide@23.1.1-alpha.27313d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-29 23:17 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +                </Box>
Duh! Thanks for catching this!

2021-01-29 23:17 UTC, saghdaey commented on packages/gamut-labs/src/experimental/AppHeader/mockAppHeaderItems.tsx
> +  return {
nice love this v useful

2021-01-29 23:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6014980413fd1710b53ef028--gamut-preview.netlify.app>https://6014980413fd1710b53ef028--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6014980413fd1710b53ef028>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-01-29 23:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.0.3-alpha.7bb6ae.0<br/>@codecademy/styleguide@23.1.1-alpha.7bb6ae.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-01-29 23:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601499c3d3430b1010c875bf--gamut-preview.netlify.app>https://601499c3d3430b1010c875bf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601499c3d3430b1010c875bf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-01 19:01 UTC, JoshuaKGoldberg approved these changes
Awesome! Left a little bit of DRY nitting, but nothing blocking. 🌮 

I suspect that this header will need some tweaking once we get it into the monolith and static-sites, but that's normal. Let's get it in!

2021-02-01 19:01 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
> +### Anonymous User
We'll probably need to add some kind of `<Meta ... />` prop to specify that this page needs wide styles. I think the page is just not wide enough for it.

![Screenshot of not very wide page shrinking the header width](https://user-images.githubusercontent.com/3335181/106504980-ae2cac00-6495-11eb-85a1-2e0f5a57baea.png)

fyi @codecaaron

2021-02-01 19:43 UTC, katiezutter commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +                <Box key={link.id} paddingX={16}>
If `type === 'profile-dropdown'` then we do the double mapping, first mapping over each section (`AppHeaderLinkItem[]`) then each `AppHeaderLinkItem`, vs. a normal dropdown, which does not have a 2D array of links, just maps over `AppHeaderLinkItem`s. But I was able to change the `Box` and key things!

2021-02-01 19:44 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +                <Box key={link.id} paddingX={16}>
Oh gotcha - thanks!

2021-02-01 19:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@8.0.3-alpha.e25339.0<br/>@codecademy/styleguide@23.1.2-alpha.e25339.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-01 19:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60185b99d1b09419c0c3363a--gamut-preview.netlify.app>https://60185b99d1b09419c0c3363a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60185b99d1b09419c0c3363a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-01 19:58 UTC, merged