fix: add event parameter to landing page CTA onClick
Codecademy/client-modules pull request #1365
Opened 2021-02-04 20:40 UTC by aresnik11

### Overview

Add event parameter to landing page CTA onClick prop

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-04 20:57 UTC, christian-dinh approved these changes
🎉

2021-02-04 23:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.1.1-alpha.19181b.0<br/>@codecademy/styleguide@25.1.1-alpha.19181b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-04 23:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://601c826db85e480f4ca24554--gamut-preview.netlify.app>https://601c826db85e480f4ca24554--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/601c826db85e480f4ca24554>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-05 14:33 UTC, dreamwasp reviewed
🚀

2021-02-08 22:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.30-alpha.79393c.0<br/>@codecademy/gamut-labs@9.2.7-alpha.79393c.0<br/>@codecademy/gamut@21.3.3-alpha.79393c.0<br/>@codecademy/styleguide@25.1.8-alpha.79393c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-08 22:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.2.8-alpha.1fe3ab.0<br/>@codecademy/styleguide@25.1.9-alpha.1fe3ab.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-08 23:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6021c2862a132f2d221f29d7--gamut-preview.netlify.app>https://6021c2862a132f2d221f29d7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6021c2862a132f2d221f29d7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-09 02:35 UTC, JoshuaKGoldberg requested changes
The runtime code looks reasonable, but one request on the typings 🤗

2021-02-09 02:35 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/types.tsx
> +) => void;
`&` _intersection_ types say that they are _both_ of the things at the same time. It looks like you meant to use a `|` _union_ type to say that it can be _either_ of the things.

```suggestion
export type CTAOnClickCallback = (
  event: React.MouseEvent<HTMLButtonElement> | React.MouseEvent<HTMLLinkElement>
) => void;
```

However, this can be simplified a bit by using the union type in the generic instead:

```suggestion
export type CTAOnClickCallback = (
  event: React.MouseEvent<HTMLButtonElement | HTMLLinkElement>
) => void;
```

However, does whoever's receiving that event care that it's a button or link element? Can we skip telling them the possible element types, and use the default declared in the React types of `Element`? (right click -> go to definition on `MouseEvent` in your editor):

```suggestion
export type CTAOnClickCallback = (event: React.MouseEvent) => void;
```

If so, good news, there's a built-in `React.MouseEventHandler` type in the React types you can use instead of this.

```suggestion
export type CTAOnClickCallback = React.MouseEventHandler;
```

_(or you could remove `CTAOnClickCallback` altogether and directly use `React.MouseEventHandler` -- that's probably what I'd do)_

Docs ref for the curious: https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

2021-02-09 02:37 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/CTA.tsx
> +  onCtaButtonClick?: CTAOnClickCallback;
Btw I don't think this change is breaking. We don't rely on there being _no_ parameters in this function anywhere (I can't think of any easy way to!)_.

2021-02-10 15:26 UTC, aresnik11 commented on packages/gamut-labs/src/landingPage/types.tsx
> +) => void;
Agh yes you're right. Curious though because I think I got the `&` from the from type expected in the CTA `onClick` which does use an `&`:
```
(property) React.DOMAttributes<T>.onClick?: (((event: React.MouseEvent<HTMLLinkElement, MouseEvent>) => void) & ((event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void)) | undefined
```

Also wondering when we would care re:
> does whoever's receiving that event care that it's a button or link element?

2021-02-10 15:26 UTC, aresnik11 commented on packages/gamut-labs/src/landingPage/CTA.tsx
> +  onCtaButtonClick?: CTAOnClickCallback;
Ah good to know!

2021-02-10 15:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.2.8-alpha.119181.0<br/>@codecademy/styleguide@25.1.9-alpha.119181.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-10 15:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6023ff2decc3f25110f1dbb5--gamut-preview.netlify.app>https://6023ff2decc3f25110f1dbb5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6023ff2decc3f25110f1dbb5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-10 16:23 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/types.tsx
> +) => void;
> which does use an `&`

Yeahhhh, that comes from `ButtonDeprecatedBaseProps`, which has to do some _weird_ stuff to be able to support its various uses.

```ts
  /**
   * @remarks
   * Technically, this is only ever a button event *or* a link event.
   * We '&' them together for ease of usage.
   */
  onClick?: (
    event: React.MouseEvent<HTMLAnchorElement> &
      React.MouseEvent<HTMLButtonElement>
  ) => void;
```

> Also wondering when we would care re:

Personally, I don't think the consumer should :)

2021-02-10 16:24 UTC, JoshuaKGoldberg approved these changes
Perfection.

2021-02-10 16:31 UTC, aresnik11 commented on packages/gamut-labs/src/landingPage/types.tsx
> +) => void;
so if you were coding `ButtonDeprecatedBaseProps` now, would you make the `onClick`:
```
  onClick?: React.MouseEventHandler;
```

2021-02-10 17:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@9.2.10-alpha.613fab.0<br/>@codecademy/styleguide@25.1.11-alpha.613fab.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-10 17:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602411806a426100a7f4944b--gamut-preview.netlify.app>https://602411806a426100a7f4944b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602411806a426100a7f4944b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-10 17:15 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/types.tsx
> +) => void;
oh god I did this:

```ts
export type ButtonProps = HTMLProps<HTMLLinkElement> &
  HTMLProps<HTMLButtonElement> & {
    mode?: 'dark' | 'light';
  };
```

https://github.com/Codecademy/client-modules/blob/da17d069e5ec4d9b7635d7900efb13190d0aa349/packages/gamut/src/Button/shared.ts#L3-L7

2021-02-10 17:16 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/types.tsx
> +) => void;
I will emphasize, though, that these buttons use weird prop `&`s that technically don't make sense because it's pretty darn difficult to get them to work precisely and accurately. When we do get them to work with, say, a discriminated type, the error messages tend to be pretty confusing. So we went with inaccurate but easier to use.

2021-02-10 17:20 UTC, aresnik11 commented on packages/gamut-labs/src/landingPage/types.tsx
> +) => void;
thanks for the explanation!

2021-02-10 17:37 UTC, merged