feat(ContentContainer)!: update responsive padding
Codecademy/client-modules pull request #1392
Opened 2021-02-11 00:42 UTC by sooinc

### Overview

- update content container per the updated design for [responsive padding](https://www.figma.com/file/ZUJ7cfVgyoh1kiQYNN8Hbt/Grid-%E2%9C%85?node-id=0%3A1)
- add 96px to spacing

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/ZUJ7cfVgyoh1kiQYNN8Hbt/Grid-%E2%9C%85?node-id=0%3A1
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-11 00:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.34-alpha.da1c48.0<br/>@codecademy/gamut-labs@9.3.1-alpha.da1c48.0<br/>@codecademy/gamut-styles@7.7.4-alpha.da1c48.0<br/>@codecademy/gamut-tests@1.1.3-alpha.da1c48.0<br/>@codecademy/gamut@21.3.7-alpha.da1c48.0<br/>@codecademy/markdown-overrides@0.4.8-alpha.da1c48.0<br/>@codecademy/styleguide@25.2.1-alpha.da1c48.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-11 00:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60247ec7dd68787143e83088--gamut-preview.netlify.app>https://60247ec7dd68787143e83088--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60247ec7dd68787143e83088>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-11 01:17 UTC, sooinc commented on packages/styleguide/stories/Layouts/ContentContainer.stories.mdx
> +Check with design team if further padding/margin is required on a page layout as additional spacing would cause it to be misaligned with the responsive padding set on Global Header and Footer.
lmk if this all makes sense.. it might be more info than necessary 😅

2021-02-16 14:19 UTC, codecaaron requested changes
Awesome work!

A few small changes that we talked about but this is great.

2 other things:
- Do you think you could open up a pull request on the monolith with a version of this?
- We have a test for the wide prop here that needs to be updated with the new API :) https://app.circleci.com/pipelines/github/Codecademy/client-modules/10086/workflows/6983210d-7cc0-46ee-b053-8db467264b8f/jobs/62880

2021-02-16 14:19 UTC, codecaaron commented on packages/gamut/src/ContentContainer/index.tsx
> +  width: 100%;
let's also add in `margin: 0 auto;` here.  I think it's a safe default for both!

2021-02-16 14:19 UTC, codecaaron commented on packages/gamut/src/ContentContainer/index.tsx
> +  ${contentContainerVariants}
We can actually avoid these manual types like this!

```tsx
export const ContentContainer = styled.div(
 contentContainerVariants, 
  () =>  css`
     height: 100%;
     width: 100%;
`)
```

The first argument of `styled.x`'s parameter list is used to infer the rest of the props.  So if we put our functions first and our static styles later we can avoid having to use a generic and a custom type altogether!

2021-02-16 14:19 UTC, codecaaron commented on packages/gamut/src/AppBar/index.tsx
> +        className={styles.contentWrapper}
We may want to check how each place using this s overriding these styles with classNames this may no longer be a viable pattern going forward (we may introduce a higher specificity for emotion components in general)

2021-02-16 14:19 UTC, codecaaron commented on packages/styleguide/stories/Layouts/ContentContainer.stories.mdx
> +Check with design team if further padding/margin is required on a page layout as additional spacing would cause it to be misaligned with the responsive padding set on Global Header and Footer.
This is the perfect amount of specificity, love it

2021-02-16 14:19 UTC, codecaaron commented on packages/styleguide/stories/Layouts/ContentContainer.stories.mdx
> +Check with design team if further padding/margin is required on a page layout as additional spacing would cause it to be misaligned with the responsive padding set on Global Header and Footer.
```suggestion
Check with the design team if a different padding/margin is required on a page layout as additional spacing may be cause misalignment with the Header and Footer.
```

2021-02-16 14:20 UTC, codecaaron commented on packages/gamut/src/ContentContainer/index.tsx
> +export const contentContainerVariants = variant({
We don't need to export this (it's causing a snapshot test failure on our export file)

2021-02-18 14:41 UTC, sooinc commented on packages/gamut/src/ContentContainer/index.tsx
> +  ${contentContainerVariants}
got it, thank you! and it looks like we don't have to declare 'className' either in types since ".div" here is a styled component that extends the intrinsicElements types, correct?

2021-02-18 16:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.45-alpha.7f2e04.0<br/>@codecademy/gamut-labs@10.0.12-alpha.7f2e04.0<br/>@codecademy/gamut-styles@8.1.1-alpha.7f2e04.0<br/>@codecademy/gamut-tests@2.0.3-alpha.7f2e04.0<br/>@codecademy/gamut@23.2.2-alpha.7f2e04.0<br/>@codecademy/markdown-overrides@0.5.3-alpha.7f2e04.0<br/>@codecademy/styleguide@27.2.2-alpha.7f2e04.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-18 16:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602e90227d184d895dcc60f9--gamut-preview.netlify.app>https://602e90227d184d895dcc60f9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602e90227d184d895dcc60f9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 21:04 UTC, sooinc commented
Updated the test to the new API and opened a PR in the monolith with the latest version here: here is the the PR on the monolith: https://github.com/codecademy-engineering/Codecademy/pull/22210
an

2021-02-18 21:05 UTC, sooinc commented on packages/gamut/src/AppBar/index.tsx
> +        className={styles.contentWrapper}
looks like styles on classNames aren't being overridden in the monolith

2021-02-25 16:58 UTC, codecaaron reviewed
@sooinc Could you put this up on a PR env on the monolith?

2021-02-25 17:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.7.2-alpha.9cef26.0<br/>@codecademy/gamut-labs@10.2.2-alpha.9cef26.0<br/>@codecademy/gamut-styles@8.1.2-alpha.9cef26.0<br/>@codecademy/gamut-tests@2.1.2-alpha.9cef26.0<br/>@codecademy/gamut@25.3.5-alpha.9cef26.0<br/>@codecademy/markdown-overrides@0.5.4-alpha.9cef26.0<br/>@codecademy/styleguide@29.5.2-alpha.9cef26.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-25 17:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6037d8e45ef2bd1729f1e6b3--gamut-preview.netlify.app>https://6037d8e45ef2bd1729f1e6b3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6037d8e45ef2bd1729f1e6b3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-25 18:31 UTC, sooinc commented
> @sooinc Could you put this up on a PR env on the monolith?

Oh yes, it's up. I tagged the PR in the comment above but here is the actual link to the PR env: https://pr-22210.dev-eks.codecademy.com

2021-03-04 19:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.7.4-alpha.e3ca9c.0<br/>@codecademy/gamut-labs@10.4.2-alpha.e3ca9c.0<br/>@codecademy/gamut-styles@8.2.2-alpha.e3ca9c.0<br/>@codecademy/gamut-tests@2.1.5-alpha.e3ca9c.0<br/>@codecademy/gamut@25.4.4-alpha.e3ca9c.0<br/>@codecademy/markdown-overrides@0.5.6-alpha.e3ca9c.0<br/>@codecademy/styleguide@29.6.8-alpha.e3ca9c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 19:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60413237ea0f34009b5a37ff--gamut-preview.netlify.app>https://60413237ea0f34009b5a37ff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60413237ea0f34009b5a37ff>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-11 02:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.8.1-alpha.24ea82.0<br/>@codecademy/gamut-kit@0.2.14-alpha.24ea82.0<br/>@codecademy/gamut-labs@11.2.2-alpha.24ea82.0<br/>@codecademy/gamut-styles@8.3.2-alpha.24ea82.0<br/>@codecademy/gamut-tests@2.2.2-alpha.24ea82.0<br/>@codecademy/gamut@26.2.3-alpha.24ea82.0<br/>@codecademy/markdown-overrides@0.5.9-alpha.24ea82.0<br/>@codecademy/styleguide@30.5.2-alpha.24ea82.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-11 02:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604981b83b8f7e00a582ff3e--gamut-preview.netlify.app>https://604981b83b8f7e00a582ff3e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604981b83b8f7e00a582ff3e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 21:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.8.1-alpha.f43890.0<br/>@codecademy/gamut-kit@0.2.16-alpha.f43890.0<br/>@codecademy/gamut-labs@11.2.4-alpha.f43890.0<br/>@codecademy/gamut-styles@8.3.2-alpha.f43890.0<br/>@codecademy/gamut-tests@2.2.2-alpha.f43890.0<br/>@codecademy/gamut@26.3.1-alpha.f43890.0<br/>@codecademy/markdown-overrides@0.5.9-alpha.f43890.0<br/>@codecademy/styleguide@30.6.1-alpha.f43890.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 21:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604bd8365397342d392a6d87--gamut-preview.netlify.app>https://604bd8365397342d392a6d87--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604bd8365397342d392a6d87>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 22:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.8.1-alpha.4cd63f.0<br/>@codecademy/gamut-kit@0.2.16-alpha.4cd63f.0<br/>@codecademy/gamut-labs@11.2.4-alpha.4cd63f.0<br/>@codecademy/gamut-styles@8.3.2-alpha.4cd63f.0<br/>@codecademy/gamut-tests@2.2.2-alpha.4cd63f.0<br/>@codecademy/gamut@26.3.1-alpha.4cd63f.0<br/>@codecademy/markdown-overrides@0.5.9-alpha.4cd63f.0<br/>@codecademy/styleguide@30.6.1-alpha.4cd63f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 22:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604bf11f294def128936b0ca--gamut-preview.netlify.app>https://604bf11f294def128936b0ca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604bf11f294def128936b0ca>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 06:55 UTC, codecaaron approved these changes
Small changes but this looks good to me :)

Approved pending small changes here and design feedback is addressed.

2021-03-15 06:55 UTC, codecaaron commented on packages/gamut/src/ContentContainer/__tests__/ContentContainer-test.tsx
> +  render(<ContentContainer {...props} />);
We can get use gamut tests here to ensure theme provider is around.


```suggestion
import { setupRtl } from "@codecademy/gamut-tests";

const renderView = setupRtl(ContentContainer);

describe('ContentContainer', () => {
  it('has maxWidth of contentWidths.max when size is medium', () => {
    const { view } = renderView({ size: 'medium' });
    expect(view.firstChild).toHaveStyle(`maxWidth: ${contentWidths.max}`);
  });
});
```

2021-03-15 06:55 UTC, codecaaron commented on packages/gamut/src/AppBar/index.tsx
>        </ContentContainer>
We can remove that classname altogether by restructuring the html a bit :)

```suggestion
      <ContentContainer  size={wide ? 'wide' : 'medium'}>
       <FlexBox alignItems="center">{children}</FlexBox>
    </ContentContainer>
```

2021-03-15 19:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.8.1-alpha.5619c1.0<br/>@codecademy/gamut-kit@0.2.16-alpha.5619c1.0<br/>@codecademy/gamut-labs@11.2.4-alpha.5619c1.0<br/>@codecademy/gamut-styles@8.3.2-alpha.5619c1.0<br/>@codecademy/gamut-tests@2.2.2-alpha.5619c1.0<br/>@codecademy/gamut@26.3.1-alpha.5619c1.0<br/>@codecademy/markdown-overrides@0.5.9-alpha.5619c1.0<br/>@codecademy/styleguide@30.6.1-alpha.5619c1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 19:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604fb8a33ec1591459b3e934--gamut-preview.netlify.app>https://604fb8a33ec1591459b3e934--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604fb8a33ec1591459b3e934>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 19:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.1-alpha.d08a2b.0<br/>@codecademy/gamut-kit@0.2.23-alpha.d08a2b.0<br/>@codecademy/gamut-labs@12.0.3-alpha.d08a2b.0<br/>@codecademy/gamut-styles@8.3.3-alpha.d08a2b.0<br/>@codecademy/gamut-tests@2.2.3-alpha.d08a2b.0<br/>@codecademy/gamut@27.1.1-alpha.d08a2b.0<br/>@codecademy/markdown-overrides@0.5.10-alpha.d08a2b.0<br/>@codecademy/styleguide@31.1.1-alpha.d08a2b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 19:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6052550272c17c2e27bb23ea--gamut-preview.netlify.app>https://6052550272c17c2e27bb23ea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6052550272c17c2e27bb23ea>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 21:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.1-alpha.5e5347.0<br/>@codecademy/gamut-kit@0.2.23-alpha.5e5347.0<br/>@codecademy/gamut-labs@12.0.3-alpha.5e5347.0<br/>@codecademy/gamut-styles@8.3.3-alpha.5e5347.0<br/>@codecademy/gamut-tests@2.2.3-alpha.5e5347.0<br/>@codecademy/gamut@27.1.1-alpha.5e5347.0<br/>@codecademy/markdown-overrides@0.5.10-alpha.5e5347.0<br/>@codecademy/styleguide@31.1.1-alpha.5e5347.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 21:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60526ea8984d9f3d3abd02bb--gamut-preview.netlify.app>https://60526ea8984d9f3d3abd02bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60526ea8984d9f3d3abd02bb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 21:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.1-alpha.57b3f8.0<br/>@codecademy/gamut-kit@0.2.23-alpha.57b3f8.0<br/>@codecademy/gamut-labs@12.0.3-alpha.57b3f8.0<br/>@codecademy/gamut-styles@8.3.3-alpha.57b3f8.0<br/>@codecademy/gamut-tests@2.2.3-alpha.57b3f8.0<br/>@codecademy/gamut@27.1.1-alpha.57b3f8.0<br/>@codecademy/markdown-overrides@0.5.10-alpha.57b3f8.0<br/>@codecademy/styleguide@31.1.1-alpha.57b3f8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 21:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605271e5846e104b90f53466--gamut-preview.netlify.app>https://605271e5846e104b90f53466--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605271e5846e104b90f53466>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-18 14:16 UTC, dreamwasp approved these changes

2021-03-18 14:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.1-alpha.12c4ab.0<br/>@codecademy/gamut-kit@0.2.23-alpha.12c4ab.0<br/>@codecademy/gamut-labs@12.0.3-alpha.12c4ab.0<br/>@codecademy/gamut-styles@8.3.3-alpha.12c4ab.0<br/>@codecademy/gamut-tests@2.2.3-alpha.12c4ab.0<br/>@codecademy/gamut@27.1.1-alpha.12c4ab.0<br/>@codecademy/markdown-overrides@0.5.10-alpha.12c4ab.0<br/>@codecademy/styleguide@31.1.1-alpha.12c4ab.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-18 14:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6053613685a111f29fd989d3--gamut-preview.netlify.app>https://6053613685a111f29fd989d3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6053613685a111f29fd989d3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-18 14:19 UTC, sooinc commented on packages/gamut/src/AppBar/index.tsx
> +        className={styles.contentWrapper}
yes! actually addressed this - here is the latest:
```
return (
    <div className={classes}>
      <ContentContainer size={wide ? 'wide' : 'medium'}>
        <FlexBox alignItems="center" height="100%">
          {children}
        </FlexBox>
      </ContentContainer>
    </div>
  );
```

2021-03-18 14:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.1-alpha.822654.0<br/>@codecademy/gamut-kit@0.2.24-alpha.822654.0<br/>@codecademy/gamut-labs@12.0.4-alpha.822654.0<br/>@codecademy/gamut-styles@8.3.3-alpha.822654.0<br/>@codecademy/gamut-tests@2.2.3-alpha.822654.0<br/>@codecademy/gamut@27.1.2-alpha.822654.0<br/>@codecademy/markdown-overrides@0.5.10-alpha.822654.0<br/>@codecademy/styleguide@31.1.2-alpha.822654.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-18 14:54 UTC, merged

2021-03-18 14:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605369f85e5787034d1f1e25--gamut-preview.netlify.app>https://605369f85e5787034d1f1e25--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605369f85e5787034d1f1e25>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->