feat(Styleguide): Gamut System docs and routing fixes
Codecademy/client-modules pull request #1395
Opened 2021-02-11 17:47 UTC by codecaaron

### Overview

* Adds system docs to foundations.
* Fixes routing with LinkTo with defaults for pages and stories.  This will eventually need to be refactored to something that consumes stories specifically.

### Docs
Sets up a System Props about page with a quick explanation and a table of contents.  These pages are for the most part just imported `.md` files from the package's docs section, with some minor text replacement formatting.  Ideally, these are refreshed to be accurate for day to day use.  I've only included `Properties` | `Variants` | `Compose` and `Responsive Styles` as the baseline.

### SB Changes
- Fixes a bunch of problems with LinkTo routing due to the requirement of `LinkTo` to include an index story.  This adds defaults to either `page` or the kebab case name of the component which should be consistent across all stories.
- Fixes ToC nested links to use pseudo-elements for click targets.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-11 17:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@25.2.4-alpha.63081c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-11 17:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60256f73a92bf95ad97adbde--gamut-preview.netlify.app>https://60256f73a92bf95ad97adbde--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60256f73a92bf95ad97adbde>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-11 19:23 UTC, dreamwasp approved these changes
🚀

2021-02-11 19:23 UTC, dreamwasp commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +const buttonVariants = variants({
i think this is `variant({`

2021-02-11 19:23 UTC, dreamwasp commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +const colorVariant = variants({
same thing here, `variant ({` is what's been working for me

2021-02-11 19:23 UTC, dreamwasp commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +const colorVariant = variants({
one more

2021-02-11 19:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.34-alpha.292649.0<br/>@codecademy/gamut-labs@9.3.4-alpha.292649.0<br/>@codecademy/gamut-styles@7.7.4-alpha.292649.0<br/>@codecademy/gamut-system@0.3.1-alpha.292649.0<br/>@codecademy/gamut-tests@1.1.3-alpha.292649.0<br/>@codecademy/gamut@21.3.7-alpha.292649.0<br/>@codecademy/markdown-overrides@0.4.8-alpha.292649.0<br/>@codecademy/styleguide@25.2.4-alpha.292649.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-11 19:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6025895934fa0c0bc91b346c--gamut-preview.netlify.app>https://6025895934fa0c0bc91b346c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6025895934fa0c0bc91b346c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-12 17:30 UTC, JoshuaKGoldberg requested changes
Looks great as a start! LMK of what you think about all this copy editing, I can approve if you hate it. 😄

2021-02-12 17:30 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/About.stories.mdx
> +    subtitle: 'System Properties and style functions',
```suggestion
    subtitle: 'System properties and style functions',
```

2021-02-12 17:30 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/About.stories.mdx
> +Many of our components are written in emotion our CSS in JS library. In order to improve resuability, predictability and standardization across our design system we've created a set of style utilitie
```suggestion
Many of our components are written in our CSS in JS library, [Emotion](https://emotion.sh/). we've created a set of style utilities that we call **System Props** to improve reusability, predictability, and standardization across our design system .
```

2021-02-12 17:30 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +import docs from '@codecademy/gamut-system/docs/compose.md';
🤯

2021-02-12 17:30 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +<Description>{docs.replace('# Compose', '')}</Description>
```suggestion
<Description>{docs.replace('# Composition', '')}</Description>
```

Alternately, can you make a helper for removing the first title with a regex? That'd be more resilient to `.md` changes.

2021-02-16 14:54 UTC, codecaaron commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +<Description>{docs.replace('# Compose', '')}</Description>
Good call :) split out a helper to remove the H1s for now :)

2021-02-16 14:54 UTC, codecaaron commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +export const Button = styled.button(buttonVariants);
heh, fair point.  I updated it to something innocuous like `Badge`.

2021-02-16 14:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.34-alpha.ebd9d5.0<br/>@codecademy/gamut-labs@9.3.4-alpha.ebd9d5.0<br/>@codecademy/gamut-styles@7.7.4-alpha.ebd9d5.0<br/>@codecademy/gamut-system@0.3.1-alpha.ebd9d5.0<br/>@codecademy/gamut-tests@1.1.3-alpha.ebd9d5.0<br/>@codecademy/gamut@21.3.7-alpha.ebd9d5.0<br/>@codecademy/markdown-overrides@0.4.8-alpha.ebd9d5.0<br/>@codecademy/styleguide@25.2.4-alpha.ebd9d5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-16 14:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602bdd8447f3f04121940cd2--gamut-preview.netlify.app>https://602bdd8447f3f04121940cd2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602bdd8447f3f04121940cd2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-16 16:47 UTC, JoshuaKGoldberg commented on packages/styleguide/.storybook/components/utils.ts
> +  return md.replace(/(^|\n)(#\s.*)/g, '$1');
You might consider leaving a comment / JSDoc explaining why this funky looking regexp is good and necessary.

2021-02-16 16:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.38-alpha.7d0dd1.0<br/>@codecademy/gamut-labs@10.0.4-alpha.7d0dd1.0<br/>@codecademy/gamut-styles@8.0.1-alpha.7d0dd1.0<br/>@codecademy/gamut-system@0.4.1-alpha.7d0dd1.0<br/>@codecademy/gamut-tests@2.0.1-alpha.7d0dd1.0<br/>@codecademy/gamut@22.0.2-alpha.7d0dd1.0<br/>@codecademy/markdown-overrides@0.5.1-alpha.7d0dd1.0<br/>@codecademy/styleguide@26.0.4-alpha.7d0dd1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-16 16:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602bf7c16bcc7751809fa579--gamut-preview.netlify.app>https://602bf7c16bcc7751809fa579--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602bf7c16bcc7751809fa579>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-16 17:00 UTC, JoshuaKGoldberg approved these changes
🌮

2021-02-16 17:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.38-alpha.f875dc.0<br/>@codecademy/gamut-labs@10.0.4-alpha.f875dc.0<br/>@codecademy/gamut-styles@8.0.1-alpha.f875dc.0<br/>@codecademy/gamut-system@0.4.1-alpha.f875dc.0<br/>@codecademy/gamut-tests@2.0.1-alpha.f875dc.0<br/>@codecademy/gamut@22.0.2-alpha.f875dc.0<br/>@codecademy/markdown-overrides@0.5.1-alpha.f875dc.0<br/>@codecademy/styleguide@26.0.4-alpha.f875dc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-16 17:24 UTC, merged

2021-02-16 17:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602bffb56bcc775ddc9f9f4e--gamut-preview.netlify.app>https://602bffb56bcc775ddc9f9f4e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602bffb56bcc775ddc9f9f4e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->