feat(Alert)!: New Visual Identity Alert [GM-119]
Codecademy/client-modules pull request #1412
Opened 2021-02-17 05:20 UTC by codecaaron

### Overview

* Rebrands Alerts to new viisual identity.

### PR Checklist

- [x] Related to designs: [Figma](https://www.figma.com/file/TemYhRWOavsERWprDzRJCx/%5BWIP%5D-Alerts)
- [x] Related to JIRA ticket: GM-119
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-17 05:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.42-alpha.d84994.0<br/>@codecademy/gamut-labs@10.0.8-alpha.d84994.0<br/>@codecademy/gamut-styles@8.0.2-alpha.d84994.0<br/>@codecademy/gamut-tests@2.0.2-alpha.d84994.0<br/>@codecademy/gamut@23.0.2-alpha.d84994.0<br/>@codecademy/markdown-overrides@0.5.2-alpha.d84994.0<br/>@codecademy/styleguide@27.0.2-alpha.d84994.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-17 05:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602caaa56a016e50a942fed3--gamut-preview.netlify.app>https://602caaa56a016e50a942fed3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602caaa56a016e50a942fed3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-17 22:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.52d07c.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.52d07c.0<br/>@codecademy/gamut-labs@10.0.11-alpha.52d07c.0<br/>@codecademy/gamut@23.2.1-alpha.52d07c.0<br/>@codecademy/styleguide@27.2.1-alpha.52d07c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-17 22:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602d998f37aefc58ff5149fa--gamut-preview.netlify.app>https://602d998f37aefc58ff5149fa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602d998f37aefc58ff5149fa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-17 22:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.642f3a.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.642f3a.0<br/>@codecademy/gamut-labs@10.0.11-alpha.642f3a.0<br/>@codecademy/gamut@23.2.1-alpha.642f3a.0<br/>@codecademy/styleguide@27.2.1-alpha.642f3a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-17 22:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602d9c67c233055aa5f52d2c--gamut-preview.netlify.app>https://602d9c67c233055aa5f52d2c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602d9c67c233055aa5f52d2c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-17 22:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.5eed8e.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.5eed8e.0<br/>@codecademy/gamut-labs@10.0.11-alpha.5eed8e.0<br/>@codecademy/gamut@23.2.1-alpha.5eed8e.0<br/>@codecademy/styleguide@27.2.1-alpha.5eed8e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-17 22:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602d9ee9bf1ccc779c5721b0--gamut-preview.netlify.app>https://602d9ee9bf1ccc779c5721b0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602d9ee9bf1ccc779c5721b0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-17 23:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.8626a2.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.8626a2.0<br/>@codecademy/gamut-labs@10.0.11-alpha.8626a2.0<br/>@codecademy/gamut@23.2.1-alpha.8626a2.0<br/>@codecademy/styleguide@27.2.1-alpha.8626a2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-17 23:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602daa7bfc5823009e6bbb59--gamut-preview.netlify.app>https://602daa7bfc5823009e6bbb59--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602daa7bfc5823009e6bbb59>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 00:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.1e9f93.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.1e9f93.0<br/>@codecademy/gamut-labs@10.0.11-alpha.1e9f93.0<br/>@codecademy/gamut@23.2.1-alpha.1e9f93.0<br/>@codecademy/styleguide@27.2.1-alpha.1e9f93.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-18 00:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602daeb6bf5e8100f96afa63--gamut-preview.netlify.app>https://602daeb6bf5e8100f96afa63--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602daeb6bf5e8100f96afa63>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 00:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.40ab6c.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.40ab6c.0<br/>@codecademy/gamut-labs@10.0.11-alpha.40ab6c.0<br/>@codecademy/gamut@23.2.1-alpha.40ab6c.0<br/>@codecademy/styleguide@27.2.1-alpha.40ab6c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-18 00:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602db338dcfe561214a31309--gamut-preview.netlify.app>https://602db338dcfe561214a31309--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602db338dcfe561214a31309>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 05:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.576ba4.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.576ba4.0<br/>@codecademy/gamut-labs@10.0.11-alpha.576ba4.0<br/>@codecademy/gamut@23.2.1-alpha.576ba4.0<br/>@codecademy/styleguide@27.2.1-alpha.576ba4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-18 05:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602df611195b4c643a8b7e29--gamut-preview.netlify.app>https://602df611195b4c643a8b7e29--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602df611195b4c643a8b7e29>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 05:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.ac92a0.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.ac92a0.0<br/>@codecademy/gamut-labs@10.0.11-alpha.ac92a0.0<br/>@codecademy/gamut@23.2.1-alpha.ac92a0.0<br/>@codecademy/styleguide@27.2.1-alpha.ac92a0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-18 05:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602dfccb7d184d91f5cc5953--gamut-preview.netlify.app>https://602dfccb7d184d91f5cc5953--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602dfccb7d184d91f5cc5953>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 06:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.f2c87f.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.f2c87f.0<br/>@codecademy/gamut-labs@10.0.11-alpha.f2c87f.0<br/>@codecademy/gamut@23.2.1-alpha.f2c87f.0<br/>@codecademy/styleguide@27.2.1-alpha.f2c87f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-18 06:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602e096216ddfe7f676409bb--gamut-preview.netlify.app>https://602e096216ddfe7f676409bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602e096216ddfe7f676409bb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 18:48 UTC, dreamwasp approved these changes
just a couple lil tweaks + storybook weirdness but these are looking 🔥

2021-02-18 18:48 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/Alert/index.stories.mdx
> +
maybe add something about truncation to one line + consistent sizing. wanna make sure folks know this is a deliberate design choice

2021-02-18 18:48 UTC, dreamwasp commented on packages/gamut/src/Button/IconButton.tsx
> +      <Icon size={size === 'small' ? 16 : 24} aria-hidden />
good catch!

2021-02-18 18:48 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/Alert/index.stories.mdx
> +</Canvas>
![image](https://user-images.githubusercontent.com/58054751/108405603-41ccdf00-71ef-11eb-8306-fc9dee813c4a.png)

color variants aren't showing up correctly for me in the pr env

2021-02-19 15:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.15.1-alpha.b7359e.0<br/>@codecademy/gamut-illustrations@0.4.44-alpha.b7359e.0<br/>@codecademy/gamut-labs@10.0.11-alpha.b7359e.0<br/>@codecademy/gamut@23.2.1-alpha.b7359e.0<br/>@codecademy/styleguide@27.2.1-alpha.b7359e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 15:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.07ff52.0<br/>@codecademy/gamut-labs@10.1.1-alpha.07ff52.0<br/>@codecademy/gamut@25.0.1-alpha.07ff52.0<br/>@codecademy/styleguide@29.1.1-alpha.07ff52.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 15:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fd722567e982f207136c6--gamut-preview.netlify.app>https://602fd722567e982f207136c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fd722567e982f207136c6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 15:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.a7b930.0<br/>@codecademy/gamut-labs@10.1.1-alpha.a7b930.0<br/>@codecademy/gamut@25.0.1-alpha.a7b930.0<br/>@codecademy/styleguide@29.1.1-alpha.a7b930.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 15:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fd9afc136b932b68585ed--gamut-preview.netlify.app>https://602fd9afc136b932b68585ed--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fd9afc136b932b68585ed>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-20 02:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.a9dc4d.0<br/>@codecademy/gamut-labs@10.1.1-alpha.a9dc4d.0<br/>@codecademy/gamut@25.0.1-alpha.a9dc4d.0<br/>@codecademy/styleguide@29.1.1-alpha.a9dc4d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-20 02:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6030753f55041095af178460--gamut-preview.netlify.app>https://6030753f55041095af178460--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6030753f55041095af178460>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-22 17:56 UTC, JoshuaKGoldberg requested changes
The variants stuff is very snazzy. Requesting changes for accessibility please!

2021-02-22 17:56 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Alert/index.stories.mdx
> +- Displayed at the top of the page, below the navigation bar.
```suggestion
- Display alerts at the top of the page, below the navigation bar.
```

2021-02-22 17:56 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Alert/index.stories.mdx
> +**General**
Maybe?

```suggestion
### General
```

2021-02-22 17:56 UTC, JoshuaKGoldberg commented on packages/gamut/src/Alert/Alert.tsx
> +      columnGap={[4, 8, , 12]}
lol... I'm on the fence about this.

2021-02-22 17:56 UTC, JoshuaKGoldberg commented on packages/gamut/src/Alert/Alert.tsx
> +        <Icon size={16} aria-label={`${props.type}-icon`} />
The `aria-label` is what gets narrated to users. Something like _"general-icon"_ would be rather confusing to them. I think these icons are decorative and could have just `""` as the label / `aria-hidden` instead.

2021-02-22 17:56 UTC, JoshuaKGoldberg commented on packages/gamut/src/Alert/Alert.tsx
> +        <IconButton
On the flip side, this should have a label saying to expand / contract.

Alternately: could this use an `AccordionArea`?

2021-02-22 19:16 UTC, codecaaron commented on packages/gamut/src/Alert/Alert.tsx
> +        <Icon size={16} aria-label={`${props.type}-icon`} />
Good call.  IIRC I cribbed this from the previous implementation so updating this will be a net improvement :D

2021-02-22 19:21 UTC, codecaaron commented on packages/gamut/src/Alert/Alert.tsx
> +        <IconButton
Hmm I wonder, I'm gonna test it out :)

2021-02-24 02:22 UTC, codecaaron commented on packages/gamut/src/Alert/Alert.tsx
> +        <IconButton
So unfortunately I'm not sure accordion area is gonna work for this since there is no way to access the amount that has been truncated inside of `TruncateMarkup`.  So there wouldn't be a way to split between top / children.  I could be missing something but I don't think we'd be able to take advantage of the utility :(.

I updated it to have a similar animation effect however and the correct aria attributes :)

2021-02-24 02:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.10-alpha.633084.0<br/>@codecademy/gamut@25.3.3-alpha.633084.0<br/>@codecademy/styleguide@29.4.3-alpha.633084.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-24 02:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6035ba50962c82509dccf65a--gamut-preview.netlify.app>https://6035ba50962c82509dccf65a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6035ba50962c82509dccf65a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-25 16:23 UTC, JoshuaKGoldberg commented on packages/gamut/src/Alert/Alert.tsx
> +        <IconButton
Talked 1:1 - yeah, `AccordionArea` isn't the right thing for this.

2021-02-25 16:28 UTC, JoshuaKGoldberg approved these changes
Yeah this looks great. Thanks Aaron!

2021-03-02 15:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.9b2a3b.0<br/>@codecademy/gamut@25.4.1-alpha.9b2a3b.0<br/>@codecademy/styleguide@29.6.2-alpha.9b2a3b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-02 15:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603e58b8a3a1ec1fe1dda024--gamut-preview.netlify.app>https://603e58b8a3a1ec1fe1dda024--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603e58b8a3a1ec1fe1dda024>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-02 17:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.4067f7.0<br/>@codecademy/gamut@25.4.1-alpha.4067f7.0<br/>@codecademy/styleguide@29.6.2-alpha.4067f7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-02 17:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603e7343e6cc00195abc3d1a--gamut-preview.netlify.app>https://603e7343e6cc00195abc3d1a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603e7343e6cc00195abc3d1a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-02 17:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.00412e.0<br/>@codecademy/gamut@25.4.1-alpha.00412e.0<br/>@codecademy/styleguide@29.6.2-alpha.00412e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-02 17:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603e76586b33aa19fade700c--gamut-preview.netlify.app>https://603e76586b33aa19fade700c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603e76586b33aa19fade700c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-02 22:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.aa92e8.0<br/>@codecademy/gamut@25.4.1-alpha.aa92e8.0<br/>@codecademy/styleguide@29.6.2-alpha.aa92e8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-02 22:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603ebbf35ea31943a56b77ba--gamut-preview.netlify.app>https://603ebbf35ea31943a56b77ba--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603ebbf35ea31943a56b77ba>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 03:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.4-alpha.e6c088.0<br/>@codecademy/gamut@25.4.2-alpha.e6c088.0<br/>@codecademy/styleguide@29.6.5-alpha.e6c088.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 03:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604057205b06ef480f38f280--gamut-preview.netlify.app>https://604057205b06ef480f38f280--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604057205b06ef480f38f280>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 19:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.4.2-alpha.fe021e.0<br/>@codecademy/gamut@25.4.4-alpha.fe021e.0<br/>@codecademy/styleguide@29.6.8-alpha.fe021e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 19:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.4.2-alpha.63ac50.0<br/>@codecademy/gamut@25.4.4-alpha.63ac50.0<br/>@codecademy/styleguide@29.6.8-alpha.63ac50.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 19:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6041340554c22e0696478c1b--gamut-preview.netlify.app>https://6041340554c22e0696478c1b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6041340554c22e0696478c1b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 21:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.4.5-alpha.5367d9.0<br/>@codecademy/gamut@25.5.2-alpha.5367d9.0<br/>@codecademy/styleguide@29.7.1-alpha.5367d9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 21:39 UTC, merged

2021-03-04 21:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604153b89d37a91381104533--gamut-preview.netlify.app>https://604153b89d37a91381104533--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604153b89d37a91381104533>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->