feat: add linting for gamut imports
Codecademy/client-modules pull request #1415
Opened 2021-02-17 18:01 UTC by sylvanasantos

### Overview

- added a new linting rule to enforce proper path declarations for gamut dependencies

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Testing

1. Checkout jg-ss-gamut-linting
2. Run yarn lint and ensure everything looks good
3. Change some import statements in different files and make sure you get the correct errors
     
Examples: 
- In a stories.mdx file, add an import statement with @codecademy/gamut-styles/src or @codecademy/gamut-styles/dist
- In a stories.mdx file, remove /src from an import statement for @codecademy/gamut 
- In a component files, add /src to an import statement for @codecademy/gamut

2021-02-17 19:00 UTC, JoshuaKGoldberg requested changes
This looks great! Props for a fantastic first lint rule!

Just requesting changes on the file name being not `temp/lint.js` 😛

2021-02-17 19:00 UTC, JoshuaKGoldberg commented on packages/gamut/temp/lint.js
> +        if (node.source.value.includes('src')) {
On the off chance a file name happens to include `src`?

```suggestion
        if (node.source.value.includes('/src')) {
```

2021-02-17 19:00 UTC, JoshuaKGoldberg commented on packages/gamut/temp/lint.js
> +      description: 'Ensure module paths are declared correctly',
Could you make this a little more clear? Maybe something about specifically _Gamut_ module paths?

2021-02-17 19:00 UTC, JoshuaKGoldberg commented on packages/gamut/temp/lint.js
> +module.exports.default = {
> `temp/lint.js`

😛  let's find a better file path than the temporary pairing one. Maybe one of something like...

* `/packages/gamut-eslint/gamut-import-paths`?
* `/packages/gamut-dev-eslint/gamut-import-paths`?
* `/eslint/gamut-import-paths`?

2021-02-17 19:00 UTC, JoshuaKGoldberg commented on packages/gamut/temp/lint.js
> +          if (importPath.includes('/gamut-styles/src')) {
You know, if the path _`endsWith`_ the `/src`(`/`) or `/dist`(`/`) and not just _includes_ it, you could add an auto-fixer to fix it up... what do you think? Up for doing that here, or in a followup?

2021-02-19 15:22 UTC, dreamwasp approved these changes
this is 😍  😍 

once the` temp/lint.js` file name is changed this is ✨

2021-02-19 15:28 UTC, sylvanasantos commented on packages/gamut/temp/lint.js
> +          if (importPath.includes('/gamut-styles/src')) {
i think i did this? lol

2021-02-19 15:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.0.12-alpha.3414f4.0<br/>@codecademy/styleguide@27.2.2-alpha.3414f4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 15:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fda4f6be83036e89d9cb7--gamut-preview.netlify.app>https://602fda4f6be83036e89d9cb7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fda4f6be83036e89d9cb7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 15:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.1-alpha.ddd99f.0<br/>@codecademy/styleguide@29.1.1-alpha.ddd99f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 15:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fdc39c0150b3d4f29c713--gamut-preview.netlify.app>https://602fdc39c0150b3d4f29c713--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fdc39c0150b3d4f29c713>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 15:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.1-alpha.a70503.0<br/>@codecademy/styleguide@29.1.1-alpha.a70503.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 15:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fdea3101e66455ee326a4--gamut-preview.netlify.app>https://602fdea3101e66455ee326a4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fdea3101e66455ee326a4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-22 20:15 UTC, JoshuaKGoldberg approved these changes
This is fantastic!

2021-02-22 20:15 UTC, JoshuaKGoldberg commented on eslint/gamut-import-paths.js
> +          const indexOfSrc = node.source.range[0] + importPath.search('/src');
This is only used in the `fix` function. You could move it into there. Same with the `indexOfDist` below.

2021-02-25 14:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.11-alpha.7e7136.0<br/>@codecademy/styleguide@29.4.4-alpha.7e7136.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-25 14:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6037af6b55b0191d61698b1b--gamut-preview.netlify.app>https://6037af6b55b0191d61698b1b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6037af6b55b0191d61698b1b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-25 14:12 UTC, merged