WIP: new notifications list & component
Codecademy/client-modules pull request #1418
Opened 2021-02-17 22:25 UTC by saghdaey

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-17 22:26 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/index.tsx
> +          You&apos;re all caught up!
being replaced by empty notifications container created in https://codecademy.atlassian.net/browse/EGG-689

2021-02-17 22:26 UTC, saghdaey commented on packages/gamut/src/Pattern/index.tsx
> +  position: absolute; // Can I do this? Or do I need to make this passable as a prop? This does mess up the story
going to test alpha build out in monolith

2021-02-17 22:27 UTC, saghdaey commented on packages/gamut/src/index.tsx
> +export * from './NotificationListNew/NotificationItemNew';
will be renamed once old notification components are deprecated & feature flag for persistent notifications (+ notifications UI update) is at 100% for some time

2021-02-17 22:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.45-alpha.b35bf6.0<br/>@codecademy/gamut-labs@10.0.12-alpha.b35bf6.0<br/>@codecademy/gamut@23.2.2-alpha.b35bf6.0<br/>@codecademy/styleguide@27.2.2-alpha.b35bf6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-17 22:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602d991306370a6c015c5026--gamut-preview.netlify.app>https://602d991306370a6c015c5026--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602d991306370a6c015c5026>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 00:02 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +      <Truncate lines={3}>{text}</Truncate>
Oh hey about the truncation: do we still want it? Last I checked, marketing was intentionally crafting messages to avoid triggering it. 

cc @codecaaron

2021-02-18 00:08 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +      <Truncate lines={3}>{text}</Truncate>
Oh hey, I just had a talk with Yassine about this today.

 I know we do want it in other areas (Alerts), but I am not sure about this one.  Could we get away with a character limit here instead?

2021-02-18 14:17 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +      <Truncate lines={3}>{text}</Truncate>
Oh good to know! I'll check in with Tuba

2021-02-19 14:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.4b9df3.0<br/>@codecademy/gamut-labs@10.0.14-alpha.4b9df3.0<br/>@codecademy/gamut@25.0.1-alpha.4b9df3.0<br/>@codecademy/styleguide@29.0.1-alpha.4b9df3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 14:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fc6b94b25ab0ffc7fa942--gamut-preview.netlify.app>https://602fc6b94b25ab0ffc7fa942--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fc6b94b25ab0ffc7fa942>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 14:20 UTC, saghdaey commented on packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
> +import { examples } from './NotificationList.stories.mdx';
Once we deprecate NotificationList +/or modify the example Notifications more to tailor the new notifications, we can move the examples out of the old stories component

2021-02-19 14:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.9d58a4.0<br/>@codecademy/gamut-labs@10.0.14-alpha.9d58a4.0<br/>@codecademy/gamut@25.0.1-alpha.9d58a4.0<br/>@codecademy/styleguide@29.0.1-alpha.9d58a4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 14:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fd0f52ffdea347d9f08d4--gamut-preview.netlify.app>https://602fd0f52ffdea347d9f08d4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fd0f52ffdea347d9f08d4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 15:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.98f1c3.0<br/>@codecademy/gamut-labs@10.1.1-alpha.98f1c3.0<br/>@codecademy/gamut@25.0.1-alpha.98f1c3.0<br/>@codecademy/styleguide@29.1.1-alpha.98f1c3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 15:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fd6cf3637795756e38b79--gamut-preview.netlify.app>https://602fd6cf3637795756e38b79--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fd6cf3637795756e38b79>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 15:33 UTC, saghdaey commented on packages/gamut/src/Pattern/index.tsx
> +  position: absolute; // Can I do this? Or do I need to make this passable as a prop? This does mess up the story
tested the EmptyEnrollments; no visible change with the position absolute

2021-02-19 15:34 UTC, katiezutter reviewed
Love this new notifications list! Visually beautiful, nice work! Just left a few minor comments.

2021-02-19 15:34 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +const StyledLink = styled.a`
Could this be `styled(Anchor)` or is there a reason it shouldn't be?

2021-02-19 15:34 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/__tests__/NotificationItemNew-test.tsx
> +};
I think these could be DRYed up!

2021-02-19 15:34 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/assets/message.svg
> +</svg>
Where is this used?

2021-02-19 15:34 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/index.tsx
> +      <Pattern name="dotsDense" height="1px" position="relative" />
Cool how you did the dot border! I think this needs to be down in the `isEmpty(notifications) == false` branch of the conditional though

2021-02-19 15:34 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +            </IconButton>
Is the Close button supposed to have this hover state? Couldn't tell from the Figma

2021-02-19 15:35 UTC, saghdaey commented on packages/gamut/src/Pattern/index.tsx
> +  position: absolute; // Can I do this? Or do I need to make this passable as a prop? This does mess up the story
@codecaaron thoughts? 
if i shouldn't force position absolute, i could do this instead?


`const Svg = styled.svg<{ position: svgProps }>`
  width: 100%;
  height: 100%;
  position: position;
`;

export const Pattern: React.FC<PatternProps> = ({
  name,
  svgPosition = 'static',
  ...props
}) => (
  <Box {...props}>
    <Svg position={svgPosition}>
      {defs(name)}
      <rect x="0" y="0" width="100%" height="100%" fill={`url(#${name})`} />
    </Svg>
  </Box>
);
`

2021-02-19 15:36 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/index.tsx
> +      <Pattern name="dotsDense" height="1px" position="relative" />
there's a dot border above the notification empty state too! see figma: https://www.figma.com/file/KIqFTtIa7WoDA8G1owEvYL/%5BWIP%5D-Notifications?node-id=620%3A233

2021-02-19 15:37 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/index.tsx
> +        <div>Empty Notifications Placeholder </div>
Curious about your conversation with @sooinc! Why did you decide to keep the empty state in this component?

2021-02-19 15:37 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +            </IconButton>
yep! I talked to Tuba about it and she said:
Clickable Notification:
Hover on notification : full background changes to Grey $color-grey-100
Hover on the dismiss icon: background changes to Grey $color-grey-200

Notification that is not clickable
Hover on dismiss icon: background changes to Grey $color-grey-200

2021-02-19 15:37 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/index.tsx
> +      <Pattern name="dotsDense" height="1px" position="relative" />
Oh woah!! Ignore me 😅

2021-02-19 15:38 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +            </IconButton>
Awesome 😎

2021-02-19 15:38 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/assets/message.svg
> +</svg>
I initially was going to do the notification type - icon matching but ended up splitting that to another ticket, since we're still waiting for assets for each type of notification. I'll remove this one! come to think of it, this isn't needed until community forum notifications anyway. oops!

2021-02-19 15:39 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/assets/message.svg
> +</svg>
Got it!

2021-02-19 15:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.bd9525.0<br/>@codecademy/gamut-labs@10.1.1-alpha.bd9525.0<br/>@codecademy/gamut@25.0.1-alpha.bd9525.0<br/>@codecademy/styleguide@29.1.1-alpha.bd9525.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 15:46 UTC, katiezutter approved these changes
Thanks for addressing those comments so quickly - nothing blocking left on my end!

2021-02-19 15:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fdd4ad52bff42f13ffa5d--gamut-preview.netlify.app>https://602fdd4ad52bff42f13ffa5d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fdd4ad52bff42f13ffa5d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 15:50 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +const StyledLink = styled.a`
I ran into similar issues as when we were working on the app header; and needed to customize Anchor too much! I can try to play w it more but tbh gave up

2021-02-19 15:50 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/assets/message.svg
> +</svg>
thanks for catching :)

2021-02-19 15:53 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/index.tsx
> +        <div>Empty Notifications Placeholder </div>
a couple reasons - to keep notification related components coupled together; so that the empty container & the notifications could share that top dotted border; & also bc that's how it's currently done in the old notifications list
I can see a world where we go back on this decision as we add more functionality in the monolith

2021-02-19 15:54 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/index.tsx
> +        <div>Empty Notifications Placeholder </div>
Make sense to me!! Thanks

2021-02-19 15:54 UTC, katiezutter commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +const StyledLink = styled.a`
Not worth playing with it more imo!!

2021-02-19 16:02 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/__tests__/NotificationItemNew-test.tsx
> +};
will fix!

2021-02-19 16:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.079277.0<br/>@codecademy/gamut-labs@10.1.1-alpha.079277.0<br/>@codecademy/gamut@25.0.1-alpha.079277.0<br/>@codecademy/styleguide@29.1.1-alpha.079277.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 16:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fe4093856f32ca610e93c--gamut-preview.netlify.app>https://602fe4093856f32ca610e93c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fe4093856f32ca610e93c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 16:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.5d33da.0<br/>@codecademy/gamut-labs@10.1.1-alpha.5d33da.0<br/>@codecademy/gamut@25.0.1-alpha.5d33da.0<br/>@codecademy/styleguide@29.1.1-alpha.5d33da.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 16:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fe5673856f32da510eca5--gamut-preview.netlify.app>https://602fe5673856f32da510eca5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fe5673856f32da510eca5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 16:21 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/__tests__/NotificationItemNew-test.tsx
> +  it('does not renders a link if no href is specified', () => {
oops typo
does not render*** 
will fix

2021-02-19 16:21 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/index.tsx
> +  className?: string;
unused; will delete

2021-02-19 16:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.75138b.0<br/>@codecademy/gamut-labs@10.1.1-alpha.75138b.0<br/>@codecademy/gamut@25.0.1-alpha.75138b.0<br/>@codecademy/styleguide@29.1.1-alpha.75138b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 16:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fe7b36be8304b879d99a9--gamut-preview.netlify.app>https://602fe7b36be8304b879d99a9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fe7b36be8304b879d99a9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 16:33 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/assets/bell.svg
> +<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
Saw the comments on @sooinc 's PR - thinking I should also move to gamut-illustrations?

2021-02-19 17:10 UTC, JoshuaKGoldberg requested changes
Looks good so far!

Codecov pointed out some general areas of missing test coverage, and I agree with the illustrations suggestion.

2021-02-19 17:10 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/__tests__/NotificationItemNew-test.tsx
> +import { render, screen } from '@testing-library/react';
Oh would you mind switching to `@codecademy/gamut-tests`? We're going to start spreading it more actively soon - it sets up a `ThemeProvider` for Gamut nicely so these tests won't break once the components start using the Emotion theme.

_(search for `${({ theme` to see examples of using the provider)_

2021-02-19 17:10 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/assets/bell.svg
> +<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
Yes please 😄

2021-02-19 17:10 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
> +New notifications list component. Icon depends on notification type, else default bell icon displayed.
This is pretty terse; maybe a more approachable phrasing?

```suggestion
New notifications list component. Each notification has in icon depending on its notification type, defaulting to a bell icon if none is provided.
```

2021-02-19 17:15 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +              <CloseIcon height={10} width={10} />
yeah, it's not narrated by voice over! remember with search component this also happened (in the static sites PR to use gamut global header)

2021-02-19 18:13 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/__tests__/NotificationItemNew-test.tsx
> +import { render, screen } from '@testing-library/react';
done! wow so nice

2021-02-19 18:13 UTC, saghdaey commented on packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
> +New notifications list component. Icon depends on notification type, else default bell icon displayed.
that definitely reads better; thanks! updated

2021-02-19 18:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.9d3172.0<br/>@codecademy/gamut-labs@10.1.1-alpha.9d3172.0<br/>@codecademy/gamut@25.0.1-alpha.9d3172.0<br/>@codecademy/styleguide@29.1.1-alpha.9d3172.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 18:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603000ff5c468a00fa676fda--gamut-preview.netlify.app>https://603000ff5c468a00fa676fda--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603000ff5c468a00fa676fda>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 20:05 UTC, saghdaey commented on packages/gamut-illustrations/package.json
> -    "@codecademy/gamut": "^25.0.0",
this fixes circular dependencies issue after I added gamut-illustrations to gamut dependencies @codecaaron

2021-02-19 20:05 UTC, saghdaey commented on packages/gamut-illustrations/package.json
> -    "@codecademy/gamut": "^25.0.0",
I checked and gamut-illustrations was actually not using gamut anywhere

2021-02-19 20:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.07d4c8.0<br/>@codecademy/gamut-labs@10.1.1-alpha.07d4c8.0<br/>@codecademy/gamut@25.0.1-alpha.07d4c8.0<br/>@codecademy/styleguide@29.1.1-alpha.07d4c8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 20:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.36449a.0<br/>@codecademy/gamut-labs@10.1.1-alpha.36449a.0<br/>@codecademy/gamut@25.0.1-alpha.36449a.0<br/>@codecademy/styleguide@29.1.1-alpha.36449a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 20:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60301bc6b2938b2293846f54--gamut-preview.netlify.app>https://60301bc6b2938b2293846f54--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60301bc6b2938b2293846f54>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 20:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.458856.0<br/>@codecademy/gamut-labs@10.1.1-alpha.458856.0<br/>@codecademy/gamut@25.0.1-alpha.458856.0<br/>@codecademy/styleguide@29.1.1-alpha.458856.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 20:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603021ddf3ce8523e3a019b2--gamut-preview.netlify.app>https://603021ddf3ce8523e3a019b2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603021ddf3ce8523e3a019b2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 20:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.cbc6b7.0<br/>@codecademy/gamut-labs@10.1.1-alpha.cbc6b7.0<br/>@codecademy/gamut@25.0.1-alpha.cbc6b7.0<br/>@codecademy/styleguide@29.1.1-alpha.cbc6b7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 20:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603024b9d1886a1eee8e5f34--gamut-preview.netlify.app>https://603024b9d1886a1eee8e5f34--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603024b9d1886a1eee8e5f34>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 20:58 UTC, codecaaron submitted a review, later dismissed

2021-02-19 20:58 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +`;
We should use our IconButton here https://gamut.codecademy.com/storybook/?path=/docs/atoms-button--light-mode

And `MiniDeleteIcon` from gamut icons.

2021-02-19 20:58 UTC, codecaaron commented on packages/gamut/src/Pattern/index.tsx
> +  position: ${({ position }) => position};
Hmm, I think we might be able to solve this without adding new props to anything.  Want to pair on it?

2021-02-19 22:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.c58a61.0<br/>@codecademy/gamut-labs@10.1.1-alpha.c58a61.0<br/>@codecademy/gamut@25.0.1-alpha.c58a61.0<br/>@codecademy/styleguide@29.1.1-alpha.c58a61.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 22:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60303b2550dc5838b67597e7--gamut-preview.netlify.app>https://60303b2550dc5838b67597e7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60303b2550dc5838b67597e7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-22 14:39 UTC, jakemhiller commented on packages/gamut-illustrations/package.json
> -    "@codecademy/gamut": "^25.0.0",
I was wondering why gamut-illustrations was being updated when we updated gamut, good find!

2021-02-22 15:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.54e95e.0<br/>@codecademy/gamut-labs@10.1.2-alpha.54e95e.0<br/>@codecademy/gamut@25.0.1-alpha.54e95e.0<br/>@codecademy/styleguide@29.1.2-alpha.54e95e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-22 15:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6033c9526df84d49b2df7fbc--gamut-preview.netlify.app>https://6033c9526df84d49b2df7fbc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6033c9526df84d49b2df7fbc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-22 15:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.2974d5.0<br/>@codecademy/gamut-labs@10.1.2-alpha.2974d5.0<br/>@codecademy/gamut@25.0.1-alpha.2974d5.0<br/>@codecademy/styleguide@29.1.3-alpha.2974d5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-22 15:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6033cce5963d4c46c648d64a--gamut-preview.netlify.app>https://6033cce5963d4c46c648d64a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6033cce5963d4c46c648d64a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-22 17:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.0e9cd3.0<br/>@codecademy/gamut-labs@10.1.2-alpha.0e9cd3.0<br/>@codecademy/gamut@25.0.1-alpha.0e9cd3.0<br/>@codecademy/styleguide@29.1.3-alpha.0e9cd3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-22 17:13 UTC, merged

2021-02-22 17:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6033e65f226abe0ac4d3fc2a--gamut-preview.netlify.app>https://6033e65f226abe0ac4d3fc2a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6033e65f226abe0ac4d3fc2a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->