fix TOC links
Codecademy/client-modules pull request #1421
Opened 2021-02-18 20:29 UTC by dreamwasp

### Overview
Tweak to how Gamut generates page links + fixes previous broken Table of Contents links like Button + Theme

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-18 20:30 UTC, JoshuaKGoldberg commented on packages/styleguide/.storybook/components/TableOfContents/utils.tsx
> +  console.log('Store', storiesStore);
```suggestion
```

2021-02-18 20:30 UTC, codecaaron requested changes

2021-02-18 20:30 UTC, codecaaron commented on packages/styleguide/.storybook/components/TableOfContents/utils.tsx
> +  console.log('Store', storiesStore);
```suggestion
  const allStories = useMemo(() => Object.keys(storyStore?._stories), [storyStore?._stories])
```

2021-02-18 20:36 UTC, dreamwasp commented on packages/styleguide/.storybook/components/TableOfContents/utils.tsx
> +  console.log('Store', storiesStore);
d'oh

2021-02-18 20:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@27.2.2-alpha.68a316.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-18 20:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602ed0c7b96f443755735afd--gamut-preview.netlify.app>https://602ed0c7b96f443755735afd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602ed0c7b96f443755735afd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-18 20:42 UTC, codecaaron approved these changes
🚀

2021-02-18 20:47 UTC, JoshuaKGoldberg approved these changes
🚢

2021-02-23 15:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@29.3.4-alpha.f31cff.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-23 15:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60351bdeaef4b52cf9e64da7--gamut-preview.netlify.app>https://60351bdeaef4b52cf9e64da7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60351bdeaef4b52cf9e64da7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-23 15:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@29.3.5-alpha.f4c9ce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-23 15:20 UTC, merged

2021-02-23 15:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60351d5bb8b2f12d2dd3c779--gamut-preview.netlify.app>https://60351d5bb8b2f12d2dd3c779--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60351d5bb8b2f12d2dd3c779>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->