Sc empty notification
Codecademy/client-modules pull request #1422
Opened 2021-02-19 14:09 UTC by sooinc

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-19 14:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.4.47-alpha.a920a6.0<br/>@codecademy/gamut-labs@10.0.14-alpha.a920a6.0<br/>@codecademy/gamut@25.0.1-alpha.a920a6.0<br/>@codecademy/styleguide@29.0.1-alpha.a920a6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-19 14:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://602fc9d0c0150b277629c1cd--gamut-preview.netlify.app>https://602fc9d0c0150b277629c1cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/602fc9d0c0150b277629c1cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-19 14:38 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/assets/bee.svg
> +<svg width="75" height="52" viewBox="0 0 75 52" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
These might make sense to belong in https://github.com/Codecademy/client-modules/tree/main/packages/gamut-illustrations

2021-02-19 15:22 UTC, sooinc commented on packages/gamut/src/NotificationListNew/assets/bee.svg
> +<svg width="75" height="52" viewBox="0 0 75 52" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
ooh yes, will move them!

2021-02-19 15:22 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/assets/bee.svg
> +<svg width="75" height="52" viewBox="0 0 75 52" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
LMK when you make the change, we'll need to reorder our dependency graph a bit to have gamut consume illustrations :)

2021-02-19 15:22 UTC, JoshuaKGoldberg requested changes
Looks great in general! A couple of touchups & the moving illustrations to gamut-illustrations, if you don't mind 😁

2021-02-19 15:22 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/EmptyNotification.tsx
> +  const randomIndex = getRandomIndex(emptyNotificationMessages.length);
✨   https://lodash.com/docs/4.17.15#sample ✨ 

```ts
import { sample } from 'lodash';
```

```suggestion
  const message = sample(emptyNotificationMessages);
```

2021-02-19 15:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
> +## Empty Notification
Could you add a little explanation here about the randomization? A new reader likely wouldn't pick up on it.

2021-02-19 15:22 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/EmptyNotification.tsx
> +        <Text>{emptyNotificationMessages[randomIndex].subtext}</Text>{' '}
Little extra `{' '}` on there from the Prettier run? 😄

2021-02-19 15:22 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/assets/emptyNotificationMessages.tsx
> +export const slugToSvgMap: Record<string, string> = {
Nit: you should be able to get away with not including this:

```suggestion
export const slugToSvgMap = {
```

If you use an `as const` on `emptyNotificationMessages`. I think that'd be a little more preferable because it's more representative of how the types work. https://blog.logrocket.com/const-assertions-are-the-killer-new-typescript-feature-b73451f35802/

Meaning: `slugToSvgMap` is really only supposed to be used with one of these known keys (`'bee'`, `'confetti'`, ...). `Record<string, string>` says it will give back a `string` value under _any_ key.

Definitely not a high priority change request 😄, just a nice-to-have.

2021-02-23 14:07 UTC, sooinc commented on packages/gamut/src/NotificationListNew/EmptyNotification.tsx
> +  const randomIndex = getRandomIndex(emptyNotificationMessages.length);
✨✨✨

2021-02-23 14:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.6-alpha.036858.0<br/>@codecademy/gamut@25.2.2-alpha.036858.0<br/>@codecademy/styleguide@29.3.4-alpha.036858.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-23 14:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60350ccf99afcc1b95d3013c--gamut-preview.netlify.app>https://60350ccf99afcc1b95d3013c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60350ccf99afcc1b95d3013c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-23 14:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.6.1-alpha.58f34f.0<br/>@codecademy/gamut-labs@10.1.6-alpha.58f34f.0<br/>@codecademy/gamut@25.2.2-alpha.58f34f.0<br/>@codecademy/styleguide@29.3.4-alpha.58f34f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-23 14:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60350e40f4261b1d2140ae54--gamut-preview.netlify.app>https://60350e40f4261b1d2140ae54--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60350e40f4261b1d2140ae54>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-23 14:18 UTC, sooinc commented on packages/gamut/src/NotificationListNew/EmptyNotification.tsx
> +        <Text>{emptyNotificationMessages[randomIndex].subtext}</Text>{' '}
😅

2021-02-23 14:19 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/EmptyNotification.tsx
> +        <Text>{emptyNotificationMessages[randomIndex].subtext}</Text>{' '}
this happened to me yesterday too ha!

2021-02-23 14:20 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
> +  const content = sample(emptyNotificationContents)!;
rad

2021-02-23 14:21 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
> +        return <Sun height={60} width={60} />;
are these supposed to all be dif heights & widths? i wonder if that was intentional by design

2021-02-23 14:22 UTC, saghdaey commented on packages/gamut/src/Pattern/index.tsx
> +  position: absolute; // Can I do this? Or do I need to make this passable as a prop? This does mess up the story
this must have been bc you branched off of my feature branch. you can delete this line! we found a better solution :)

2021-02-23 14:23 UTC, sooinc commented on packages/gamut/src/Pattern/index.tsx
> +  position: absolute; // Can I do this? Or do I need to make this passable as a prop? This does mess up the story
yea just saw this. removing! :D

2021-02-23 14:24 UTC, sooinc commented on packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
> +        return <Sun height={60} width={60} />;
this was straight off the figma. i can share with tuba and double check it's all looking good.

2021-02-23 14:24 UTC, sooinc commented on packages/gamut/src/NotificationListNew/assets/emptyNotificationMessages.tsx
> +export const slugToSvgMap: Record<string, string> = {
ooh thanks for teaching me!

2021-02-23 14:28 UTC, JoshuaKGoldberg approved these changes
Rad indeed.

2021-02-23 14:28 UTC, JoshuaKGoldberg commented on packages/gamut-illustrations/src/Bee.tsx
> +        xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAACkSURBVHgB7dcxEsIwDAVR6f53Boo/FNBkPEkYrN3Xye
This image is of a repeating pattern... do you think the designer could crop it to save a little bit of bandwidth?

Definitely not high priority (the image is pretty small as-is).

2021-02-23 14:29 UTC, JoshuaKGoldberg commented
The note in the description about waiting for another branch is about this visual hiccup in the Storybook, right? 😄 

![Notification list in storybook with dark pattern backgrounds](https://user-images.githubusercontent.com/3335181/108857960-a4402980-75b9-11eb-9b0b-9c38287a5794.png)

2021-02-23 14:36 UTC, sooinc commented
> The note in the description about waiting for another branch is about this visual hiccup in the Storybook, right? 😄
> 
> ![Notification list in storybook with dark pattern backgrounds](https://user-images.githubusercontent.com/3335181/108857960-a4402980-75b9-11eb-9b0b-9c38287a5794.png)

yes that's right!

2021-02-23 14:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.6.1-alpha.c38728.0<br/>@codecademy/gamut-labs@10.1.6-alpha.c38728.0<br/>@codecademy/gamut@25.2.2-alpha.c38728.0<br/>@codecademy/styleguide@29.3.4-alpha.c38728.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-23 14:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603514bd99afcc24bbd2fdc4--gamut-preview.netlify.app>https://603514bd99afcc24bbd2fdc4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603514bd99afcc24bbd2fdc4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-23 15:44 UTC, sooinc commented on packages/gamut-illustrations/src/Bee.tsx
> +        xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAACkSURBVHgB7dcxEsIwDAVR6f53Boo/FNBkPEkYrN3Xye
sorry if this is obvious...but how were you able to tell it is of a repeating pattern?

2021-02-23 17:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.6.1-alpha.2aaedb.0<br/>@codecademy/gamut-labs@10.1.6-alpha.2aaedb.0<br/>@codecademy/gamut@25.2.2-alpha.2aaedb.0<br/>@codecademy/styleguide@29.3.4-alpha.2aaedb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-23 17:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60354285091eef00a9d7cbfa--gamut-preview.netlify.app>https://60354285091eef00a9d7cbfa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60354285091eef00a9d7cbfa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-23 18:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.6.1-alpha.52fe78.0<br/>@codecademy/gamut-labs@10.1.7-alpha.52fe78.0<br/>@codecademy/gamut@25.2.3-alpha.52fe78.0<br/>@codecademy/styleguide@29.3.6-alpha.52fe78.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-23 18:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6035452217e47b0b228fc730--gamut-preview.netlify.app>https://6035452217e47b0b228fc730--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6035452217e47b0b228fc730>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-23 18:32 UTC, merged