Je header animation
Codecademy/client-modules pull request #1430
Opened 2021-02-23 16:34 UTC by jcenglish

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-23 16:46 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +        className={props.className}
Added prop for className

2021-02-23 16:59 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +        display={{ base: 'block', md: 'none' }}
I have not yet added className prop to the AppHeaderMobile container because it's complicated...

2021-02-23 17:29 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +export const AnimatedGlobalHeader: React.FC<GlobalHeaderProps> = (props) => {
@katiezutter suggested adding a boolean `animated` prop to GlobalHeader that would turn the animation on and off, for testing and feature-flagging purposes. I just added this AnimatedGlobalHeader for easy testing locally.

2021-02-23 17:29 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +const defaultScrollingState = {
CHANGES  START HERE

2021-02-23 17:30 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +    const currentScrollPosition = window?.pageYOffset;
Needs a default numeric value for SSR.

2021-02-23 17:35 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +  const throttledHandleScroll = throttle(handleScrolling, 200);
Needs to be in `useCallback`.

https://rajeshnaroth.medium.com/using-throttle-and-debounce-in-a-react-function-component-5489fc3461b3

2021-02-24 16:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.0.7-alpha.0d00ee.0<br/>@codecademy/styleguide@27.0.1-alpha.0d00ee.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-24 16:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60367d4e18bbf83ce60d1601--gamut-preview.netlify.app>https://60367d4e18bbf83ce60d1601--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60367d4e18bbf83ce60d1601>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-24 17:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603686add6eada00a3893e8a--gamut-preview.netlify.app>https://603686add6eada00a3893e8a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603686add6eada00a3893e8a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-24 17:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.10-alpha.015fae.0<br/>@codecademy/styleguide@29.4.3-alpha.015fae.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-25 01:52 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +export const GlobalHeader: React.FC<GlobalHeaderProps> = (props) => {
> React Headroom / Headroom.js? I looked into using this, but I'm not sure if this could account for both of the main animation states (fading static header vs sliding sticky header)

@jcenglish when you say "not sure", do you mean it may or may not be doable, or do you mean you tried it out and couldn't get it to work? It seems to me like using a standard open source library to get rid of all those yucky edge cases in the otherwise tricky-to-get-right single-DOM-element version would be a much easier solution than rolling any form of logic on our own.

It looks to me like those might work if you do CSS opacity shenanigans on them per their class names?

2021-02-26 18:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.2-alpha.1a2bfe.0<br/>@codecademy/styleguide@29.5.2-alpha.1a2bfe.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-26 18:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603937a93a7cac007e374720--gamut-preview.netlify.app>https://603937a93a7cac007e374720--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603937a93a7cac007e374720>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-26 19:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.2-alpha.51e827.0<br/>@codecademy/styleguide@29.5.2-alpha.51e827.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-26 19:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6039513e9e33f31e78fbaf68--gamut-preview.netlify.app>https://6039513e9e33f31e78fbaf68--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6039513e9e33f31e78fbaf68>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 15:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.2-alpha.0e9748.0<br/>@codecademy/styleguide@29.5.2-alpha.0e9748.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 15:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d0a4b2e75db00bde0c43d--gamut-preview.netlify.app>https://603d0a4b2e75db00bde0c43d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d0a4b2e75db00bde0c43d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 17:56 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +  const throttledHandleScroll = throttle(handleScrolling, 200);
Ahhh... I wrote about this in **Issues** above.

Using throttle correctly in a callback causes all manner of visual glitches. Go to http://blobfish.codecademy.com to see how it works **without throttle**. It works fine on my Samsung Galaxy Note 10+ with no slowdowns. I am concerned about less powerful phones though.

2021-03-01 18:06 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/__tests__/GlobalHeader-test.tsx
> +});
Is this right? It can be more DRY by making a renderAnimatedGlobalHeader function out of the `animated` prop, but... Basically, I think I want to test that the AnimatedGlobalHeader shows for all sites and user types, and that the BasicGlobalHeader - the original GlobalHeader - does not show when the `animated` prop is `true`. And the inverse, when the `animated` prop is `false`. It's just a lot of the same thing, which gives me pause.

2021-03-01 21:41 UTC, JoshuaKGoldberg requested changes
Playing around on https://pr-22485.dev-eks.codecademy.com/learn, I can still pretty reliably get the bug where scrolling up and then clicking on a dropdown causes it to disappear. 😞

IMO that's a blocker?

2021-03-01 21:42 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalHeader/AnimatedGlobalHeader/index.tsx
> +const defaultScrollingState = {
This looks like it was lifted pretty directly from the old class state, right? Normally we'd set an individual `useState` for each member with these defaults and update them individually. That gives us a little better dependency tracking in general.

2021-03-01 21:43 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalHeader/AnimatedGlobalHeader/index.tsx
> +      typeof window === 'undefined' ? 0 : window?.pageYOffset;
There's no circumstance in which `window` wouldn't exist but the scroll listener would still fire. You can make this less safe. 😈 

```suggestion
    const currentScrollPosition = window.pageYOffset;
```

2021-03-01 21:44 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalHeader/AnimatedGlobalHeader/index.tsx
> +  useEffect(() => {
https://github.com/streamich/react-use/blob/master/docs/useEvent.md 😁  a bit less code!

2021-03-04 22:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.1.1-alpha.edd0f3.0<br/>@codecademy/gamut-labs@10.4.6-alpha.edd0f3.0<br/>@codecademy/styleguide@30.0.1-alpha.edd0f3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 22:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604162a3e44054097eeb9da6--gamut-preview.netlify.app>https://604162a3e44054097eeb9da6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604162a3e44054097eeb9da6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-05 03:36 UTC, jakemhiller requested changes

2021-03-05 03:36 UTC, jakemhiller commented on packages/gamut-labs/src/experimental/GlobalHeader/AnimatedGlobalHeader/index.tsx
> +  }, [handleScrolling]);
i'm pretty sure this event listener is being destroyed and recreated on every scroll event, since the `handleScrolling` effect uses the scroll position as a dependency. If you run the performance tools in Chrome you can see the event handlers getting created.

One way you could do it would be to separate the state for `scrollPosition`, and set it in a callback in this effect, instead of a separate callback. Then you can use the `scrollPosition` value in an effect to set the rest of your state.

2021-03-05 21:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.1.1-alpha.32c07c.0<br/>@codecademy/gamut-labs@10.4.6-alpha.32c07c.0<br/>@codecademy/styleguide@30.0.1-alpha.32c07c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-05 21:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60429cb9fee0870ad0f37c3c--gamut-preview.netlify.app>https://60429cb9fee0870ad0f37c3c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60429cb9fee0870ad0f37c3c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-05 21:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.3-alpha.ee8f47.0<br/>@codecademy/gamut-labs@10.5.2-alpha.ee8f47.0<br/>@codecademy/styleguide@30.1.2-alpha.ee8f47.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-05 21:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.3-alpha.1b57c6.0<br/>@codecademy/gamut-labs@10.5.2-alpha.1b57c6.0<br/>@codecademy/styleguide@30.1.2-alpha.1b57c6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-05 21:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6042a03ee74c000c90c5392a--gamut-preview.netlify.app>https://6042a03ee74c000c90c5392a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6042a03ee74c000c90c5392a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 17:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.4-alpha.9f948b.0<br/>@codecademy/gamut-labs@10.5.3-alpha.9f948b.0<br/>@codecademy/styleguide@30.1.3-alpha.9f948b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 17:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604662501cd1eb2a3fea67bd--gamut-preview.netlify.app>https://604662501cd1eb2a3fea67bd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604662501cd1eb2a3fea67bd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 17:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.4-alpha.a97172.0<br/>@codecademy/gamut-labs@10.5.3-alpha.a97172.0<br/>@codecademy/styleguide@30.1.3-alpha.a97172.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 18:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6047b820e0c1cd009822707b--gamut-preview.netlify.app>https://6047b820e0c1cd009822707b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6047b820e0c1cd009822707b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 21:50 UTC, katiezutter commented on packages/gamut-labs/src/experimental/GlobalHeader/BasicGlobalHeader/index.tsx
> +        height="80"
I think we need to add back in Aaron's header height changes from this PR: https://github.com/Codecademy/client-modules/pull/1469/files

2021-03-09 22:00 UTC, katiezutter approved these changes
Looks SO nice ✨ Super pumped about this - LGTM pending adding back in Aaron's header height changes!

2021-03-09 22:01 UTC, sylvanasantos reviewed
this LGTM, but if we are removing the animated prop, then this pr will look pretty different so gonna hold off on approving. and also, big +1 to katie's comment.

2021-03-09 22:03 UTC, katiezutter commented
Oh sorry I missed that we're removing the `animated` prop: definitely down if we want to do that! It will be a breaking change for the static-sites header, but I'm happy to do that follow-up since I spent lots of time working on the header in static-sites!

2021-03-10 20:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.14-alpha.a36365.0<br/>@codecademy/gamut-labs@11.2.2-alpha.a36365.0<br/>@codecademy/styleguide@30.5.2-alpha.a36365.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 20:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60492ad2f8546a00c0b014bb--gamut-preview.netlify.app>https://60492ad2f8546a00c0b014bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60492ad2f8546a00c0b014bb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 20:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60492f8466e5d908f447a66f--gamut-preview.netlify.app>https://60492f8466e5d908f447a66f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60492f8466e5d908f447a66f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 21:07 UTC, jakemhiller commented on packages/gamut-labs/src/experimental/GlobalHeader/AnimatedGlobalHeader/index.tsx
> +          isInHeaderRegion && styles.transitionFadeOut
not launch blocking, but now that this is so simple we should move it to css-in-js

2021-03-10 21:17 UTC, jakemhiller approved these changes
Looks good to me!

2021-03-11 02:57 UTC, saghdaey requested changes
Really great work here! the animation looks amazing in the monolith.
Unfortunately I'm seeing that these changes break the global header story. Maybe we can pair together tomorrow? I think I've figured out two ways to fix!

here is the global header story on the PR env:
https://60492f8466e5d908f447a66f--gamut-preview.netlify.app/storybook/?path=/docs/labs-experimental-molecules-globalheader--global-header

2021-03-11 04:44 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalHeader/BasicGlobalHeader/index.tsx
> +export type GlobalHeaderProps =
I think these types are exported in global header so we can just import them here

2021-03-11 05:45 UTC, saghdaey commented
nit:
codecademy logo (top left) shifts down when you open mobile hamburger menu
https://user-images.githubusercontent.com/9753446/110741598-f3fe3200-8202-11eb-8e19-9fbeb4da5287.mov

2021-03-11 05:55 UTC, saghdaey commented
i'm not sure if this is from your changes but i'm seeing the my goal component + header search overlap on kea
but not in production or on badger (where global header monolith branch is deployed)

<img width="1220" alt="Screen Shot 2021-03-11 at 12 54 06 AM" src="https://user-images.githubusercontent.com/9753446/110742494-789d8000-8204-11eb-9e77-cd0110b7288e.png">

2021-03-11 19:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.14-alpha.30bdd2.0<br/>@codecademy/gamut-labs@11.2.2-alpha.30bdd2.0<br/>@codecademy/styleguide@30.5.2-alpha.30bdd2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-11 19:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604a768c12f7b728e9345bb7--gamut-preview.netlify.app>https://604a768c12f7b728e9345bb7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604a768c12f7b728e9345bb7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-11 22:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.14-alpha.1d58e7.0<br/>@codecademy/gamut-labs@11.2.2-alpha.1d58e7.0<br/>@codecademy/styleguide@30.5.2-alpha.1d58e7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-11 22:46 UTC, saghdaey approved these changes

2021-03-11 22:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604a9df2568411007b683ccc--gamut-preview.netlify.app>https://604a9df2568411007b683ccc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604a9df2568411007b683ccc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 17:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.736cba.0<br/>@codecademy/gamut-labs@11.2.4-alpha.736cba.0<br/>@codecademy/styleguide@30.6.1-alpha.736cba.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 17:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604ba955ba1d7d00b88af971--gamut-preview.netlify.app>https://604ba955ba1d7d00b88af971--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604ba955ba1d7d00b88af971>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 19:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.8951bf.0<br/>@codecademy/gamut-labs@11.2.4-alpha.8951bf.0<br/>@codecademy/styleguide@30.6.1-alpha.8951bf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 19:42 UTC, jcenglish commented on packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
> +    <Box height={theme.elements.headerHeight}>
I don't know how this outermost box got here.

2021-03-12 19:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604bc44510dbf015310777ad--gamut-preview.netlify.app>https://604bc44510dbf015310777ad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604bc44510dbf015310777ad>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 21:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.8fc870.0<br/>@codecademy/gamut-labs@11.2.4-alpha.8fc870.0<br/>@codecademy/styleguide@30.6.1-alpha.8fc870.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 21:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604be00f64e22200b58efa33--gamut-preview.netlify.app>https://604be00f64e22200b58efa33--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604be00f64e22200b58efa33>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 14:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.9bd574.0<br/>@codecademy/gamut-labs@11.2.4-alpha.9bd574.0<br/>@codecademy/gamut@26.3.1-alpha.9bd574.0<br/>@codecademy/styleguide@30.6.1-alpha.9bd574.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 14:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604f755b30d9eb0789bb6260--gamut-preview.netlify.app>https://604f755b30d9eb0789bb6260--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604f755b30d9eb0789bb6260>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 16:40 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
> +  const content = useMemo(() => sample(emptyNotificationContents), [])!;
ty!!

2021-03-15 20:58 UTC, merged