Cass gm 150
Codecademy/client-modules pull request #1439
Opened 2021-02-25 19:35 UTC by dreamwasp

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-03-01 15:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.11-alpha.0845ed.0<br/>@codecademy/gamut@25.3.4-alpha.0845ed.0<br/>@codecademy/styleguide@29.4.4-alpha.0845ed.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 15:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d0d1cc754d600d6b25a03--gamut-preview.netlify.app>https://603d0d1cc754d600d6b25a03--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d0d1cc754d600d6b25a03>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 16:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.11-alpha.00367c.0<br/>@codecademy/gamut@25.3.4-alpha.00367c.0<br/>@codecademy/styleguide@29.4.4-alpha.00367c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 16:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.11-alpha.3a752a.0<br/>@codecademy/gamut@25.3.4-alpha.3a752a.0<br/>@codecademy/styleguide@29.4.4-alpha.3a752a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 16:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d1b6de96b3c0796d69142--gamut-preview.netlify.app>https://603d1b6de96b3c0796d69142--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d1b6de96b3c0796d69142>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 17:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.11-alpha.88a353.0<br/>@codecademy/gamut@25.3.4-alpha.88a353.0<br/>@codecademy/styleguide@29.4.4-alpha.88a353.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 17:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d1f1d0431670d1a154ab8--gamut-preview.netlify.app>https://603d1f1d0431670d1a154ab8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d1f1d0431670d1a154ab8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 18:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.1.11-alpha.395a3e.0<br/>@codecademy/gamut@25.3.4-alpha.395a3e.0<br/>@codecademy/styleguide@29.4.4-alpha.395a3e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 18:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d2c64cec8971b7d67c407--gamut-preview.netlify.app>https://603d2c64cec8971b7d67c407--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d2c64cec8971b7d67c407>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 18:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.4-alpha.3a4fb0.0<br/>@codecademy/gamut@25.3.6-alpha.3a4fb0.0<br/>@codecademy/styleguide@29.5.4-alpha.3a4fb0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 18:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d2f1db2fe591f5a49b64b--gamut-preview.netlify.app>https://603d2f1db2fe591f5a49b64b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d2f1db2fe591f5a49b64b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 21:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.4-alpha.179835.0<br/>@codecademy/gamut@25.3.6-alpha.179835.0<br/>@codecademy/styleguide@29.5.4-alpha.179835.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 21:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d5a90e2d59d1a077b3830--gamut-preview.netlify.app>https://603d5a90e2d59d1a077b3830--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d5a90e2d59d1a077b3830>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 21:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.4-alpha.3aed2d.0<br/>@codecademy/gamut@25.3.6-alpha.3aed2d.0<br/>@codecademy/styleguide@29.5.4-alpha.3aed2d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 21:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d5ca850ff481d73adc5e3--gamut-preview.netlify.app>https://603d5ca850ff481d73adc5e3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d5ca850ff481d73adc5e3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 21:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.4-alpha.30ff37.0<br/>@codecademy/gamut@25.3.6-alpha.30ff37.0<br/>@codecademy/styleguide@29.5.4-alpha.30ff37.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 21:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d6390aff72823ef4942eb--gamut-preview.netlify.app>https://603d6390aff72823ef4942eb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d6390aff72823ef4942eb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 22:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.4-alpha.789cf9.0<br/>@codecademy/gamut@25.3.6-alpha.789cf9.0<br/>@codecademy/styleguide@29.5.4-alpha.789cf9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 22:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d6acda4b3732b15b338c6--gamut-preview.netlify.app>https://603d6acda4b3732b15b338c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d6acda4b3732b15b338c6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 23:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.5-alpha.8b08f5.0<br/>@codecademy/gamut@25.3.7-alpha.8b08f5.0<br/>@codecademy/styleguide@29.5.5-alpha.8b08f5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 23:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d73b99e097400ce0b7a13--gamut-preview.netlify.app>https://603d73b99e097400ce0b7a13--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d73b99e097400ce0b7a13>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-02 15:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.601cb9.0<br/>@codecademy/gamut@25.4.1-alpha.601cb9.0<br/>@codecademy/styleguide@29.6.2-alpha.601cb9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-02 15:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603e56ce87912b1a6ade5ff0--gamut-preview.netlify.app>https://603e56ce87912b1a6ade5ff0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603e56ce87912b1a6ade5ff0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-02 16:16 UTC, cstatro commented on packages/gamut/src/Form/Input.tsx
> +  children?: CustomInputChild;
Why do we need to type `children`?  I think it's already going to be implicitly a react node

2021-03-02 16:42 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +  children?: CustomInputChild;
It does get implicitly typed as a ReactNode but not one with props. The typing here basically exists to ensure that this is a ReactNode that has props +  type those props as a ReactNode. (as least this is my understanding of it + not typing it results in a TypeError). I may play around with typing to type this strictly as an  `HTMLInputElement`.

2021-03-02 16:48 UTC, borisonr reviewed
this looks great @dreamwasp! thank you for handling all of this!
couple notes from a quick QA:
looks like the icon is not quite centered in the registration form (probably bc there's junky css in the monolith) so just noting we may not want to turn it on before QA-ing across the monolith unfortunately...
<img width="389" alt="Screen Shot 2021-03-02 at 8 38 34 AM" src="https://user-images.githubusercontent.com/16214204/109681812-d9192700-7b4b-11eb-8182-3abaa1d14d05.png">
also apologies if you mentioned this in your description but are you handling the check mark validation in a separate pr? or is it just that we need to do something in the monolith to get it to work for the registration form?
and mind adding an error message to the input story so we can see how it looks below the input?
lastly, i think we need a disabled cursor for disabled fields

and when you're ready, mind sending the preview links to tamar to QA too? (maybe just highlight where in the monolith we already use gamut inputs right now because we don't yet in checkout)

2021-03-02 17:10 UTC, dreamwasp commented
> this looks great @dreamwasp! thank you for handling all of this!
> couple notes from a quick QA:
> looks like the icon is not quite centered in the registration form (probably bc there's junky css in the monolith) so just noting we may not want to turn it on before QA-ing across the monolith unfortunately...
> <img alt="Screen Shot 2021-03-02 at 8 38 34 AM" width="389" src="https://user-images.githubusercontent.com/16214204/109681812-d9192700-7b4b-11eb-8182-3abaa1d14d05.png">
> also apologies if you mentioned this in your description but are you handling the check mark validation in a separate pr? or is it just that we need to do something in the monolith to get it to work for the registration form?
> and mind adding an error message to the input story so we can see how it looks below the input?
> lastly, i think we need a disabled cursor for disabled fields
> 
> and when you're ready, mind sending the preview links to tamar to QA too? (maybe just highlight where in the monolith we already use gamut inputs right now because we don't yet in checkout)

- I've only just starting QA-ing across the monolith, definitely won't ship this until that work is all done!
- The checkmark icon is in this PR but I haven't hooked it up to the FormLabels / LabelGroups yet. Now that you mention it I do think it is a good idea to do that here, so I will include it.
- I'll add an error messages FormGroup to the Input story. You can check them out in the GridForm story to see how they look currently.
- Good eye, I'll fix the disabled cursor now! 
- Yes! I'll slack Tamar with the monolith PR env before I ship it.

2021-03-03 03:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.13a806.0<br/>@codecademy/gamut@25.4.1-alpha.13a806.0<br/>@codecademy/styleguide@29.6.2-alpha.13a806.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-03 03:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603f047c19abb49eb0db2929--gamut-preview.netlify.app>https://603f047c19abb49eb0db2929--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603f047c19abb49eb0db2929>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-03 15:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.63842b.0<br/>@codecademy/gamut@25.4.1-alpha.63842b.0<br/>@codecademy/styleguide@29.6.2-alpha.63842b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-03 15:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603fac7644fb8e3c7028b82a--gamut-preview.netlify.app>https://603fac7644fb8e3c7028b82a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603fac7644fb8e3c7028b82a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-03 15:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.254855.0<br/>@codecademy/gamut@25.4.1-alpha.254855.0<br/>@codecademy/styleguide@29.6.2-alpha.254855.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-03 15:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603fae9c6bfd884bb9459938--gamut-preview.netlify.app>https://603fae9c6bfd884bb9459938--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603fae9c6bfd884bb9459938>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-03 15:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.264f67.0<br/>@codecademy/gamut@25.4.1-alpha.264f67.0<br/>@codecademy/styleguide@29.6.2-alpha.264f67.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-03 15:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603fb1394f0e346de38c45ca--gamut-preview.netlify.app>https://603fb1394f0e346de38c45ca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603fb1394f0e346de38c45ca>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-03 18:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.1-alpha.ad052d.0<br/>@codecademy/gamut@25.4.1-alpha.ad052d.0<br/>@codecademy/styleguide@29.6.2-alpha.ad052d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-03 18:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603fd492d766ba64fc1ad6c7--gamut-preview.netlify.app>https://603fd492d766ba64fc1ad6c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603fd492d766ba64fc1ad6c7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-03 19:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.3-alpha.1d31f1.0<br/>@codecademy/gamut@25.4.2-alpha.1d31f1.0<br/>@codecademy/styleguide@29.6.4-alpha.1d31f1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-03 19:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603fe5ba75f3e5097d73923f--gamut-preview.netlify.app>https://603fe5ba75f3e5097d73923f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603fe5ba75f3e5097d73923f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 19:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.3-alpha.a85c82.0<br/>@codecademy/gamut@25.4.2-alpha.a85c82.0<br/>@codecademy/styleguide@29.6.4-alpha.a85c82.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 19:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60413573c3fd4f09e725631c--gamut-preview.netlify.app>https://60413573c3fd4f09e725631c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60413573c3fd4f09e725631c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.3-alpha.a3959a.0<br/>@codecademy/gamut@25.4.2-alpha.a3959a.0<br/>@codecademy/styleguide@29.6.4-alpha.a3959a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 19:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60413a1fe2badc0d9e720adc--gamut-preview.netlify.app>https://60413a1fe2badc0d9e720adc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60413a1fe2badc0d9e720adc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 20:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.3-alpha.fdaeff.0<br/>@codecademy/gamut@25.4.2-alpha.fdaeff.0<br/>@codecademy/styleguide@29.6.4-alpha.fdaeff.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 20:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60413e77951db200cf82df99--gamut-preview.netlify.app>https://60413e77951db200cf82df99--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60413e77951db200cf82df99>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 21:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.3-alpha.c11edd.0<br/>@codecademy/gamut@25.4.2-alpha.c11edd.0<br/>@codecademy/styleguide@29.6.4-alpha.c11edd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 21:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6041502a5e61cd12a166807c--gamut-preview.netlify.app>https://6041502a5e61cd12a166807c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6041502a5e61cd12a166807c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 22:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.3.3-alpha.54e6d2.0<br/>@codecademy/gamut@25.4.2-alpha.54e6d2.0<br/>@codecademy/styleguide@29.6.4-alpha.54e6d2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 22:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604158ddec5665007d297f5d--gamut-preview.netlify.app>https://604158ddec5665007d297f5d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604158ddec5665007d297f5d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-05 15:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.1-alpha.17a930.0<br/>@codecademy/gamut-labs@10.4.7-alpha.17a930.0<br/>@codecademy/gamut@26.0.2-alpha.17a930.0<br/>@codecademy/styleguide@30.0.2-alpha.17a930.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-05 15:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6042488fec56651882297e86--gamut-preview.netlify.app>https://6042488fec56651882297e86--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6042488fec56651882297e86>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-05 19:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.1-alpha.5a02c0.0<br/>@codecademy/gamut-labs@10.4.7-alpha.5a02c0.0<br/>@codecademy/gamut@26.0.2-alpha.5a02c0.0<br/>@codecademy/styleguide@30.0.2-alpha.5a02c0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-05 20:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.1-alpha.3f44ed.0<br/>@codecademy/gamut-labs@10.4.7-alpha.3f44ed.0<br/>@codecademy/gamut@26.0.2-alpha.3f44ed.0<br/>@codecademy/styleguide@30.0.2-alpha.3f44ed.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-05 20:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604290091423b4251301730f--gamut-preview.netlify.app>https://604290091423b4251301730f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604290091423b4251301730f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-05 23:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.4-alpha.365cd4.0<br/>@codecademy/gamut-labs@10.5.3-alpha.365cd4.0<br/>@codecademy/gamut@26.0.2-alpha.365cd4.0<br/>@codecademy/styleguide@30.1.3-alpha.365cd4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-05 23:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6042c1c2a5d98f2031a2c110--gamut-preview.netlify.app>https://6042c1c2a5d98f2031a2c110--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6042c1c2a5d98f2031a2c110>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 15:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.4-alpha.32072d.0<br/>@codecademy/gamut-labs@10.5.3-alpha.32072d.0<br/>@codecademy/gamut@26.0.2-alpha.32072d.0<br/>@codecademy/styleguide@30.1.3-alpha.32072d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 15:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604643fb7de1101125f57281--gamut-preview.netlify.app>https://604643fb7de1101125f57281--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604643fb7de1101125f57281>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 16:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.4-alpha.076307.0<br/>@codecademy/gamut-labs@10.5.3-alpha.076307.0<br/>@codecademy/gamut@26.0.2-alpha.076307.0<br/>@codecademy/styleguide@30.1.3-alpha.076307.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 16:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604657831481c51f9e1183ed--gamut-preview.netlify.app>https://604657831481c51f9e1183ed--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604657831481c51f9e1183ed>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 17:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.4-alpha.a53af8.0<br/>@codecademy/gamut-labs@10.5.3-alpha.a53af8.0<br/>@codecademy/gamut@26.0.2-alpha.a53af8.0<br/>@codecademy/styleguide@30.1.3-alpha.a53af8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 17:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60465d4bc21ff3276765bb9c--gamut-preview.netlify.app>https://60465d4bc21ff3276765bb9c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60465d4bc21ff3276765bb9c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 17:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.4-alpha.0199be.0<br/>@codecademy/gamut-labs@10.5.3-alpha.0199be.0<br/>@codecademy/gamut@26.0.2-alpha.0199be.0<br/>@codecademy/styleguide@30.1.3-alpha.0199be.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 17:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604664b11481c52de71182c4--gamut-preview.netlify.app>https://604664b11481c52de71182c4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604664b11481c52de71182c4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 19:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.4-alpha.91d76f.0<br/>@codecademy/gamut-labs@10.5.3-alpha.91d76f.0<br/>@codecademy/gamut@26.0.2-alpha.91d76f.0<br/>@codecademy/styleguide@30.1.3-alpha.91d76f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 19:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604681a85052f1100042a105--gamut-preview.netlify.app>https://604681a85052f1100042a105--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604681a85052f1100042a105>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 20:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.6-alpha.f64d27.0<br/>@codecademy/gamut-labs@11.0.2-alpha.f64d27.0<br/>@codecademy/gamut@26.1.1-alpha.f64d27.0<br/>@codecademy/styleguide@30.2.1-alpha.f64d27.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 21:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.6-alpha.d923e2.0<br/>@codecademy/gamut-labs@11.0.2-alpha.d923e2.0<br/>@codecademy/gamut@26.1.1-alpha.d923e2.0<br/>@codecademy/styleguide@30.2.1-alpha.d923e2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 21:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604694ef36223600b48ad7b9--gamut-preview.netlify.app>https://604694ef36223600b48ad7b9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604694ef36223600b48ad7b9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 23:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.6-alpha.745828.0<br/>@codecademy/gamut-labs@11.0.2-alpha.745828.0<br/>@codecademy/gamut@26.1.1-alpha.745828.0<br/>@codecademy/styleguide@30.2.1-alpha.745828.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 23:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6046b38220c3c00090e3609a--gamut-preview.netlify.app>https://6046b38220c3c00090e3609a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6046b38220c3c00090e3609a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-08 23:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.6-alpha.73e661.0<br/>@codecademy/gamut-labs@11.0.2-alpha.73e661.0<br/>@codecademy/gamut@26.1.1-alpha.73e661.0<br/>@codecademy/styleguide@30.2.1-alpha.73e661.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-08 23:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6046b64ee2ce2c00cbe3482c--gamut-preview.netlify.app>https://6046b64ee2ce2c00cbe3482c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6046b64ee2ce2c00cbe3482c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 17:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6047b2655b9188184d983985--gamut-preview.netlify.app>https://6047b2655b9188184d983985--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6047b2655b9188184d983985>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 18:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.8-alpha.8d5b44.0<br/>@codecademy/gamut-labs@11.0.4-alpha.8d5b44.0<br/>@codecademy/gamut@26.2.1-alpha.8d5b44.0<br/>@codecademy/styleguide@30.3.1-alpha.8d5b44.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 18:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6047ba49433a71008bca141d--gamut-preview.netlify.app>https://6047ba49433a71008bca141d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6047ba49433a71008bca141d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 19:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.8-alpha.a03bfd.0<br/>@codecademy/gamut-labs@11.0.4-alpha.a03bfd.0<br/>@codecademy/gamut@26.2.1-alpha.a03bfd.0<br/>@codecademy/styleguide@30.3.1-alpha.a03bfd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 19:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6047cc8c322ac412cf22ca24--gamut-preview.netlify.app>https://6047cc8c322ac412cf22ca24--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6047cc8c322ac412cf22ca24>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 20:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.9-alpha.6490a8.0<br/>@codecademy/gamut-labs@11.0.5-alpha.6490a8.0<br/>@codecademy/gamut@26.2.2-alpha.6490a8.0<br/>@codecademy/styleguide@30.4.1-alpha.6490a8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 20:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6047d4d08697281a11f4ce75--gamut-preview.netlify.app>https://6047d4d08697281a11f4ce75--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6047d4d08697281a11f4ce75>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 20:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.9-alpha.f1ca8e.0<br/>@codecademy/gamut-labs@11.0.5-alpha.f1ca8e.0<br/>@codecademy/gamut@26.2.2-alpha.f1ca8e.0<br/>@codecademy/styleguide@30.4.1-alpha.f1ca8e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 20:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6047e0944d1e64007d7d79ab--gamut-preview.netlify.app>https://6047e0944d1e64007d7d79ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6047e0944d1e64007d7d79ab>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 21:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.9-alpha.0a8643.0<br/>@codecademy/gamut-labs@11.0.5-alpha.0a8643.0<br/>@codecademy/gamut@26.2.2-alpha.0a8643.0<br/>@codecademy/styleguide@30.4.1-alpha.0a8643.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 21:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6047e76ba3f7b307d85c00a3--gamut-preview.netlify.app>https://6047e76ba3f7b307d85c00a3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6047e76ba3f7b307d85c00a3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 21:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.9-alpha.1c1e0c.0<br/>@codecademy/gamut-labs@11.0.5-alpha.1c1e0c.0<br/>@codecademy/gamut@26.2.2-alpha.1c1e0c.0<br/>@codecademy/styleguide@30.4.1-alpha.1c1e0c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 21:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6047ea12bed0cf007febddad--gamut-preview.netlify.app>https://6047ea12bed0cf007febddad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6047ea12bed0cf007febddad>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 23:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.9-alpha.78941b.0<br/>@codecademy/gamut-labs@11.0.5-alpha.78941b.0<br/>@codecademy/gamut@26.2.2-alpha.78941b.0<br/>@codecademy/styleguide@30.4.1-alpha.78941b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 23:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604805220d4b6618fc7812c1--gamut-preview.netlify.app>https://604805220d4b6618fc7812c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604805220d4b6618fc7812c1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-09 23:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.b6e3cc.0<br/>@codecademy/gamut-labs@11.1.1-alpha.b6e3cc.0<br/>@codecademy/gamut@26.2.3-alpha.b6e3cc.0<br/>@codecademy/styleguide@30.4.3-alpha.b6e3cc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-09 23:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604806cd6df36717219980f9--gamut-preview.netlify.app>https://604806cd6df36717219980f9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604806cd6df36717219980f9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 00:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.089cf5.0<br/>@codecademy/gamut-labs@11.1.1-alpha.089cf5.0<br/>@codecademy/gamut@26.2.3-alpha.089cf5.0<br/>@codecademy/styleguide@30.4.3-alpha.089cf5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 01:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60481a41bbe120399bd32c1a--gamut-preview.netlify.app>https://60481a41bbe120399bd32c1a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60481a41bbe120399bd32c1a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 15:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.b5d566.0<br/>@codecademy/gamut-labs@11.1.1-alpha.b5d566.0<br/>@codecademy/gamut@26.2.3-alpha.b5d566.0<br/>@codecademy/styleguide@30.4.3-alpha.b5d566.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 15:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6048e43bfe54cc0084c186c1--gamut-preview.netlify.app>https://6048e43bfe54cc0084c186c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6048e43bfe54cc0084c186c1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 15:30 UTC, jakemhiller commented on packages/gamut/src/Form/Input.tsx
> +export const ReactRecurlyStyles = ({
How recurly-specific are these styles? is their purpose to reset the styles of the iframe?

2021-03-10 16:19 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +export const ReactRecurlyStyles = ({
basically yes - they exist to apply these styles to the iframe. react-recurly is the only place we're using iframe input right now but i'll rename them to something more generic

2021-03-10 16:44 UTC, jakemhiller commented on packages/gamut/src/Form/Input.tsx
> +export type InputWrapperProps = InputProps & {
Should this omit `activated`? since it is only set in local state, and can't be overridden?
```suggestion
export type InputWrapperProps =Omit<InputProps, 'activated'> & {
```

2021-03-10 16:47 UTC, jakemhiller commented on packages/gamut/src/Form/Input.tsx
> +export type InputWrapperProps = InputProps & {
actually, you might want `InputProps` to exclude activated, since that's what folks will import, and include it in the type you use when you pass props to `InputElement`

2021-03-10 17:18 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +export type InputWrapperProps = InputProps & {
definitely - fixed!

2021-03-10 17:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.e45597.0<br/>@codecademy/gamut-labs@11.1.1-alpha.e45597.0<br/>@codecademy/gamut@26.2.3-alpha.e45597.0<br/>@codecademy/styleguide@30.4.3-alpha.e45597.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 17:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6049007cc3f35c00bb0e5867--gamut-preview.netlify.app>https://6049007cc3f35c00bb0e5867--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6049007cc3f35c00bb0e5867>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 18:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.801c21.0<br/>@codecademy/gamut-labs@11.1.1-alpha.801c21.0<br/>@codecademy/gamut@26.2.3-alpha.801c21.0<br/>@codecademy/styleguide@30.4.3-alpha.801c21.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 18:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604910cef69bd6114add7958--gamut-preview.netlify.app>https://604910cef69bd6114add7958--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604910cef69bd6114add7958>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 18:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.f76867.0<br/>@codecademy/gamut-labs@11.1.1-alpha.f76867.0<br/>@codecademy/gamut@26.2.3-alpha.f76867.0<br/>@codecademy/styleguide@30.4.3-alpha.f76867.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 18:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6049161d925594166bbe1888--gamut-preview.netlify.app>https://6049161d925594166bbe1888--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6049161d925594166bbe1888>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 19:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.5c1e3b.0<br/>@codecademy/gamut-labs@11.1.1-alpha.5c1e3b.0<br/>@codecademy/gamut@26.2.3-alpha.5c1e3b.0<br/>@codecademy/styleguide@30.4.3-alpha.5c1e3b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 19:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6049248ac3f35c28260e5ccf--gamut-preview.netlify.app>https://6049248ac3f35c28260e5ccf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6049248ac3f35c28260e5ccf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 21:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.ffaccc.0<br/>@codecademy/gamut-labs@11.1.1-alpha.ffaccc.0<br/>@codecademy/gamut@26.2.3-alpha.ffaccc.0<br/>@codecademy/styleguide@30.4.3-alpha.ffaccc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 21:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60493d03317536089e601193--gamut-preview.netlify.app>https://60493d03317536089e601193--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60493d03317536089e601193>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-10 21:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.11-alpha.644803.0<br/>@codecademy/gamut-labs@11.1.1-alpha.644803.0<br/>@codecademy/gamut@26.2.3-alpha.644803.0<br/>@codecademy/styleguide@30.4.3-alpha.644803.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-10 21:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60493f77b6f79609e7e9544f--gamut-preview.netlify.app>https://60493f77b6f79609e7e9544f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60493f77b6f79609e7e9544f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-11 14:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.14-alpha.c8497e.0<br/>@codecademy/gamut-labs@11.2.2-alpha.c8497e.0<br/>@codecademy/gamut@26.2.3-alpha.c8497e.0<br/>@codecademy/styleguide@30.5.2-alpha.c8497e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-11 14:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604a280f07d7b000ae3a39fb--gamut-preview.netlify.app>https://604a280f07d7b000ae3a39fb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604a280f07d7b000ae3a39fb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-11 15:14 UTC, codecaaron requested changes
Just one change on the transition!  And this looks good to go for me!

2021-03-11 15:14 UTC, codecaaron commented on packages/gamut/src/Form/styles/shared.tsx
> +  transition: all 0.2s ease-in-out;
This will also add lag to trying to resize TextAreas.  We could make a helper to specify and concatenate properties we want to transition to make this easier though :)

2021-03-11 15:14 UTC, codecaaron commented on packages/gamut/src/Form/styles/shared.tsx
> +  &:disabled {
We may also want to add `[disabled]` to this selector list JIC

2021-03-11 15:14 UTC, codecaaron commented on packages/gamut/src/Form/styles/shared.tsx
> +  width: 16px;
1rem :)

2021-03-11 15:50 UTC, codecaaron commented on packages/gamut/src/Form/styles/FormError.module.scss
>  }
IIRC this is no longer used :)

2021-03-11 15:59 UTC, jakemhiller commented on packages/gamut/src/Form/Input.tsx
> +      <Box position="relative" onChange={() => setActivated(true)}>
wrapping these components like this remove the ability to change things like layout without either wrapping in another component or adjusting it with parent flex/grid layouts, right? is that an issue?

2021-03-11 16:15 UTC, borisonr reviewed
this is looking so great!
one tiny question: do we want a pointer cursor on the select component?

2021-03-11 19:22 UTC, jakemhiller commented on packages/gamut/src/Form/Input.tsx
> +      <Box position="relative" onChange={() => setActivated(true)}>
to be clear, i think if this isn't causing major layout issues in existing use cases we can punt on it until it comes up as a need

2021-03-11 19:30 UTC, jakemhiller commented on packages/gamut/src/Form/Input.tsx
> +      </Box>
Would this work? the props are the same.

I'm also curious, our normal name for this type of prop is `as`, was there a reason to use `component` as the prop name instead?

```
const AsComponent = Component || InputElement;
```

```
<AsComponent
  {...rest}
  id={id || rest.htmlFor}
  ref={ref}
  error={error}
  activated={activated}
  className={className}
/>
```

2021-03-12 14:36 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +      <Box position="relative" onChange={() => setActivated(true)}>
i don't think it's an issue + it hasn't popped up anywhere in the monolith afaik. i have it wrapped right now to reliably position the icons but super down to change that if there is a better way to it.

2021-03-12 14:40 UTC, dreamwasp commented on packages/gamut/src/Form/FormGroup.tsx
> +  showRequired,
exactly yes, i don't want to change the fields of the existing forms on the monolith *too much* in the initial rollout here

2021-03-12 14:41 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +      </Box>
no reason, i'll try this out!

2021-03-12 15:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.14-alpha.dd7cfd.0<br/>@codecademy/gamut-labs@11.2.2-alpha.dd7cfd.0<br/>@codecademy/gamut@26.2.3-alpha.dd7cfd.0<br/>@codecademy/styleguide@30.5.2-alpha.dd7cfd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 16:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b8ff85155751a14f2fd95--gamut-preview.netlify.app>https://604b8ff85155751a14f2fd95--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b8ff85155751a14f2fd95>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 16:01 UTC, dreamwasp commented on packages/gamut/src/Form/styles/shared.tsx
> +};
yes! i think it'll be a pretty easy swap once we have darkMode designs for these.

2021-03-12 16:02 UTC, dreamwasp commented on packages/gamut/src/Form/styles/shared.tsx
> +  transition: all 0.2s ease-in-out;
word, lmk if the solution i came up with makes sense!

2021-03-12 16:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.14-alpha.3e2c39.0<br/>@codecademy/gamut-labs@11.2.2-alpha.3e2c39.0<br/>@codecademy/gamut@26.2.3-alpha.3e2c39.0<br/>@codecademy/styleguide@30.5.2-alpha.3e2c39.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 16:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b9656370ed41fd4cd67cd--gamut-preview.netlify.app>https://604b9656370ed41fd4cd67cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b9656370ed41fd4cd67cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 16:38 UTC, dreamwasp commented on packages/gamut/src/Form/FormGroup.tsx
>    const labelComponent = label ? (
i'm guessing the description exists for labels that might need specific further instructions? it predates these edits so i'm not 100% sure but didn't wanna remove that functionality in case it's useful down the line

2021-03-12 16:46 UTC, borisonr commented on packages/gamut/src/Form/FormGroup.tsx
>    const labelComponent = label ? (
yeah was just curious :)

2021-03-12 16:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.14-alpha.eb6318.0<br/>@codecademy/gamut-labs@11.2.2-alpha.eb6318.0<br/>@codecademy/gamut@26.2.3-alpha.eb6318.0<br/>@codecademy/styleguide@30.5.2-alpha.eb6318.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 16:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b9c834138fc2865c8acdb--gamut-preview.netlify.app>https://604b9c834138fc2865c8acdb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b9c834138fc2865c8acdb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 17:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.370745.0<br/>@codecademy/gamut-labs@11.2.4-alpha.370745.0<br/>@codecademy/gamut@26.3.1-alpha.370745.0<br/>@codecademy/styleguide@30.6.1-alpha.370745.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 17:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604ba41652044d2c78ba3bee--gamut-preview.netlify.app>https://604ba41652044d2c78ba3bee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604ba41652044d2c78ba3bee>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 17:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.b5b8cf.0<br/>@codecademy/gamut-labs@11.2.4-alpha.b5b8cf.0<br/>@codecademy/gamut@26.3.1-alpha.b5b8cf.0<br/>@codecademy/styleguide@30.6.1-alpha.b5b8cf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 17:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604ba5acd51191354f28abbc--gamut-preview.netlify.app>https://604ba5acd51191354f28abbc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604ba5acd51191354f28abbc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 20:03 UTC, codecaaron approved these changes
💯  Love the transition helper!

I have like 1 or two questions about the forwardRef stuff and React Recurly but that's not blocking.

2021-03-12 20:03 UTC, codecaaron commented on packages/gamut/src/Form/FormGroupLabel.tsx
> +`;
Also if `formLabelStyles` is a function emotion will automatically infer the type if you don't use the template literal.

```tsx
const StyledLabel = styled.label(formLabelStyles)
```

2021-03-12 21:16 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> +      <Box>
i'm not sure if you're asking about `StyledFormGroup` or `{field.size}`?

2021-03-12 21:17 UTC, dreamwasp commented on packages/gamut/src/Form/FormGroupLabel.tsx
> +`;
!! sick, yes. will implement

2021-03-12 21:17 UTC, codecaaron commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> +      <Box>
This <Box> on 119

2021-03-12 21:17 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +`;
🙏

2021-03-12 21:46 UTC, dreamwasp commented on packages/gamut/src/Form/TextArea.tsx
> +      <Box onChange={() => setActivated(true)}>
yeah that's what i'm worried about, do you think something like this would be better?

```
 const changeHandler = (event) => {
      rest.onChange ? rest.onChange(event) : null;
      setActivated(true);
    };

    return (
      <StyledTextArea
        {...rest}
        id={id || rest.htmlFor}
        className={className}
        ref={ref}
        error={error}
        activated={activated}
        onChange={(event) => changeHandler(event)}
      />
    );
```

2021-03-12 21:49 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> +      <Box>
oh! it creates a wrapper for the errorMessage to calculate off of so that when there is more space things like this : 
![image](https://user-images.githubusercontent.com/58054751/111002117-dc35c380-8352-11eb-8e76-f7cc137535f9.png): don't happen

2021-03-12 23:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.c58a34.0<br/>@codecademy/gamut-labs@11.2.4-alpha.c58a34.0<br/>@codecademy/gamut@26.3.1-alpha.c58a34.0<br/>@codecademy/styleguide@30.6.1-alpha.c58a34.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 23:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604bf7cf648d6c14459ccba7--gamut-preview.netlify.app>https://604bf7cf648d6c14459ccba7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604bf7cf648d6c14459ccba7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 15:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.685445.0<br/>@codecademy/gamut-labs@11.2.4-alpha.685445.0<br/>@codecademy/gamut@26.3.1-alpha.685445.0<br/>@codecademy/styleguide@30.6.1-alpha.685445.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 15:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604f7d989b38f512d7919b23--gamut-preview.netlify.app>https://604f7d989b38f512d7919b23--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604f7d989b38f512d7919b23>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 15:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.8474df.0<br/>@codecademy/gamut-labs@11.2.4-alpha.8474df.0<br/>@codecademy/gamut@26.3.1-alpha.8474df.0<br/>@codecademy/styleguide@30.6.1-alpha.8474df.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 15:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604f80b84f3a6f140b5d2266--gamut-preview.netlify.app>https://604f80b84f3a6f140b5d2266--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604f80b84f3a6f140b5d2266>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 18:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.c587f8.0<br/>@codecademy/gamut-labs@11.2.4-alpha.c587f8.0<br/>@codecademy/gamut@26.3.1-alpha.c587f8.0<br/>@codecademy/styleguide@30.6.1-alpha.c587f8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 18:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604fac59a766140952b4ec97--gamut-preview.netlify.app>https://604fac59a766140952b4ec97--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604fac59a766140952b4ec97>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 19:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.df8137.0<br/>@codecademy/gamut-labs@11.2.4-alpha.df8137.0<br/>@codecademy/gamut@26.3.1-alpha.df8137.0<br/>@codecademy/styleguide@30.6.1-alpha.df8137.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 19:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604fb348b093300fa8da24e3--gamut-preview.netlify.app>https://604fb348b093300fa8da24e3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604fb348b093300fa8da24e3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 21:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.720172.0<br/>@codecademy/gamut-labs@11.2.4-alpha.720172.0<br/>@codecademy/gamut@26.3.1-alpha.720172.0<br/>@codecademy/styleguide@30.6.1-alpha.720172.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 21:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604fd33dacba020e4ab14598--gamut-preview.netlify.app>https://604fd33dacba020e4ab14598--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604fd33dacba020e4ab14598>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 23:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.18-alpha.16bd1e.0<br/>@codecademy/gamut-labs@11.4.1-alpha.16bd1e.0<br/>@codecademy/gamut@26.4.1-alpha.16bd1e.0<br/>@codecademy/styleguide@30.7.2-alpha.16bd1e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 23:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604ff1f1e095990084d58574--gamut-preview.netlify.app>https://604ff1f1e095990084d58574--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604ff1f1e095990084d58574>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-16 13:44 UTC, merged