feat(HubCard): Created a new hub page card component
Codecademy/client-modules pull request #1442
Opened 2021-02-26 21:37 UTC by aionate0812

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-02-26 21:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.2-alpha.3ae82e.0<br/>@codecademy/styleguide@29.5.2-alpha.3ae82e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-02-26 21:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60396cf1d002323557098451--gamut-preview.netlify.app>https://60396cf1d002323557098451--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60396cf1d002323557098451>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-02-26 22:19 UTC, codecaaron reviewed
Glad we went with just specifying a background image. 

This is looking very nice.

2021-02-26 22:19 UTC, codecaaron commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +      >
```suggestion
    <FlexBox
      backgroundRepeat="no-repeat"
      backgroundPosition={backgroundPosition}
      backgroundImage={backgroundImg}
      justifyContent="center"
      alignItems="center"
      paddingX={24}
      height="180px"
    >
        <StyledCardBox
        padding={24}
        backgroundColor="white"
        width="100%"
        maxWidth="280px"
      >
```

2021-02-26 22:19 UTC, codecaaron commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +      >
I think we can use FlexBox and Box and forego extending these components :)

2021-03-01 15:29 UTC, rogervera reviewed
Nice work on translating the designs! Looks good.
Question: Since this is a card, what hover/focus states are we going to use?

2021-03-01 16:04 UTC, aionate0812 commented
@rogervera I will ask Dev about this. When adding this card to the monolith I wrapped it in a `Card` component which added the hover/focus states for me

2021-03-01 18:17 UTC, aionate0812 commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +      >
I made the change and also switched the `backgroundImage`prop. I still had to extend the component for now because `FlexBox` does not have the `backgroundOrigin` property

2021-03-01 18:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.2-alpha.1598c9.0<br/>@codecademy/styleguide@29.5.2-alpha.1598c9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-01 18:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603d305f38123b203979147d--gamut-preview.netlify.app>https://603d305f38123b203979147d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603d305f38123b203979147d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-01 19:53 UTC, christian-dinh commented
looks great! one other thing to ask dev would be if these will always have hover/focus states, in which case we can just add `Card` to the implementation here. If it turns out no action is required on that front then this lgtm 👍

2021-03-02 00:48 UTC, aresnik11 commented on packages/styleguide/stories/Brand/Atoms/HubCard.stories.mdx
> +<PropsTable story="HubCard" />
can we add the background system props as a default group so it's clear what all the available props are? otherwise it could be confusing for someone looking to use this component
```suggestion
<PropsTable story="HubCard" defaultGroups={['background']} />
```

2021-03-02 18:48 UTC, aionate0812 commented on packages/styleguide/stories/Brand/Atoms/HubCard.stories.mdx
> +<PropsTable story="HubCard" />
added the change as well as a variant with a background image positioned to the right

2021-03-02 18:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.2-alpha.98a731.0<br/>@codecademy/styleguide@29.5.2-alpha.98a731.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-02 18:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://603e89a719abb40f01db2999--gamut-preview.netlify.app>https://603e89a719abb40f01db2999--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/603e89a719abb40f01db2999>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 20:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.2-alpha.54b158.0<br/>@codecademy/styleguide@29.5.2-alpha.54b158.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 20:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6041408831f50300bbf37a10--gamut-preview.netlify.app>https://6041408831f50300bbf37a10--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6041408831f50300bbf37a10>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 20:29 UTC, judahtanthony approved these changes
Functional, simple.  I don't know if we have a convention for the term "eyebrowTitle", but it seems pretty straightforward.

2021-03-04 20:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.2.2-alpha.4ce1ce.0<br/>@codecademy/styleguide@29.5.2-alpha.4ce1ce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 20:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6041444d31f50300cff37850--gamut-preview.netlify.app>https://6041444d31f50300cff37850--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6041444d31f50300cff37850>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 22:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@10.4.2-alpha.a847e9.0<br/>@codecademy/styleguide@29.6.8-alpha.a847e9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 22:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60416025f4075c060627a1e1--gamut-preview.netlify.app>https://60416025f4075c060627a1e1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60416025f4075c060627a1e1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 22:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.1.1-alpha.29fbd5.0<br/>@codecademy/gamut-labs@10.4.6-alpha.29fbd5.0<br/>@codecademy/styleguide@30.0.1-alpha.29fbd5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 22:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604161e8ec566506ca298371--gamut-preview.netlify.app>https://604161e8ec566506ca298371--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604161e8ec566506ca298371>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-04 22:44 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +    <Box padding={24} backgroundColor="white" width="100%" maxWidth="280px">
> 180px
> 280px

We normally use rem; up for switching this over?

2021-03-04 22:46 UTC, JoshuaKGoldberg requested changes
LGTM in general! Just questioning `StyledCard` and the accessibility of the `h5`.

2021-03-04 22:46 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +      <StyledText as="h5" fontSize={22}>
> h5

Should this be a heading? I would think it's just bold text from an accessibility perspective, no?

2021-03-04 22:46 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +const StyledCard = styled(Card)`
After all the overrides done below, is this still really a Card? Would it be about the same amount of code to make it a `Box`?

2021-03-04 22:53 UTC, judahtanthony commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +      <StyledText as="h5" fontSize={22}>
That is a good question.  The other catalog cards seem to be an h3 (/catalog), but to your point, I have heard that you shouldn't use a headline if there is not content below it.  We can certainly change that if you want it.  Should we also change the other catalog cards?

2021-03-04 22:56 UTC, aresnik11 commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +      <StyledText as="h5" fontSize={22}>
FWIW the old explore card titles were h3 and the course/path card titles are h3: https://www.codecademy.com/catalog

that doesn't mean those are correct...

2021-03-04 22:57 UTC, aresnik11 commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +      <StyledText as="h5" fontSize={22}>
@judahtanthony ha i was 3 mins late to the party here

2021-03-04 23:01 UTC, judahtanthony commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +const StyledCard = styled(Card)`
That is fair.  We are mostly just leveraging the Card shadow (and border).  Would you be objected to use export the createShadow helper?  Do we have a place for these types of emotion "mixins"?

2021-03-04 23:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.1.1-alpha.c647b1.0<br/>@codecademy/gamut-labs@10.4.6-alpha.c647b1.0<br/>@codecademy/styleguide@30.0.1-alpha.c647b1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-04 23:13 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/HubCard/index.tsx
> +const StyledCard = styled(Card)`
Ohh, hmm, maybe this is bad feedback then - I forgot how intense those styles are. Never mind 😄

2021-03-04 23:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6041699b2f309f0bc3b25368--gamut-preview.netlify.app>https://6041699b2f309f0bc3b25368--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6041699b2f309f0bc3b25368>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-05 15:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.1-alpha.21d34b.0<br/>@codecademy/gamut-labs@10.4.7-alpha.21d34b.0<br/>@codecademy/styleguide@30.0.2-alpha.21d34b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-05 15:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6042556907354210f7c33f91--gamut-preview.netlify.app>https://6042556907354210f7c33f91--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6042556907354210f7c33f91>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-05 17:02 UTC, merged