feat(Modal): V2
Codecademy/client-modules pull request #1494
Opened 2021-03-12 14:45 UTC by codecaaron

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-03-12 14:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.69c773.0<br/>@codecademy/gamut-labs@11.2.3-alpha.69c773.0<br/>@codecademy/gamut@26.2.4-alpha.69c773.0<br/>@codecademy/styleguide@30.5.3-alpha.69c773.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 14:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b81a182825a0ec353e4fb--gamut-preview.netlify.app>https://604b81a182825a0ec353e4fb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b81a182825a0ec353e4fb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 15:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.4ecbb1.0<br/>@codecademy/gamut-labs@11.2.3-alpha.4ecbb1.0<br/>@codecademy/gamut@26.2.4-alpha.4ecbb1.0<br/>@codecademy/macros@2.0.1-alpha.4ecbb1.0<br/>@codecademy/styleguide@30.5.3-alpha.4ecbb1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 15:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b84c35c66ce0e24048061--gamut-preview.netlify.app>https://604b84c35c66ce0e24048061--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b84c35c66ce0e24048061>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 15:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.8dcc67.0<br/>@codecademy/gamut-labs@11.2.3-alpha.8dcc67.0<br/>@codecademy/gamut@26.2.4-alpha.8dcc67.0<br/>@codecademy/macros@2.0.1-alpha.8dcc67.0<br/>@codecademy/styleguide@30.5.3-alpha.8dcc67.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 15:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b8b92370ed41b69cd5dff--gamut-preview.netlify.app>https://604b8b92370ed41b69cd5dff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b8b92370ed41b69cd5dff>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 15:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b8d285155751a14f2f6d4--gamut-preview.netlify.app>https://604b8d285155751a14f2f6d4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b8d285155751a14f2f6d4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 15:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.1f1cca.0<br/>@codecademy/gamut-labs@11.2.3-alpha.1f1cca.0<br/>@codecademy/gamut@26.2.4-alpha.1f1cca.0<br/>@codecademy/macros@2.0.1-alpha.1f1cca.0<br/>@codecademy/styleguide@30.5.3-alpha.1f1cca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 15:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.cd9c91.0<br/>@codecademy/gamut-labs@11.2.3-alpha.cd9c91.0<br/>@codecademy/gamut@26.2.4-alpha.cd9c91.0<br/>@codecademy/macros@2.0.1-alpha.cd9c91.0<br/>@codecademy/styleguide@30.5.3-alpha.cd9c91.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 15:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b8ee3fdd72d1b1e80d11b--gamut-preview.netlify.app>https://604b8ee3fdd72d1b1e80d11b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b8ee3fdd72d1b1e80d11b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 16:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.05e998.0<br/>@codecademy/gamut-labs@11.2.3-alpha.05e998.0<br/>@codecademy/gamut@26.2.4-alpha.05e998.0<br/>@codecademy/macros@2.0.1-alpha.05e998.0<br/>@codecademy/styleguide@30.5.3-alpha.05e998.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 16:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b94b593a4de23b81254f2--gamut-preview.netlify.app>https://604b94b593a4de23b81254f2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b94b593a4de23b81254f2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 17:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.fc891f.0<br/>@codecademy/gamut-labs@11.2.4-alpha.fc891f.0<br/>@codecademy/gamut@26.3.1-alpha.fc891f.0<br/>@codecademy/macros@2.0.1-alpha.fc891f.0<br/>@codecademy/styleguide@30.6.1-alpha.fc891f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 17:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604ba93b39bba032296cdc91--gamut-preview.netlify.app>https://604ba93b39bba032296cdc91--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604ba93b39bba032296cdc91>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-13 23:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.b42729.0<br/>@codecademy/gamut-labs@11.2.4-alpha.b42729.0<br/>@codecademy/gamut@26.3.1-alpha.b42729.0<br/>@codecademy/macros@2.0.1-alpha.b42729.0<br/>@codecademy/styleguide@30.6.1-alpha.b42729.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-13 23:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604d51445052f6ce8c21e4f0--gamut-preview.netlify.app>https://604d51445052f6ce8c21e4f0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604d51445052f6ce8c21e4f0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-14 00:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.e5f01d.0<br/>@codecademy/gamut-labs@11.2.4-alpha.e5f01d.0<br/>@codecademy/gamut@26.3.1-alpha.e5f01d.0<br/>@codecademy/macros@2.0.1-alpha.e5f01d.0<br/>@codecademy/styleguide@30.6.1-alpha.e5f01d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-14 00:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604d5911a9112e9f794f9e2e--gamut-preview.netlify.app>https://604d5911a9112e9f794f9e2e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604d5911a9112e9f794f9e2e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 17:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605238afb089260d27ee99a6--gamut-preview.netlify.app>https://605238afb089260d27ee99a6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605238afb089260d27ee99a6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 18:39 UTC, codecaaron commented on packages/gamut/src/Dialog/index.tsx
> +  title: string | React.ReactNode;
Very true, nice catch!

2021-03-17 18:39 UTC, codecaaron commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +<Props story="Modal" />
Updated!

2021-03-17 18:40 UTC, codecaaron commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +## Style
I copied it from Figma, which is kinda unfinished and not out standard template.  But yeah needs another pass.  Changed it from style to this.

2021-03-17 18:45 UTC, codecaaron commented on packages/gamut/src/Dialog/index.tsx
> +  light: 'rgba(255, 255, 255, 0.95)',
Yeah I was thinking that too.  I was thinking we should probably split out parts of this to separate more general components but only expose dialog for the interim so patterns are locked down while we figure out what we want to support for a less opinionated Modal.

+ the card and backdrop pattern can be combined into a shared one for 3-4 other components so theres less divergence, and its technically a card so why not make it one!

2021-03-17 18:47 UTC, codecaaron commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +- Modals should always be displayed over an overlay. The overlay in light mode should be white at 95% opacity, the overlay in dark mode should be black at 75% opacity.
Oh definitely, I can mark these pieces to be split out for the more general version of Modal and other modal variants.

In the interim how do you feel about keeping these internal but with comments suggesting these are to be moved to new shared homes once design has commited to these other patterns?

2021-03-17 18:53 UTC, codecaaron commented
> Great start. I'm starting to think we should provide more out-of-the-box, kind of following up on your points in the convo we'd had informally in a standup or two ago. What do you think?

Re: Out of the box features I'm not sure if we need them right now, and any uses shouldn't need any customization by product teams if we're working within the constraints suggested by the guidelines.  Having a consistent structure to get component coverage with right now will make the initial wave of migration easier.   Then we can open up options to ensure that we don't unnecessarily customize or recreate things.

We 100% will need them in the future (near future) but I think it might end up slowing down onboarding if there are infinite options right now.

That make sense?

2021-03-17 19:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.8f326a.0<br/>@codecademy/gamut-labs@12.0.3-alpha.8f326a.0<br/>@codecademy/gamut@27.1.1-alpha.8f326a.0<br/>@codecademy/macros@2.0.1-alpha.8f326a.0<br/>@codecademy/styleguide@31.1.1-alpha.8f326a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 19:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605252cea1577b279e05e9d8--gamut-preview.netlify.app>https://605252cea1577b279e05e9d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605252cea1577b279e05e9d8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 23:14 UTC, dreamwasp approved these changes
✨

2021-03-17 23:14 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/Modal.stories.mdx
> +Other than creating buttons that can close the Modal, there are other ways a Mdal can be closed by the user.
`there are other ways a *Modal`

2021-03-17 23:14 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +## Usage Guidelines
maybe  change to 'Design Usage Guidelines' or something to make this section more explicit since engineers aren't used to seeing this info here yet

2021-03-17 23:14 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +    }}
![image](https://user-images.githubusercontent.com/58054751/111550447-7d0def80-8754-11eb-9b01-0ef88c05bd4f.png)

Storybook up to it's usual hijinks

2021-03-17 23:14 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +    cancelCta: { children: 'Heart?' },
maybe clarification in docs which FillButton props these can/should use

2021-03-19 15:00 UTC, JoshuaKGoldberg requested changes
Looks lovely! Both as a new component (that design!!) and as a way to get us to a more locked down Modal experience.

Unit tests please? 😄

2021-03-20 03:25 UTC, codecaaron commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +    }}
I think using the iframe messes this up -_-

2021-03-20 04:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.cf8a58.0<br/>@codecademy/gamut-labs@12.0.3-alpha.cf8a58.0<br/>@codecademy/gamut@27.1.1-alpha.cf8a58.0<br/>@codecademy/macros@2.0.1-alpha.cf8a58.0<br/>@codecademy/styleguide@31.1.1-alpha.cf8a58.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-20 04:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605575e0c009850f49866fcb--gamut-preview.netlify.app>https://605575e0c009850f49866fcb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605575e0c009850f49866fcb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-20 04:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.07a51c.0<br/>@codecademy/gamut-labs@12.0.3-alpha.07a51c.0<br/>@codecademy/gamut@27.1.1-alpha.07a51c.0<br/>@codecademy/macros@2.0.1-alpha.07a51c.0<br/>@codecademy/styleguide@31.1.1-alpha.07a51c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-20 04:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605578b6b16f08126baa713e--gamut-preview.netlify.app>https://605578b6b16f08126baa713e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605578b6b16f08126baa713e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-20 04:45 UTC, codecaaron commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +## Usage Guidelines
Yeah but it's backlogged right now.

2021-03-20 04:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60557f7e9d138248030c61d3--gamut-preview.netlify.app>https://60557f7e9d138248030c61d3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60557f7e9d138248030c61d3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-21 15:17 UTC, JoshuaKGoldberg commented on packages/gamut/src/Dialog/__tests__/Dialog-test.tsx
> +    jest.resetAllMocks();
Is this not done in the `jest.config.js` for this repo? If not, it should be..

2021-03-21 15:18 UTC, JoshuaKGoldberg commented on packages/gamut/src/Dialog/__tests__/Dialog-test.tsx
> +  it('renders a close button', () => {
```suggestion
  it('requests closing the dialog when the close button is clicked', () => {
```

2021-03-21 15:18 UTC, JoshuaKGoldberg approved these changes
Sweet, this is looking good! Thanks 😄

2021-03-21 15:18 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Dialog.stories.mdx
> +- Modals should always be displayed over an overlay. The overlay in light mode should be white at 95% opacity, the overlay in dark mode should be black at 75% opacity.
Sounds perfect 💯

2021-03-23 12:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.29-alpha.6c83af.0<br/>@codecademy/gamut-labs@13.0.5-alpha.6c83af.0<br/>@codecademy/gamut@29.1.1-alpha.6c83af.0<br/>@codecademy/macros@2.0.1-alpha.6c83af.0<br/>@codecademy/styleguide@33.0.3-alpha.6c83af.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-23 12:39 UTC, merged

2021-03-23 12:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6059e161170050048acd8f00--gamut-preview.netlify.app>https://6059e161170050048acd8f00--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6059e161170050048acd8f00>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->