add height animation to dropdown
Codecademy/client-modules pull request #1496
Opened 2021-03-12 15:00 UTC by sylvanasantos

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-03-12 15:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b83034138fc105ec8ad77--gamut-preview.netlify.app>https://604b83034138fc105ec8ad77--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b83034138fc105ec8ad77>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 15:20 UTC, codecaaron commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +              animate={{ height: 'auto' }}
Animating height is kinda tricky.

If we use auto here with the same duration each drop down will open at a different velocity, since drop downs might have different heights. 

A big one will go really fast, a small one will go really slow.  In order to have consistent visual timing on opening we'd need to use something like min-height (with an arbitrary number larger than all popovers) to make each popover expand with the same perceived velocity.

2021-03-12 15:23 UTC, sylvanasantos commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +              animate={{ height: 'auto' }}
oh, hello there! ahhhh that's a great point. will change to min-height.

2021-03-12 15:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604b8b9d0b626e14586d5fc5--gamut-preview.netlify.app>https://604b8b9d0b626e14586d5fc5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604b8b9d0b626e14586d5fc5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-12 15:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.0037cb.0<br/>@codecademy/gamut-labs@11.2.3-alpha.0037cb.0<br/>@codecademy/styleguide@30.5.3-alpha.0037cb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-12 16:35 UTC, jcenglish commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +              animate={{ maxHeight: '32rem' }}
The maxHeight is tricky because when you open the dropdown, the animation plays out for the maxHeight of the element. It's more noticeable when you close the drop down and there's a pause - it's because it's animating in reverse from the maxHeight that you can't see. [I used 200px (12.5rem)](https://github.com/codecademy-engineering/Codecademy/blob/ebe373045e640947775a18fdcd355b80fc20779c/webpack/assets/components/HeaderDropdown/index.tsx#L77), which is a magic number I figured no menu height would _probably_ exceed, and it seemed short enough to not cause a noticeable animation pause.

2021-03-12 16:38 UTC, sylvanasantos commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +              animate={{ maxHeight: '32rem' }}
yeahhhh, i just noticed that...problem is that the avatar dropdown is ~450px

2021-03-12 16:39 UTC, sylvanasantos commented on packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +              animate={{ maxHeight: '32rem' }}
i will continue to play around with it

2021-03-15 20:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.d401b4.0<br/>@codecademy/gamut-labs@11.2.3-alpha.d401b4.0<br/>@codecademy/styleguide@30.5.3-alpha.d401b4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 20:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604fc388b41f8209369cc3b4--gamut-preview.netlify.app>https://604fc388b41f8209369cc3b4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604fc388b41f8209369cc3b4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-16 17:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.1a0b33.0<br/>@codecademy/gamut-labs@11.2.3-alpha.1a0b33.0<br/>@codecademy/styleguide@30.5.3-alpha.1a0b33.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-16 17:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6050ea471520b706e4cc8062--gamut-preview.netlify.app>https://6050ea471520b706e4cc8062--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6050ea471520b706e4cc8062>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-16 18:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.15-alpha.55585a.0<br/>@codecademy/gamut-labs@11.2.3-alpha.55585a.0<br/>@codecademy/styleguide@30.5.3-alpha.55585a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-16 18:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6050f4580f5b8e13f4a8d5a5--gamut-preview.netlify.app>https://6050f4580f5b8e13f4a8d5a5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6050f4580f5b8e13f4a8d5a5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-16 21:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.1b483b.0<br/>@codecademy/gamut-labs@12.0.3-alpha.1b483b.0<br/>@codecademy/styleguide@31.1.1-alpha.1b483b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-16 21:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60512908e506cd08a97209cd--gamut-preview.netlify.app>https://60512908e506cd08a97209cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60512908e506cd08a97209cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-16 22:37 UTC, jakemhiller requested changes
Did you look into using framer motion "layout" animations for this? I think it would give you better results. Can give you an example tomorrow.

2021-03-17 20:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.dc97a7.0<br/>@codecademy/gamut-labs@12.0.3-alpha.dc97a7.0<br/>@codecademy/styleguide@31.1.1-alpha.dc97a7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 20:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60526a14edf7ea382e3c30dd--gamut-preview.netlify.app>https://60526a14edf7ea382e3c30dd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60526a14edf7ea382e3c30dd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-18 14:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.5a7c71.0<br/>@codecademy/gamut-labs@12.0.3-alpha.5a7c71.0<br/>@codecademy/styleguide@31.1.1-alpha.5a7c71.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-18 14:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605364cd3fc29ceca3a2b274--gamut-preview.netlify.app>https://605364cd3fc29ceca3a2b274--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605364cd3fc29ceca3a2b274>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-18 15:53 UTC, sylvanasantos commented
alrighty, so after talking to multiple people and going through various implementations, it seems like this is the best approach. it's definitely not ideal that we are calculating the height based on assumptions about the spacing of links/separators, but this seems to be the only implementation that does not weirdly shift the contents of the dropdown or cause weird timing issues. let me know if this seems reasonable and I'll add tests for the changes.

2021-03-23 15:06 UTC, jakemhiller approved these changes
looks good to me! Calculating the height like this isn't ideal, but given the bug we found I think it's reasonable for now

2021-03-23 15:33 UTC, dreamwasp approved these changes
lgtm!

2021-03-25 17:27 UTC, katiezutter approved these changes
Pumped about this animation!! Thanks Sylvana!

2021-03-25 18:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.37-alpha.968991.0<br/>@codecademy/gamut-labs@13.1.7-alpha.968991.0<br/>@codecademy/styleguide@33.3.5-alpha.968991.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 18:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605cda82f074c787b973dbb1--gamut-preview.netlify.app>https://605cda82f074c787b973dbb1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605cda82f074c787b973dbb1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 21:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.37-alpha.8646c4.0<br/>@codecademy/gamut-labs@13.1.7-alpha.8646c4.0<br/>@codecademy/styleguide@33.3.5-alpha.8646c4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 21:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605d00fed363cabb02cadce4--gamut-preview.netlify.app>https://605d00fed363cabb02cadce4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605d00fed363cabb02cadce4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 21:43 UTC, merged