feat: Refactor Testimonial and Avatar to Emotion
Codecademy/client-modules pull request #1498
Opened 2021-03-14 16:13 UTC by rogervera

### Overview

Refactors Testimonial and Avatar to Emotion.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-03-14 16:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604e37ff64e222335b8ef8a9--gamut-preview.netlify.app>https://604e37ff64e222335b8ef8a9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604e37ff64e222335b8ef8a9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-14 17:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.dbb9be.0<br/>@codecademy/gamut-labs@11.2.4-alpha.dbb9be.0<br/>@codecademy/styleguide@30.6.1-alpha.dbb9be.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-14 17:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604e4edae8131884f74bbe4d--gamut-preview.netlify.app>https://604e4edae8131884f74bbe4d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604e4edae8131884f74bbe4d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 12:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.16-alpha.2cea65.0<br/>@codecademy/gamut-labs@11.2.4-alpha.2cea65.0<br/>@codecademy/styleguide@30.6.1-alpha.2cea65.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-15 12:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://604f4ceaa9112ec4384fa092--gamut-preview.netlify.app>https://604f4ceaa9112ec4384fa092--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/604f4ceaa9112ec4384fa092>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-15 14:34 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +    ${mediaQueries.sm} {
There's probably a way to do something like `${!compact && ` so we don't end up with a bunch of `grid-auto-flow: false;`s. 

Looking through https://gamut.codecademy.com/storybook/?path=/docs/foundations-layout--page, how about `atViewport`?

2021-03-15 14:35 UTC, JoshuaKGoldberg requested changes
LGTM in general and the story is very nice 😄 . I think this at risk of producing invalid CSS, so can we try the `atViewport` approach or similar?

2021-03-15 19:43 UTC, rogervera commented
> LGTM in general and the story is very nice 😄 . I think this at risk of producing invalid CSS, so can we try the `atViewport` approach or similar?

Just met with Aaron to go over the finer details on improvements here. Stayed tuned!

2021-03-19 18:20 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Avatar/index.tsx
> +  const { shadowColor } = modes[mode];
TIL!

2021-03-19 18:22 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +    textColor: colors.white,
curious why we're using both `brandColors` and `colors` here? shouldn't the `brandColors` be encompassed in `colors`?

2021-03-19 18:24 UTC, rogervera commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +    textColor: colors.white,
That's a good nit. White is the same in both, so I wanted to atleast move the needle a tiny bit.

2021-03-19 18:28 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +`;
wondering if instead of this we can do something along the lines of
```
<Box as="span" display={{ base: 'none', md: 'initial' }}>
```
i've seen @codecaaron do this but not sure if it is best practice

2021-03-19 21:05 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +const TestimonialCard = styled(GridBox)();
is this necessary? i'm guessing it's to be more explicit with the naming but not sure if that is really needed

2021-03-19 21:10 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +`;
oh you are below! so i think `LongQuote` and `ShortQuote` here aren't used and can be removed

2021-03-19 21:22 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Quote/__tests__/Quote-test.tsx
> +    const wrapper = render(<Quote>Timshel!</Quote>);
according to the build errors, we need to pass in the `mode` prop here

2021-03-19 21:22 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Quote/__tests__/Quote-test.tsx
> +    const wrapper = render(<Quote>Timshel!</Quote>);
```
src/brand/Quote/__tests__/Quote-test.tsx(8,29): error TS2741: Property 'mode' is missing in type '{ children: string; }' but required in type 'QuoteProps'.
```

2021-03-19 21:24 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Testimonial/__tests__/Testimonial-test.tsx
> +      <Testimonial {...exampleTestmonial} size="small" theme="dark" />
anddd `size` needs to be removed here and in the test above
https://app.circleci.com/pipelines/github/Codecademy/client-modules/11450/workflows/6836b604-1fc6-4897-a49e-73d07070c7c3/jobs/74341
```
src/brand/Testimonial/__tests__/Testimonial-test.tsx(20,9): error TS2322: Type '{ imageUrl: string; size: string; theme: string; firstName: string; lastName: string; occupation: string; quote: string; }' is not assignable to type 'IntrinsicAttributes & TestimonialProps & { children?: ReactNode; }'.
  Property 'size' does not exist on type 'IntrinsicAttributes & TestimonialProps & { children?: ReactNode; }'.
src/brand/Testimonial/__tests__/Testimonial-test.tsx(30,43): error TS2322: Type '{ size: string; theme: string; firstName: string; lastName: string; occupation: string; quote: string; }' is not assignable to type 'IntrinsicAttributes & TestimonialProps & { children?: ReactNode; }'.
  Property 'size' does not exist on type 'IntrinsicAttributes & TestimonialProps & { children?: ReactNode; }'.
```

2021-03-19 21:58 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Avatar/index.tsx
> +};
is this intentionally reversed from the current implementation? on prod we have orange shadow for light and purple shadow for dark

2021-03-19 22:01 UTC, aresnik11 commented on packages/styleguide/stories/Brand/Atoms/Quote.stories.mdx
> +<Canvas withSource="open" className="dark">
suggest adding another example here set to light so that it is easier to see what both variations looks like. currently if you toggle, the background doesn't change but the font colors do

2021-03-19 22:02 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Quote/index.tsx
> +    <QuoteIcon alt="" src={mode === 'light' ? purpleQuotes : orangeQuotes} />
is this intentionally reversed so purple quote is for light and orange for dark?

2021-03-19 22:02 UTC, rogervera commented on packages/gamut-labs/src/brand/Avatar/index.tsx
> +};
Ah yes, good catch. Thank you.  This should be reveresed.
https://gamut.codecademy.com/storybook/?path=/docs/atoms-tooltip--tool-tip as an example.

2021-03-19 22:02 UTC, rogervera commented on packages/gamut-labs/src/brand/Quote/index.tsx
> +    <QuoteIcon alt="" src={mode === 'light' ? purpleQuotes : orangeQuotes} />
Will swap: https://github.com/Codecademy/client-modules/pull/1498#discussion_r597996841

2021-03-19 22:54 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +                lastName={lastName}
should this be centered?
old testimonial:
<img width="963" alt="Screen Shot 2021-03-19 at 6 52 52 PM" src="https://user-images.githubusercontent.com/8761638/111849591-567ebe80-88e4-11eb-9b12-46638eb63471.png">

new testimonial:
<img width="970" alt="Screen Shot 2021-03-19 at 6 52 57 PM" src="https://user-images.githubusercontent.com/8761638/111849594-57afeb80-88e4-11eb-9cbe-af03df5b1b25.png">

2021-03-19 23:12 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +          paddingBottom={48}
the old testimonial has more padding at the larger viewports, should we do that here as well?

2021-03-19 23:23 UTC, aresnik11 reviewed
I'm super excited about this! It's coming along nicely but I have a bunch of questions/comments/nits that I scattered throughout, mostly around slight differences between this and the existing testimonial that aren't necessarily wrong but I just wanted to flag. Some more here:

1. The original testimonial has an animation on hover that isn't included here, was that intentional? https://github.com/Codecademy/client-modules/blob/main/packages/gamut-labs/src/brand/Testimonial/styles.module.scss#L79-L82. also that entire testimonial styles file can probably be deleted now 😬 
2. The original small testimonial has a different layout than this one, is that intentional? this one has the avatar/byline side by side with the quote vs the old one had the avatar/byline on top of the quote
old testimonial:
<img width="405" alt="Screen Shot 2021-03-19 at 7 17 34 PM" src="https://user-images.githubusercontent.com/8761638/111850852-c6db0f00-88e7-11eb-856b-a4f1cb66086e.png">
new testimonial:
<img width="477" alt="Screen Shot 2021-03-19 at 7 17 29 PM" src="https://user-images.githubusercontent.com/8761638/111850858-cc385980-88e7-11eb-99c2-ab29b48f49a7.png">

2021-03-22 19:10 UTC, rogervera commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +          paddingBottom={48}
Will add for the respective viewport!

2021-03-22 19:10 UTC, rogervera commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +                lastName={lastName}
Will look into having the Byline spans their content width.

2021-03-22 19:13 UTC, rogervera commented on packages/styleguide/stories/Brand/Atoms/Quote.stories.mdx
> +<Canvas withSource="open" className="dark">
Got it, so will add a dark wrapper className example to these.

2021-03-22 19:15 UTC, rogervera commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +`;
Totally right. Will remove.

2021-03-22 19:28 UTC, rogervera commented
> I'm super excited about this! It's coming along nicely but I have a bunch of questions/comments/nits that I scattered throughout, mostly around slight differences between this and the existing testimonial that aren't necessarily wrong but I just wanted to flag. Some more here:
> 
> 1. The original testimonial has an animation on hover that isn't included here, was that intentional? https://github.com/Codecademy/client-modules/blob/main/packages/gamut-labs/src/brand/Testimonial/styles.module.scss#L79-L82. also that entire testimonial styles file can probably be deleted now 😬
> 2. The original small testimonial has a different layout than this one, is that intentional? this one has the avatar/byline side by side with the quote vs the old one had the avatar/byline on top of the quote
>    old testimonial:
> 
> <img alt="Screen Shot 2021-03-19 at 7 17 34 PM" width="405" src="https://user-images.githubusercontent.com/8761638/111850852-c6db0f00-88e7-11eb-856b-a4f1cb66086e.png">
> 
> new testimonial:
> <img alt="Screen Shot 2021-03-19 at 7 17 29 PM" width="477" src="https://user-images.githubusercontent.com/8761638/111850858-cc385980-88e7-11eb-99c2-ab29b48f49a7.png">

1. On hover, we can add that back. 

> 2\. The original small testimonial has a different layout than this one, is that intentional? this one has the avatar/byline side by side with the quote vs the old one had the avatar/byline on top of the quote
>     old testimonial:


2. @aresnik11 and I paired on this. The `min-width` on the Quote Container needs to be set to something else than `min-content`. And I'll put up PRs for the migration for comparisons on the monolith and static sites usage spots for the testimonial.

2021-03-25 12:46 UTC, rogervera commented on packages/gamut-labs/src/brand/Testimonial/index.tsx
> +const TestimonialCard = styled(GridBox)();
Using this as an explicit selector in the parent TestimonialWrapper
```jsx
${TestimonialCard} {
   align-content: center;
```

2021-03-25 12:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.35-alpha.93a56e.0<br/>@codecademy/gamut-labs@13.1.5-alpha.93a56e.0<br/>@codecademy/styleguide@33.3.3-alpha.93a56e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 12:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605c88ca7204d900908b4c17--gamut-preview.netlify.app>https://605c88ca7204d900908b4c17--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605c88ca7204d900908b4c17>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-07 19:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.aa0a1d.0<br/>@codecademy/gamut-labs@13.3.1-alpha.aa0a1d.0<br/>@codecademy/styleguide@33.7.2-alpha.aa0a1d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-07 19:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606e07ce80a3bf2643c4bd9b--gamut-preview.netlify.app>https://606e07ce80a3bf2643c4bd9b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606e07ce80a3bf2643c4bd9b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-07 20:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.582263.0<br/>@codecademy/gamut-labs@13.3.1-alpha.582263.0<br/>@codecademy/styleguide@33.7.2-alpha.582263.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-07 21:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606e1d5d4983973c9704ce2b--gamut-preview.netlify.app>https://606e1d5d4983973c9704ce2b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606e1d5d4983973c9704ce2b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-08 14:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.3d003a.0<br/>@codecademy/gamut-labs@13.3.1-alpha.3d003a.0<br/>@codecademy/styleguide@33.7.2-alpha.3d003a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-08 14:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606f1814efa402f248d1ebc0--gamut-preview.netlify.app>https://606f1814efa402f248d1ebc0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606f1814efa402f248d1ebc0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-08 15:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.6-alpha.daef87.0<br/>@codecademy/gamut-labs@13.3.6-alpha.daef87.0<br/>@codecademy/styleguide@33.8.2-alpha.daef87.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-08 15:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606f267d7cbf9401507755c0--gamut-preview.netlify.app>https://606f267d7cbf9401507755c0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606f267d7cbf9401507755c0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 20:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.6-alpha.84507b.0<br/>@codecademy/gamut-labs@13.3.6-alpha.84507b.0<br/>@codecademy/styleguide@33.8.2-alpha.84507b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 20:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070b383533b4a53e5b54122--gamut-preview.netlify.app>https://6070b383533b4a53e5b54122--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070b383533b4a53e5b54122>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 20:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.6-alpha.4ff6ee.0<br/>@codecademy/gamut-labs@13.3.6-alpha.4ff6ee.0<br/>@codecademy/styleguide@33.8.2-alpha.4ff6ee.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 20:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070b9a7093f7e51d5709c07--gamut-preview.netlify.app>https://6070b9a7093f7e51d5709c07--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070b9a7093f7e51d5709c07>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 21:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.6-alpha.e295ba.0<br/>@codecademy/gamut-labs@13.3.6-alpha.e295ba.0<br/>@codecademy/styleguide@33.8.2-alpha.e295ba.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 21:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070c14ddd12ea56c63fbd92--gamut-preview.netlify.app>https://6070c14ddd12ea56c63fbd92--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070c14ddd12ea56c63fbd92>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 21:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.8-alpha.13400f.0<br/>@codecademy/gamut-labs@13.3.8-alpha.13400f.0<br/>@codecademy/styleguide@33.8.5-alpha.13400f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 21:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070c418a3287262c56138f6--gamut-preview.netlify.app>https://6070c418a3287262c56138f6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070c418a3287262c56138f6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 21:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.8-alpha.8fc3c3.0<br/>@codecademy/gamut-labs@13.3.8-alpha.8fc3c3.0<br/>@codecademy/styleguide@33.8.5-alpha.8fc3c3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 21:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070c872ba6b5a00bf1e64aa--gamut-preview.netlify.app>https://6070c872ba6b5a00bf1e64aa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070c872ba6b5a00bf1e64aa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 21:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.9-alpha.35a043.0<br/>@codecademy/gamut-labs@13.4.1-alpha.35a043.0<br/>@codecademy/styleguide@33.9.1-alpha.35a043.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 21:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070cb0a872c9400b81759cf--gamut-preview.netlify.app>https://6070cb0a872c9400b81759cf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070cb0a872c9400b81759cf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 22:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.9-alpha.187534.0<br/>@codecademy/gamut-labs@13.4.1-alpha.187534.0<br/>@codecademy/styleguide@33.9.1-alpha.187534.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 23:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070dc68fe86ed164ce9ca18--gamut-preview.netlify.app>https://6070dc68fe86ed164ce9ca18--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070dc68fe86ed164ce9ca18>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-11 21:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.9-alpha.3d40a2.0<br/>@codecademy/gamut-labs@13.4.1-alpha.3d40a2.0<br/>@codecademy/styleguide@33.9.1-alpha.3d40a2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-11 22:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.10-alpha.aafefc.0<br/>@codecademy/gamut-labs@13.4.2-alpha.aafefc.0<br/>@codecademy/styleguide@33.9.2-alpha.aafefc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-11 22:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607376231217934e6b58b024--gamut-preview.netlify.app>https://607376231217934e6b58b024--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607376231217934e6b58b024>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-13 15:48 UTC, aresnik11 commented on packages/gamut-labs/src/brand/Byline/index.tsx
> +`;
is this not an option for the `width` prop within `FlexBox`?

2021-04-14 14:45 UTC, aresnik11 reviewed
This is looking so good!!! Not going to officially approve since I know Timea had some design feedback that still needs to be incorporated, but once that is in I'll take another look!

2021-04-21 18:10 UTC, christian-dinh commented
is this still pending design feedback?

2021-04-21 18:14 UTC, rogervera commented
> is this still pending design feedback?

Currently yes. Pending changes are for addressing these points from Tímea! Will tag you and @aresnik11 for the check when in. :)
![testimonial notes](https://user-images.githubusercontent.com/17210163/115601461-c0202d00-a2d5-11eb-8847-8b4c3e12bae8.png)

2021-04-26 13:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.48-alpha.b90b1d.0<br/>@codecademy/gamut-labs@14.3.2-alpha.b90b1d.0<br/>@codecademy/styleguide@36.3.2-alpha.b90b1d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 13:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086c699e0d27300a2bae38a--gamut-preview.netlify.app>https://6086c699e0d27300a2bae38a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086c699e0d27300a2bae38a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 13:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.e185d4.0<br/>@codecademy/gamut-labs@14.4.4-alpha.e185d4.0<br/>@codecademy/styleguide@36.4.4-alpha.e185d4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 13:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088182bfa8e8b483f646d2e--gamut-preview.netlify.app>https://6088182bfa8e8b483f646d2e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088182bfa8e8b483f646d2e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-12 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.0f785b.0<br/>@codecademy/gamut-labs@16.0.2-alpha.0f785b.0<br/>@codecademy/styleguide@37.5.5-alpha.0f785b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-12 19:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c31d2d2553e18e1a0384e--gamut-preview.netlify.app>https://609c31d2d2553e18e1a0384e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c31d2d2553e18e1a0384e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-12 20:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.e5fd8b.0<br/>@codecademy/gamut-labs@16.0.2-alpha.e5fd8b.0<br/>@codecademy/styleguide@37.5.5-alpha.e5fd8b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-12 20:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c347f8f8eb119f0e4ebe0--gamut-preview.netlify.app>https://609c347f8f8eb119f0e4ebe0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c347f8f8eb119f0e4ebe0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-12 20:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.946780.0<br/>@codecademy/gamut-labs@16.0.2-alpha.946780.0<br/>@codecademy/styleguide@37.5.5-alpha.946780.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-12 20:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c3d1ea957662d125ffa58--gamut-preview.netlify.app>https://609c3d1ea957662d125ffa58--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c3d1ea957662d125ffa58>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-12 21:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.c672cc.0<br/>@codecademy/gamut-labs@16.0.2-alpha.c672cc.0<br/>@codecademy/styleguide@37.5.5-alpha.c672cc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-12 21:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c48c2d2553e3027a03896--gamut-preview.netlify.app>https://609c48c2d2553e3027a03896--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c48c2d2553e3027a03896>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-12 22:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.ea2cd6.0<br/>@codecademy/gamut-labs@16.0.2-alpha.ea2cd6.0<br/>@codecademy/styleguide@37.5.5-alpha.ea2cd6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-12 23:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c5decf061ec00940ea61f--gamut-preview.netlify.app>https://609c5decf061ec00940ea61f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c5decf061ec00940ea61f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-13 17:45 UTC, JoshuaKGoldberg commented
TBH I think @codecaaron is better positioned than me to review these - but lmk if I should step back up Aaron!

2021-05-13 17:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.6b246a.0<br/>@codecademy/gamut-labs@16.0.2-alpha.6b246a.0<br/>@codecademy/styleguide@37.5.5-alpha.6b246a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-13 17:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609d668e4e929e3a68b59515--gamut-preview.netlify.app>https://609d668e4e929e3a68b59515--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609d668e4e929e3a68b59515>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-14 13:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609e7ac8592700df7b45e145--gamut-preview.netlify.app>https://609e7ac8592700df7b45e145--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609e7ac8592700df7b45e145>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-14 13:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.102-alpha.cb9ccf.0<br/>@codecademy/gamut-labs@17.0.1-alpha.cb9ccf.0<br/>@codecademy/styleguide@38.0.1-alpha.cb9ccf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-14 13:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609e7f5d155fddecfb26769e--gamut-preview.netlify.app>https://609e7f5d155fddecfb26769e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609e7f5d155fddecfb26769e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-15 03:46 UTC, JoshuaKGoldberg approved these changes
Great to see progress on this 😁  love it!

2021-05-15 03:46 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/Testimonial/index.tsx
> +  /** Click callback */
Nit: you don't say!

```suggestion
```

2021-05-17 14:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.103-alpha.356ac8.0<br/>@codecademy/gamut-labs@17.1.1-alpha.356ac8.0<br/>@codecademy/styleguide@38.1.1-alpha.356ac8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-17 14:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a279b1be2e5110096f1f5a--gamut-preview.netlify.app>https://60a279b1be2e5110096f1f5a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a279b1be2e5110096f1f5a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-17 21:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.103-alpha.eea689.0<br/>@codecademy/gamut-labs@17.1.1-alpha.eea689.0<br/>@codecademy/styleguide@38.1.1-alpha.eea689.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-17 21:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a2dd189b1e03345b167b12--gamut-preview.netlify.app>https://60a2dd189b1e03345b167b12--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a2dd189b1e03345b167b12>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-18 15:51 UTC, aresnik11 commented on packages/gamut-labs/src/Testimonial/index.tsx
> +              </Box>
curious why you decided to inline this instead of using the `Quote` component we previously had

2021-05-18 15:53 UTC, aresnik11 commented on packages/gamut-labs/src/Testimonial/index.tsx
> +            <Box flexGrow={9999} flexShrink={1} flexBasis="0" minWidth="70%">
i'm not the best at `flex` yet but `flexGrow={9999}` seems icky. @christian-dinh @JoshuaKGoldberg can i get a sanity check here?

2021-05-18 16:13 UTC, christian-dinh commented on packages/gamut-labs/src/Testimonial/index.tsx
> +            <Box flexGrow={9999} flexShrink={1} flexBasis="0" minWidth="70%">
ah yeah this was my suggestion. it's definitely a [bit of a hack](https://joren.co/flex-grow-9999-hack/)

basically what this does (along with the `flexBasis={0}` in the left column's `FlexBox`) is always expand the right column while always shrinking the left column if they are side-by-side, and always expanding both if the right column wraps to a new line.

2021-05-18 16:19 UTC, christian-dinh commented on packages/gamut-labs/src/Testimonial/index.tsx
> +            <Box flexGrow={9999} flexShrink={1} flexBasis="0" minWidth="70%">
might be good to include a comment here if we're ok with doing it this way

2021-05-18 21:07 UTC, aresnik11 commented on packages/gamut-labs/src/Testimonial/index.tsx
> +                  height="74px"
are these needed? they weren't included when we were using the `Quote` component

2021-05-19 00:37 UTC, aresnik11 commented on packages/gamut-labs/src/Testimonial/index.tsx
> +            <Box flexGrow={9999} flexShrink={1} flexBasis="0" minWidth="70%">
ohhh i see, that link was super helpful

2021-05-19 01:02 UTC, aresnik11 commented on packages/gamut-labs/src/Testimonial/index.tsx
> +              <Box mb={16} mr={16} minWidth="11rem">
any reason why this is specifically `11rem`? on iphone x and smaller, the byline falls to below the avatar. if we reduced this to `9.5rem` it would not do this, or even `10rem` would cover more of the phones
<img width="368" alt="Screen Shot 2021-05-18 at 8 59 53 PM" src="https://user-images.githubusercontent.com/8761638/118741329-06f13c00-b81c-11eb-80c6-66487c33c9d9.png">

2021-05-19 16:53 UTC, judahtanthony commented on packages/gamut-labs/src/Testimonial/index.tsx
> +                  height="74px"
yes.  They were requested by Timea.

2021-05-19 17:01 UTC, aresnik11 approved these changes

2021-05-19 17:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.103-alpha.e69b98.0<br/>@codecademy/gamut-labs@17.1.1-alpha.e69b98.0<br/>@codecademy/styleguide@38.1.1-alpha.e69b98.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-19 17:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a54504a1b0d618db82f1c2--gamut-preview.netlify.app>https://60a54504a1b0d618db82f1c2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a54504a1b0d618db82f1c2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-19 17:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.106-alpha.b047fb.0<br/>@codecademy/gamut-labs@17.3.1-alpha.b047fb.0<br/>@codecademy/styleguide@38.3.1-alpha.b047fb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-19 17:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a54c6068578f1f62bbb5a5--gamut-preview.netlify.app>https://60a54c6068578f1f62bbb5a5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a54c6068578f1f62bbb5a5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-19 18:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.107-alpha.319059.0<br/>@codecademy/gamut-labs@17.3.2-alpha.319059.0<br/>@codecademy/styleguide@38.3.2-alpha.319059.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-19 18:58 UTC, merged

2021-05-19 18:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a55ffa27170d37aace3255--gamut-preview.netlify.app>https://60a55ffa27170d37aace3255--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a55ffa27170d37aace3255>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->