feat(Input): Add custom gamut-icons to Input components
Codecademy/client-modules pull request #1513
Opened 2021-03-17 00:04 UTC by dreamwasp

### Overview
Feature to add (relatively) custom gamut-icons to Input components + some 🧹 here and there.

### PR Checklist

- [x] Related to designs:[Form Updates](https://www.figma.com/file/9Ke4l9EdIup7kiB3KsbEHx/Form-Inputs-Components?node-id=1218%3A0) [Form Checkout](https://www.figma.com/file/xaosTDGWkXtTJBLPDV7ME2/Checkout---Clarity-improvements?node-id=1043%3A643)
- [x] Related to JIRA ticket:[ GM-161](https://codecademy.atlassian.net/browse/GM-161)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

2021-03-17 00:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.22-alpha.eb6f84.0<br/>@codecademy/gamut-labs@12.0.2-alpha.eb6f84.0<br/>@codecademy/gamut@27.0.2-alpha.eb6f84.0<br/>@codecademy/styleguide@31.0.2-alpha.eb6f84.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 00:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60514a44e2aff500bfdd9096--gamut-preview.netlify.app>https://60514a44e2aff500bfdd9096--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60514a44e2aff500bfdd9096>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 18:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.4e82fd.0<br/>@codecademy/gamut-labs@12.0.3-alpha.4e82fd.0<br/>@codecademy/gamut@27.1.1-alpha.4e82fd.0<br/>@codecademy/styleguide@31.1.1-alpha.4e82fd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 18:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.c2a123.0<br/>@codecademy/gamut-labs@12.0.3-alpha.c2a123.0<br/>@codecademy/gamut@27.1.1-alpha.c2a123.0<br/>@codecademy/styleguide@31.1.1-alpha.c2a123.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 18:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605250efe07380266356a413--gamut-preview.netlify.app>https://605250efe07380266356a413--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605250efe07380266356a413>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 19:16 UTC, borisonr reviewed
looking great, thanks! just left a few comments/qs

2021-03-17 19:16 UTC, borisonr commented on packages/gamut/src/Form/Input.tsx
> +   * An custom icon svg from gamut-icons.
please don't hate me
```suggestion
   * A custom icon svg from gamut-icons.
```

2021-03-17 19:16 UTC, borisonr commented on packages/gamut/src/Form/Input.tsx
> +    const ShownIcon = error
i personally find nested ternaries to be difficult to read, but leave that up to you

2021-03-17 19:16 UTC, borisonr commented on packages/gamut/src/Form/Input.tsx
> +        {ShownIcon && <ShownIcon textColor={iconColor} />}
should this be
```suggestion
        {!!ShownIcon && <ShownIcon textColor={iconColor} />}
```

2021-03-17 19:18 UTC, borisonr commented on packages/gamut/src/Form/Input.tsx
> +      : valid
oh also i ~ think ~ tamar wants the credit card icons to show even when the field is valid? not sure if you want to chat with her or we can

2021-03-17 19:20 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +      : valid
yeah that makes sense! i can switch up the precedence

2021-03-17 19:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.dd9657.0<br/>@codecademy/gamut-labs@12.0.3-alpha.dd9657.0<br/>@codecademy/gamut@27.1.1-alpha.dd9657.0<br/>@codecademy/styleguide@31.1.1-alpha.dd9657.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 19:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60525770984d9f27aabd03e2--gamut-preview.netlify.app>https://60525770984d9f27aabd03e2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60525770984d9f27aabd03e2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 22:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.c66ca9.0<br/>@codecademy/gamut-labs@12.0.3-alpha.c66ca9.0<br/>@codecademy/gamut@27.1.1-alpha.c66ca9.0<br/>@codecademy/styleguide@31.1.1-alpha.c66ca9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 22:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605285e8d498590f22869418--gamut-preview.netlify.app>https://605285e8d498590f22869418--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605285e8d498590f22869418>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-19 16:25 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/styles/shared.tsx
> +  const StyledIcon = styled(Icon, { shouldForwardProp })(
@codecaaron just raising this - I've previously skirted around the issue of a dynamic styled component before, but don't see a way around here... would sure be nice if we had a thing for this to avoid recreating a component each render.

2021-03-19 16:30 UTC, JoshuaKGoldberg requested changes
Looks good to start! A bit unfortunate that custom styled components is hard, but I don't think that's specific to this PR.

Requesting changes on the padding?

2021-03-19 16:30 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/styles/shared.tsx
> +export const miniIconStyles = css`
Looks like the icons are a little more padded from the right than in the designs, or compared to the field contents. Maybe `right: 0.5rem` instead of `right: 1rem`?

![Figma design of a credit card input](https://user-images.githubusercontent.com/3335181/111812218-4815b000-88ae-11eb-98ac-e05550bc0ce9.png)

![Screenshot of an overly padded form in the Storybook](https://user-images.githubusercontent.com/3335181/111812286-58c62600-88ae-11eb-91da-fae3d34e041b.png)

2021-03-19 16:56 UTC, codecaaron commented on packages/gamut/src/Form/styles/shared.tsx
> +  const StyledIcon = styled(Icon, { shouldForwardProp })(
Yeah I'm working on adding our own instance that does this automagically, but there's some real funkiness with re-exporting it.

I'm going to have another package that exports our own version of styled that does this any some other things under the hood for ALL styled components.

It'll be something like `import styled from "@codecademy/styled"` or something.

On the code sharing side of this we can resolve this with `as` for now. 

```tsx
const InputIcon = styled('svg', { shouldForwardProp })(properties.textColor);

<InputIcon as={AlertIcon} />
```

FWIW this isn't necessary if currentColor is what we want it do be.

2021-03-19 21:15 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/__tests__/Input-test.tsx
> +  it('renders a text input type', () => {
Nit: these test names make it seem like these situations happen always. Adding a "when" clause would help clarify.

```suggestion
  it('renders a text input type when the type is text', () => {
```

2021-03-19 21:16 UTC, JoshuaKGoldberg reviewed
(just waiting on the alpha deploy)

2021-03-19 23:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.26-alpha.ee9485.0<br/>@codecademy/gamut-labs@13.0.2-alpha.ee9485.0<br/>@codecademy/gamut@28.0.2-alpha.ee9485.0<br/>@codecademy/styleguide@32.0.4-alpha.ee9485.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-19 23:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605530c854783c9d1f1b764a--gamut-preview.netlify.app>https://605530c854783c9d1f1b764a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605530c854783c9d1f1b764a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-20 03:16 UTC, codecaaron commented on packages/gamut/src/Form/Input.tsx
> +    const iconColor = error ? 'red' : valid ? 'green' : 'gray-600';
It's possible that we might need to add new conditions to this in future (like dirty state!).   I've found that input states can end up getting pretty tricky as we start to do more complex things with them (managing touched / clean / form resets etc). 

Reducing all these flags down to a single state enum (which be used to key objects, human readable in devtool) may be something  worth exploring down the line.

```tsx
const inputStates = {
 error: { 
    color: 'red', 
    icon: AlertIcon
  },
  valid: {
    color:  'green',
    icon: CheckCircleIcon,
  }
  clean: {
    color: 'gray-600',
  }
}

const getInputState = ({ error, valid, activated }) => {
  if (!activated &&  error) return 'error';
  if (!activated && valid) return 'valid';
  // any other complex set of conditions 
  return 'clean';
}


const Input = (props) => {
  const { color, icon } = inputStates[getInputState(props)];
}

```

2021-03-21 15:16 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +import * as icons from '@codecademy/gamut-icons';
Oh, wait, we probably don't want to do this - this will bring in _all_ icons from `@codecademy/gamut-icons`.

We should lint against it...

2021-03-22 00:32 UTC, codecaaron commented on packages/gamut/src/Form/Input.tsx
> +import * as icons from '@codecademy/gamut-icons';
Yeah we want the types but not the actual code for compile.  I think we need some intermediate union so we don't end up pulling in everything.  (Unless the compile step somehow messes with tree shaking)

2021-03-22 01:39 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +import * as icons from '@codecademy/gamut-icons';
Maybe a case for `import type` then?

2021-03-22 17:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.26-alpha.b3a7ff.0<br/>@codecademy/gamut-labs@13.0.2-alpha.b3a7ff.0<br/>@codecademy/gamut@28.0.2-alpha.b3a7ff.0<br/>@codecademy/styleguide@32.0.4-alpha.b3a7ff.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-22 17:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6058d69d066a6010e587b770--gamut-preview.netlify.app>https://6058d69d066a6010e587b770--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6058d69d066a6010e587b770>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-22 20:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.28-alpha.da55cb.0<br/>@codecademy/gamut-labs@13.0.4-alpha.da55cb.0<br/>@codecademy/gamut@29.0.2-alpha.da55cb.0<br/>@codecademy/styleguide@33.0.2-alpha.da55cb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-22 20:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6058fd30842eb8009b67fab4--gamut-preview.netlify.app>https://6058fd30842eb8009b67fab4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6058fd30842eb8009b67fab4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-22 21:03 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +import * as icons from '@codecademy/gamut-icons';
i couldn't really figure out how to do this gracefully (without lots of `React.ForwardRefExoticComponent<Pick<GamutIconProps, "string" | "m`... etc.). 

my solution is a pretty inelegant + am open to alternatives 🙂

2021-03-22 21:04 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +    const iconColor = error ? 'red' : valid ? 'green' : 'gray-600';
word, lmk if my implementation makes sense! i was getting some type errors from just declaring colors as strings but think i got there 😬

2021-03-22 21:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.28-alpha.f11423.0<br/>@codecademy/gamut-labs@13.0.4-alpha.f11423.0<br/>@codecademy/gamut@29.0.2-alpha.f11423.0<br/>@codecademy/styleguide@33.0.2-alpha.f11423.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-22 21:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60590ec173a1a61b94c8d1d5--gamut-preview.netlify.app>https://60590ec173a1a61b94c8d1d5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60590ec173a1a61b94c8d1d5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-22 22:07 UTC, codecaaron approved these changes
LGTM with a few non blocking clean up thingies

I think we can probably get the icons to work without any extra styles on the next pass :)

2021-03-22 22:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.28-alpha.1bcb27.0<br/>@codecademy/gamut-labs@13.0.4-alpha.1bcb27.0<br/>@codecademy/gamut@29.0.2-alpha.1bcb27.0<br/>@codecademy/styleguide@33.0.2-alpha.1bcb27.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-22 22:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605920cde1558400d32c0d50--gamut-preview.netlify.app>https://605920cde1558400d32c0d50--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605920cde1558400d32c0d50>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-22 23:37 UTC, JoshuaKGoldberg approved these changes
Great!

2021-03-22 23:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.29-alpha.8fc2a9.0<br/>@codecademy/gamut-labs@13.0.5-alpha.8fc2a9.0<br/>@codecademy/gamut@29.1.1-alpha.8fc2a9.0<br/>@codecademy/styleguide@33.0.3-alpha.8fc2a9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-22 23:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60592ee8c7095021b1374c35--gamut-preview.netlify.app>https://60592ee8c7095021b1374c35--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60592ee8c7095021b1374c35>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-23 12:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.30-alpha.8dd58f.0<br/>@codecademy/gamut-labs@13.0.6-alpha.8dd58f.0<br/>@codecademy/gamut@29.2.1-alpha.8dd58f.0<br/>@codecademy/styleguide@33.1.1-alpha.8dd58f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-23 12:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6059e5ba60104a340bc97d60--gamut-preview.netlify.app>https://6059e5ba60104a340bc97d60--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6059e5ba60104a340bc97d60>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-23 13:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.32-alpha.f947dc.0<br/>@codecademy/gamut-labs@13.1.2-alpha.f947dc.0<br/>@codecademy/gamut@29.3.2-alpha.f947dc.0<br/>@codecademy/styleguide@33.2.2-alpha.f947dc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-23 13:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6059ee8f9020374392cc375a--gamut-preview.netlify.app>https://6059ee8f9020374392cc375a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6059ee8f9020374392cc375a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-23 13:37 UTC, merged