fix(NotificationItemNew): dismiss icon hover
Codecademy/client-modules pull request #1514
Opened 2021-03-17 14:21 UTC by saghdaey

### Overview

add style for dismiss icon hover

To test: visit NotificationListNew story in the preview environment; hover over the dismiss icon on the Notification w/ a link. Confirm that you see the clickable area for the dismiss icon on hover. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket:[ EGG-893](https://codecademy.atlassian.net/browse/EGG-893)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-03-17 14:37 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +    background-color: rgba(0, 0, 0, 0.05);
Let's either bump it to `.1` if looks a bit faint, or swap this to a gray that is ~`200` more than the one we've used for the background.

Also lets make a comment here that we are doing this for a specific case and that we should not be doing this in other places.

2021-03-17 14:37 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +    background-color: rgba(0, 0, 0, 0.05);
i'll try that. thanks!

2021-03-17 14:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6052157acc165da43c8d4d2c--gamut-preview.netlify.app>https://6052157acc165da43c8d4d2c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6052157acc165da43c8d4d2c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 15:06 UTC, codecaaron requested changes

2021-03-17 15:06 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +`;
```suggestion
const StyledIconButton = styled(IconButton)`
  ${ButtonInner}:hover {
      background-color: ${({ theme }) => theme.colors['gray-400']}; // this will break on darkmode
  }
`;
```

2021-03-17 15:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.56e81e.0<br/>@codecademy/gamut-labs@12.0.3-alpha.56e81e.0<br/>@codecademy/gamut@27.1.1-alpha.56e81e.0<br/>@codecademy/styleguide@31.1.1-alpha.56e81e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-17 15:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60521b3f8179f6ac6e1f356d--gamut-preview.netlify.app>https://60521b3f8179f6ac6e1f356d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60521b3f8179f6ac6e1f356d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-17 16:14 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +        theme.colors['gray-300']} !important; // this will break on darkmode
🤔 

This makes me nervous. I think it'd be better to have a specific button for this probably... We don't guarantee across components that CSS properties like `background-color` will aways be the right thing to change.

Also the `!important`

2021-03-17 16:15 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +`;
Ah just seeing this now. @codecaaron what do you think about making a new button for this? In my mind there are two options for special cases like this:

* Design is unintentionally introducing a new button variant and we should not support that
* Design is intentionally introducing a new button variant and we should support that first-class

2021-03-17 16:17 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +`;
I can go back to my initial implementation?
https://github.com/Codecademy/client-modules/pull/1418#discussion_r579469709

2021-03-17 16:28 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +`;
I think the best option is to just only use backgrounds with opacity for these emphasis effects across these buttons.

// light mode
background-color: rgab(0, 0, 0, 0.05); // dark

// dark mode
background-color: rgba(255, 255, 255, 0.15);  // lighten 

It messes with the hue a bit but its gets us out of having to find something darker since the effects will stack due to their alpha being < 1

This will have some unintended effects though.

Other option is to use a pseudo element on the container provision the hover effect for the anchor (as a sibling) and make the anchor not be a parent of the button (no more propogation bugs too, but a consistent experience with no nested hover effects).

2021-03-17 16:31 UTC, JoshuaKGoldberg commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +`;
@saghdaey I was thinking of still using the normal buttons, but adding a variant for this case. Or, even better, swapping the design to use an existing variant.

2021-03-17 16:36 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +`;
Option 2 avoids us having to mess with any colors or buttons or event propagation, complexity reduction abound.

2021-03-17 16:44 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +`;
ok ill try this aaron!

2021-03-18 05:18 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +  const notificationContent: ReactElement = (
this was renderNotificationContent() before but since were not taking in any parameters i've changed it to plain jsx

2021-03-18 05:24 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +  const notificationContent: ReactElement = (
this is essentially the inner notification content
if the notification has a url (ie is a link) --> we'll have 
```
<Container>
     <StyledLink>{notificationContent}</StyledLink}
     <DismissIcon/>
</Container>
```
otherwise we'll have
```
<Container>
     {notificationContent}
     <DismissIcon/>
</Container>
```

2021-03-18 05:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.52c62d.0<br/>@codecademy/gamut-labs@12.0.3-alpha.52c62d.0<br/>@codecademy/gamut@27.1.1-alpha.52c62d.0<br/>@codecademy/styleguide@31.1.1-alpha.52c62d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-18 05:25 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +  const notificationContent: ReactElement = (
notificationContent is dependent on the NotificationItem's props but i've de-structured those at the top of the component

2021-03-18 05:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6052e45d21ad636cb1e859ee--gamut-preview.netlify.app>https://6052e45d21ad636cb1e859ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6052e45d21ad636cb1e859ee>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-18 05:28 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> + this practice should not be replicated elsewhere */
this comment still feels relevant after the refactor, but lmk if i should remove!

2021-03-18 05:29 UTC, saghdaey commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> -    event.stopPropagation();
no longer needed :)

2021-03-18 13:13 UTC, codecaaron approved these changes
Tested and this works great!!!  💯 🥇  Thank you! 

Some small clean up / comments but good to go on my side!

2021-03-18 13:13 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +  }
We can remove this :)

2021-03-18 13:13 UTC, codecaaron commented on packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
> +      justifyContent="space-between"
IIRC we want to add alignItems flex-start here for the dismiss to be aligned with text (ignore if thats not intended behavior :)

2021-03-18 14:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.23-alpha.656962.0<br/>@codecademy/gamut-labs@12.0.3-alpha.656962.0<br/>@codecademy/gamut@27.1.1-alpha.656962.0<br/>@codecademy/styleguide@31.1.1-alpha.656962.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-18 14:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605361d021ad63eafee858a2--gamut-preview.netlify.app>https://605361d021ad63eafee858a2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605361d021ad63eafee858a2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-18 14:32 UTC, merged