add
Codecademy/client-modules pull request #1558
Opened 2021-03-23 15:59 UTC by dreamwasp

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-03-23 16:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.33-alpha.318413.0<br/>@codecademy/gamut-labs@13.1.3-alpha.318413.0<br/>@codecademy/gamut@29.4.1-alpha.318413.0<br/>@codecademy/styleguide@33.3.1-alpha.318413.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-23 16:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605a12264734d8679c3ebb75--gamut-preview.netlify.app>https://605a12264734d8679c3ebb75--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605a12264734d8679c3ebb75>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-23 16:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.33-alpha.3777e2.0<br/>@codecademy/gamut-labs@13.1.3-alpha.3777e2.0<br/>@codecademy/gamut@29.4.1-alpha.3777e2.0<br/>@codecademy/styleguide@33.3.1-alpha.3777e2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-23 16:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605a143bd2d7f19866b3a008--gamut-preview.netlify.app>https://605a143bd2d7f19866b3a008--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605a143bd2d7f19866b3a008>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-23 16:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.33-alpha.0a4a4e.0<br/>@codecademy/gamut-labs@13.1.3-alpha.0a4a4e.0<br/>@codecademy/gamut@29.4.1-alpha.0a4a4e.0<br/>@codecademy/styleguide@33.3.1-alpha.0a4a4e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-23 16:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605a19af1a9ffd0093c118fa--gamut-preview.netlify.app>https://605a19af1a9ffd0093c118fa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605a19af1a9ffd0093c118fa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-24 23:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.35-alpha.d119b4.0<br/>@codecademy/gamut-labs@13.1.5-alpha.d119b4.0<br/>@codecademy/gamut@29.4.3-alpha.d119b4.0<br/>@codecademy/styleguide@33.3.3-alpha.d119b4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-24 23:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605bc51930951d1c77041478--gamut-preview.netlify.app>https://605bc51930951d1c77041478--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605bc51930951d1c77041478>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 13:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.35-alpha.04c70c.0<br/>@codecademy/gamut-labs@13.1.5-alpha.04c70c.0<br/>@codecademy/gamut@29.4.3-alpha.04c70c.0<br/>@codecademy/styleguide@33.3.3-alpha.04c70c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 13:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605c9722bd0c92384432218c--gamut-preview.netlify.app>https://605c9722bd0c92384432218c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605c9722bd0c92384432218c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 14:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.35-alpha.6812af.0<br/>@codecademy/gamut-labs@13.1.5-alpha.6812af.0<br/>@codecademy/gamut@29.4.3-alpha.6812af.0<br/>@codecademy/styleguide@33.3.3-alpha.6812af.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 14:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.35-alpha.d3096a.0<br/>@codecademy/gamut-labs@13.1.5-alpha.d3096a.0<br/>@codecademy/gamut@29.4.3-alpha.d3096a.0<br/>@codecademy/styleguide@33.3.3-alpha.d3096a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 14:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605c9b078ea010363777e985--gamut-preview.netlify.app>https://605c9b078ea010363777e985--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605c9b078ea010363777e985>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 14:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605c9e53ed9ffd3d4b662132--gamut-preview.netlify.app>https://605c9e53ed9ffd3d4b662132--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605c9e53ed9ffd3d4b662132>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 14:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.36-alpha.b1a726.0<br/>@codecademy/gamut-labs@13.1.6-alpha.b1a726.0<br/>@codecademy/gamut@29.4.4-alpha.b1a726.0<br/>@codecademy/styleguide@33.3.4-alpha.b1a726.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 14:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605ca32ab24a303fbbc7c2d6--gamut-preview.netlify.app>https://605ca32ab24a303fbbc7c2d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605ca32ab24a303fbbc7c2d6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 15:21 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +// These styles will be eventually moved into use with the Input higher order component: see GM-188.
If we're going to do this, we should make the comments much more explicit about this being a "DON'T NORMALLY DO THIS" temporary fix.

2021-03-25 15:22 UTC, JoshuaKGoldberg requested changes
@dreamwasp could you fill out the GM ticket please? I'm out of context here and don't understand why this is necessary :(

2021-03-25 17:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.36-alpha.d51f9b.0<br/>@codecademy/gamut-labs@13.1.6-alpha.d51f9b.0<br/>@codecademy/gamut@29.4.4-alpha.d51f9b.0<br/>@codecademy/styleguide@33.3.4-alpha.d51f9b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 17:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605ccc0e7204d96dcf8b481f--gamut-preview.netlify.app>https://605ccc0e7204d96dcf8b481f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605ccc0e7204d96dcf8b481f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 18:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.36-alpha.fc24cb.0<br/>@codecademy/gamut-labs@13.1.6-alpha.fc24cb.0<br/>@codecademy/gamut@29.4.4-alpha.fc24cb.0<br/>@codecademy/styleguide@33.3.4-alpha.fc24cb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 18:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605cd9b600b0898d5b3c3cbf--gamut-preview.netlify.app>https://605cd9b600b0898d5b3c3cbf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605cd9b600b0898d5b3c3cbf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 19:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.37-alpha.5ad122.0<br/>@codecademy/gamut-labs@13.1.7-alpha.5ad122.0<br/>@codecademy/gamut@29.4.5-alpha.5ad122.0<br/>@codecademy/styleguide@33.3.5-alpha.5ad122.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 19:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605ce2a0cab0b0955b0fdb46--gamut-preview.netlify.app>https://605ce2a0cab0b0955b0fdb46--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605ce2a0cab0b0955b0fdb46>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 19:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.37-alpha.e9e44a.0<br/>@codecademy/gamut-labs@13.1.7-alpha.e9e44a.0<br/>@codecademy/gamut@29.4.5-alpha.e9e44a.0<br/>@codecademy/styleguide@33.3.5-alpha.e9e44a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 19:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605cea186e0b34a290c2a544--gamut-preview.netlify.app>https://605cea186e0b34a290c2a544--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605cea186e0b34a290c2a544>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 21:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.37-alpha.bfab00.0<br/>@codecademy/gamut-labs@13.1.7-alpha.bfab00.0<br/>@codecademy/gamut@29.4.5-alpha.bfab00.0<br/>@codecademy/styleguide@33.3.5-alpha.bfab00.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 21:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605d006ac976bab576e925c9--gamut-preview.netlify.app>https://605d006ac976bab576e925c9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605d006ac976bab576e925c9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 22:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.37-alpha.4be3c9.0<br/>@codecademy/gamut-labs@13.1.7-alpha.4be3c9.0<br/>@codecademy/gamut@29.4.5-alpha.4be3c9.0<br/>@codecademy/styleguide@33.3.5-alpha.4be3c9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 22:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605d0d286b2d8900d8d51f19--gamut-preview.netlify.app>https://605d0d286b2d8900d8d51f19--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605d0d286b2d8900d8d51f19>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 22:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.37-alpha.3e4a9d.0<br/>@codecademy/gamut-labs@13.1.7-alpha.3e4a9d.0<br/>@codecademy/gamut@29.4.5-alpha.3e4a9d.0<br/>@codecademy/styleguide@33.3.5-alpha.3e4a9d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 22:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605d10b5e5934800862b7235--gamut-preview.netlify.app>https://605d10b5e5934800862b7235--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605d10b5e5934800862b7235>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 15:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.38-alpha.102612.0<br/>@codecademy/gamut-labs@13.2.1-alpha.102612.0<br/>@codecademy/gamut@29.4.5-alpha.102612.0<br/>@codecademy/styleguide@33.3.6-alpha.102612.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 15:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e00762464ee66b627a07b--gamut-preview.netlify.app>https://605e00762464ee66b627a07b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e00762464ee66b627a07b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 17:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.39-alpha.11222e.0<br/>@codecademy/gamut-labs@13.2.2-alpha.11222e.0<br/>@codecademy/gamut@29.4.6-alpha.11222e.0<br/>@codecademy/styleguide@33.3.7-alpha.11222e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 17:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e16a9d8caca00d5d5e71d--gamut-preview.netlify.app>https://605e16a9d8caca00d5d5e71d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e16a9d8caca00d5d5e71d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 17:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.39-alpha.92286e.0<br/>@codecademy/gamut-labs@13.2.2-alpha.92286e.0<br/>@codecademy/gamut@29.4.6-alpha.92286e.0<br/>@codecademy/styleguide@33.3.7-alpha.92286e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 17:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e18a4d8caca00abd5e5a4--gamut-preview.netlify.app>https://605e18a4d8caca00abd5e5a4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e18a4d8caca00abd5e5a4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 17:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.39-alpha.b70570.0<br/>@codecademy/gamut-labs@13.2.2-alpha.b70570.0<br/>@codecademy/gamut@29.4.6-alpha.b70570.0<br/>@codecademy/styleguide@33.3.7-alpha.b70570.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 17:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e20156804560fc1c2afaf--gamut-preview.netlify.app>https://605e20156804560fc1c2afaf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e20156804560fc1c2afaf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 19:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.ff5443.0<br/>@codecademy/gamut-labs@13.2.3-alpha.ff5443.0<br/>@codecademy/gamut@29.4.7-alpha.ff5443.0<br/>@codecademy/styleguide@33.3.8-alpha.ff5443.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 19:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e3cf6aed973310bc9632e--gamut-preview.netlify.app>https://605e3cf6aed973310bc9632e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e3cf6aed973310bc9632e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 20:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.09b264.0<br/>@codecademy/gamut-labs@13.2.3-alpha.09b264.0<br/>@codecademy/gamut@29.4.7-alpha.09b264.0<br/>@codecademy/styleguide@33.3.8-alpha.09b264.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 20:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e42e95036620080438433--gamut-preview.netlify.app>https://605e42e95036620080438433--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e42e95036620080438433>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 20:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.3a0a9d.0<br/>@codecademy/gamut-labs@13.2.3-alpha.3a0a9d.0<br/>@codecademy/gamut@29.4.7-alpha.3a0a9d.0<br/>@codecademy/styleguide@33.3.8-alpha.3a0a9d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 20:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e48f05d5dcb007be9a64f--gamut-preview.netlify.app>https://605e48f05d5dcb007be9a64f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e48f05d5dcb007be9a64f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 21:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.f76867.0<br/>@codecademy/gamut-labs@13.2.3-alpha.f76867.0<br/>@codecademy/gamut@29.4.7-alpha.f76867.0<br/>@codecademy/styleguide@33.3.8-alpha.f76867.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 21:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e4d19cce7cd008474d975--gamut-preview.netlify.app>https://605e4d19cce7cd008474d975--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e4d19cce7cd008474d975>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 21:08 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +    const [hasBeenFocused, setHasBeenFocused] = useState(false);
added this because the iFrame mounting within this wrapper was triggering an onChange event + preemptively setting the "activated" style

2021-03-26 21:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.951bf6.0<br/>@codecademy/gamut-labs@13.2.3-alpha.951bf6.0<br/>@codecademy/gamut@29.4.7-alpha.951bf6.0<br/>@codecademy/styleguide@33.3.8-alpha.951bf6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 21:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e4f14a0cf9b1445b6d9d6--gamut-preview.netlify.app>https://605e4f14a0cf9b1445b6d9d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e4f14a0cf9b1445b6d9d6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 21:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.61c108.0<br/>@codecademy/gamut-labs@13.2.3-alpha.61c108.0<br/>@codecademy/gamut@29.4.7-alpha.61c108.0<br/>@codecademy/styleguide@33.3.8-alpha.61c108.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 21:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e50b6ca324b00cbee32c0--gamut-preview.netlify.app>https://605e50b6ca324b00cbee32c0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e50b6ca324b00cbee32c0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 22:03 UTC, JoshuaKGoldberg requested changes
Cool code changes, and wonderful job getting the `any`s down to just one.. but, could this be unit tested please?

2021-03-26 22:03 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +    const [hasBeenFocused, setHasBeenFocused] = useState(false);
That feels like a problem for the child to solve.. is it _always_ going to be case that we only want to set activated if there's been focus?

2021-03-26 22:03 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +          }
```suggestion
          onChange={changeHandler}
```

2021-03-29 15:11 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +    const [hasBeenFocused, setHasBeenFocused] = useState(false);
we will only ever want to set activated if the element has ever had focus on this page load and if the field has been changed in some way. 

 another way i can think of solving it is adding a conditional style state override prop (since activated + the conditional style are set to the inner component) so that it's a little less tricky to have the child deal with the issue

2021-03-29 15:13 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +// ReactRecurly has some specific needs around padding and focus.
we do still need to export them separately - padding needs to be applied to the iframe itself + focus has to manually applied (pseudo selectors don't work in iframes 🙃)

2021-03-29 15:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.b730a0.0<br/>@codecademy/gamut-labs@13.2.3-alpha.b730a0.0<br/>@codecademy/gamut@29.4.7-alpha.b730a0.0<br/>@codecademy/styleguide@33.3.8-alpha.b730a0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-29 15:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6061f075b3a9e63ff8995d15--gamut-preview.netlify.app>https://6061f075b3a9e63ff8995d15--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6061f075b3a9e63ff8995d15>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-29 17:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.de0257.0<br/>@codecademy/gamut-labs@13.2.3-alpha.de0257.0<br/>@codecademy/gamut@29.4.7-alpha.de0257.0<br/>@codecademy/styleguide@33.3.8-alpha.de0257.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-29 17:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60621529e802b600d143e45b--gamut-preview.netlify.app>https://60621529e802b600d143e45b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60621529e802b600d143e45b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-29 21:50 UTC, codecaaron approved these changes

2021-03-29 21:50 UTC, codecaaron commented on packages/gamut/src/Form/Input.tsx
> +`;
```suggestion
export const reactRecurlyFormFieldFocusStyles = formFieldFocusStyles

export const reactRecurlyFormFieldPaddingStyles = formFieldPaddingStyles
```

I think we end up creating a className with `reactRecurlyFormFieldPaddingStyles-formFieldPaddingStyles` if we chain these.  Highly annoying TBH.

2021-03-29 22:50 UTC, dreamwasp commented on packages/gamut/src/Form/Input.tsx
> +`;
oh fun! i'll swap it 🙏

2021-03-30 13:37 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +    const [hasBeenFocused, setHasBeenFocused] = useState(false);
Gotcha. I'll retract then, whichever you prefer!

2021-03-30 13:57 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +// ReactRecurly has some specific needs around padding and focus.
Rip, sad. Could you document the heck out of it? This feels like something people would copy & on their own unless told not to without consulting us.

2021-03-30 16:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.43-alpha.ce3acd.0<br/>@codecademy/gamut-labs@13.2.6-alpha.ce3acd.0<br/>@codecademy/gamut@29.5.1-alpha.ce3acd.0<br/>@codecademy/styleguide@33.4.1-alpha.ce3acd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-30 16:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6063574b187b04341a95aed0--gamut-preview.netlify.app>https://6063574b187b04341a95aed0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6063574b187b04341a95aed0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-30 17:14 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> + *tldr: Do not do this unless you have already talked to Web-Plat and have failed to find any alternate (and better) solutions. */
hahaha I love it

2021-03-30 17:22 UTC, dreamwasp commented on packages/styleguide/stories/Atoms/FormInputs/Input.stories.mdx
> -
😅 yes

2021-03-30 20:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.43-alpha.1031b1.0<br/>@codecademy/gamut-labs@13.2.6-alpha.1031b1.0<br/>@codecademy/gamut@29.5.1-alpha.1031b1.0<br/>@codecademy/styleguide@33.4.1-alpha.1031b1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-30 20:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60638cd2c46cb22c1864bbfc--gamut-preview.netlify.app>https://60638cd2c46cb22c1864bbfc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60638cd2c46cb22c1864bbfc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-31 21:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.45-alpha.73c5b8.0<br/>@codecademy/gamut-labs@13.2.8-alpha.73c5b8.0<br/>@codecademy/gamut@29.5.3-alpha.73c5b8.0<br/>@codecademy/styleguide@33.4.3-alpha.73c5b8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-31 21:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6064e3665472ea8f3f0dd0da--gamut-preview.netlify.app>https://6064e3665472ea8f3f0dd0da--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6064e3665472ea8f3f0dd0da>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-01 13:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.46-alpha.2d5f33.0<br/>@codecademy/gamut-labs@13.2.9-alpha.2d5f33.0<br/>@codecademy/gamut@29.6.1-alpha.2d5f33.0<br/>@codecademy/styleguide@33.5.1-alpha.2d5f33.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-01 13:28 UTC, merged

2021-04-01 13:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6065ca83d277ba2cdf5f4607--gamut-preview.netlify.app>https://6065ca83d277ba2cdf5f4607--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6065ca83d277ba2cdf5f4607>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->