feat(themeValue): Autocomplete utility for lodash syntax theme values
Codecademy/client-modules pull request #1560
Opened 2021-03-24 19:59 UTC by codecaaron

### Overview

I feel like this might be a nice way to get everything using the ThemeContext without huge boilerplate :) 

* Adds lodash like higher order function for looking up theme values in `styled` tagged templates.

### Usage
```tsx
import { themeValue } from '@codecademy/gamut-styles';

const Something = styled.div`
   border: 1px solid ${themeValue('secondary')};
`k
```
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-03-24 20:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.4-alpha.1adb78.0<br/>@codecademy/gamut-kit@0.2.35-alpha.1adb78.0<br/>@codecademy/gamut-labs@13.1.5-alpha.1adb78.0<br/>@codecademy/gamut-styles@9.1.1-alpha.1adb78.0<br/>@codecademy/gamut-tests@2.3.1-alpha.1adb78.0<br/>@codecademy/gamut@29.4.3-alpha.1adb78.0<br/>@codecademy/markdown-overrides@0.5.13-alpha.1adb78.0<br/>@codecademy/styleguide@33.3.3-alpha.1adb78.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-24 20:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605ba30a88a90f1429a7ede9--gamut-preview.netlify.app>https://605ba30a88a90f1429a7ede9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605ba30a88a90f1429a7ede9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-24 21:03 UTC, dreamwasp approved these changes
🔥

2021-03-25 00:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.4-alpha.f1d0c8.0<br/>@codecademy/gamut-kit@0.2.35-alpha.f1d0c8.0<br/>@codecademy/gamut-labs@13.1.5-alpha.f1d0c8.0<br/>@codecademy/gamut-styles@9.1.1-alpha.f1d0c8.0<br/>@codecademy/gamut-tests@2.3.1-alpha.f1d0c8.0<br/>@codecademy/gamut@29.4.3-alpha.f1d0c8.0<br/>@codecademy/markdown-overrides@0.5.13-alpha.f1d0c8.0<br/>@codecademy/styleguide@33.3.3-alpha.f1d0c8.0<br/>@codecademy/variance@0.1.2-alpha.f1d0c8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 00:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605bd4cdfcbff736c9634aa3--gamut-preview.netlify.app>https://605bd4cdfcbff736c9634aa3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605bd4cdfcbff736c9634aa3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 01:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.4-alpha.77a123.0<br/>@codecademy/gamut-kit@0.2.35-alpha.77a123.0<br/>@codecademy/gamut-labs@13.1.5-alpha.77a123.0<br/>@codecademy/gamut-styles@9.1.1-alpha.77a123.0<br/>@codecademy/gamut-tests@2.3.1-alpha.77a123.0<br/>@codecademy/gamut@29.4.3-alpha.77a123.0<br/>@codecademy/markdown-overrides@0.5.13-alpha.77a123.0<br/>@codecademy/styleguide@33.3.3-alpha.77a123.0<br/>@codecademy/variance@0.1.2-alpha.77a123.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 01:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605be92afbd69063c3a8c8fc--gamut-preview.netlify.app>https://605be92afbd69063c3a8c8fc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605be92afbd69063c3a8c8fc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-25 13:50 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
> +    expect(errors[1].getAttribute('aria-live')).toBe('off');
Unintentionally included changes here?

2021-03-25 13:50 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/index.tsx
> +      data-testid="why"
NO U

2021-03-25 13:56 UTC, JoshuaKGoldberg requested changes
Looks reasonable to me so far. A few things we should discuss:
* Is this going to be the recommended approach 100% of the time? If not, is it worth it? _(I'm in favor)_
* Should we recommend something like <code>themed`colors.hyper`</code> for brevity?

2021-03-25 13:56 UTC, JoshuaKGoldberg commented on yarn.lock
> +  integrity sha512-qOcYwxaByStAWrBf4x0fibwZvMRG+r4cQoTjbPtUlrWjBHbmCAww1i448U0GJ+3cNNEtebDteo/cHOR3xJ4wEw==
We should stick to a single TypeScript version. Let's bump this to 4.2.3 for everyone?

2021-03-25 13:56 UTC, JoshuaKGoldberg commented on packages/gamut/src/SkipToContent/index.tsx
> +`;
Oh yeah 👌

2021-03-25 13:56 UTC, JoshuaKGoldberg commented on packages/gamut-styles/src/utilities/themeValue.ts
> +type PathImpl<T, K extends keyof T> = K extends string | number
Nit: what does `Impl` mean here? Can this be not abbreviated, for clarity?

Also: this is a lot of complicated type system magicks. We the web plat team seem to all be understanding of it all but it's pretty difficult to ramp up into. Do you think you could add some helpful comments? See convos in: https://github.com/Codecademy/component-test-setup/pull/7

2021-03-25 13:56 UTC, JoshuaKGoldberg commented on packages/gamut-styles/src/utilities/themeValue.ts
> +export function themeValue<P extends Path<Theme>>(
I'm way of having two-word values for commonly used utilities. How about `themed`?

```suggestion
export function themed<P extends Path<Theme>>(
```

2021-03-25 14:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.4-alpha.087d0d.0<br/>@codecademy/gamut-kit@0.2.35-alpha.087d0d.0<br/>@codecademy/gamut-labs@13.1.5-alpha.087d0d.0<br/>@codecademy/gamut-styles@9.1.1-alpha.087d0d.0<br/>@codecademy/gamut-tests@2.3.1-alpha.087d0d.0<br/>@codecademy/gamut@29.4.3-alpha.087d0d.0<br/>@codecademy/markdown-overrides@0.5.13-alpha.087d0d.0<br/>@codecademy/styleguide@33.3.3-alpha.087d0d.0<br/>@codecademy/variance@0.1.2-alpha.087d0d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-25 14:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605c988a7058c930ff807588--gamut-preview.netlify.app>https://605c988a7058c930ff807588--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605c988a7058c930ff807588>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-28 21:29 UTC, codecaaron commented on yarn.lock
> +  integrity sha512-qOcYwxaByStAWrBf4x0fibwZvMRG+r4cQoTjbPtUlrWjBHbmCAww1i448U0GJ+3cNNEtebDteo/cHOR3xJ4wEw==
👍  added a resolution for this.  The unused import eslint analogue only has 4.0.3 so I've bumped it there, but it shouldn't matter.

2021-03-28 21:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.5-alpha.40ce0a.0<br/>@codecademy/gamut-kit@0.2.40-alpha.40ce0a.0<br/>@codecademy/gamut-labs@13.2.3-alpha.40ce0a.0<br/>@codecademy/gamut-styles@9.1.2-alpha.40ce0a.0<br/>@codecademy/gamut-tests@2.3.2-alpha.40ce0a.0<br/>@codecademy/gamut@29.4.7-alpha.40ce0a.0<br/>@codecademy/konamimojisplosion@0.2.2-alpha.40ce0a.0<br/>@codecademy/markdown-overrides@0.5.15-alpha.40ce0a.0<br/>@codecademy/styleguide@33.3.8-alpha.40ce0a.0<br/>@codecademy/variance@0.1.2-alpha.40ce0a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-28 21:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6060f6b205956ada9bbed956--gamut-preview.netlify.app>https://6060f6b205956ada9bbed956--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6060f6b205956ada9bbed956>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-29 01:33 UTC, codecaaron commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> -`;
IIRC this might have been broken just moved this to general FormGroup stuff.  Can revert if needed.

2021-03-29 01:33 UTC, codecaaron commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> -      <Box>
I believe this is unneeded?

2021-03-29 01:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.5-alpha.4d7fac.0<br/>@codecademy/gamut-kit@0.2.40-alpha.4d7fac.0<br/>@codecademy/gamut-labs@13.2.3-alpha.4d7fac.0<br/>@codecademy/gamut-styles@9.1.2-alpha.4d7fac.0<br/>@codecademy/gamut-tests@2.3.2-alpha.4d7fac.0<br/>@codecademy/gamut@29.4.7-alpha.4d7fac.0<br/>@codecademy/konamimojisplosion@0.2.2-alpha.4d7fac.0<br/>@codecademy/markdown-overrides@0.5.15-alpha.4d7fac.0<br/>@codecademy/styleguide@33.3.8-alpha.4d7fac.0<br/>@codecademy/variance@0.1.2-alpha.4d7fac.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-29 01:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60612f4b6369ff7bece6fc7a--gamut-preview.netlify.app>https://60612f4b6369ff7bece6fc7a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60612f4b6369ff7bece6fc7a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-29 07:14 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
> +import { fireEvent, render, screen } from '@testing-library/react';
Haha, I was wondering if & when people would start using `screen` instead of the returned `view`...

2021-03-29 07:19 UTC, JoshuaKGoldberg commented on yarn.lock
> +  integrity sha512-qOcYwxaByStAWrBf4x0fibwZvMRG+r4cQoTjbPtUlrWjBHbmCAww1i448U0GJ+3cNNEtebDteo/cHOR3xJ4wEw==
Word. You can actually get rid of the `resolution` now; I tried re-running `yarn` after that locally and `yarn.lock` didn't change.

2021-03-29 07:19 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
> -`;
Heh. Tracing back through history:

* #1560 preserved it from the old `packages/gamut/src/GridForm/GridFormInputGroup/styles.module.scss`
* #653 intentionally bumped up its specificity to override Gamut defaults (https://github.com/Codecademy/client-modules/commit/a99c1caaacf76374bc61dc41c3037adaee479fef)
* #605 is when I originally added it

Amusingly, the form on `/business` doesn't need this CSS anyway. But I do wonder about the rest of the monolith's users...

2021-03-29 07:21 UTC, JoshuaKGoldberg requested changes
Looks beautiful overall - just requesting changes for tests on `themed`! 🙌

2021-03-29 07:21 UTC, JoshuaKGoldberg commented on packages/gamut-styles/src/utilities/themed.ts
> +  return ({ theme }) => get(theme, path);
😄 , Codecov is right, this should probably have tests.

2021-03-29 13:26 UTC, JoshuaKGoldberg approved these changes
💯 

`themed` is going to make things awesome, very nice!

2021-03-29 13:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.5-alpha.7f468d.0<br/>@codecademy/gamut-kit@0.2.40-alpha.7f468d.0<br/>@codecademy/gamut-labs@13.2.3-alpha.7f468d.0<br/>@codecademy/gamut-styles@9.1.2-alpha.7f468d.0<br/>@codecademy/gamut-tests@2.3.2-alpha.7f468d.0<br/>@codecademy/gamut@29.4.7-alpha.7f468d.0<br/>@codecademy/konamimojisplosion@0.2.2-alpha.7f468d.0<br/>@codecademy/markdown-overrides@0.5.15-alpha.7f468d.0<br/>@codecademy/styleguide@33.3.8-alpha.7f468d.0<br/>@codecademy/variance@0.1.2-alpha.7f468d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-29 13:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6061d64a4b6e2319c2852e82--gamut-preview.netlify.app>https://6061d64a4b6e2319c2852e82--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6061d64a4b6e2319c2852e82>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-29 13:30 UTC, codecaaron commented on packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
> +import { fireEvent, render, screen } from '@testing-library/react';
I tried moving to this in the monolith :/ Unfortunately this didn't seem the most straight forward for some reason (probably me just messing things up).

I like it though makes refactoring a breeze

2021-03-29 19:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.5-alpha.b12b16.0<br/>@codecademy/gamut-kit@0.2.40-alpha.b12b16.0<br/>@codecademy/gamut-labs@13.2.3-alpha.b12b16.0<br/>@codecademy/gamut-styles@9.1.2-alpha.b12b16.0<br/>@codecademy/gamut-tests@2.3.2-alpha.b12b16.0<br/>@codecademy/gamut@29.4.7-alpha.b12b16.0<br/>@codecademy/konamimojisplosion@0.2.2-alpha.b12b16.0<br/>@codecademy/markdown-overrides@0.5.15-alpha.b12b16.0<br/>@codecademy/styleguide@33.3.8-alpha.b12b16.0<br/>@codecademy/variance@0.1.2-alpha.b12b16.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-29 19:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606231a66f2656007ccbc11b--gamut-preview.netlify.app>https://606231a66f2656007ccbc11b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606231a66f2656007ccbc11b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-29 21:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.5-alpha.35eb1f.0<br/>@codecademy/gamut-kit@0.2.41-alpha.35eb1f.0<br/>@codecademy/gamut-labs@13.2.4-alpha.35eb1f.0<br/>@codecademy/gamut-styles@9.1.2-alpha.35eb1f.0<br/>@codecademy/gamut-tests@2.3.2-alpha.35eb1f.0<br/>@codecademy/gamut@29.4.8-alpha.35eb1f.0<br/>@codecademy/konamimojisplosion@0.2.2-alpha.35eb1f.0<br/>@codecademy/markdown-overrides@0.5.15-alpha.35eb1f.0<br/>@codecademy/styleguide@33.3.9-alpha.35eb1f.0<br/>@codecademy/variance@0.1.2-alpha.35eb1f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-29 21:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60624b816c80b72b7d4d343a--gamut-preview.netlify.app>https://60624b816c80b72b7d4d343a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60624b816c80b72b7d4d343a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-30 01:03 UTC, merged