feat(GridForm): Update the buttons for GridFrom submit
Codecademy/client-modules pull request #1567
Opened 2021-03-26 19:09 UTC by vonbarown

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-03-26 20:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.811165.0<br/>@codecademy/gamut-labs@13.2.3-alpha.811165.0<br/>@codecademy/gamut@29.4.7-alpha.811165.0<br/>@codecademy/styleguide@33.3.8-alpha.811165.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 20:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e402aaed9733b67c964f4--gamut-preview.netlify.app>https://605e402aaed9733b67c964f4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e402aaed9733b67c964f4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 22:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.900cca.0<br/>@codecademy/gamut-labs@13.2.3-alpha.900cca.0<br/>@codecademy/gamut@29.4.7-alpha.900cca.0<br/>@codecademy/styleguide@33.3.8-alpha.900cca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 22:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e6162b37d2a1900cd8ecc--gamut-preview.netlify.app>https://605e6162b37d2a1900cd8ecc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e6162b37d2a1900cd8ecc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-26 23:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.2df1ce.0<br/>@codecademy/gamut-labs@13.2.3-alpha.2df1ce.0<br/>@codecademy/gamut@29.4.7-alpha.2df1ce.0<br/>@codecademy/styleguide@33.3.8-alpha.2df1ce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-26 23:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://605e6c5b976fa84d5b211c0d--gamut-preview.netlify.app>https://605e6c5b976fa84d5b211c0d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/605e6c5b976fa84d5b211c0d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-29 18:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.40-alpha.cac28c.0<br/>@codecademy/gamut-labs@13.2.3-alpha.cac28c.0<br/>@codecademy/gamut@29.4.7-alpha.cac28c.0<br/>@codecademy/styleguide@33.3.8-alpha.cac28c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-29 18:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606221247798e5180f57b093--gamut-preview.netlify.app>https://606221247798e5180f57b093--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606221247798e5180f57b093>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-29 20:57 UTC, dreamwasp requested changes
~would love to get rid of deprecated-button (maybe is this optimistic of me though 😅) and default to <FillButton mode="light/> if those props aren't provided.~ lol nvm

looks ✨ to me, just waiting on monolith integration branch to approve ☺️

2021-03-29 20:57 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +        );
i feel like we could replace this with FillButton / light mode without pushback?

2021-03-29 20:57 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +  mode,
i think we should have buttonType + mode default to fill-button + light to make this a less breaking change

2021-03-29 20:57 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
>    theme = 'brand-purple',
yeah i feel like we can pretty safely get rid of theme

2021-03-29 20:57 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +        // There are current designs that currently rely on the deprecated button
there shouldn't be,  which designs are you seeing the deprecated button in?

2021-03-29 20:58 UTC, dreamwasp commented on packages/styleguide/stories/Organisms/GridForm.stories.mdx
> +        />
would love to see these against a dark background!

2021-03-29 21:26 UTC, vonbarown commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +        // There are current designs that currently rely on the deprecated button
The file ```/CompletedItem/CertificateModal/EditNameView/index.tsx ``` currently uses the blue deprecated button. along with the Business Account Management page currently uses the deprecated button, I have spoken with Julia one of our designers and they want to keep the blue outlined button

2021-03-29 21:27 UTC, vonbarown commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +  mode,
I believe Yassine doesn't want one to be defaulted over the other

2021-03-29 21:45 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +        // There are current designs that currently rely on the deprecated button
yeah theres some other gamut-work that needs to happen before that is possible with `StrokeButton` so i'm fine with this change for now

2021-03-30 12:54 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +  mode,
@vonbarown I think that was from a design perspective, not an engineering one. And designers typically don't weigh in on this granular an engineering change 😄 

IMO we should go with the defaulting because requiring an extra field be filled out when it doesn't have to makes it harder & more irritating to use `GridForm`.

2021-03-30 12:55 UTC, JoshuaKGoldberg requested changes
+1 to the defaulting 🤗

2021-03-30 13:03 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +  outline?: ButtonDeprecatedProps['outline'];
If we do end up going with the deprecated button, you'll want to use a [discriminated union type](https://basarat.gitbook.io/typescript/type-system/discriminated-unions) so that the folks using this interface for the new button don't see the deprecated button options:

```ts
export type GridFormSubmitProps = GridFormSubmitPropsDeprecated | GridFormSubmitPropsStandard;
```

2021-03-30 13:36 UTC, vonbarown commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +  mode,
Thank you for the clarification, I'll update to use defaults

2021-03-30 13:46 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +        // There are current designs that currently rely on the deprecated button
Oh @dreamwasp is telling me this is intentional for now, pending the `ColorMode` stuff.

Can the API name be switched to something like `'business'` then? And really informative todo-y comments around it so people understand how intentional this change is? 😄

2021-03-30 13:47 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +export type ButtonType = 'cta-button' | 'fill-button' | 'deprecated-button';
re: conversation with Josh - i think best move forward is swapping this over to "enterprise-submit" / "business"

2021-03-30 13:57 UTC, vonbarown commented on packages/gamut/src/GridForm/GridFormSubmit/index.tsx
> +export type ButtonType = 'cta-button' | 'fill-button' | 'deprecated-button';
will update to business

2021-03-30 15:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.43-alpha.75d186.0<br/>@codecademy/gamut-labs@13.2.6-alpha.75d186.0<br/>@codecademy/gamut@29.5.1-alpha.75d186.0<br/>@codecademy/styleguide@33.4.1-alpha.75d186.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-30 15:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606349b438abea0fae535d27--gamut-preview.netlify.app>https://606349b438abea0fae535d27--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606349b438abea0fae535d27>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-30 17:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.43-alpha.471232.0<br/>@codecademy/gamut-labs@13.2.6-alpha.471232.0<br/>@codecademy/gamut@29.5.1-alpha.471232.0<br/>@codecademy/styleguide@33.4.1-alpha.471232.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-30 20:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60638e31f4757e3f691416b5--gamut-preview.netlify.app>https://60638e31f4757e3f691416b5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60638e31f4757e3f691416b5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-30 20:49 UTC, JoshuaKGoldberg approved these changes
Glorious, thanks Voniel! 🙌 🌮

2021-03-30 21:05 UTC, dreamwasp approved these changes
beautiful

2021-03-30 21:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606393fff4757e44ac141445--gamut-preview.netlify.app>https://606393fff4757e44ac141445--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606393fff4757e44ac141445>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-03-30 23:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.43-alpha.801216.0<br/>@codecademy/gamut-labs@13.2.6-alpha.801216.0<br/>@codecademy/gamut@29.5.1-alpha.801216.0<br/>@codecademy/styleguide@33.4.1-alpha.801216.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-03-30 23:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6063b478caa37d009da41926--gamut-preview.netlify.app>https://6063b478caa37d009da41926--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6063b478caa37d009da41926>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-01 12:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.45-alpha.c1f6a8.0<br/>@codecademy/gamut-labs@13.2.8-alpha.c1f6a8.0<br/>@codecademy/gamut@29.5.3-alpha.c1f6a8.0<br/>@codecademy/styleguide@33.4.3-alpha.c1f6a8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-01 13:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6065c400a93b7b247db8a88d--gamut-preview.netlify.app>https://6065c400a93b7b247db8a88d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6065c400a93b7b247db8a88d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-01 13:18 UTC, merged