feat: added GlobalFooter molecule
Codecademy/client-modules pull request #1598
Opened 2021-04-05 17:43 UTC by JoshuaKGoldberg

### Overview

Adds a new `GlobalFooter` component to complement the existing `GlobalHeader`.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: REACH-836
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

![Screenshot of the new GlobalFooter](https://user-images.githubusercontent.com/3335181/113605652-f478c580-9614-11eb-8b38-bd4374c9c8c6.png)

2021-04-05 17:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.48ae43.0<br/>@codecademy/gamut-labs@13.3.0-alpha.48ae43.0<br/>@codecademy/styleguide@33.7.0-alpha.48ae43.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-05 17:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606b4d84263526483943bd07--gamut-preview.netlify.app>https://606b4d84263526483943bd07--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606b4d84263526483943bd07>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-05 18:07 UTC, katiezutter commented
YES. 🙌

Haven't looked at the code yet but here are a few small visual things I noticed on Storybook:

1. Some spacing issues between the top headers and the top divider, and spacing above the "SUPPORT" heading

<img width="600" alt="Screen Shot 2021-04-05 at 12 53 00 PM" src="https://user-images.githubusercontent.com/14988121/113607221-9648e400-960e-11eb-94aa-7b0c341694d5.png">

2. For mobile screens the Languages columns should be separated out to match the columns in the section above
<img width="400" alt="Screen Shot 2021-04-05 at 12 53 23 PM" src="https://user-images.githubusercontent.com/14988121/113607238-99dc6b00-960e-11eb-93e7-14e99dfbb804.png">

3. The tabbing order is off for the links; it currently skips around a bit and should flow Company -> Resources -> Community -> Mobile -> Individual -> Enterprise -> Support -> Subjects -> Languages

I am pumped!!!

2021-04-05 19:03 UTC, JoshuaKGoldberg commented
Thanks for the spotting @katiezutter! I think I fixed what you spotted out, and double-checked & did a few touchups mobile up. It _should_ be clean now. 🤞

2021-04-05 19:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.a6578a.0<br/>@codecademy/gamut-labs@13.3.0-alpha.a6578a.0<br/>@codecademy/styleguide@33.7.0-alpha.a6578a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-05 19:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606b601c81af7d007ac377dc--gamut-preview.netlify.app>https://606b601c81af7d007ac377dc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606b601c81af7d007ac377dc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-05 21:15 UTC, saghdaey commented
nit: inconsistent focus-visible on some of the links (ex. most are outlined purple but then the social media icons are navy (is that by design?)

2021-04-05 21:17 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterHeading.tsx
> +  margin: 1.5rem 0 1rem;
does Text not take in these values as props? is there a reason why we use a styled component instead?

2021-04-05 21:20 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterLegal/MadeIn.tsx
> +  filter: saturate(0.7);
^TIL that this css property existed, so ty!

2021-04-05 21:21 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterLegal/index.tsx
> +    </ContentContainer>
so fresh so clean

2021-04-05 21:23 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterLinkItem.tsx
> +export const FooterLinkItem = styled.li`
any reason why we wouldnt keep FooterLinkItem & FooterLinkArea in the same file? they feel tightly coupled (or maybe in the same subdirectory?)

2021-04-05 21:26 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalFooter/__tests__/GlobalFooter-test.tsx
> +  it('does not explode', () => {
lmao

2021-04-05 21:26 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalFooter/index.tsx
> +  className?: string;
+ onClick to handle tracking :)

2021-04-05 21:28 UTC, saghdaey commented on packages/styleguide/stories/Molecules/GlobalFooter.stories.mdx
> +> This story is best viewed in Canvas mode.
smart to add this; we should include this copy for global header (maybe you can sneak it in as part of this PR? ✨)

2021-04-06 13:25 UTC, codecaaron approved these changes
:D

2021-04-06 13:25 UTC, codecaaron commented on packages/styleguide/stories/Molecules/GlobalFooter.stories.mdx
> +  }}
```suggestion
  parameters={{
    figmaId: 'as1W6qIWUlibYKiSUWB2S4',
    source: 'gamut-labs',
    status: 'volatile',
    subtitle: `Global footer to be displayed on the bottom of each page.`,
    viewMode: 'canvas',
    layout: 'fullscreen',
  }}
```

Default canvas view :) + [no extra padding](https://storybook.js.org/docs/react/configure/story-layout)

2021-04-06 13:25 UTC, codecaaron commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterSubHeading.tsx
> +import { Text } from '../Text';
```suggestion
import { Text } from '@codecademy/gamut';
```

2021-04-06 13:25 UTC, codecaaron commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/SocialMediaLinks.tsx
> +`;
`Anchor` maybe?

2021-04-06 13:25 UTC, codecaaron commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
> +`;
Maybe GridBox?

Also we may want to set these to `minmax(0, 1fr)` for overflow safety.

```suggestion
<GridBox gridTemplateColumns={['repeat(2, minmax(0, 1fr))', , repeat(3, minmax(0, 1fr))']} />
```

2021-04-06 13:25 UTC, codecaaron commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
> +`;
Maybe?

```suggestion
<FlexBox flexDirection={['column', ,'row', 'row-reverse']} />
```

2021-04-06 13:25 UTC, codecaaron commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterHeading.tsx
> +};
```suggestion
import { Text } from '@codecademy/gamut';

export const FooterHeading = styled(Text)()

FooterHeading.defaultProps = {
  as: 'h2',
  fontSize: [14, ,16],
  marginTop: [24, ,0],
  marginBottom: 16,
  textTransform: 'uppercase',
  fontWeight: 'base',
};
```

2021-04-06 13:25 UTC, codecaaron commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
> +`;
```suggestion
const CatalogLinkArea = styled(LinkArea)<{ variant?: 'fullHeight' }>`
  display: flex;
  max-height: 14rem;
  flex-direction: column;
  flex-wrap: wrap;
  margin-bottom: 1rem;
  ${variant({ fullHeight: { maxHeight: {  md: 'none' } })}
`;
```

2021-04-06 13:31 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/GlobalFooter.stories.mdx
> +  }}
Oh heck yes, thanks!

2021-04-06 13:33 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterLinkItem.tsx
> +export const FooterLinkItem = styled.li`
No reason! One file it shall be.

2021-04-06 13:35 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
> +`;
Nice! Yeah I'm still not used to these 😄

2021-04-06 13:41 UTC, codecaaron commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
> +`;
Pretty handy for these boolean props :D.

I think I might try to allow variance version of this to take `false | undefined | null` as keys just to make it easy to conditionally set them.

2021-04-06 13:56 UTC, saghdaey commented on packages/styleguide/stories/Molecules/GlobalFooter.stories.mdx
> +    layout: 'fullscreen',
ty!

2021-04-06 13:58 UTC, saghdaey commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/SocialMediaLinks.tsx
> +      target="_blank"
i see u alphabetizing :D

2021-04-06 15:14 UTC, katiezutter approved these changes
Awesome!! LGTM pending tracking changes!!

2021-04-06 21:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.03351b.0<br/>@codecademy/gamut-labs@13.3.0-alpha.03351b.0<br/>@codecademy/styleguide@33.7.0-alpha.03351b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-06 21:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606cd01f0f1c7912bfc859d8--gamut-preview.netlify.app>https://606cd01f0f1c7912bfc859d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606cd01f0f1c7912bfc859d8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-06 21:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.7a48ef.0<br/>@codecademy/gamut-labs@13.3.0-alpha.7a48ef.0<br/>@codecademy/styleguide@33.7.0-alpha.7a48ef.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-06 21:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606cd2f68ee5e81c8cff73fb--gamut-preview.netlify.app>https://606cd2f68ee5e81c8cff73fb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606cd2f68ee5e81c8cff73fb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-06 21:49 UTC, JoshuaKGoldberg commented
@katiezutter @saghdaey I think I've gotten to everything -including `onClick` and tab order- but apologies if I missed a comment!

2021-04-06 21:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.cd0539.0<br/>@codecademy/gamut-labs@13.3.0-alpha.cd0539.0<br/>@codecademy/styleguide@33.7.0-alpha.cd0539.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-06 21:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606cd8477df3df1cf43514d2--gamut-preview.netlify.app>https://606cd8477df3df1cf43514d2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606cd8477df3df1cf43514d2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-07 13:24 UTC, dreamwasp requested changes
would love to see this deployed in a monolith PR env just to check out the behavior there but looking good!

2021-04-07 13:24 UTC, dreamwasp commented on packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
> +        </MobileImageLink>
i'm getting some weird behavior on focus for these links - 
![image](https://user-images.githubusercontent.com/58054751/113873307-b0a3ce80-9782-11eb-8d7a-095d324ddd83.png)

2021-04-07 14:56 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalFooter/types.ts
> +export type GlobalFooterClickHandler = (
Thanks @dreamwasp for prompting me to add a monolith PR (https://github.com/codecademy-engineering/Codecademy/pull/23563): I just noticed the tracking right now is set up with keys like `about`, not full URL hrefs. So I'll have to change this to account for that.

2021-04-07 14:56 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalFooter/index.tsx
> +  className?: string;
Done! Targets and all.

I think 😄

2021-04-07 14:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.4adb36.0<br/>@codecademy/gamut-labs@13.3.0-alpha.4adb36.0<br/>@codecademy/styleguide@33.7.0-alpha.4adb36.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-07 14:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606dc8b7c480bf2cee05eabe--gamut-preview.netlify.app>https://606dc8b7c480bf2cee05eabe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606dc8b7c480bf2cee05eabe>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-07 15:03 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalFooter/types.ts
> +export type GlobalFooterClickHandler = (
https://pr-23563.dev-eks.codecademy.com/

2021-04-07 15:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.0661f3.0<br/>@codecademy/gamut-labs@13.3.0-alpha.0661f3.0<br/>@codecademy/styleguide@33.7.0-alpha.0661f3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-07 15:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606dcd1da980f731878e65b9--gamut-preview.netlify.app>https://606dcd1da980f731878e65b9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606dcd1da980f731878e65b9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-07 15:19 UTC, dreamwasp approved these changes
🚀

2021-04-07 16:47 UTC, saghdaey approved these changes
looks great to me! ty for doing this work and for addressing all the comments:)

2021-04-07 17:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.fe9f27.0<br/>@codecademy/gamut-labs@13.3.0-alpha.fe9f27.0<br/>@codecademy/styleguide@33.7.0-alpha.fe9f27.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-07 17:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606df12449839700c604d08d--gamut-preview.netlify.app>https://606df12449839700c604d08d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606df12449839700c604d08d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-07 18:30 UTC, katiezutter approved these changes
A few non-blocking/take-it-or-leave-it comments! Tabbing looks excellent and thanks for adding in functionality for tracking 👌

2021-04-07 18:30 UTC, katiezutter commented on packages/gamut-labs/src/experimental/GlobalFooter/index.tsx
> +  onClick: GlobalFooterClickHandler;
I wonder if this should be named `action` instead, to keep consistent with GlobalHeader naming conventions. Maybe worth making a story for this too like [Global Header With an Action Function](https://gamut.codecademy.com/storybook/?path=/docs/organisms-globalheader--global-header-with-an-action-function)

2021-04-07 18:30 UTC, katiezutter commented on packages/styleguide/stories/Molecules/GlobalFooter.stories.mdx
> +Users with `userGeo` set to `"IN"` will not see the _Shop_ link.
Would it be worth having a story for each country that differs from default? (For now, just India)

2021-04-07 19:34 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalFooter/index.tsx
> +  onClick: GlobalFooterClickHandler;
Hmm yeah, in retrospect I think it's more typical of React props to name it `on*`, so `onAction`. Thoughts @katiezutter?

I can update the header stuff for you too, since I probably should have mentioned this a while ago.

2021-04-07 19:34 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/GlobalFooter.stories.mdx
> +Users with `userGeo` set to `"IN"` will not see the _Shop_ link.
Yes!

2021-04-07 19:39 UTC, katiezutter commented on packages/gamut-labs/src/experimental/GlobalFooter/index.tsx
> +  onClick: GlobalFooterClickHandler;
Makes sense - yeah I remember there was some discussion around that before, can't remember why we changed it but I am okay with either `onClick` or `onAction` - and thanks for offering to update the header too!! 🙌

2021-04-07 19:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.cfb8b1.0<br/>@codecademy/gamut-labs@13.3.0-alpha.cfb8b1.0<br/>@codecademy/styleguide@33.7.0-alpha.cfb8b1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-07 19:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606e0b6150c50e253d52c06b--gamut-preview.netlify.app>https://606e0b6150c50e253d52c06b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606e0b6150c50e253d52c06b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-07 21:01 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/GlobalFooter/index.tsx
> +  onClick: GlobalFooterClickHandler;
Cool! If you don't mind I do prefer `onClick` 😁  to stay consistent with other clicky things. Thanks!

2021-04-07 21:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.fb7593.0<br/>@codecademy/gamut-labs@13.3.0-alpha.fb7593.0<br/>@codecademy/styleguide@33.7.0-alpha.fb7593.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-07 21:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606e1f332144f23fceb7762b--gamut-preview.netlify.app>https://606e1f332144f23fceb7762b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606e1f332144f23fceb7762b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-08 02:02 UTC, ZackMFleischman commented
This looks great other than 3 minor regressions in accessibility for the footer here. (You can refer to [this PR](https://github.com/codecademy-engineering/Codecademy/pull/22960) to see how the code handled it before). It's also live in Prod. 

1. The social icons are grouped as a single list item in the Company list. They should be their own list, so the company list should have 3 items, and then tabbing from "Shop" to the "Twitter icon" would label it as a "Social Media list 4 items".
![image](https://user-images.githubusercontent.com/4298857/113955899-731a6200-97d1-11eb-9ccc-a104bb1ce6e7.png)
![image](https://user-images.githubusercontent.com/4298857/113956149-e1f7bb00-97d1-11eb-929e-a5fc82429764.png)

2. The download on mobile images are no longer a list
![image](https://user-images.githubusercontent.com/4298857/113956368-356a0900-97d2-11eb-87ac-3e8e12c28330.png)
![image](https://user-images.githubusercontent.com/4298857/113956471-5b8fa900-97d2-11eb-8f94-2c256b20faa9.png)

3. In the Course Catalog "subjects" list, the list isn't labeled as "subjects" anymore, and there's a divider represented by "—" that is incorrectly counted as a list item (it's not focusable, so it shouldn't be one). This means the list reports 11 items instead of the 10 selectable ones.
![image](https://user-images.githubusercontent.com/4298857/113957243-b70e6680-97d3-11eb-9422-96ed71520a4f.png)
![image](https://user-images.githubusercontent.com/4298857/113957062-6e56ad80-97d3-11eb-8233-e89a01a9dc06.png)

2021-04-08 02:05 UTC, ZackMFleischman requested changes
Found a few accessibility regressions as mentioned in a previous comment

2021-04-08 21:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.2.47-alpha.8c52d6.0<br/>@codecademy/gamut-labs@13.3.0-alpha.8c52d6.0<br/>@codecademy/styleguide@33.7.0-alpha.8c52d6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-08 21:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://606f75aaba21a42a91659889--gamut-preview.netlify.app>https://606f75aaba21a42a91659889--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/606f75aaba21a42a91659889>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 18:56 UTC, ZackMFleischman approved these changes
🚢  it!
Thanks for making the A11y fixes!

2021-04-09 21:22 UTC, JoshuaKGoldberg commented
I started a separate conversation in Slack with some of the (very good) points @ZackMFleischman brought up, since I'm not sure which way is best: https://codecademy.slack.com/archives/CGQPTPR27/p1617996737046900

Either way for now I suspect we can merge, since none of this blocks screenreader users from easily using the footer! Woop!

2021-04-09 21:23 UTC, merged

2023-11-07 12:43 UTC, jamesjacob-jack commented
![Uploading Screenshot (421).png…]()

2024-05-30 00:28 UTC, don-mo commented
Very cool. I am taking a github pull request course right now! So cool to see collaboration in action!

2025-05-31 13:29 UTC, wearesoback commented
Nice collab example!