Cass gm 151
Codecademy/client-modules pull request #1608
Opened 2021-04-07 22:26 UTC by dreamwasp

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-09 19:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.8119b4.0<br/>@codecademy/gamut-labs@13.3.1-alpha.8119b4.0<br/>@codecademy/gamut@29.8.1-alpha.8119b4.0<br/>@codecademy/styleguide@33.7.2-alpha.8119b4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 19:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070b162023b0c4a1efe41c6--gamut-preview.netlify.app>https://6070b162023b0c4a1efe41c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070b162023b0c4a1efe41c6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-09 22:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.612543.0<br/>@codecademy/gamut-labs@13.3.1-alpha.612543.0<br/>@codecademy/gamut@29.8.1-alpha.612543.0<br/>@codecademy/styleguide@33.7.2-alpha.612543.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 22:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6070d120f0ca0d00bf6c408a--gamut-preview.netlify.app>https://6070d120f0ca0d00bf6c408a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6070d120f0ca0d00bf6c408a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-12 18:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.62277b.0<br/>@codecademy/gamut-labs@13.3.1-alpha.62277b.0<br/>@codecademy/gamut@29.8.1-alpha.62277b.0<br/>@codecademy/styleguide@33.7.2-alpha.62277b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-12 18:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6074974023c65f00dd7573fa--gamut-preview.netlify.app>https://6074974023c65f00dd7573fa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6074974023c65f00dd7573fa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-13 15:36 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
> +        '"Normal',
```suggestion
        'Normal',
```

2021-04-13 16:11 UTC, JoshuaKGoldberg requested changes
Indeed, will wait for unit tests :). But this looks great so far!

2021-04-13 16:11 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  if (isArray(options)) {
Nit: I think it's a little cleaner to use native operations when possible, instead of pulling in extraneous code:

```suggestion
  if (options instanceof Array) {
```

...and later down, can `isObject` be replaced with `if (options)`, since the only options are array, object, and undefined?

2021-04-13 17:53 UTC, dreamwasp commented on packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
> +      options: ['Base', 'Regular Size', '"Normal'],
i've been having some pains with the options types so was planning on splitting that into another ticket

2021-04-13 20:05 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  appearance: none;
This should be automatically prefixed with `appearance: none` I would assume.

2021-04-13 20:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607605b63f89c0348a2be88d--gamut-preview.netlify.app>https://607605b63f89c0348a2be88d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607605b63f89c0348a2be88d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-13 22:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.be6f3b.0<br/>@codecademy/gamut-labs@13.3.1-alpha.be6f3b.0<br/>@codecademy/gamut@29.8.1-alpha.be6f3b.0<br/>@codecademy/styleguide@33.7.2-alpha.be6f3b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-13 22:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60761bd791a8bc00e43b9d94--gamut-preview.netlify.app>https://60761bd791a8bc00e43b9d94--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60761bd791a8bc00e43b9d94>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-13 23:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.672ab2.0<br/>@codecademy/gamut-labs@13.3.1-alpha.672ab2.0<br/>@codecademy/gamut@29.8.1-alpha.672ab2.0<br/>@codecademy/styleguide@33.7.2-alpha.672ab2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-13 23:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607622afdd647a00cf8b4fb2--gamut-preview.netlify.app>https://607622afdd647a00cf8b4fb2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607622afdd647a00cf8b4fb2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-14 17:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.3f3f09.0<br/>@codecademy/gamut-labs@13.3.1-alpha.3f3f09.0<br/>@codecademy/gamut@29.8.1-alpha.3f3f09.0<br/>@codecademy/styleguide@33.7.2-alpha.3f3f09.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-14 17:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607720753c9a6900a080fea0--gamut-preview.netlify.app>https://607720753c9a6900a080fea0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607720753c9a6900a080fea0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-14 17:04 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
> +      options: ['Base', 'Regular Size', '"Normal'],
I'm down to help with this if you want 😁 , types are always fun

2021-04-14 17:04 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
> +This is a variant of our Select component with a styled dropdown menu. This is slightly heavier than our standard `Select` component so should not be used unless specified in designs.
> heavier

I don't think most people would be able to interpret that correctly

2021-04-14 17:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.6c870b.0<br/>@codecademy/gamut-labs@13.3.1-alpha.6c870b.0<br/>@codecademy/gamut@29.8.1-alpha.6c870b.0<br/>@codecademy/styleguide@33.7.2-alpha.6c870b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-14 17:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60772729807c2d0b6c656a18--gamut-preview.netlify.app>https://60772729807c2d0b6c656a18--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60772729807c2d0b6c656a18>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-14 21:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.1-alpha.d28200.0<br/>@codecademy/gamut-labs@13.3.1-alpha.d28200.0<br/>@codecademy/gamut@29.8.1-alpha.d28200.0<br/>@codecademy/styleguide@33.7.2-alpha.d28200.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-14 22:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60776630449dda5e7a41014c--gamut-preview.netlify.app>https://60776630449dda5e7a41014c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60776630449dda5e7a41014c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-15 00:18 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
> +### SelectDropdown
word

2021-04-15 17:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.26-alpha.79ccb1.0<br/>@codecademy/gamut-labs@13.5.3-alpha.79ccb1.0<br/>@codecademy/gamut@30.1.3-alpha.79ccb1.0<br/>@codecademy/styleguide@34.2.3-alpha.79ccb1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-15 17:41 UTC, dreamwasp commented on packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
> +      placeholder: 'all about that',
I'm pretty sure I'm going to need to create a CustomOption component in order to reliably pass in JSX elements so I think it's safer to test this then iterate on it to take care of the option styling + custom components in another PR

2021-04-15 17:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60787ad5c80c18470a3f9c02--gamut-preview.netlify.app>https://60787ad5c80c18470a3f9c02--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60787ad5c80c18470a3f9c02>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 13:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.28-alpha.3e7018.0<br/>@codecademy/gamut-labs@13.5.5-alpha.3e7018.0<br/>@codecademy/gamut@31.0.2-alpha.3e7018.0<br/>@codecademy/styleguide@35.0.2-alpha.3e7018.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 14:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.30-alpha.4c0a5e.0<br/>@codecademy/gamut-labs@13.5.7-alpha.4c0a5e.0<br/>@codecademy/gamut@31.0.2-alpha.4c0a5e.0<br/>@codecademy/styleguide@35.0.4-alpha.4c0a5e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 16:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607da9030b1eb600951130ef--gamut-preview.netlify.app>https://607da9030b1eb600951130ef--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607da9030b1eb600951130ef>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 16:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.32-alpha.cda9ec.0<br/>@codecademy/gamut-labs@13.5.9-alpha.cda9ec.0<br/>@codecademy/gamut@31.0.3-alpha.cda9ec.0<br/>@codecademy/styleguide@35.0.6-alpha.cda9ec.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 16:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607daa9c2122ef00bac5c2f1--gamut-preview.netlify.app>https://607daa9c2122ef00bac5c2f1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607daa9c2122ef00bac5c2f1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 16:13 UTC, JoshuaKGoldberg approved these changes
Looks great to me from a general code perspective. But, as with the integration branch, I'd like to see review from a product team that is actually going to use it 😄 

We'd played around with Reach UI before because of its great accessibility. If this ends up violating good practices in a test.io test, maybe it'd make sense to switch to that? I don't know that it will - just hypothesizing.

2021-04-19 16:13 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  dropdownIndicator: (provided, state) => ({
(nothing to change, just griping) this is why I don't like it when libraries have >=2 parameters when not all of them are intended for use all the time... now we have these unused props when we really would have wanted to make this `dropdownindicator: ({ state }) => ({`. _sigh_

2021-04-19 16:16 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +    <components.DropdownIndicator {...props}>
it does work! not sure why react-select named components that way but ... it did 🤷🏻

2021-04-19 16:16 UTC, dreamwasp commented on yarn.lock
> +"@emotion/react@^11.1.1", "@emotion/react@^11.1.4", "@emotion/react@^11.1.5":
ah yeah, i will try that!

2021-04-19 16:25 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  dropdownIndicator: (provided, state) => ({
yeah ... i do not like it either

2021-04-19 18:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.33-alpha.cf3670.0<br/>@codecademy/gamut-labs@13.5.10-alpha.cf3670.0<br/>@codecademy/gamut@31.0.4-alpha.cf3670.0<br/>@codecademy/styleguide@35.0.7-alpha.cf3670.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 18:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607dca02f044af008f25fca2--gamut-preview.netlify.app>https://607dca02f044af008f25fca2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607dca02f044af008f25fca2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 19:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607de0252479a81f444f877c--gamut-preview.netlify.app>https://607de0252479a81f444f877c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607de0252479a81f444f877c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 20:02 UTC, codecaaron approved these changes
Noice!

Some nit notes, but this looks great.

2021-04-19 20:38 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +      })}
yeah, didn't need it!! removed

2021-04-19 20:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.33-alpha.8d26e7.0<br/>@codecademy/gamut-labs@13.5.10-alpha.8d26e7.0<br/>@codecademy/gamut@31.0.4-alpha.8d26e7.0<br/>@codecademy/styleguide@35.0.7-alpha.8d26e7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 20:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607deb795283b12aa12c19eb--gamut-preview.netlify.app>https://607deb795283b12aa12c19eb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607deb795283b12aa12c19eb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 20:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.34-alpha.bbdcfe.0<br/>@codecademy/gamut-labs@13.5.11-alpha.bbdcfe.0<br/>@codecademy/gamut@31.0.5-alpha.bbdcfe.0<br/>@codecademy/styleguide@35.0.8-alpha.bbdcfe.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 20:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607dee1c8e142900db30d5d3--gamut-preview.netlify.app>https://607dee1c8e142900db30d5d3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607dee1c8e142900db30d5d3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 02:47 UTC, codecaaron commented on packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
> +  "SelectIcon",
I don't think we export this anymore :).  RE: Failing tests

2021-04-20 02:47 UTC, codecaaron commented on packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
> +  "StyledFlexbox",
We probably shouldn't export this https://github.com/Codecademy/client-modules/pull/1608/files#diff-e8e618f0fa471d94e1b31b91051dc1140e91094189470c38911ea6c7f2b28fc0R66

2021-04-20 13:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.37-alpha.7862d4.0<br/>@codecademy/gamut-labs@13.5.14-alpha.7862d4.0<br/>@codecademy/gamut@31.0.8-alpha.7862d4.0<br/>@codecademy/styleguide@35.0.11-alpha.7862d4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 13:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607ed6995a138837990c29e9--gamut-preview.netlify.app>https://607ed6995a138837990c29e9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607ed6995a138837990c29e9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 13:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.37-alpha.61e5f9.0<br/>@codecademy/gamut-labs@13.5.14-alpha.61e5f9.0<br/>@codecademy/gamut@31.0.8-alpha.61e5f9.0<br/>@codecademy/styleguide@35.0.11-alpha.61e5f9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 13:38 UTC, merged