Ar theme builder
Codecademy/client-modules pull request #1611
Opened 2021-04-09 14:28 UTC by codecaaron

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-09 14:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.10-alpha.5dc511.0<br/>@codecademy/gamut-kit@0.3.7-alpha.5dc511.0<br/>@codecademy/gamut-labs@13.3.7-alpha.5dc511.0<br/>@codecademy/gamut-styles@9.3.1-alpha.5dc511.0<br/>@codecademy/gamut-tests@2.3.7-alpha.5dc511.0<br/>@codecademy/gamut@29.9.3-alpha.5dc511.0<br/>@codecademy/konamimojisplosion@0.2.7-alpha.5dc511.0<br/>@codecademy/markdown-overrides@0.5.20-alpha.5dc511.0<br/>@codecademy/styleguide@33.8.4-alpha.5dc511.0<br/>@codecademy/variance@0.7.1-alpha.5dc511.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 15:37 UTC, codecaaron commented on packages/gamut-styles/src/GamutProvider.tsx
> +      <Global styles={css({ ':root': colorMode })} />
These should be separate as updating colorMode would cause issues with style insertion and we don't want to update other root variables ever.

2021-04-09 16:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.10-alpha.8829b7.0<br/>@codecademy/gamut-kit@0.3.7-alpha.8829b7.0<br/>@codecademy/gamut-labs@13.3.7-alpha.8829b7.0<br/>@codecademy/gamut-styles@9.3.1-alpha.8829b7.0<br/>@codecademy/gamut-tests@2.3.7-alpha.8829b7.0<br/>@codecademy/gamut@29.9.3-alpha.8829b7.0<br/>@codecademy/konamimojisplosion@0.2.7-alpha.8829b7.0<br/>@codecademy/markdown-overrides@0.5.20-alpha.8829b7.0<br/>@codecademy/styleguide@33.8.4-alpha.8829b7.0<br/>@codecademy/variance@0.7.1-alpha.8829b7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 16:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.10-alpha.b9cc32.0<br/>@codecademy/gamut-kit@0.3.7-alpha.b9cc32.0<br/>@codecademy/gamut-labs@13.3.7-alpha.b9cc32.0<br/>@codecademy/gamut-styles@9.3.1-alpha.b9cc32.0<br/>@codecademy/gamut-tests@2.3.7-alpha.b9cc32.0<br/>@codecademy/gamut@29.9.3-alpha.b9cc32.0<br/>@codecademy/konamimojisplosion@0.2.7-alpha.b9cc32.0<br/>@codecademy/markdown-overrides@0.5.20-alpha.b9cc32.0<br/>@codecademy/styleguide@33.8.4-alpha.b9cc32.0<br/>@codecademy/variance@0.7.1-alpha.b9cc32.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-09 16:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.10-alpha.c6ea0d.0<br/>@codecademy/gamut-kit@0.3.7-alpha.c6ea0d.0<br/>@codecademy/gamut-labs@13.3.7-alpha.c6ea0d.0<br/>@codecademy/gamut-styles@9.3.1-alpha.c6ea0d.0<br/>@codecademy/gamut-tests@2.3.7-alpha.c6ea0d.0<br/>@codecademy/gamut@29.9.3-alpha.c6ea0d.0<br/>@codecademy/konamimojisplosion@0.2.7-alpha.c6ea0d.0<br/>@codecademy/markdown-overrides@0.5.20-alpha.c6ea0d.0<br/>@codecademy/styleguide@33.8.4-alpha.c6ea0d.0<br/>@codecademy/variance@0.7.1-alpha.c6ea0d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-10 19:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.11-alpha.6b76e1.0<br/>@codecademy/gamut-kit@0.3.10-alpha.6b76e1.0<br/>@codecademy/gamut-labs@13.4.2-alpha.6b76e1.0<br/>@codecademy/gamut-styles@9.3.2-alpha.6b76e1.0<br/>@codecademy/gamut-tests@2.3.8-alpha.6b76e1.0<br/>@codecademy/gamut@29.9.4-alpha.6b76e1.0<br/>@codecademy/konamimojisplosion@0.2.8-alpha.6b76e1.0<br/>@codecademy/markdown-overrides@0.5.21-alpha.6b76e1.0<br/>@codecademy/styleguide@33.9.2-alpha.6b76e1.0<br/>@codecademy/variance@0.7.2-alpha.6b76e1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-10 19:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6071f6139bf93389d26e3d4c--gamut-preview.netlify.app>https://6071f6139bf93389d26e3d4c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6071f6139bf93389d26e3d4c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-10 22:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.11-alpha.86540f.0<br/>@codecademy/gamut-kit@0.3.10-alpha.86540f.0<br/>@codecademy/gamut-labs@13.4.2-alpha.86540f.0<br/>@codecademy/gamut-styles@9.3.2-alpha.86540f.0<br/>@codecademy/gamut-tests@2.3.8-alpha.86540f.0<br/>@codecademy/gamut@29.9.4-alpha.86540f.0<br/>@codecademy/konamimojisplosion@0.2.8-alpha.86540f.0<br/>@codecademy/markdown-overrides@0.5.21-alpha.86540f.0<br/>@codecademy/styleguide@33.9.2-alpha.86540f.0<br/>@codecademy/variance@0.7.2-alpha.86540f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-10 22:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60722a3ad2f5ece1f12af4c4--gamut-preview.netlify.app>https://60722a3ad2f5ece1f12af4c4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60722a3ad2f5ece1f12af4c4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-10 22:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.11-alpha.e7cfef.0<br/>@codecademy/gamut-kit@0.3.10-alpha.e7cfef.0<br/>@codecademy/gamut-labs@13.4.2-alpha.e7cfef.0<br/>@codecademy/gamut-styles@9.3.2-alpha.e7cfef.0<br/>@codecademy/gamut-tests@2.3.8-alpha.e7cfef.0<br/>@codecademy/gamut@29.9.4-alpha.e7cfef.0<br/>@codecademy/konamimojisplosion@0.2.8-alpha.e7cfef.0<br/>@codecademy/markdown-overrides@0.5.21-alpha.e7cfef.0<br/>@codecademy/styleguide@33.9.2-alpha.e7cfef.0<br/>@codecademy/variance@0.7.2-alpha.e7cfef.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-10 22:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.11-alpha.4daa4c.0<br/>@codecademy/gamut-kit@0.3.10-alpha.4daa4c.0<br/>@codecademy/gamut-labs@13.4.2-alpha.4daa4c.0<br/>@codecademy/gamut-styles@9.3.2-alpha.4daa4c.0<br/>@codecademy/gamut-tests@2.3.8-alpha.4daa4c.0<br/>@codecademy/gamut@29.9.4-alpha.4daa4c.0<br/>@codecademy/konamimojisplosion@0.2.8-alpha.4daa4c.0<br/>@codecademy/markdown-overrides@0.5.21-alpha.4daa4c.0<br/>@codecademy/styleguide@33.9.2-alpha.4daa4c.0<br/>@codecademy/variance@0.7.2-alpha.4daa4c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-10 22:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60722d3f0db6e3e7afcff4bc--gamut-preview.netlify.app>https://60722d3f0db6e3e7afcff4bc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60722d3f0db6e3e7afcff4bc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-11 05:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.11-alpha.44ad46.0<br/>@codecademy/gamut-kit@0.3.10-alpha.44ad46.0<br/>@codecademy/gamut-labs@13.4.2-alpha.44ad46.0<br/>@codecademy/gamut-styles@9.3.2-alpha.44ad46.0<br/>@codecademy/gamut-tests@2.3.8-alpha.44ad46.0<br/>@codecademy/gamut@29.9.4-alpha.44ad46.0<br/>@codecademy/konamimojisplosion@0.2.8-alpha.44ad46.0<br/>@codecademy/markdown-overrides@0.5.21-alpha.44ad46.0<br/>@codecademy/styleguide@33.9.2-alpha.44ad46.0<br/>@codecademy/variance@0.7.2-alpha.44ad46.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-11 05:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60728854fb8cb20095d84bce--gamut-preview.netlify.app>https://60728854fb8cb20095d84bce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60728854fb8cb20095d84bce>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-11 13:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6072f9134a2623a3e8f210be--gamut-preview.netlify.app>https://6072f9134a2623a3e8f210be--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6072f9134a2623a3e8f210be>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-11 13:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.11-alpha.7e67f7.0<br/>@codecademy/gamut-kit@0.3.10-alpha.7e67f7.0<br/>@codecademy/gamut-labs@13.4.2-alpha.7e67f7.0<br/>@codecademy/gamut-styles@9.3.2-alpha.7e67f7.0<br/>@codecademy/gamut-tests@2.3.8-alpha.7e67f7.0<br/>@codecademy/gamut@29.9.4-alpha.7e67f7.0<br/>@codecademy/konamimojisplosion@0.2.8-alpha.7e67f7.0<br/>@codecademy/markdown-overrides@0.5.21-alpha.7e67f7.0<br/>@codecademy/styleguide@33.9.2-alpha.7e67f7.0<br/>@codecademy/variance@0.7.2-alpha.7e67f7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-11 13:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.11-alpha.629042.0<br/>@codecademy/gamut-kit@0.3.10-alpha.629042.0<br/>@codecademy/gamut-labs@13.4.2-alpha.629042.0<br/>@codecademy/gamut-styles@9.3.2-alpha.629042.0<br/>@codecademy/gamut-tests@2.3.8-alpha.629042.0<br/>@codecademy/gamut@29.9.4-alpha.629042.0<br/>@codecademy/konamimojisplosion@0.2.8-alpha.629042.0<br/>@codecademy/markdown-overrides@0.5.21-alpha.629042.0<br/>@codecademy/styleguide@33.9.2-alpha.629042.0<br/>@codecademy/variance@0.7.2-alpha.629042.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-11 13:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6072fc79ca631cb0469b0f9f--gamut-preview.netlify.app>https://6072fc79ca631cb0469b0f9f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6072fc79ca631cb0469b0f9f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-12 14:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.11-alpha.a9293d.0<br/>@codecademy/gamut-kit@0.3.10-alpha.a9293d.0<br/>@codecademy/gamut-labs@13.4.2-alpha.a9293d.0<br/>@codecademy/gamut-styles@9.3.2-alpha.a9293d.0<br/>@codecademy/gamut-tests@2.3.8-alpha.a9293d.0<br/>@codecademy/gamut@29.9.4-alpha.a9293d.0<br/>@codecademy/konamimojisplosion@0.2.8-alpha.a9293d.0<br/>@codecademy/markdown-overrides@0.5.21-alpha.a9293d.0<br/>@codecademy/styleguide@33.9.2-alpha.a9293d.0<br/>@codecademy/variance@0.7.2-alpha.a9293d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-12 14:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60745add79123633cf30f9d8--gamut-preview.netlify.app>https://60745add79123633cf30f9d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60745add79123633cf30f9d8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-14 12:55 UTC, JoshuaKGoldberg requested changes
> will increase coverage by 0.98%.

Damn Aaron, keep sending these kinds of PRs and none of us will be able to get a >= test coverage number in any of ours! 😜 

Love the core logic of this PR & how it stitches together the existing color stuff. Let's talk about the `createTheme.ts` suggestions?

2021-04-14 12:55 UTC, JoshuaKGoldberg commented on packages/gamut-styles/src/theme.ts
> +  .build();
This file is one of the coolest things I've ever seen you do. It brings everything together. Very nice!

2021-04-14 12:55 UTC, JoshuaKGoldberg commented on packages/variance/src/createTheme/createTheme.ts
> +   * @returns
Eventually someone will add a typescript-eslint rule about unnecessary return values like `@returns` or `@returns this`... until then, we can remove these for not adding any info.

2021-04-14 12:55 UTC, JoshuaKGoldberg commented on packages/variance/src/createTheme/createTheme.ts
> +   * @example .addColors({ navy: 'navy', hyper: 'purple' })
OTOH really appreciating these examples and param docs!

2021-04-14 12:55 UTC, JoshuaKGoldberg commented on packages/variance/src/createTheme/createTheme.ts
> +  private theme = {} as T;
Consider `#`, maybe?

2021-04-14 12:55 UTC, JoshuaKGoldberg commented on packages/variance/src/createTheme/createTheme.ts
> +  }
There's a really good [suggestion](https://effectivetypescript.com/2020/03/24/null-values-to-perimeter/) about roughly this in @danvk's _Effective TypeScript_ book _(tagging him because I think he'd get a kick out of this file & the discussions, hi Dan!)_. This `ThemeBuilder` class starts out not-type-safe and then only becomes type safe once these things are provided. It'd be easy for someone new to it to slip up and call `.build()` without calling the intermediate methods first.

How about having a class for each iteration of the generation pipeline?

```ts
createTheme(...)    // 1. ThemeBuilderEmpty
  .withColors()     // 2. ThemeBuilderWithColors
  .withColorModes() // 3. ThemeBuilderWithColorModes
  .withVariables()  // 4. ThemeBuilderWithVariables
  .build()
```

That might make it easier to express some of the complex types more succinctly.. or maybe just add more indirection & places to redeclare those types 😬

2021-04-14 13:14 UTC, codecaaron commented on packages/variance/src/createTheme/createTheme.ts
> +  }
This is actually something I wanted to ask you about! 

Love the idea!  I considered it for a second because of the security in available methods but wasn't sure what the ideal way was :) 

Let me get something together!

2021-04-14 13:14 UTC, codecaaron commented on packages/variance/src/createTheme/createTheme.ts
> +  private theme = {} as T;
Sorry I think I missed something.  Whats `#`?  A bit confused here -_-

2021-04-14 13:14 UTC, codecaaron commented on packages/gamut-styles/src/theme.ts
> +  .build();
<3 <3

Refactoring this gave me a huge sigh of relief.   One of those rare things that feels right, makes me super happy to hear that it did for you too!

2021-04-14 13:14 UTC, codecaaron commented on packages/variance/src/createTheme/createTheme.ts
> +   * @example .addColors({ navy: 'navy', hyper: 'purple' })
I've been looking into generating them for variance prop functions and wanted to start doing more of them, glad they're helping in a small way.

2021-04-14 13:14 UTC, codecaaron commented on packages/variance/src/createTheme/createTheme.ts
> +   * @returns
Should we maybe add a styleguide for JSDoc?  At least for our shared stuff I think its gonna start being V important when source may be transpiled. 

If you've got specific preferences I can update these to match to start!

2021-04-14 13:25 UTC, danvk commented on packages/variance/src/createTheme/createTheme.ts
> +  }
Hi @JoshuaKGoldberg! Fun PR :) Do you have to call all four of those methods (`withColors`, `withColorModes`, `withVariables`, `build`) in that exact order? Then your sequence of classes makes a lot of sense. If not then it might be a little trickier to model. Without knowing much about the specifics, it might be easier to model the exact set of allowable/not allowable uses if it were more like `.build({colors, colorModes, variables})`, so that you could define a type for that parameter.

2021-04-14 13:26 UTC, JoshuaKGoldberg commented on packages/variance/src/createTheme/createTheme.ts
> +   * @returns
Yeah for sure, as a followup?

So far I've just been nitting for unnecessary stuff, not too much around style. We should look at https://github.com/microsoft/tsdoc to see how far they've come...

2021-04-14 13:27 UTC, JoshuaKGoldberg commented on packages/variance/src/createTheme/createTheme.ts
> +  private theme = {} as T;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

A whole new world 🙌 

Definitely not blocking, just a minor preference of moving away from TS-specific constructs.

2021-04-14 13:28 UTC, JoshuaKGoldberg commented on packages/variance/src/createTheme/createTheme.ts
> +  }
We actually did try that in a pairing a bit back! One tricky part was providing _all_ type information to start, since some parts of the initial API had cross-dependencies (e.g. variants that described behavior at different breakpoints needing to know the types of breakpoints). I don't know how much that's still a blocker here.

2021-04-14 14:11 UTC, codecaaron commented on packages/variance/src/createTheme/createTheme.ts
> +  }
There's some restriction on ordering, but not a huge amount:
1. Breakpoints are required so that we can serialize variables with them.  (though this could be a required method rather than an at the base constructor)
2. Color methods are not required, but do require correct sequence `colors` => `colorModes` to ensure correct type restrictions + variable references.
3. Final `build()` call that can happen at any time.

I think theres some natural lines forming here for the class structure.

2021-04-14 18:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.12-alpha.93d14b.0<br/>@codecademy/gamut-kit@0.3.19-alpha.93d14b.0<br/>@codecademy/gamut-labs@13.4.11-alpha.93d14b.0<br/>@codecademy/gamut-styles@9.3.3-alpha.93d14b.0<br/>@codecademy/gamut-tests@2.3.10-alpha.93d14b.0<br/>@codecademy/gamut@29.9.9-alpha.93d14b.0<br/>@codecademy/konamimojisplosion@0.2.10-alpha.93d14b.0<br/>@codecademy/markdown-overrides@0.5.22-alpha.93d14b.0<br/>@codecademy/styleguide@33.9.11-alpha.93d14b.0<br/>@codecademy/variance@0.7.2-alpha.93d14b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-14 18:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60772e72f0fe2117b47ba7d7--gamut-preview.netlify.app>https://60772e72f0fe2117b47ba7d7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60772e72f0fe2117b47ba7d7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-14 18:21 UTC, codecaaron commented on packages/variance/src/createTheme/createTheme.ts
> +  private theme = {} as T;
Love it, done!

2021-04-14 18:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.12-alpha.4c9185.0<br/>@codecademy/gamut-kit@0.3.19-alpha.4c9185.0<br/>@codecademy/gamut-labs@13.4.11-alpha.4c9185.0<br/>@codecademy/gamut-styles@9.3.3-alpha.4c9185.0<br/>@codecademy/gamut-tests@2.3.10-alpha.4c9185.0<br/>@codecademy/gamut@29.9.9-alpha.4c9185.0<br/>@codecademy/konamimojisplosion@0.2.10-alpha.4c9185.0<br/>@codecademy/markdown-overrides@0.5.22-alpha.4c9185.0<br/>@codecademy/styleguide@33.9.11-alpha.4c9185.0<br/>@codecademy/variance@0.7.2-alpha.4c9185.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-14 18:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607733aa13dff723935d7eb1--gamut-preview.netlify.app>https://607733aa13dff723935d7eb1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607733aa13dff723935d7eb1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-14 18:50 UTC, codecaaron commented on packages/variance/src/createTheme/createTheme.ts
> +  }
@JoshuaKGoldberg adding this as a new ticket https://codecademy.atlassian.net/browse/WEB-1410

2021-04-14 22:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.12-alpha.946b7b.0<br/>@codecademy/gamut-kit@0.3.22-alpha.946b7b.0<br/>@codecademy/gamut-labs@13.4.14-alpha.946b7b.0<br/>@codecademy/gamut-styles@9.3.3-alpha.946b7b.0<br/>@codecademy/gamut-tests@2.3.10-alpha.946b7b.0<br/>@codecademy/gamut@30.0.1-alpha.946b7b.0<br/>@codecademy/konamimojisplosion@0.2.10-alpha.946b7b.0<br/>@codecademy/markdown-overrides@0.5.22-alpha.946b7b.0<br/>@codecademy/styleguide@34.0.1-alpha.946b7b.0<br/>@codecademy/variance@0.7.2-alpha.946b7b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-14 22:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60777175d4c2655ec22e6e26--gamut-preview.netlify.app>https://60777175d4c2655ec22e6e26--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60777175d4c2655ec22e6e26>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-15 00:12 UTC, JoshuaKGoldberg approved these changes
Yup yup, I think this is ready for initial flighting. Let's do this!!

2021-04-15 01:58 UTC, merged