Anchor Conversaion
Codecademy/client-modules pull request #1619
Opened 2021-04-12 21:10 UTC by codecaaron

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-16 23:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.15-alpha.9e4d40.0<br/>@codecademy/gamut-kit@0.3.29-alpha.9e4d40.0<br/>@codecademy/gamut-labs@13.5.6-alpha.9e4d40.0<br/>@codecademy/gamut-styles@9.5.2-alpha.9e4d40.0<br/>@codecademy/gamut-tests@2.3.13-alpha.9e4d40.0<br/>@codecademy/gamut@31.0.2-alpha.9e4d40.0<br/>@codecademy/konamimojisplosion@0.2.13-alpha.9e4d40.0<br/>@codecademy/markdown-overrides@0.5.25-alpha.9e4d40.0<br/>@codecademy/styleguide@35.0.3-alpha.9e4d40.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-16 23:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.15-alpha.5ad90a.0<br/>@codecademy/gamut-kit@0.3.29-alpha.5ad90a.0<br/>@codecademy/gamut-labs@13.5.6-alpha.5ad90a.0<br/>@codecademy/gamut-styles@9.5.2-alpha.5ad90a.0<br/>@codecademy/gamut-tests@2.3.13-alpha.5ad90a.0<br/>@codecademy/gamut@31.0.2-alpha.5ad90a.0<br/>@codecademy/konamimojisplosion@0.2.13-alpha.5ad90a.0<br/>@codecademy/markdown-overrides@0.5.25-alpha.5ad90a.0<br/>@codecademy/styleguide@35.0.3-alpha.5ad90a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-16 23:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607a1eb3815f4c1c996c63f9--gamut-preview.netlify.app>https://607a1eb3815f4c1c996c63f9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607a1eb3815f4c1c996c63f9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 01:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.9.15-alpha.3b89d7.0<br/>@codecademy/gamut-kit@0.3.29-alpha.3b89d7.0<br/>@codecademy/gamut-labs@13.5.6-alpha.3b89d7.0<br/>@codecademy/gamut-styles@9.5.2-alpha.3b89d7.0<br/>@codecademy/gamut-tests@2.3.13-alpha.3b89d7.0<br/>@codecademy/gamut@31.0.2-alpha.3b89d7.0<br/>@codecademy/konamimojisplosion@0.2.13-alpha.3b89d7.0<br/>@codecademy/markdown-overrides@0.5.25-alpha.3b89d7.0<br/>@codecademy/styleguide@35.0.3-alpha.3b89d7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 01:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607cd791c418d64c5b677a35--gamut-preview.netlify.app>https://607cd791c418d64c5b677a35--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607cd791c418d64c5b677a35>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 19:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.06208a.0<br/>@codecademy/gamut-kit@0.3.39-alpha.06208a.0<br/>@codecademy/gamut-labs@14.0.1-alpha.06208a.0<br/>@codecademy/gamut-styles@9.5.4-alpha.06208a.0<br/>@codecademy/gamut-tests@2.3.15-alpha.06208a.0<br/>@codecademy/gamut@32.0.1-alpha.06208a.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.06208a.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.06208a.0<br/>@codecademy/styleguide@36.0.1-alpha.06208a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 19:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f2f5070a5bf0093ef041c--gamut-preview.netlify.app>https://607f2f5070a5bf0093ef041c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f2f5070a5bf0093ef041c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 21:11 UTC, codecaaron commented on packages/gamut/src/BodyPortal/index.tsx
> +    <PortalWrapper mode={active}>{children}</PortalWrapper>,
This reprovisions the variables of the current context to the new root. 

Since portals escape the dom context where variables would apply this ensures that the pointers will find the correct version.

2021-04-20 21:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.b3d852.0<br/>@codecademy/gamut-kit@0.3.39-alpha.b3d852.0<br/>@codecademy/gamut-labs@14.0.1-alpha.b3d852.0<br/>@codecademy/gamut-styles@9.5.4-alpha.b3d852.0<br/>@codecademy/gamut-tests@2.3.15-alpha.b3d852.0<br/>@codecademy/gamut@32.0.1-alpha.b3d852.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.b3d852.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.b3d852.0<br/>@codecademy/styleguide@36.0.1-alpha.b3d852.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 21:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f443313c9c000e6243c15--gamut-preview.netlify.app>https://607f443313c9c000e6243c15--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f443313c9c000e6243c15>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 21:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.233979.0<br/>@codecademy/gamut-kit@0.3.39-alpha.233979.0<br/>@codecademy/gamut-labs@14.0.1-alpha.233979.0<br/>@codecademy/gamut-styles@9.5.4-alpha.233979.0<br/>@codecademy/gamut-tests@2.3.15-alpha.233979.0<br/>@codecademy/gamut@32.0.1-alpha.233979.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.233979.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.233979.0<br/>@codecademy/styleguide@36.0.1-alpha.233979.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 21:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f4637ca77a30097ed6c32--gamut-preview.netlify.app>https://607f4637ca77a30097ed6c32--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f4637ca77a30097ed6c32>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 21:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.9b2dff.0<br/>@codecademy/gamut-kit@0.3.39-alpha.9b2dff.0<br/>@codecademy/gamut-labs@14.0.1-alpha.9b2dff.0<br/>@codecademy/gamut-styles@9.5.4-alpha.9b2dff.0<br/>@codecademy/gamut-tests@2.3.15-alpha.9b2dff.0<br/>@codecademy/gamut@32.0.1-alpha.9b2dff.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.9b2dff.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.9b2dff.0<br/>@codecademy/styleguide@36.0.1-alpha.9b2dff.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 21:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f48371a48c4009ba827cd--gamut-preview.netlify.app>https://607f48371a48c4009ba827cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f48371a48c4009ba827cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 01:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.a05191.0<br/>@codecademy/gamut-kit@0.3.39-alpha.a05191.0<br/>@codecademy/gamut-labs@14.0.1-alpha.a05191.0<br/>@codecademy/gamut-styles@9.5.4-alpha.a05191.0<br/>@codecademy/gamut-tests@2.3.15-alpha.a05191.0<br/>@codecademy/gamut@32.0.1-alpha.a05191.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.a05191.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.a05191.0<br/>@codecademy/styleguide@36.0.1-alpha.a05191.0<br/>@codecademy/variance@0.9.1-alpha.a05191.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 01:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f84d6cf83cc3149ec0c06--gamut-preview.netlify.app>https://607f84d6cf83cc3149ec0c06--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f84d6cf83cc3149ec0c06>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 01:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.178d15.0<br/>@codecademy/gamut-kit@0.3.39-alpha.178d15.0<br/>@codecademy/gamut-labs@14.0.1-alpha.178d15.0<br/>@codecademy/gamut-styles@9.5.4-alpha.178d15.0<br/>@codecademy/gamut-tests@2.3.15-alpha.178d15.0<br/>@codecademy/gamut@32.0.1-alpha.178d15.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.178d15.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.178d15.0<br/>@codecademy/styleguide@36.0.1-alpha.178d15.0<br/>@codecademy/variance@0.9.1-alpha.178d15.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 02:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f875baeb4143a36837fba--gamut-preview.netlify.app>https://607f875baeb4143a36837fba--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f875baeb4143a36837fba>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 03:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.2fd74c.0<br/>@codecademy/gamut-kit@0.3.39-alpha.2fd74c.0<br/>@codecademy/gamut-labs@14.0.1-alpha.2fd74c.0<br/>@codecademy/gamut-styles@9.5.4-alpha.2fd74c.0<br/>@codecademy/gamut-tests@2.3.15-alpha.2fd74c.0<br/>@codecademy/gamut@32.0.1-alpha.2fd74c.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.2fd74c.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.2fd74c.0<br/>@codecademy/styleguide@36.0.1-alpha.2fd74c.0<br/>@codecademy/variance@0.9.1-alpha.2fd74c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 03:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f95e867fb7a456de6aebb--gamut-preview.netlify.app>https://607f95e867fb7a456de6aebb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f95e867fb7a456de6aebb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 12:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.87e649.0<br/>@codecademy/gamut-kit@0.3.39-alpha.87e649.0<br/>@codecademy/gamut-labs@14.0.1-alpha.87e649.0<br/>@codecademy/gamut-styles@9.5.4-alpha.87e649.0<br/>@codecademy/gamut-tests@2.3.15-alpha.87e649.0<br/>@codecademy/gamut@32.0.1-alpha.87e649.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.87e649.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.87e649.0<br/>@codecademy/styleguide@36.0.1-alpha.87e649.0<br/>@codecademy/variance@0.9.1-alpha.87e649.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 12:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6080191d2d320608ee106e01--gamut-preview.netlify.app>https://6080191d2d320608ee106e01--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6080191d2d320608ee106e01>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 16:20 UTC, dreamwasp approved these changes
i love it

2021-04-21 17:37 UTC, JoshuaKGoldberg commented on packages/variance/src/types/properties.ts
> +export interface PropertyTypes<Overrides = (string & {}) | 0>
wut

2021-04-21 17:41 UTC, JoshuaKGoldberg requested changes
Waiting on that one docs line 😄

2021-04-21 17:41 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Typography/Anchor.stories.mdx
> +- `standard`: For use outside of a ‘menu’ instance where (for a good reason) you can’t use the Text Button with the included button-padding.
This is like how movie posters don't match the order of faces to names. 

![Screenshot of anchor orders not matching](https://user-images.githubusercontent.com/3335181/115597172-fabea100-a2a6-11eb-9376-5ceb505b4bce.png)

2021-04-21 17:45 UTC, codecaaron commented on packages/styleguide/stories/Typography/Anchor.stories.mdx
> +There are three main varaints for Anchor links that are meant to be used in specific contexts. Their default states all a visually distinct. Please refer to the
Added Link <3

2021-04-21 17:48 UTC, codecaaron commented on packages/variance/src/types/properties.ts
> +export interface PropertyTypes<Overrides = (string & {}) | 0>
Ahh this is the type loosening I was talking about in the change log.  Basically if there are no actual types associated with a specific property the only type it ends up referring to is never.  For whatever reason things like `outlineOffset` have this issue.

This change gives all CSSType definitions an actual default value (we strip out `string & {}` for system props) to ensure that `variant` and `css` functions can use these properties.

2021-04-21 17:49 UTC, codecaaron commented on packages/styleguide/stories/Typography/Anchor.stories.mdx
> +- `standard`: For use outside of a ‘menu’ instance where (for a good reason) you can’t use the Text Button with the included button-padding.
Hahaha oh man yeah, that is irksome.  Fixed!

2021-04-21 17:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.c3534c.0<br/>@codecademy/gamut-kit@0.3.39-alpha.c3534c.0<br/>@codecademy/gamut-labs@14.0.1-alpha.c3534c.0<br/>@codecademy/gamut-styles@9.5.4-alpha.c3534c.0<br/>@codecademy/gamut-tests@2.3.15-alpha.c3534c.0<br/>@codecademy/gamut@32.0.1-alpha.c3534c.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.c3534c.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.c3534c.0<br/>@codecademy/styleguide@36.0.1-alpha.c3534c.0<br/>@codecademy/variance@0.9.1-alpha.c3534c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 17:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608065e0fbce2c2b87b25b44--gamut-preview.netlify.app>https://608065e0fbce2c2b87b25b44--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608065e0fbce2c2b87b25b44>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 19:40 UTC, JoshuaKGoldberg commented on packages/variance/src/types/properties.ts
> +export interface PropertyTypes<Overrides = (string & {}) | 0>
Caaaan we get a doc comment on this? It's... very confusing to read this 😄

2021-04-21 19:50 UTC, codecaaron commented on packages/variance/src/types/properties.ts
> +export interface PropertyTypes<Overrides = (string & {}) | 0>
@JoshuaKGoldberg  done :)

2021-04-21 19:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.3-alpha.4b188c.0<br/>@codecademy/gamut-kit@0.3.39-alpha.4b188c.0<br/>@codecademy/gamut-labs@14.0.1-alpha.4b188c.0<br/>@codecademy/gamut-styles@9.5.4-alpha.4b188c.0<br/>@codecademy/gamut-tests@2.3.15-alpha.4b188c.0<br/>@codecademy/gamut@32.0.1-alpha.4b188c.0<br/>@codecademy/konamimojisplosion@0.2.15-alpha.4b188c.0<br/>@codecademy/markdown-overrides@0.5.27-alpha.4b188c.0<br/>@codecademy/styleguide@36.0.1-alpha.4b188c.0<br/>@codecademy/variance@0.9.1-alpha.4b188c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 19:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60808374e2cf0610ef3d75e8--gamut-preview.netlify.app>https://60808374e2cf0610ef3d75e8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60808374e2cf0610ef3d75e8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 12:40 UTC, JoshuaKGoldberg approved these changes
Word, thanks for the extra docs! 🌮

2021-04-23 12:40 UTC, JoshuaKGoldberg commented on packages/gamut-styles/src/ColorMode.tsx
> +  setVariables?: boolean;
Nit: maybe `variablesSet`, since `setVariables` in our naming would generally imply it's a function? And could you TSDoc it?

2021-04-23 12:40 UTC, JoshuaKGoldberg commented on packages/gamut/src/ButtonBase/ButtonBase.tsx
> +const ButtonReset = styled.button`
Ha, we're finally getting back to `ButtonBase`... should we replace `ButtonDeprecatedBase` with it in a bunch of places?

2021-04-23 12:44 UTC, codecaaron commented on packages/gamut/src/ButtonBase/ButtonBase.tsx
> +const ButtonReset = styled.button`
I think we'll probably need to replace that with `Anchor` proper for anything that still uses SCSS, but for any place that already uses emotion overrides I believe we can totally do that :)

2021-04-23 12:48 UTC, rogervera commented on packages/gamut-styles/src/ColorMode.tsx
> +  setVariables?: boolean;
+1

2021-04-23 12:54 UTC, codecaaron commented on packages/gamut-styles/src/ColorMode.tsx
> +  setVariables?: boolean;
Hmm yeah this is a weird one.  

Technically it's just a flag to force the provider to manually set the variables regardless of whether the actual context has a changed.   So maybe `alwaysSetVars` or `provision` or `alwaysProvide`.   I don't know 🤷

2021-04-23 12:58 UTC, rogervera commented on packages/gamut-styles/src/ColorMode.tsx
> +  setVariables?: boolean;
> a flag to force the provider to manually set the variables regardless of whether the actual context has a changed.

`forceProvision`, `forceSetVars`? 🤔

2021-04-23 17:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6083062444d33f00a746332b--gamut-preview.netlify.app>https://6083062444d33f00a746332b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6083062444d33f00a746332b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 17:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60830807699c1900a2701acd--gamut-preview.netlify.app>https://60830807699c1900a2701acd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60830807699c1900a2701acd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 18:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.5-alpha.1f23fd.0<br/>@codecademy/gamut-kit@0.3.44-alpha.1f23fd.0<br/>@codecademy/gamut-labs@14.2.4-alpha.1f23fd.0<br/>@codecademy/gamut-styles@9.5.6-alpha.1f23fd.0<br/>@codecademy/gamut-tests@2.3.17-alpha.1f23fd.0<br/>@codecademy/gamut@32.1.4-alpha.1f23fd.0<br/>@codecademy/konamimojisplosion@0.2.17-alpha.1f23fd.0<br/>@codecademy/markdown-overrides@0.5.29-alpha.1f23fd.0<br/>@codecademy/styleguide@36.2.5-alpha.1f23fd.0<br/>@codecademy/variance@0.9.1-alpha.1f23fd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-23 20:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.5-alpha.b5fe5a.0<br/>@codecademy/gamut-kit@0.3.45-alpha.b5fe5a.0<br/>@codecademy/gamut-labs@14.2.5-alpha.b5fe5a.0<br/>@codecademy/gamut-styles@9.5.6-alpha.b5fe5a.0<br/>@codecademy/gamut-tests@2.3.17-alpha.b5fe5a.0<br/>@codecademy/gamut@32.1.4-alpha.b5fe5a.0<br/>@codecademy/konamimojisplosion@0.2.17-alpha.b5fe5a.0<br/>@codecademy/markdown-overrides@0.5.29-alpha.b5fe5a.0<br/>@codecademy/styleguide@36.2.6-alpha.b5fe5a.0<br/>@codecademy/variance@0.9.1-alpha.b5fe5a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-23 20:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60832d9524fe1424306b7b19--gamut-preview.netlify.app>https://60832d9524fe1424306b7b19--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60832d9524fe1424306b7b19>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 13:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.6-alpha.29cae4.0<br/>@codecademy/gamut-kit@0.3.47-alpha.29cae4.0<br/>@codecademy/gamut-labs@14.3.1-alpha.29cae4.0<br/>@codecademy/gamut-styles@9.5.7-alpha.29cae4.0<br/>@codecademy/gamut-tests@2.3.18-alpha.29cae4.0<br/>@codecademy/gamut@32.2.1-alpha.29cae4.0<br/>@codecademy/konamimojisplosion@0.2.18-alpha.29cae4.0<br/>@codecademy/markdown-overrides@0.5.30-alpha.29cae4.0<br/>@codecademy/styleguide@36.3.1-alpha.29cae4.0<br/>@codecademy/variance@0.9.1-alpha.29cae4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 13:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086bd7dcdefd99a17fa56fb--gamut-preview.netlify.app>https://6086bd7dcdefd99a17fa56fb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086bd7dcdefd99a17fa56fb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 13:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086c4d5f702d200adcc8a05--gamut-preview.netlify.app>https://6086c4d5f702d200adcc8a05--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086c4d5f702d200adcc8a05>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 13:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.6-alpha.65aa96.0<br/>@codecademy/gamut-kit@0.3.48-alpha.65aa96.0<br/>@codecademy/gamut-labs@14.3.2-alpha.65aa96.0<br/>@codecademy/gamut-styles@9.5.7-alpha.65aa96.0<br/>@codecademy/gamut-tests@2.3.18-alpha.65aa96.0<br/>@codecademy/gamut@32.2.2-alpha.65aa96.0<br/>@codecademy/konamimojisplosion@0.2.18-alpha.65aa96.0<br/>@codecademy/markdown-overrides@0.5.30-alpha.65aa96.0<br/>@codecademy/styleguide@36.3.2-alpha.65aa96.0<br/>@codecademy/variance@0.9.1-alpha.65aa96.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 13:52 UTC, merged