feat: Add PageSection molecule
Codecademy/client-modules pull request #1632
Opened 2021-04-15 18:06 UTC by ZackMFleischman

### Overview

As part of [EGG-968](https://codecademy.atlassian.net/browse/EGG-968), I'm creating this abstract `PageSection` component to use throughout the Profile page and later to be used in the dashboard as well. 

I've added some stories to Storybook, so you should be able to see it by searching for `PageSection`. 

I've built it to handle the use-case in the main dashboard as well as everything we'll need for the Profile page:
![image](https://user-images.githubusercontent.com/4298857/114916071-3950e900-9dd9-11eb-9989-34bf525b7884.png)
![image](https://user-images.githubusercontent.com/4298857/114916404-99478f80-9dd9-11eb-8de0-6a03830f32cc.png)

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/PG0kVYDIuLk3hE566beZUV/Profiles-Concept-Refinement?node-id=337%3A3435
- [x] Related to JIRA ticket: [EGG-968](https://codecademy.atlassian.net/browse/EGG-968)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-15 18:10 UTC, ZackMFleischman commented on packages/gamut/src/Button/TextButton.tsx
> +  React.ComponentProps<typeof TextButtonOuter>;
I had thought I needed this before, and was able to actually refactor it out. Before that though I had already exposed the type. If you don't think the `TextButtonProps` is helpful to export I can revert this change.

2021-04-15 18:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.28-alpha.00d5a8.0<br/>@codecademy/gamut-labs@13.5.5-alpha.00d5a8.0<br/>@codecademy/gamut@31.0.2-alpha.00d5a8.0<br/>@codecademy/styleguide@35.0.2-alpha.00d5a8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-15 18:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607883eca8875e8958c57a82--gamut-preview.netlify.app>https://607883eca8875e8958c57a82--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607883eca8875e8958c57a82>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-15 22:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6078c0eda05776ab7c39dc4f--gamut-preview.netlify.app>https://6078c0eda05776ab7c39dc4f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6078c0eda05776ab7c39dc4f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-15 22:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.28-alpha.8a4ba4.0<br/>@codecademy/gamut-labs@13.5.5-alpha.8a4ba4.0<br/>@codecademy/gamut@31.0.2-alpha.8a4ba4.0<br/>@codecademy/styleguide@35.0.2-alpha.8a4ba4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-15 22:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.29-alpha.c279ca.0<br/>@codecademy/gamut-labs@13.5.6-alpha.c279ca.0<br/>@codecademy/gamut@31.0.2-alpha.c279ca.0<br/>@codecademy/styleguide@35.0.3-alpha.c279ca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-15 22:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6078c45830e8a1d60a0c1083--gamut-preview.netlify.app>https://6078c45830e8a1d60a0c1083--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6078c45830e8a1d60a0c1083>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-18 18:28 UTC, codecaaron approved these changes

2021-04-18 18:28 UTC, codecaaron commented on packages/gamut/src/Button/TextButton.tsx
> +  React.ComponentProps<typeof TextButtonOuter>;
This is helpful!  Let's keep it in

2021-04-18 18:28 UTC, codecaaron commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +  text: string;
This might make sense to keep as `ReactNode`, as I believe there are cases where these need to have icons.

2021-04-18 18:28 UTC, codecaaron commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +      {maybeRenderHeaderSecondaryButton()}
We don't really have a styleguide for this conditional rendering, but was just curious as to your preference between:
```tsx
{headerSecondaryButton && renderHeaderSecondaryButton()}
// vs
{maybeRenderHeaderSecondaryButton()}
```

2021-04-19 13:02 UTC, JoshuaKGoldberg requested changes
Looks good and I love the drive to Gamut-ize so much of the site!

Unit tests please? 😊

2021-04-19 13:03 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/PageSection.stories.mdx
> +    subtitle: `An abstract Page Section with a title and optional header and footer buttons`,
Could you talk a little bit somewhere in this docs page about where/when you'd use this? Are there any guidelines we should know about?

2021-04-19 15:39 UTC, ZackMFleischman commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +      {maybeRenderHeaderSecondaryButton()}
No terribly strong feelings towards either. I have a small preference towards using the latter as it supports cases where the conditional isn't a single flag, and I've worked in a codebase before that established it as an agreed upon convention and it worked nicely. It's one of those things where I figure I'll submit code with it and see what people have to say about it haha.

2021-04-19 15:40 UTC, ZackMFleischman commented on packages/styleguide/stories/Molecules/PageSection.stories.mdx
> +    subtitle: `An abstract Page Section with a title and optional header and footer buttons`,
Good call 👍

2021-04-19 15:42 UTC, ZackMFleischman commented on packages/gamut/src/Button/TextButton.tsx
> +  React.ComponentProps<typeof TextButtonOuter>;
👍

2021-04-19 15:51 UTC, ZackMFleischman commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +  text: string;
@codecaaron what do you think about supporting ReactNode as an escape hatch type, but since the 90% use-case will just use TextButtons without the default styling, we can encourage consumers to stick to the design paradigm by just passing the basics? 

Something like:
```
type TextButtonMinimumProps = {
    text: string;
    href?: string;
    onClick?: () => void;
};

type SectionButton = TextButtonMinimumProps | ReactNode;

const isSectionButtonAReactNode(button: SectionButton) button is ReactNode {
  return (button as TextButtonMinimumProps).text === undefined;
}
```

2021-04-19 18:34 UTC, sooinc commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +  const maybeRenderHeaderButton = () => {
terrible with names so definitely just a suggestion, but what do you think about `optionalHeaderButton` or `renderOptionalHeaderButton` to be a bit explicit?

2021-04-19 21:33 UTC, ZackMFleischman commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +  const maybeRenderHeaderButton = () => {
So I actually find those suggestions to be a bit more ambiguous. 
`optionalHeaderButton` to me feels like a variable representing the object, not a method that does something.
`renderOptionalHeaderButton` is a bit better, but I would expect this method to _always_ render an optional header button (that is to say, I wouldn't expect it to conditionally render the button).

If you feel strongly about changing the name, why don't we chat through it offline?

2021-04-19 23:16 UTC, sooinc commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +  const maybeRenderHeaderButton = () => {
No that makes sense! I'm not feeling too strongly about changing the name. I'm realizing that if we went the route of having the conditional check outside the method `headerSecondaryButton && renderHeaderSecondaryButton()` then my suggestions would've made more sense 😅

But I'm with you on the way we have it in a function as it can support multiple conditions (if that be the case in the future).

2021-04-19 23:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.29-alpha.1e1acd.0<br/>@codecademy/gamut-labs@13.5.6-alpha.1e1acd.0<br/>@codecademy/gamut@31.0.2-alpha.1e1acd.0<br/>@codecademy/styleguide@35.0.3-alpha.1e1acd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 23:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607e11e750afd118325dd3a7--gamut-preview.netlify.app>https://607e11e750afd118325dd3a7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607e11e750afd118325dd3a7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 23:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.29-alpha.d55955.0<br/>@codecademy/gamut-labs@13.5.6-alpha.d55955.0<br/>@codecademy/gamut@31.0.2-alpha.d55955.0<br/>@codecademy/styleguide@35.0.3-alpha.d55955.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 23:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607e143c5a1388135a0c2531--gamut-preview.netlify.app>https://607e143c5a1388135a0c2531--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607e143c5a1388135a0c2531>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 00:48 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +  text: string;
Or maybe just an `icon` prop, as an optional...

2021-04-20 15:36 UTC, JoshuaKGoldberg requested changes
Description looks great, thank you!

Just requesting changes on the testing thing.

2021-04-20 15:36 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/PageSection/__tests__/PageSection-test.tsx
> +  setupRtl(PageSection, { title: 'Default Section Title', ...props })();
This code is trying very hard to recreate the exact functionality of the library already 😛 

```suggestion
import { PageSection } from '..';

const renderView = setupRtl(PageSection, {
  title: 'Default Section Title',
});
```

2021-04-20 15:36 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/PageSection/__tests__/PageSection-test.tsx
> +  setupRtl(PageSection, { title: 'Default Section Title', ...props })();
Also, you don't want to use `render(...)` -> `screen...` on their own. Soon components will all use theming that breaks without the test provider set up in `@codecademy/gamut-tests`.

2021-04-20 18:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.359624.0<br/>@codecademy/gamut-labs@14.0.1-alpha.359624.0<br/>@codecademy/gamut@32.0.1-alpha.359624.0<br/>@codecademy/styleguide@36.0.1-alpha.359624.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 18:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f211f44ce3f11fcd763df--gamut-preview.netlify.app>https://607f211f44ce3f11fcd763df--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f211f44ce3f11fcd763df>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 18:57 UTC, ZackMFleischman commented on packages/gamut-labs/src/experimental/PageSection/__tests__/PageSection-test.tsx
> +  setupRtl(PageSection, { title: 'Default Section Title', ...props })();
Roger that. I'll stick to using `setupRtl`. I think I was thrown off by wanting to nest stuff inside the body of my elements and it didn't occur to me to just pass in `children` directly in the props object of `setupRtl`.

Question though: should I avoid `screen` altogether and always make my queries directly on the rendered view?

2021-04-20 19:12 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/PageSection/__tests__/PageSection-test.tsx
> +  setupRtl(PageSection, { title: 'Default Section Title', ...props })();
Yeah that's the style we're going for. In theory `screen` may work but no guarantees it'll stick to that.

2021-04-20 19:15 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +      {maybeRenderHeaderSecondaryButton()}
Just putting a couple of cents forward... It's probably better to get consensus in a particular product team on this kind of low-priority but aesthetically-pleasing note.

We've generally trended towards code minimalism for a few good reasons:
* _less code -> good_
* Adding more functions makes for harder TypeScript inferences

2021-04-20 19:17 UTC, JoshuaKGoldberg approved these changes
Glorious. Thanks for the initiative!!

2021-04-21 14:05 UTC, sooinc approved these changes
LGTM! thanks for building this! also for teaching me the `is` keyword lol

2021-04-21 18:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.40-alpha.107dba.0<br/>@codecademy/gamut-labs@14.1.1-alpha.107dba.0<br/>@codecademy/gamut@32.0.1-alpha.107dba.0<br/>@codecademy/styleguide@36.1.1-alpha.107dba.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 18:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608075ddbd372745d705fecc--gamut-preview.netlify.app>https://608075ddbd372745d705fecc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608075ddbd372745d705fecc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 20:00 UTC, merged

2021-04-21 22:40 UTC, sooinc commented on packages/gamut-labs/src/experimental/PageSection/index.tsx
> +      {maybeRenderHeaderSecondaryButton()}
sorry just saw this! but that's a good idea, Josh. @ZackMFleischman maybe this is something we can discuss in egg sync or retro to get team consensus!