chore(Labs): Flattens labs file structure [GM-201]
Codecademy/client-modules pull request #1636
Opened 2021-04-18 19:11 UTC by codecaaron

### Overview

Removes the distinction between brand / experimental to make this a blanket component library.

- Flattens labs to a single level structure `brand` and `experimental`.  
- Flattens other index files.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: GM-201
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-18 19:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.29-alpha.69de15.0<br/>@codecademy/gamut-labs@13.5.6-alpha.69de15.0<br/>@codecademy/styleguide@35.0.3-alpha.69de15.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-18 20:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.29-alpha.33a1aa.0<br/>@codecademy/gamut-labs@13.5.6-alpha.33a1aa.0<br/>@codecademy/styleguide@35.0.3-alpha.33a1aa.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-18 20:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607c94bc20bfc4002a542e44--gamut-preview.netlify.app>https://607c94bc20bfc4002a542e44--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607c94bc20bfc4002a542e44>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 13:06 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/Title.tsx
> -      fontWeight="title"
Should this be in a separate PR?

2021-04-19 13:06 UTC, JoshuaKGoldberg requested changes
Unintended changes towards the end?

Also, maybe we should split labs into two packages?

2021-04-19 13:18 UTC, codecaaron commented on packages/gamut-labs/src/landingPage/Title.tsx
> -      fontWeight="title"
Heh yeah, undid any changes.  Guess I think I autosuggested my way into this :P

2021-04-19 13:19 UTC, JoshuaKGoldberg approved these changes
I think it makes sense to start the conversation soon about splitting packages, but until then this makes sense to me :+1:. Thanks!

2021-04-19 13:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.29-alpha.514e9e.0<br/>@codecademy/gamut-labs@13.5.6-alpha.514e9e.0<br/>@codecademy/styleguide@35.0.3-alpha.514e9e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 13:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607d85868a19395ffa2841d0--gamut-preview.netlify.app>https://607d85868a19395ffa2841d0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607d85868a19395ffa2841d0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 13:32 UTC, merged