feat(Logo): V2
Codecademy/client-modules pull request #1637
Opened 2021-04-18 21:58 UTC by codecaaron

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-18 22:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.29-alpha.571caa.0<br/>@codecademy/gamut-labs@13.5.6-alpha.571caa.0<br/>@codecademy/gamut@31.0.2-alpha.571caa.0<br/>@codecademy/styleguide@35.0.3-alpha.571caa.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-18 22:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607cadc0d842d09c2eecb92b--gamut-preview.netlify.app>https://607cadc0d842d09c2eecb92b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607cadc0d842d09c2eecb92b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 16:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.43fa61.0<br/>@codecademy/gamut-labs@14.4.1-alpha.43fa61.0<br/>@codecademy/gamut@32.3.1-alpha.43fa61.0<br/>@codecademy/styleguide@36.4.1-alpha.43fa61.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 16:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086eb4532d34e2ae4cf6214--gamut-preview.netlify.app>https://6086eb4532d34e2ae4cf6214--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086eb4532d34e2ae4cf6214>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 17:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.8ff117.0<br/>@codecademy/gamut-labs@14.4.1-alpha.8ff117.0<br/>@codecademy/gamut@32.3.1-alpha.8ff117.0<br/>@codecademy/styleguide@36.4.1-alpha.8ff117.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 17:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086f599996c643217d6d276--gamut-preview.netlify.app>https://6086f599996c643217d6d276--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086f599996c643217d6d276>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 17:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.514943.0<br/>@codecademy/gamut-labs@14.4.1-alpha.514943.0<br/>@codecademy/gamut@32.3.1-alpha.514943.0<br/>@codecademy/styleguide@36.4.1-alpha.514943.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 17:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086fa937e10874209489816--gamut-preview.netlify.app>https://6086fa937e10874209489816--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086fa937e10874209489816>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 17:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.e4a4a8.0<br/>@codecademy/gamut-labs@14.4.1-alpha.e4a4a8.0<br/>@codecademy/gamut@32.3.1-alpha.e4a4a8.0<br/>@codecademy/styleguide@36.4.1-alpha.e4a4a8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 17:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086febcad07d5008ef67e97--gamut-preview.netlify.app>https://6086febcad07d5008ef67e97--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086febcad07d5008ef67e97>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 18:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.7-alpha.1d53f4.0<br/>@codecademy/gamut-kit@0.3.49-alpha.1d53f4.0<br/>@codecademy/gamut-labs@14.4.1-alpha.1d53f4.0<br/>@codecademy/gamut-styles@9.6.1-alpha.1d53f4.0<br/>@codecademy/gamut-tests@2.3.19-alpha.1d53f4.0<br/>@codecademy/gamut@32.3.1-alpha.1d53f4.0<br/>@codecademy/konamimojisplosion@0.2.19-alpha.1d53f4.0<br/>@codecademy/markdown-overrides@0.5.31-alpha.1d53f4.0<br/>@codecademy/styleguide@36.4.1-alpha.1d53f4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 18:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608703e6c658a300bc49a18a--gamut-preview.netlify.app>https://608703e6c658a300bc49a18a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608703e6c658a300bc49a18a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 19:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.7-alpha.4382fe.0<br/>@codecademy/gamut-kit@0.3.49-alpha.4382fe.0<br/>@codecademy/gamut-labs@14.4.1-alpha.4382fe.0<br/>@codecademy/gamut-styles@9.6.1-alpha.4382fe.0<br/>@codecademy/gamut-tests@2.3.19-alpha.4382fe.0<br/>@codecademy/gamut@32.3.1-alpha.4382fe.0<br/>@codecademy/konamimojisplosion@0.2.19-alpha.4382fe.0<br/>@codecademy/markdown-overrides@0.5.31-alpha.4382fe.0<br/>@codecademy/styleguide@36.4.1-alpha.4382fe.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 19:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60870e8eb685fc0eb3095263--gamut-preview.netlify.app>https://60870e8eb685fc0eb3095263--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60870e8eb685fc0eb3095263>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 21:49 UTC, dreamwasp commented on packages/gamut/src/Logo/index.tsx
> +const Svg = styled('svg', styledConfig)<Omit<LogoProps, 'variant'>>(
cool

2021-04-27 13:39 UTC, dreamwasp approved these changes
would like to see a integration branch PR cos i think these old Logos are still used in a couple places, but otherwise ✅

2021-04-27 16:35 UTC, JoshuaKGoldberg requested changes
Something is unhappy with the ProLabel story:

![Screenshot of a blank ProLabel](https://user-images.githubusercontent.com/3335181/116279067-1a494400-a755-11eb-99ec-35f4533d0359.png)

2021-04-27 17:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.7-alpha.a9fd1c.0<br/>@codecademy/gamut-kit@0.3.49-alpha.a9fd1c.0<br/>@codecademy/gamut-labs@14.4.1-alpha.a9fd1c.0<br/>@codecademy/gamut-styles@9.6.1-alpha.a9fd1c.0<br/>@codecademy/gamut-tests@2.3.19-alpha.a9fd1c.0<br/>@codecademy/gamut@32.3.1-alpha.a9fd1c.0<br/>@codecademy/konamimojisplosion@0.2.19-alpha.a9fd1c.0<br/>@codecademy/markdown-overrides@0.5.31-alpha.a9fd1c.0<br/>@codecademy/styleguide@36.4.1-alpha.a9fd1c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 17:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60884e40d479690090ab33ee--gamut-preview.netlify.app>https://60884e40d479690090ab33ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60884e40d479690090ab33ee>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 18:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.53-alpha.41dcc3.0<br/>@codecademy/gamut-labs@14.4.5-alpha.41dcc3.0<br/>@codecademy/gamut@32.4.1-alpha.41dcc3.0<br/>@codecademy/styleguide@36.5.1-alpha.41dcc3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 18:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.53-alpha.fe7bb3.0<br/>@codecademy/gamut-labs@14.4.5-alpha.fe7bb3.0<br/>@codecademy/gamut@32.4.1-alpha.fe7bb3.0<br/>@codecademy/styleguide@36.5.1-alpha.fe7bb3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 18:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60885e338ee052008b6b7858--gamut-preview.netlify.app>https://60885e338ee052008b6b7858--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60885e338ee052008b6b7858>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 19:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.53-alpha.808e89.0<br/>@codecademy/gamut-labs@14.4.5-alpha.808e89.0<br/>@codecademy/gamut@32.4.1-alpha.808e89.0<br/>@codecademy/styleguide@36.5.1-alpha.808e89.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 19:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608863e18dcf6100a2b47bab--gamut-preview.netlify.app>https://608863e18dcf6100a2b47bab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608863e18dcf6100a2b47bab>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 19:50 UTC, codecaaron commented
> Something is unhappy with the ProLabel story:
> 
> ![Screenshot of a blank ProLabel](https://user-images.githubusercontent.com/3335181/116279067-1a494400-a755-11eb-99ec-35f4533d0359.png)

Ah whoops this should be fixed!  https://github.com/Codecademy/client-modules/pull/1637/commits/a9fd1cb442aaf951e500dcaedcd36ca5ea67448e#diff-4d2f1d3cc2b180117b7beeedf7d1d5308720bbf2476f9864c0f09a83e96e01b7L13 Old habits :P

2021-04-28 15:34 UTC, dreamwasp approved these changes

2021-04-28 16:53 UTC, JoshuaKGoldberg requested changes
LGTM overall (yay modes!) but can we separate into logos? I really like the standard we've been setting around having individual components for unique cases...

2021-04-28 16:53 UTC, JoshuaKGoldberg commented on packages/gamut/src/Logo/index.tsx
> +      {variant !== 'mini' && (
Nit: maybe use a single ternary, instead of two tenaries with `&&`?

2021-04-29 14:50 UTC, codecaaron commented on packages/gamut/src/Logo/index.tsx
> +      {variant !== 'mini' && (
> LGTM overall (yay modes!) but can we separate into logos? I really like the standard we've been setting around having individual components for unique cases...

I tend to agree RE: separate components for static usages like patterns or icons, buuuut I think the the issue is that anywhere they are used we would likely need to reimplement what we lost to internal switching to `pro` `default` and sometimes `mini` in the component where we use them.

2021-04-29 14:54 UTC, codecaaron commented on packages/gamut/src/Logo/index.tsx
> +      {variant !== 'mini' && (
Do you think that there are enough cases where we won't be implementing this everywhere?

```tsx
import { CodecademyProLogo, CodecademyLogo } from '@codecademy/gamut';

if (isPro) {
  return <CodecademyProLogo />
} else {
 return <CodecademyLogo />
}
```

2021-04-29 14:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.60-alpha.8df6a8.0<br/>@codecademy/gamut-labs@15.1.3-alpha.8df6a8.0<br/>@codecademy/gamut@32.4.4-alpha.8df6a8.0<br/>@codecademy/styleguide@36.6.3-alpha.8df6a8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-29 14:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608ac9c92ac77600935dd67a--gamut-preview.netlify.app>https://608ac9c92ac77600935dd67a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608ac9c92ac77600935dd67a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-29 16:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.60-alpha.a86668.0<br/>@codecademy/gamut-labs@15.1.3-alpha.a86668.0<br/>@codecademy/gamut@32.4.4-alpha.a86668.0<br/>@codecademy/styleguide@36.6.3-alpha.a86668.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-29 16:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608ae37c30093131832a109c--gamut-preview.netlify.app>https://608ae37c30093131832a109c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608ae37c30093131832a109c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-29 16:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.60-alpha.fd47da.0<br/>@codecademy/gamut-labs@15.1.3-alpha.fd47da.0<br/>@codecademy/gamut@32.4.4-alpha.fd47da.0<br/>@codecademy/styleguide@36.6.3-alpha.fd47da.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-29 17:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608ae614b9b24125d8ced92b--gamut-preview.netlify.app>https://608ae614b9b24125d8ced92b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608ae614b9b24125d8ced92b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-29 18:02 UTC, JoshuaKGoldberg approved these changes
_perfection_

2021-04-29 19:53 UTC, merged