docs: Add Dynamic tables for System Props
Codecademy/client-modules pull request #1641
Opened 2021-04-19 12:16 UTC by codecaaron

### Overview

* Adds linked tables for system props

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-19 12:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.3-alpha.3fae8f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 12:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607d76be39599b4b01421c21--gamut-preview.netlify.app>https://607d76be39599b4b01421c21--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607d76be39599b4b01421c21>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 18:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.8f3158.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 18:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.5ed8e6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-19 18:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607dca832479a800a04f878c--gamut-preview.netlify.app>https://607dca832479a800a04f878c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607dca832479a800a04f878c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 20:48 UTC, JoshuaKGoldberg requested changes
A great start 🚀

2021-04-19 20:48 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Props.stories.mdx
> +# Layout
Reading through this page, I'm finding it hard to really connect what it all means -> how it's used. How about some code examples?

2021-04-19 20:48 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
> +Responsive configurations are two basic shape a map of breakpoint aliases / values or an array of values:
Maybe I'm just projecting here, but IMO people generally prefer an easy-to-read example to come _before_ the full technical descriptor when the technical descriptor is kinda misdirect-y TypeScript syntax by nature. Can you put the full description last, maybe?

2021-04-22 14:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.ae1c2e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 14:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60818413ac107a55be077d5f--gamut-preview.netlify.app>https://60818413ac107a55be077d5f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60818413ac107a55be077d5f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 14:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.a792c9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 14:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60818a989fb6095954c04481--gamut-preview.netlify.app>https://60818a989fb6095954c04481--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60818a989fb6095954c04481>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 14:48 UTC, rogervera reviewed
Feedback from `packages/styleguide/stories/Foundations/System/Props.stories.mdx` and `packages/styleguide/stories/Foundations/System/Props.stories.mdx` so far after https://github.com/Codecademy/client-modules/pull/1641/commits/a792c9c1e2305ff39d4360597aba00ebc4dec011.

2021-04-22 14:48 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/Props.stories.mdx
> +Props that affect positioning contexts.
Nit:
Idea! We should link to MDN for this (and others where applicable).

2021-04-22 14:48 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/Props.stories.mdx
> +Shadow props.
SUPER Nit: To end with `.` or not to end with `.`?

2021-04-22 14:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.15305f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 14:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60818d9b6ea64e5baef88e7c--gamut-preview.netlify.app>https://60818d9b6ea64e5baef88e7c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60818d9b6ea64e5baef88e7c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 14:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.cbd349.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 16:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.cbbc45.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 16:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6081a7f07aa88f009e6e992e--gamut-preview.netlify.app>https://6081a7f07aa88f009e6e992e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6081a7f07aa88f009e6e992e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 19:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.5790ec.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 19:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6081d3f979494313e0d32462--gamut-preview.netlify.app>https://6081d3f979494313e0d32462--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6081d3f979494313e0d32462>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 20:22 UTC, JoshuaKGoldberg approved these changes
Just nitpicks from me, very nice! I'm starting to have a hard time being objective on these docs so someone else should probably take the reviewing home 😄

2021-04-22 20:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +However there are many cases where we want to combine or add new props to a single function to increase performance and guard against possible property collisions. To help with this `variance` comes
I think you can streamline this intro a bit to reduce duplicated information:

1. Delete the first sentence
2. Move any information from that first sentence that isn't already in the last once to after the last one

Thoughts?

2021-04-22 20:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +<Grid width="100%" justifyContent="center" />; // typeerror justifyContent is not a prop
```suggestion
<Grid width="100%" justifyContent="center" />; // TypeError: justifyContent is not a prop
```

2021-04-22 20:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +<Grid width="100%" justifyContent="center" />; // works but no manual config :)
```suggestion
<Grid width="100%" justifyContent="center" />; // works with no manual config :)
```

2021-04-22 20:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +When emotion serializes styles it does not attempt to merge styles and allows all styles to exist and be progressively overriden. This can create issues with styles that might conflict between scopes
```suggestion
When Emotion serializes styles it does not attempt to merge styles and allows all styles to exist and be progressively overriden. This can create issues with styles that might conflict between scopes.
```

2021-04-22 20:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +This outputs several media queries
```suggestion
This outputs several media queries:
```

2021-04-22 22:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.b9ee1c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 22:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6081fc25f6671000c3bd183f--gamut-preview.netlify.app>https://6081fc25f6671000c3bd183f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6081fc25f6671000c3bd183f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 22:52 UTC, codecaaron commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +However there are many cases where we want to combine or add new props to a single function to increase performance and guard against possible property collisions. To help with this `variance` comes
Good call lots of duplication.  Took another pass.

2021-04-22 22:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.d9ca59.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 22:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6081ff6342b5ab1307f86e7e--gamut-preview.netlify.app>https://6081ff6342b5ab1307f86e7e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6081ff6342b5ab1307f86e7e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 23:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@35.0.7-alpha.2dc735.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 23:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608202c1464885009ce0966d--gamut-preview.netlify.app>https://608202c1464885009ce0966d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608202c1464885009ce0966d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 10:25 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +Using `variance.compose()` will take any number of system prop functions and merge them left to right (the last argument takes precedence if props conflict) and returns a new prop function with the i
Breaking this up into two sentences. 1) Input, 2) Output
```suggestion
Using `variance.compose()` will take any number of system prop functions and merge them left to right (the last argument takes precedence if props conflict). `variance.compose()` returns a new prop function with the intersection of these pieces.
```

2021-04-23 10:27 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +When Emotion serializes styles it does not attempt to merge styles and allows all styles to exist and be progressively overriden. This can create issues with styles that might conflict between scopes
```suggestion
When Emotion serializes styles, it does not attempt to merge styles. Instead, it allows all styles to exist and be progressively overridden. This can create issues with styles that might conflict between scopes.
```

2021-04-23 10:28 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +With uncombined props this can produce multiple sets of media queries that are not ordered, or in cases where 2 style functions template the same property unmerged styles.
```suggestion
With uncombined props, this can produce multiple sets of media queries that are not ordered, or in cases where 2 style functions template the same property, unmerged styles.
```

2021-04-23 10:31 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +However if we've composed these functions our scopes will be combined preventing unexpected behavior.
```suggestion
However, if we've composed these functions, our scopes will be combined and prevent unexpected behavior.
```

2021-04-23 11:24 UTC, rogervera requested changes
Nice. The changes since my last review on the overall PR improved comprehension and clarity IMO. I think it's almost there! The blocker for me is:
> the wonky links in PropsTable that don't route to the intended section.

Currently, the UX is clicking a link that doesn't go where you think it would go to. Arg!

I left several small edits on grammar/spelling. 
An explanation of Scale and Transform at the top of the Props docs (before we see them as columns) would be _really_  nice.

2021-04-23 11:24 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
> +Here are some examples of what the expected out put will be for certain configurations:
```suggestion
Here are some examples of what the expected output will be for certain configurations:
```

2021-04-23 11:24 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
> +
Thanks for adding.

2021-04-23 11:24 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/tables.tsx
> +    <LinkTo id={`foundations-theme--${kebabCase(scale)}`}>{scale}</LinkTo>
This isn't working on the latest preview. For the Props page, the links here aren't routing to the actual section of `https://608202c1464885009ce0966d--gamut-preview.netlify.app/storybook/?path=/docs/foundations-theme--spacing#spacing`.
Same for the other links from the output of `getPropsRow`


https://user-images.githubusercontent.com/17210163/115863436-55820500-a42d-11eb-8958-660cea29d79f.mov



https://608202c1464885009ce0966d--gamut-preview.netlify.app/storybook/?path=/docs/foundations-system-props--layout

2021-04-23 12:11 UTC, codecaaron commented on packages/styleguide/stories/Foundations/System/tables.tsx
> +    <LinkTo id={`foundations-theme--${kebabCase(scale)}`}>{scale}</LinkTo>
If you try using the side bar you'll have the same problem :/ 

I'm gonna need to do this in a separate PR I think.  It's not a problem with the links per se but Storybook Docs stuff that i might have messed up when I replaced the docs page.

2021-04-23 12:18 UTC, rogervera commented on packages/styleguide/stories/Foundations/System/tables.tsx
> +    <LinkTo id={`foundations-theme--${kebabCase(scale)}`}>{scale}</LinkTo>
Ah, damn. Then a separate PR SGTM! Happy to review when it gets there.

2021-04-23 12:18 UTC, rogervera approved these changes

2021-04-23 16:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@36.2.4-alpha.5ee303.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-23 16:18 UTC, merged

2021-04-23 16:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6082f383e8fe8f789aa70937--gamut-preview.netlify.app>https://6082f383e8fe8f789aa70937--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6082f383e8fe8f789aa70937>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 15:13 UTC, LinKCoding reviewed
Mostly added notes about typos and consistent styling. I opted not to comment too much about we/you esp towards the end. 

Some questions I'm left wondering about:
* Are there more opportunities to link to specific sections (i.e. creating a table of contents) 
* How are these docs maintained? Are people encouraged to make PRs to this story?
* Are these specific files that could be good examples?

2021-04-27 15:13 UTC, LinKCoding commented on packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
> +Since both syntaxes perform the same task it can be unclear which syntax is preferrable to another, heres some best practices for picking the syntax that will be most readable.
heres => here are

2021-04-27 15:13 UTC, LinKCoding commented on packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
> +#### When to use object syntax
title case entire title?

2021-04-27 15:13 UTC, LinKCoding commented on packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
> +#### When to use the array syntax
noting title case

2021-04-27 15:13 UTC, LinKCoding commented on packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
> +2. When default values matter - There are some cases where not having a base style set to a property will cause uninteded behavior, object lets you omit these without being explicit potentially causi
object lets you => objects let you

2021-04-27 15:13 UTC, LinKCoding commented on packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
> +// this will not as we must explicity declare the breakpoint value as undefined
"this will not ..." maybe frame it as "this syntax is safe because ..." or be more explicit about what this code will not do

2021-04-27 15:13 UTC, LinKCoding commented on packages/styleguide/stories/Foundations/System/Compose.stories.mdx
> +There are a few benefits to composition:
This organization seems a little odd to be since the colon denotes what immediately follows as benefits. so the reader might just see Predictable CSS. 

Maybe: "There are few benefits to composition, such as having [Predictable CSS](#predictable-css) and [Type Simplification](#type-simplification)" <- not sure if this linking actually works lol