docs: Add `variant` and `css` docs for variance
Codecademy/client-modules pull request #1645
Opened 2021-04-19 17:39 UTC by codecaaron

### Overview

* Adds basic documentation for the `variant` and `css` documentation for variance API in place of original gamut-styles documention.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-19 17:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607dc2661468c11128928a1b--gamut-preview.netlify.app>https://607dc2661468c11128928a1b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607dc2661468c11128928a1b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-19 21:11 UTC, dreamwasp approved these changes
🎉

2021-04-20 14:41 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +A standalone theme aware method that accepts and object of system props and returns the correct style object. Is cached after being called with theme once, preventing more expensive calculations.
```suggestion
A standalone theme aware method that accepts an object of system props and returns the correct style object. Is cached after being called with theme once, preventing more expensive calculations.
```

2021-04-20 14:52 UTC, JoshuaKGoldberg requested changes
A few things to think about - I think some of them are relevant for the last third of docs too?

2021-04-20 14:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +A standalone theme aware method that accepts and object of system props and returns the correct style object. Is cached after being called with theme once, preventing more expensive calculations.
```suggestion
A standalone theme aware method that accepts an object of system props and returns the correct style object. It is cached after being called with theme once, preventing more expensive calculations.
```

2021-04-20 14:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +- `prop`: The prop key that variants should be. Defaults to `variant`
Nit: every other item in this list ends with one, heh

```suggestion
- `prop`: The prop key that variants should be. Defaults to `variant`.
```

2021-04-20 14:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +const Anchor = styled.a(variant({
Nittiest of the nites: `css({` was on a new line above, but this one is on the same line? Maybe standardize to make it easier to skim through the docs?

2021-04-20 14:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +});
Can we file tickets somewhere about these two parsing bugs? lol

![Screenshot of a different font for the a link and blue color for interface](https://user-images.githubusercontent.com/3335181/115415919-4e58be00-a1c5-11eb-88ed-56e6065b2d62.png)

2021-04-20 14:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +This change lets us configure anything that is likely to be non dynamic but required for a complete and discrete style. The typings for both `variant` and `css` accept all properties that are not pre
> This change lets us configure anything that is likely to be non dynamic but required for a complete and discrete style.

I don't understand what this means 😕 ... could you maybe rephrase in this thread so we can wordsmith it?

2021-04-20 14:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +         listStyleType: "\1F44D",  // not
I don't think it's clear from reading through this that `// not` means TypeScript won't allow it (or what "will not accept values" means). Maybe include an abridged TypeScript error in the comment?

2021-04-20 14:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +When generating the styles the function will ignore the all props not specified by our configuration and simply pass them through to the result CSSObject.
Can you show an example?

Also, personal pet peeve, nothing is ever "simple" - so words like "simply" shouldn't be in docs IMO.

2021-04-20 15:04 UTC, codecaaron commented on packages/styleguide/stories/Foundations/System/Variants.stories.mdx
> +         listStyleType: "\1F44D",  // not
Heh this I think is just a typo, may have deleted it accidentally.

2021-04-21 11:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.10.1-alpha.4cced8.0<br/>@codecademy/gamut-kit@0.3.33-alpha.4cced8.0<br/>@codecademy/gamut-labs@13.5.10-alpha.4cced8.0<br/>@codecademy/gamut-styles@9.5.2-alpha.4cced8.0<br/>@codecademy/gamut-tests@2.3.13-alpha.4cced8.0<br/>@codecademy/gamut@31.0.4-alpha.4cced8.0<br/>@codecademy/konamimojisplosion@0.2.13-alpha.4cced8.0<br/>@codecademy/markdown-overrides@0.5.25-alpha.4cced8.0<br/>@codecademy/styleguide@35.0.7-alpha.4cced8.0<br/>@codecademy/variance@0.9.1-alpha.4cced8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 11:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60800f009af319f40d4c8d5d--gamut-preview.netlify.app>https://60800f009af319f40d4c8d5d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60800f009af319f40d4c8d5d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-26 11:12 UTC, codecaaron commented
Closing in favor of https://github.com/Codecademy/client-modules/pull/1783

2021-05-26 11:12 UTC, closed without merging