feat(Pattern): add new Patterns and rename some old ones
Codecademy/client-modules pull request #1646
Opened 2021-04-19 18:24 UTC by natalieweesh

### Overview

add some new patterns and rename dots to checker and rename diagonalStripes to diagonalStripeB

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: EGG-1085
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-19 20:00 UTC, JoshuaKGoldberg commented on packages/gamut/src/Pattern/index.tsx
> +  | 'stripeDense';
lol why do we have so many of these...

2021-04-19 20:05 UTC, JoshuaKGoldberg requested changes
If we _do_ have dozens of different patterns, let's split them up into separate components the way icons and illustrations are. We're getting to the point where that'd be both more scalable and better for performance _(such a huge file to always import!)_

2021-04-19 20:18 UTC, JoshuaKGoldberg commented on packages/gamut/src/Pattern/index.tsx
> +  | 'stripeDense';
asking on Slack: https://codecademy.slack.com/archives/CTVEHH2PP/p1618862487000400

2021-04-27 13:23 UTC, natalieweesh commented
closing in favor of #1654 which creates a new package for patterns instead

2021-04-27 13:23 UTC, closed without merging