refactor: add additional properties to userclickdata
Codecademy/client-modules pull request #1653
Opened 2021-04-20 18:56 UTC by sooinc

### Overview
Adds additional properties (`goal_setting` and `longterm_goal`) to user click data for goal setting.

See tracking doc for reference: https://docs.google.com/spreadsheets/d/1lWs2B2k3uFwvdnoRdyqsw4c2sK_-XZBl1Mdj_6P7mn0/edit#gid=0

- add additional properties (`goal_setting` and `longterm_goal`) to user click data for goal setting 

### PR Checklist
- [ ] Related to designs:
- [x] Related to JIRA ticket: EGG-1007
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-20 19:16 UTC, JoshuaKGoldberg approved these changes
Cool! Though I suspect you probably want a review from an @Codecademy/engagement peer more than us 😄

2021-04-20 19:17 UTC, sooinc commented
> Cool! Though I suspect you probably want a review from an @Codecademy/engagement peer more than us 😄

Good point - adding @sylvanasantos  :)

2021-04-21 14:28 UTC, hmafzal commented on packages/tracking/src/types.ts
> +  goal_setting?: string;
FYI, doing this actually adds additional columns to all user click events in our database and we should generally avoid doing it. It means we'll add NULL values to every user click event on this column, which over time slows down these tables. Although that's not necessarily clear from the comment on this type!

https://www.notion.so/codecademy/Guide-to-Event-Tracking-Schema-5d40b09a297743f7a30a2690208194c8#800bbf6cdf2e44de9823cd75bcc574e5

Instead we should try to use existing properties on this type. For example instead of adding new properties called `goal_setting` or `longterm_goal` that only make sense for 1 particular user click type, could we use the existing properties `action` for `goal_setting`, and rename `longterm_goal` to `selection` so it can be more generic?

2021-04-21 14:29 UTC, hmafzal requested changes
Requesting changes on using existing properties instead. We can update the tracking schema to reflect what properties we'll actually end up using!

2021-04-21 14:38 UTC, hmafzal commented on packages/tracking/src/types.ts
>    course_progress?: number;
Maybe we should update the comments on `UserClickData` and `UserVisitData` to make that clearer?

```
/**
 * Data sent to user click event table
 * NOTE: avoid adding additional properties to these objects
 * Instead, reuse existing properties, or make any additional properties generic.
 * https://www.notion.so/codecademy/Guide-to-Event-Tracking-Schema-5d40b09a297743f7a30a2690208194c8#800bbf6cdf2e44de9823cd75bcc574e5
 */
```

2021-04-21 14:46 UTC, sooinc commented on packages/tracking/src/types.ts
> +  goal_setting?: string;
Got it, thanks for sharing the doc! And yes will update to use existing / make more generic.

2021-04-21 14:47 UTC, sooinc commented on packages/tracking/src/types.ts
>    course_progress?: number;
Agree, I think that would be helpful!

2021-04-21 15:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.5.3-alpha.0e7d94.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 15:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608048d241909f0fd1a594f7--gamut-preview.netlify.app>https://608048d241909f0fd1a594f7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608048d241909f0fd1a594f7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 15:49 UTC, sooinc commented
Synced again with Sylvana/Richie, and we'll not be adding new properties anymore to avoid cluttering the userClickData.

I still updated the comments though to help the next person.

2021-04-21 16:00 UTC, hmafzal approved these changes
LGTM, thanks for changing the comment! I also pushed an additional commit to separate out the optional "generic" properties from the specific "additional properties". Hopefully that helps make it clearer as well

2021-04-21 16:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.5.3-alpha.fd41f3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 16:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.5.3-alpha.f136d7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 16:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60804e0408f4b0129744e4a7--gamut-preview.netlify.app>https://60804e0408f4b0129744e4a7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60804e0408f4b0129744e4a7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 16:16 UTC, merged