feat!: add new gamut-patterns package
Codecademy/client-modules pull request #1654
Opened 2021-04-20 20:39 UTC by natalieweesh

### Overview

create a new gamut-patterns package for all the new patterns

also update current gamut components that use patterns (Dialog, Popover, ProgressBar)

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-21 13:44 UTC, natalieweesh commented on packages/gamut-patterns/src/helpers.tsx
> +export const getPattern = (name: string) => {
not sure if this is the best strategy, but added this function for use in components like Popover and ProgressBar where the component can be given a pattern name to decide which pattern to use

2021-04-21 13:47 UTC, natalieweesh commented
@JoshuaKGoldberg @codecaaron hoping to get some 👀 on this to see if i'm going in the right direction, before i start adding tests and polish, etc.

2021-04-21 15:19 UTC, JoshuaKGoldberg commented
@natalieweesh thanks for the early PR! Will look today! 🙌

2021-04-21 15:24 UTC, JoshuaKGoldberg commented on packages/gamut-patterns/src/CheckerDense.tsx
> +`;
Pretty much all these patterns have the same `Svg` declared at the top, with really similar viewbox/sizing attributes.. I was thinking it _might_ make sense to have these all more like `gamut-icons`, where you just check in a single asset file (here it'd be an `.svg`) and then the build system attaches the standard component+props on top of that.

All these patterns are squares of height 4, 8, or 16 in sizing in code. We could probably work around that...

I set up a meeting for us to hash this out tomorrow afternoon!

2021-04-27 13:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.4e592c.0<br/>@codecademy/gamut-labs@15.0.0-alpha.4e592c.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.4e592c.0<br/>@codecademy/gamut@33.0.0-alpha.4e592c.0<br/>@codecademy/styleguide@37.0.0-alpha.4e592c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 13:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088120872bc013f0220b163--gamut-preview.netlify.app>https://6088120872bc013f0220b163--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088120872bc013f0220b163>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 13:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.d6429d.0<br/>@codecademy/gamut-labs@15.0.0-alpha.d6429d.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.d6429d.0<br/>@codecademy/gamut@33.0.0-alpha.d6429d.0<br/>@codecademy/styleguide@37.0.0-alpha.d6429d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 13:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608816c5976dc64d6e5390bb--gamut-preview.netlify.app>https://608816c5976dc64d6e5390bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608816c5976dc64d6e5390bb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 14:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.955f90.0<br/>@codecademy/gamut-labs@15.0.0-alpha.955f90.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.955f90.0<br/>@codecademy/gamut@33.0.0-alpha.955f90.0<br/>@codecademy/styleguide@37.0.0-alpha.955f90.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 14:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608819976070655a160fc714--gamut-preview.netlify.app>https://608819976070655a160fc714--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608819976070655a160fc714>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 14:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.882aea.0<br/>@codecademy/gamut-labs@15.0.0-alpha.882aea.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.882aea.0<br/>@codecademy/gamut@33.0.0-alpha.882aea.0<br/>@codecademy/styleguide@37.0.0-alpha.882aea.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 14:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60881f4177283a4a8c21a30c--gamut-preview.netlify.app>https://60881f4177283a4a8c21a30c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60881f4177283a4a8c21a30c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 14:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.f654e8.0<br/>@codecademy/gamut-labs@15.0.0-alpha.f654e8.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.f654e8.0<br/>@codecademy/gamut@33.0.0-alpha.f654e8.0<br/>@codecademy/styleguide@37.0.0-alpha.f654e8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 14:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608820b60431bb589da07075--gamut-preview.netlify.app>https://608820b60431bb589da07075--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608820b60431bb589da07075>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 14:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.9f779f.0<br/>@codecademy/gamut-labs@15.0.0-alpha.9f779f.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.9f779f.0<br/>@codecademy/gamut@33.0.0-alpha.9f779f.0<br/>@codecademy/styleguide@37.0.0-alpha.9f779f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 14:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608825287f416e5619295f34--gamut-preview.netlify.app>https://608825287f416e5619295f34--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608825287f416e5619295f34>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 14:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.2929bd.0<br/>@codecademy/gamut-labs@15.0.0-alpha.2929bd.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.2929bd.0<br/>@codecademy/gamut@33.0.0-alpha.2929bd.0<br/>@codecademy/styleguide@37.0.0-alpha.2929bd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 15:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.7974d8.0<br/>@codecademy/gamut-labs@15.0.0-alpha.7974d8.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.7974d8.0<br/>@codecademy/gamut@33.0.0-alpha.7974d8.0<br/>@codecademy/styleguide@37.0.0-alpha.7974d8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 15:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088283dbc2af74c2da831cd--gamut-preview.netlify.app>https://6088283dbc2af74c2da831cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088283dbc2af74c2da831cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 15:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.5ee3c8.0<br/>@codecademy/gamut-labs@15.0.0-alpha.5ee3c8.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.5ee3c8.0<br/>@codecademy/gamut@33.0.0-alpha.5ee3c8.0<br/>@codecademy/styleguide@37.0.0-alpha.5ee3c8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 15:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60882a078a02f454e3a49c4f--gamut-preview.netlify.app>https://60882a078a02f454e3a49c4f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60882a078a02f454e3a49c4f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 15:21 UTC, natalieweesh commented
update:

tried using svgr similarly to how gamut-icons does, but it would not work for patterns because we can't really modify the svg at all, like adding the `<pattern>` inside of it, so ended up not going with the svgr method

instead, just followed the gamut-illustrations method, and added all the patterns, organized into folders with different densities

also got rid of the `<Box>` wrapping the svg, and instead used the system layout props, similarly to how the Logo and ProLabel do [here](https://github.com/Codecademy/client-modules/pull/1637)

2021-04-27 15:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.dd7526.0<br/>@codecademy/gamut-labs@15.0.0-alpha.dd7526.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.dd7526.0<br/>@codecademy/gamut@33.0.0-alpha.dd7526.0<br/>@codecademy/styleguide@37.0.0-alpha.dd7526.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 15:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60882c623dfd0d71e7067166--gamut-preview.netlify.app>https://60882c623dfd0d71e7067166--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60882c623dfd0d71e7067166>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 15:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.bb4e99.0<br/>@codecademy/gamut-labs@15.0.0-alpha.bb4e99.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.bb4e99.0<br/>@codecademy/gamut@33.0.0-alpha.bb4e99.0<br/>@codecademy/styleguide@37.0.0-alpha.bb4e99.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 15:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088307b050a51541552c2a1--gamut-preview.netlify.app>https://6088307b050a51541552c2a1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088307b050a51541552c2a1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 16:28 UTC, natalieweesh commented
corresponding monolith pr to update anywhere that used the old gamut `<Pattern>` component: https://github.com/codecademy-engineering/Codecademy/pull/24018

2021-04-27 16:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.53-alpha.1476dd.0<br/>@codecademy/gamut-labs@15.0.0-alpha.1476dd.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.1476dd.0<br/>@codecademy/gamut@33.0.0-alpha.1476dd.0<br/>@codecademy/styleguide@37.0.0-alpha.1476dd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 16:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60883d39050a51683b52ba63--gamut-preview.netlify.app>https://60883d39050a51683b52ba63--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60883d39050a51683b52ba63>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 16:57 UTC, JoshuaKGoldberg commented on packages/gamut-patterns/README.md
> +> TODO: description
😄

2021-04-27 17:01 UTC, JoshuaKGoldberg approved these changes
LGTM, but @codecaaron should take a look at it from the perspective of all the recent Gamut changes.

I don't want to keep blocking you on internal details - we can take on the automation if it all as a followup task. Thanks for pushing through!

2021-04-27 17:01 UTC, JoshuaKGoldberg commented on packages/gamut-patterns/__tests__/patterns-test.tsx
> +import { mount } from 'enzyme';
Ah you've stumbled onto an old piece of code we'll have to update... these should be using `@codecademy/gamut-tests`. 

It doesn't break now but in theory we might want to make icons, patterns, etc. use stuff from the Gamut theme provider.

2021-04-27 17:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.53-alpha.321063.0<br/>@codecademy/gamut-labs@15.0.0-alpha.321063.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.321063.0<br/>@codecademy/gamut@33.0.0-alpha.321063.0<br/>@codecademy/styleguide@37.0.0-alpha.321063.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 17:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088481dd1651d009e62ea4f--gamut-preview.netlify.app>https://6088481dd1651d009e62ea4f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088481dd1651d009e62ea4f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 20:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.55-alpha.fb02a7.0<br/>@codecademy/gamut-labs@15.0.0-alpha.fb02a7.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.fb02a7.0<br/>@codecademy/gamut@33.0.0-alpha.fb02a7.0<br/>@codecademy/styleguide@37.0.0-alpha.fb02a7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 20:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608878642ef85e0090b1455c--gamut-preview.netlify.app>https://608878642ef85e0090b1455c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608878642ef85e0090b1455c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 21:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.55-alpha.c1f572.0<br/>@codecademy/gamut-labs@15.0.0-alpha.c1f572.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.c1f572.0<br/>@codecademy/gamut@33.0.0-alpha.c1f572.0<br/>@codecademy/styleguide@37.0.0-alpha.c1f572.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 21:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60887c25c16ceb12269a05a2--gamut-preview.netlify.app>https://60887c25c16ceb12269a05a2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60887c25c16ceb12269a05a2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 21:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.55-alpha.40728c.0<br/>@codecademy/gamut-labs@15.0.0-alpha.40728c.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.40728c.0<br/>@codecademy/gamut@33.0.0-alpha.40728c.0<br/>@codecademy/styleguide@37.0.0-alpha.40728c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 21:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608887a8f5f1db24029e9e10--gamut-preview.netlify.app>https://608887a8f5f1db24029e9e10--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608887a8f5f1db24029e9e10>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 22:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.55-alpha.a8f603.0<br/>@codecademy/gamut-labs@15.0.0-alpha.a8f603.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.a8f603.0<br/>@codecademy/gamut@33.0.0-alpha.a8f603.0<br/>@codecademy/styleguide@37.0.0-alpha.a8f603.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 22:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608889ba1243ce12d36e6a75--gamut-preview.netlify.app>https://608889ba1243ce12d36e6a75--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608889ba1243ce12d36e6a75>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 22:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.55-alpha.dd1efc.0<br/>@codecademy/gamut-labs@15.0.0-alpha.dd1efc.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.dd1efc.0<br/>@codecademy/gamut@33.0.0-alpha.dd1efc.0<br/>@codecademy/styleguide@37.0.0-alpha.dd1efc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 22:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60888d26dd2947245ea239ad--gamut-preview.netlify.app>https://60888d26dd2947245ea239ad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60888d26dd2947245ea239ad>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 22:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.e8fa9a.0<br/>@codecademy/gamut-labs@15.0.0-alpha.e8fa9a.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.e8fa9a.0<br/>@codecademy/gamut@33.0.0-alpha.e8fa9a.0<br/>@codecademy/styleguide@37.0.0-alpha.e8fa9a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 22:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60888e8f7af5572059c509ea--gamut-preview.netlify.app>https://60888e8f7af5572059c509ea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60888e8f7af5572059c509ea>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 22:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.78645a.0<br/>@codecademy/gamut-labs@15.0.0-alpha.78645a.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.78645a.0<br/>@codecademy/gamut@33.0.0-alpha.78645a.0<br/>@codecademy/styleguide@37.0.0-alpha.78645a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 22:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608892431243ce24406e658b--gamut-preview.netlify.app>https://608892431243ce24406e658b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608892431243ce24406e658b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 23:18 UTC, codecaaron requested changes
Great start!

2021-04-27 23:18 UTC, codecaaron commented on packages/gamut-patterns/src/types.ts
> +);
So unless these are added onto a styled component they won't do anything, so our component has the types it needs but not the actual style props.

What I think you will need to do is to create a single wrapper `styled.svg` that has these props.

```tsx
export const PatternSvg = styled.svg(patternStyles);
// Typeforward valid SVG attrs.
export type PatternComponent = React.FC<React.ComponentProps<typeof PatternSvg>>
```

And use it in place of the svg on each pattern.

```tsx
import React from 'react';

import { PatternSvg, PatternComponent } from '../somewhere';

export const RainLoose: PatternComponent = (props) => (
  <svg width="100%" height="100%" {...props} aria-hidden>
    <pattern
      id="rainLoose"
      x="0"
      y="0"
      width="16"
      height="16"
      patternUnits="userSpaceOnUse"
    >
      <rect width="1" height="1" fill="currentColor" />
      <rect x="1" y="1" width="1" height="1" fill="currentColor" />
    </pattern>
    <rect x="0" y="0" width="100%" height="100%" fill="url(#rainLoose)" />
  </svg>
);
```

2021-04-28 01:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.c3e36a.0<br/>@codecademy/gamut-labs@15.0.0-alpha.c3e36a.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.c3e36a.0<br/>@codecademy/gamut@33.0.0-alpha.c3e36a.0<br/>@codecademy/styleguide@37.0.0-alpha.c3e36a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-28 01:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6088bc26a3f38a2ee2dc9bcc--gamut-preview.netlify.app>https://6088bc26a3f38a2ee2dc9bcc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6088bc26a3f38a2ee2dc9bcc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-28 12:15 UTC, natalieweesh commented on packages/gamut-patterns/src/types.ts
> +);
updated! thanks!

2021-04-29 23:32 UTC, codecaaron commented on packages/gamut-patterns/src/patterns/stripe/StripeRegular.tsx
> +  <PatternSvg width="100%" height="100%" {...props} aria-hidden>
You can make these default props on Pattern SVG so you don't have to repeat it every file :)
```suggestion
  <PatternSvg width="100%" height="100%" {...props} aria-hidden>
```

2021-04-30 00:03 UTC, codecaaron approved these changes
Just curious, why were we unable to do this with `svgr` again?

2021-04-30 00:03 UTC, codecaaron commented on packages/gamut-patterns/__tests__/patterns-test.tsx
> +    const { wrapper } = renderWrapper({ color: 'red' });
`textColor` will be the prop that works for our actual colors.  Unfortunately `color` has some issues as a system prop type as it conflicts with certain base elements.  Eventually this should be fixable but I have not been able to do so yet.

2021-04-30 02:00 UTC, natalieweesh commented on packages/gamut-labs/src/Popover/index.tsx
> +              <CheckerDense
yea, discussed with josh, and decided that we should just limit other gamut components' use of the Pattern to just one design, rather than let them choose which Pattern to use, because that would require importing all the possible patterns you're allowed to pick into that one gamut component that uses the Pattern, and we want to avoid doing that

2021-04-30 02:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.32253f.0<br/>@codecademy/gamut-labs@15.0.0-alpha.32253f.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.32253f.0<br/>@codecademy/gamut@33.0.0-alpha.32253f.0<br/>@codecademy/styleguide@37.0.0-alpha.32253f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-30 02:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608b66795c87d8191b231b8d--gamut-preview.netlify.app>https://608b66795c87d8191b231b8d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608b66795c87d8191b231b8d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-30 13:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.65-alpha.a03188.0<br/>@codecademy/gamut-labs@16.0.0-alpha.a03188.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.a03188.0<br/>@codecademy/gamut@33.0.0-alpha.a03188.0<br/>@codecademy/styleguide@37.0.0-alpha.a03188.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-30 13:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608c01bbaa5c290ef266bcaa--gamut-preview.netlify.app>https://608c01bbaa5c290ef266bcaa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608c01bbaa5c290ef266bcaa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-30 13:32 UTC, natalieweesh commented
@codecaaron couldn't use svgr because svgr lets you change some attributes of the svg but not the overall structure of the svg, so we wouldn't be able to put the `<pattern>` inside of the svg

2021-05-05 21:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.81-alpha.7fb2ec.0<br/>@codecademy/gamut-labs@16.0.0-alpha.7fb2ec.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.7fb2ec.0<br/>@codecademy/gamut@33.0.0-alpha.7fb2ec.0<br/>@codecademy/styleguide@37.0.0-alpha.7fb2ec.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 21:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60930c25d55a6524509d67a2--gamut-preview.netlify.app>https://60930c25d55a6524509d67a2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60930c25d55a6524509d67a2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 21:22 UTC, natalieweesh commented
as discussed with @codecaaron, removed changes to the old Pattern component but also kept the new gamut-patterns package 
so we do not have to change any current uses of Pattern (don't need this PR anymore: https://github.com/codecademy-engineering/Codecademy/pull/24018)
but we can also fiddle around with using the patterns from gamut-patterns if we want to

2021-05-06 02:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-patterns@1.0.0-alpha.17fc8e.0<br/>@codecademy/styleguide@37.0.0-alpha.17fc8e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-06 02:22 UTC, merged

2021-05-06 02:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6093535767f82100c6534b78--gamut-preview.netlify.app>https://6093535767f82100c6534b78--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6093535767f82100c6534b78>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->