feat(Text): Migrate to variance and add new semantic variants
Codecademy/client-modules pull request #1655
Opened 2021-04-20 22:34 UTC by codecaaron

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-20 23:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.c7a752.0<br/>@codecademy/gamut-labs@14.0.1-alpha.c7a752.0<br/>@codecademy/gamut@32.0.1-alpha.c7a752.0<br/>@codecademy/styleguide@36.0.1-alpha.c7a752.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 23:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f5d998616ef00d52a9280--gamut-preview.netlify.app>https://607f5d998616ef00d52a9280--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f5d998616ef00d52a9280>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 23:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.df0407.0<br/>@codecademy/gamut-labs@14.0.1-alpha.df0407.0<br/>@codecademy/gamut@32.0.1-alpha.df0407.0<br/>@codecademy/styleguide@36.0.1-alpha.df0407.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 23:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f5f8439dd56039790fee8--gamut-preview.netlify.app>https://607f5f8439dd56039790fee8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f5f8439dd56039790fee8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-20 23:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.181d24.0<br/>@codecademy/gamut-labs@14.0.1-alpha.181d24.0<br/>@codecademy/gamut@32.0.1-alpha.181d24.0<br/>@codecademy/styleguide@36.0.1-alpha.181d24.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-20 23:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f64d111f9a7009ebf1488--gamut-preview.netlify.app>https://607f64d111f9a7009ebf1488--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f64d111f9a7009ebf1488>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 01:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.20423d.0<br/>@codecademy/gamut-labs@14.0.1-alpha.20423d.0<br/>@codecademy/gamut@32.0.1-alpha.20423d.0<br/>@codecademy/styleguide@36.0.1-alpha.20423d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 01:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f7df7a274872e8fc626ce--gamut-preview.netlify.app>https://607f7df7a274872e8fc626ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f7df7a274872e8fc626ce>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 01:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.6e1384.0<br/>@codecademy/gamut-labs@14.0.1-alpha.6e1384.0<br/>@codecademy/gamut@32.0.1-alpha.6e1384.0<br/>@codecademy/styleguide@36.0.1-alpha.6e1384.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 01:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://607f7ff8f522f02d62e583d5--gamut-preview.netlify.app>https://607f7ff8f522f02d62e583d5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/607f7ff8f522f02d62e583d5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 15:21 UTC, dreamwasp approved these changes
tiny grammar thing but this looks 🔥

2021-04-21 15:21 UTC, dreamwasp commented on packages/styleguide/stories/Foundations/Typography.stories.mdx
> +Our primary typeface is Aperçu Pro. It is a geometric-ish, humanist-ish sans-serif. Which basically means it gives us a voice that says “We are ruled by logic, but are creative and a bit unexpected a
```suggestion
Our primary typeface is Aperçu Pro. It is a geometric-ish, humanist-ish sans-serif. Which basically means it gives us a voice that says “We are ruled by logic, but are creative and a bit unexpected as well”. Its weight makes it attention-grabbing in dense layouts, and its legibility allows us to use it for both long-form articles and fine print.
```

it's -> contraction, its -> possessive

2021-04-21 15:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.088988.0<br/>@codecademy/gamut-labs@14.0.1-alpha.088988.0<br/>@codecademy/gamut@32.0.1-alpha.088988.0<br/>@codecademy/styleguide@36.0.1-alpha.088988.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 15:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608044bcdcf15600d4b8367a--gamut-preview.netlify.app>https://608044bcdcf15600d4b8367a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608044bcdcf15600d4b8367a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 17:30 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalFooter/__tests__/GlobalFooter-test.tsx
>    it('does not explode', () => {
This is no longer just a "does not explode" test 😄

2021-04-21 17:36 UTC, JoshuaKGoldberg requested changes
The new docs are great, very nice!

Requesting changes on `-1` -> `-xs`?

2021-04-21 17:36 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/landingPage/PageVideoGallery.tsx
> +    */
Nit 😄 , unrelated?

2021-04-21 17:36 UTC, JoshuaKGoldberg commented on packages/gamut/src/Typography/variants.ts
> +  'title-1': {
Can we use `xs`, `sm`, etc. on these? I don't like using the same terminology as the heading role sizes; people tend to mess up accessibility when we do.

2021-04-21 17:36 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Foundations/Typography.stories.mdx
> +Our primary typeface is Aperçu Pro. It is a geometric-ish, humanist-ish sans-serif. Which basically means it gives us a voice that says “We are ruled by logic, but are creative and a bit unexpected a
```suggestion
Our primary typeface is Aperçu Pro. It is a geometric-ish, humanist-ish sans-serif. Its voice says _“we are ruled by logic, but are creative and a bit unexpected as well”_. Its weight makes it attention-grabbing in dense layouts, and its legibility allows us to use it for both long-form articles and fine print.
```

2021-04-21 17:36 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Typography/Text.stories.mdx
> +**Note**: Be aware that you must replicate any default behavior if you override these props with responsive values.
Err, what does this mean?

2021-04-21 17:36 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Typography/Text.stories.mdx
> +<PropsTable story="Text" defaultGroups={['typography']} />
Tangentially related, is there a ticket somewhere for maybe adding the alias more prominently? 
![Screenshot of the props table with unclear aliases](https://user-images.githubusercontent.com/3335181/115596750-79670e80-a2a6-11eb-86ec-c4b63eb3f455.png)

2021-04-21 17:53 UTC, codecaaron commented on packages/styleguide/stories/Typography/Text.stories.mdx
> +<PropsTable story="Text" defaultGroups={['typography']} />
Yeah, not a ticket proper but there is a [note in the migration doc](https://www.notion.so/codecademy/Variance-Migration-a675bbc31b584fec9dfff72c0364b194#371aa6a1abee440b8cd3c2404419c72f).

The current enhancers read the old system props, I believe switching them over will be pretty painless (hopefully).

2021-04-21 17:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.efc620.0<br/>@codecademy/gamut-labs@14.0.1-alpha.efc620.0<br/>@codecademy/gamut@32.0.1-alpha.efc620.0<br/>@codecademy/styleguide@36.0.1-alpha.efc620.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 17:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.b7c305.0<br/>@codecademy/gamut-labs@14.0.1-alpha.b7c305.0<br/>@codecademy/gamut@32.0.1-alpha.b7c305.0<br/>@codecademy/styleguide@36.0.1-alpha.b7c305.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 18:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60806871b6e8d12ac7967239--gamut-preview.netlify.app>https://60806871b6e8d12ac7967239--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60806871b6e8d12ac7967239>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-21 18:07 UTC, codecaaron commented on packages/gamut/src/Typography/variants.ts
> +  'title-1': {
Concur.  Let me ask Yassine, should be good :)

2021-04-21 19:33 UTC, codecaaron commented on packages/gamut/src/Typography/variants.ts
> +  'title-1': {
Went ahead and updated.

2021-04-21 19:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.39-alpha.4539a6.0<br/>@codecademy/gamut-labs@14.0.1-alpha.4539a6.0<br/>@codecademy/gamut@32.0.1-alpha.4539a6.0<br/>@codecademy/styleguide@36.0.1-alpha.4539a6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-21 19:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60807f815dedb900bd76b223--gamut-preview.netlify.app>https://60807f815dedb900bd76b223--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60807f815dedb900bd76b223>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 12:41 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalFooter/__tests__/GlobalFooter-test.tsx
>    it('does not explode', () => {
bamp @codecaaron - thoughts on renaming the test? (definitely a nit, not blocking)

2021-04-23 12:43 UTC, JoshuaKGoldberg approved these changes
Glorious!! 💯

2021-04-23 18:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60830e54baaec00091595303--gamut-preview.netlify.app>https://60830e54baaec00091595303--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60830e54baaec00091595303>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 18:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.44-alpha.147708.0<br/>@codecademy/gamut-labs@14.2.4-alpha.147708.0<br/>@codecademy/gamut@32.1.4-alpha.147708.0<br/>@codecademy/styleguide@36.2.5-alpha.147708.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-23 18:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608314e9f57f200095cf53a5--gamut-preview.netlify.app>https://608314e9f57f200095cf53a5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608314e9f57f200095cf53a5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 18:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.44-alpha.6d7846.0<br/>@codecademy/gamut-labs@14.2.4-alpha.6d7846.0<br/>@codecademy/gamut@32.1.4-alpha.6d7846.0<br/>@codecademy/styleguide@36.2.5-alpha.6d7846.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-23 18:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6083164abaaec0009d5953bd--gamut-preview.netlify.app>https://6083164abaaec0009d5953bd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6083164abaaec0009d5953bd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 18:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.44-alpha.db274e.0<br/>@codecademy/gamut-labs@14.2.4-alpha.db274e.0<br/>@codecademy/gamut@32.1.4-alpha.db274e.0<br/>@codecademy/styleguide@36.2.5-alpha.db274e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-23 18:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608317d7ff5c3200dc8b9baa--gamut-preview.netlify.app>https://608317d7ff5c3200dc8b9baa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608317d7ff5c3200dc8b9baa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-23 20:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.45-alpha.98b642.0<br/>@codecademy/gamut-labs@14.2.5-alpha.98b642.0<br/>@codecademy/gamut@32.1.4-alpha.98b642.0<br/>@codecademy/styleguide@36.2.6-alpha.98b642.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-23 20:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608333904eaeae2bf73dcae8--gamut-preview.netlify.app>https://608333904eaeae2bf73dcae8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608333904eaeae2bf73dcae8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 13:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.46-alpha.c78829.0<br/>@codecademy/gamut-labs@14.2.6-alpha.c78829.0<br/>@codecademy/gamut@32.1.5-alpha.c78829.0<br/>@codecademy/styleguide@36.2.7-alpha.c78829.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 13:01 UTC, merged

2021-04-26 13:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086b9b24165ec89a656c8a6--gamut-preview.netlify.app>https://6086b9b24165ec89a656c8a6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086b9b24165ec89a656c8a6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->