Cass gm 212
Codecademy/client-modules pull request #1662
Opened 2021-04-22 14:01 UTC by dreamwasp

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-04-22 14:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.41-alpha.34591a.0<br/>@codecademy/gamut-labs@14.2.1-alpha.34591a.0<br/>@codecademy/gamut@32.1.1-alpha.34591a.0<br/>@codecademy/styleguide@36.2.1-alpha.34591a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 14:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608182ff13e33f4d6cf53846--gamut-preview.netlify.app>https://608182ff13e33f4d6cf53846--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608182ff13e33f4d6cf53846>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 15:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.42-alpha.0284b9.0<br/>@codecademy/gamut-labs@14.2.2-alpha.0284b9.0<br/>@codecademy/gamut@32.1.2-alpha.0284b9.0<br/>@codecademy/styleguide@36.2.2-alpha.0284b9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 15:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60819981a6cc975ca3d9f5bd--gamut-preview.netlify.app>https://60819981a6cc975ca3d9f5bd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60819981a6cc975ca3d9f5bd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-22 20:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.42-alpha.5aaf74.0<br/>@codecademy/gamut-labs@14.2.2-alpha.5aaf74.0<br/>@codecademy/gamut@32.1.2-alpha.5aaf74.0<br/>@codecademy/styleguide@36.2.2-alpha.5aaf74.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-22 20:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6081d8023e555c009ce3998c--gamut-preview.netlify.app>https://6081d8023e555c009ce3998c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6081d8023e555c009ce3998c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 14:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086c9e32afed4009e7c18ca--gamut-preview.netlify.app>https://6086c9e32afed4009e7c18ca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086c9e32afed4009e7c18ca>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 14:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.142c3f.0<br/>@codecademy/gamut-labs@14.4.1-alpha.142c3f.0<br/>@codecademy/gamut@32.3.1-alpha.142c3f.0<br/>@codecademy/styleguide@36.4.1-alpha.142c3f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 14:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086cd6032d34e00e8cf6987--gamut-preview.netlify.app>https://6086cd6032d34e00e8cf6987--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086cd6032d34e00e8cf6987>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 15:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.71cd96.0<br/>@codecademy/gamut-labs@14.4.1-alpha.71cd96.0<br/>@codecademy/gamut@32.3.1-alpha.71cd96.0<br/>@codecademy/styleguide@36.4.1-alpha.71cd96.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 15:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086de82f702d223b9cc8a05--gamut-preview.netlify.app>https://6086de82f702d223b9cc8a05--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086de82f702d223b9cc8a05>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 15:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086e225e15f781aa2234c70--gamut-preview.netlify.app>https://6086e225e15f781aa2234c70--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086e225e15f781aa2234c70>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 16:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.086f6f.0<br/>@codecademy/gamut-labs@14.4.1-alpha.086f6f.0<br/>@codecademy/gamut@32.3.1-alpha.086f6f.0<br/>@codecademy/styleguide@36.4.1-alpha.086f6f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 16:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086e87871bddb2907378b61--gamut-preview.netlify.app>https://6086e87871bddb2907378b61--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086e87871bddb2907378b61>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 17:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.97124a.0<br/>@codecademy/gamut-labs@14.4.1-alpha.97124a.0<br/>@codecademy/gamut@32.3.1-alpha.97124a.0<br/>@codecademy/styleguide@36.4.1-alpha.97124a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 17:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6086f9e7f702d23c6ccc8bb7--gamut-preview.netlify.app>https://6086f9e7f702d23c6ccc8bb7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6086f9e7f702d23c6ccc8bb7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 20:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.1741cb.0<br/>@codecademy/gamut-labs@14.4.1-alpha.1741cb.0<br/>@codecademy/gamut@32.3.1-alpha.1741cb.0<br/>@codecademy/styleguide@36.4.1-alpha.1741cb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 20:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608721745c17c800e65bc8cd--gamut-preview.netlify.app>https://608721745c17c800e65bc8cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608721745c17c800e65bc8cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 21:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.49-alpha.a2a88f.0<br/>@codecademy/gamut-labs@14.4.1-alpha.a2a88f.0<br/>@codecademy/gamut@32.3.1-alpha.a2a88f.0<br/>@codecademy/styleguide@36.4.1-alpha.a2a88f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 21:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608730f20e649b00d414b0c6--gamut-preview.netlify.app>https://608730f20e649b00d414b0c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608730f20e649b00d414b0c6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-26 21:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.50-alpha.f8bba9.0<br/>@codecademy/gamut-labs@14.4.2-alpha.f8bba9.0<br/>@codecademy/gamut@32.3.2-alpha.f8bba9.0<br/>@codecademy/styleguide@36.4.2-alpha.f8bba9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-26 21:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608732dc607065008b0fc635--gamut-preview.netlify.app>https://608732dc607065008b0fc635--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608732dc607065008b0fc635>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 14:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.99edad.0<br/>@codecademy/gamut-labs@14.4.4-alpha.99edad.0<br/>@codecademy/gamut@32.3.4-alpha.99edad.0<br/>@codecademy/styleguide@36.4.4-alpha.99edad.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 14:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608824663f8f57616dec5cea--gamut-preview.netlify.app>https://608824663f8f57616dec5cea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608824663f8f57616dec5cea>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 15:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608826ebafcd25551bd5d1a3--gamut-preview.netlify.app>https://608826ebafcd25551bd5d1a3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608826ebafcd25551bd5d1a3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 15:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60882a4704bd595610fbfdc9--gamut-preview.netlify.app>https://60882a4704bd595610fbfdc9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60882a4704bd595610fbfdc9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-28 02:37 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +        SelectContainer: CustomContainer,
We can probably move this up to a file level object since we don't need anything inside of the components scope :) 

Outside of component:
```tsx
const reactSelectDefaultProps = {
   name: undefined, 
   isSearchable: false,
   isMulti: false,
   styles: customStyles,
  components: {
        DropdownIndicator: ChevronDropdown,
        IndicatorSeparator: () => null,
        SelectContainer: CustomContainer,
  }
}
```

Inside a bit easier to read :)  
```tsx
<ReactSelect
     {...defaultProps}
      id={id || rest.htmlFor}
      isSearchable={false}
      isMulti={false}
      isDisabled={disabled}
      options={selectOptions}
      placeholder={placeholder}
      activated={activated}
      onChange={changeHandler}
      error={Boolean(error)}
     {...rest}
/>
```

2021-04-28 02:37 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  inputProps?: { [key: string]: string | number };
```suggestion
  inputProps?: Record<string, string | number | boolean>;
```

2021-04-28 02:37 UTC, codecaaron commented on packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
> +`SelectDropdown` has a larger JavaScript dependency size than our standard `Select` component so should not be used unless specified in designs. If you wish to define an intial value, you must format
We probably should add an example that shows how we should use controlled inputs within a form :)

Is there anywhere this won't work?

2021-04-28 02:37 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +    return parsedOptions;
We can also move this up and out to a utility (makes it easier to test / use elsewhere :D

2021-04-28 15:45 UTC, borisonr commented on packages/gamut/src/Form/SelectDropdown.tsx
> +      <input type="hidden" value={value} {...inputProps} />
so we'll pass in the prop `inputProps={ data-recurly:"country"}`?

2021-04-28 15:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.5059a0.0<br/>@codecademy/gamut-labs@14.5.2-alpha.5059a0.0<br/>@codecademy/gamut@32.4.2-alpha.5059a0.0<br/>@codecademy/styleguide@36.5.4-alpha.5059a0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-28 15:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608983c5db4b002857bf4f27--gamut-preview.netlify.app>https://608983c5db4b002857bf4f27--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608983c5db4b002857bf4f27>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-28 15:54 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +      <input type="hidden" value={value} {...inputProps} />
i believe it's `inputProps={ `data-recurly`:"country", id: 'country'}`. i have a proof of concept branch where i have the alpha build working that i'll send your way in few!

2021-04-29 15:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.d77391.0<br/>@codecademy/gamut-labs@14.5.2-alpha.d77391.0<br/>@codecademy/gamut@32.4.2-alpha.d77391.0<br/>@codecademy/styleguide@36.5.4-alpha.d77391.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-29 15:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608acad28957230e27e6f1c6--gamut-preview.netlify.app>https://608acad28957230e27e6f1c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608acad28957230e27e6f1c6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-29 15:33 UTC, dreamwasp commented on packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
> +`SelectDropdown` has a larger JavaScript dependency size than our standard `Select` component so should not be used unless specified in designs. If you wish to define an intial value, you must format
yes! i'll add an example and some more robust documentation on how to do that. 

not that i know of *right now* but i think moving all GridForms => useController will establish that convention of using controlled forms a bit better across the code base.

right now we're only using this component in on the Checkout page + i've made sure it works in both places there

2021-04-29 21:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.64-alpha.f1a676.0<br/>@codecademy/gamut-labs@15.2.4-alpha.f1a676.0<br/>@codecademy/gamut@32.7.1-alpha.f1a676.0<br/>@codecademy/styleguide@36.9.1-alpha.f1a676.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-29 21:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608b26ce4800be9863e4c426--gamut-preview.netlify.app>https://608b26ce4800be9863e4c426--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608b26ce4800be9863e4c426>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-30 13:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608c03dec510ec0ddde7f527--gamut-preview.netlify.app>https://608c03dec510ec0ddde7f527--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608c03dec510ec0ddde7f527>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-30 13:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.64-alpha.5c0123.0<br/>@codecademy/gamut-labs@15.2.4-alpha.5c0123.0<br/>@codecademy/gamut@32.7.1-alpha.5c0123.0<br/>@codecademy/styleguide@36.9.1-alpha.5c0123.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-30 13:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.64-alpha.ac152f.0<br/>@codecademy/gamut-labs@15.2.4-alpha.ac152f.0<br/>@codecademy/gamut@32.7.1-alpha.ac152f.0<br/>@codecademy/styleguide@36.9.1-alpha.ac152f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-30 13:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608c0b901a04d42145d4bc6b--gamut-preview.netlify.app>https://608c0b901a04d42145d4bc6b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608c0b901a04d42145d4bc6b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-30 13:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.65-alpha.e67c54.0<br/>@codecademy/gamut-labs@15.2.5-alpha.e67c54.0<br/>@codecademy/gamut@32.7.2-alpha.e67c54.0<br/>@codecademy/styleguide@36.9.2-alpha.e67c54.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-30 13:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608c0cf7ae85581e4db16c0b--gamut-preview.netlify.app>https://608c0cf7ae85581e4db16c0b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608c0cf7ae85581e4db16c0b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-30 16:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.65-alpha.5ce282.0<br/>@codecademy/gamut-labs@15.2.5-alpha.5ce282.0<br/>@codecademy/gamut@32.7.2-alpha.5ce282.0<br/>@codecademy/styleguide@36.9.2-alpha.5ce282.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-30 16:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608c2daab1870900a23d16fd--gamut-preview.netlify.app>https://608c2daab1870900a23d16fd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608c2daab1870900a23d16fd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-30 16:41 UTC, codecaaron approved these changes

2021-04-30 16:41 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +      }
Object spread works with undefined values :) 
```suggestion
      inputProps={{ ...inputProps, ...baseInputProps }}
```

2021-04-30 16:41 UTC, codecaaron commented on packages/gamut/src/Form/utils.tsx
> +};
Let's add some unit tests for this on the next pass since its not react-select specific :)

2021-04-30 16:41 UTC, codecaaron commented on packages/gamut/src/Form/utils.tsx
> +  : JSX.Element;
I think we might need to export these as well since there can be issues with internal types not being available in some cases :)

2021-04-30 17:08 UTC, dreamwasp commented on packages/gamut/src/Form/utils.tsx
> +};
i have some from the last go around - do you mean unit tests for parseOptions specifically?

2021-04-30 17:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.65-alpha.169139.0<br/>@codecademy/gamut-labs@15.2.5-alpha.169139.0<br/>@codecademy/gamut@32.7.2-alpha.169139.0<br/>@codecademy/styleguide@36.9.2-alpha.169139.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-30 17:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608c3b5f2cea1b00ad0556b1--gamut-preview.netlify.app>https://608c3b5f2cea1b00ad0556b1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608c3b5f2cea1b00ad0556b1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-30 17:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.65-alpha.ad135e.0<br/>@codecademy/gamut-labs@15.2.5-alpha.ad135e.0<br/>@codecademy/gamut@32.7.2-alpha.ad135e.0<br/>@codecademy/styleguide@36.9.2-alpha.ad135e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-30 17:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608c3cb87923b3008a9bc6ab--gamut-preview.netlify.app>https://608c3cb87923b3008a9bc6ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608c3cb87923b3008a9bc6ab>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-02 17:44 UTC, JoshuaKGoldberg requested changes
Looking good so far 😎

2021-05-02 17:44 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Select.tsx
> +  SelectHTMLAttributes<HTMLSelectElement> & {
If `SelectComponentProps` is a `Pick` from `SelectHTMLAttributes<HTMLSelectElement> ` already...

```suggestion
export type SelectWrapperProps = SelectHTMLAttributes<HTMLSelectElement> & {
```

2021-05-02 17:44 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Select.tsx
> +> & {
Nit: this is already picking up `htmlFor` and `id`... can this either expand the pick to include those instead of manually redeclaring them, or switch to just adding `disabled?: boolean`?

2021-05-02 17:44 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Select.tsx
> +    }, [options, id]);
Nit: do these really need a memo? I'd be surprised if the performance is noticeably different?

2021-05-02 17:44 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/utils.tsx
> +};
Hmm, this function is putting a lot of effort into being a single function with a different return type in the type system. I think it'd be simpler to export _two_ functions instead and not have to use generic types or whatnot.

2021-05-03 14:45 UTC, dreamwasp commented on packages/gamut/src/Form/Select.tsx
> +  SelectHTMLAttributes<HTMLSelectElement> & {
it's separate because i export + reuse `SelectComponentProps` in `SelectDropdown`

2021-05-03 14:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.65-alpha.7eb77c.0<br/>@codecademy/gamut-labs@15.2.5-alpha.7eb77c.0<br/>@codecademy/gamut@32.7.2-alpha.7eb77c.0<br/>@codecademy/styleguide@36.9.2-alpha.7eb77c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 14:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60900e2f628a15009d567faa--gamut-preview.netlify.app>https://60900e2f628a15009d567faa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60900e2f628a15009d567faa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 14:54 UTC, dreamwasp commented on packages/gamut/src/Form/Select.tsx
> +> & {
included id but TS errors out when i try to Pick htmlFor' i looked into the SelectHTMLAttributes and (from what i can tell) it doesn't exist there so i've left it as is

2021-05-03 14:55 UTC, dreamwasp commented on packages/gamut/src/Form/Select.tsx
> +    }, [options, id]);
whats the downside of using useMemo?  without it it regenerates the list of options every time an option is selected (i think?)

2021-05-03 14:56 UTC, dreamwasp commented on packages/gamut/src/Form/utils.tsx
> +};
it is a little DRYer this way, but i don't really mind changing it.

2021-05-03 15:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.65-alpha.0b2546.0<br/>@codecademy/gamut-labs@15.2.5-alpha.0b2546.0<br/>@codecademy/gamut@32.7.2-alpha.0b2546.0<br/>@codecademy/styleguide@36.9.2-alpha.0b2546.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 15:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090137b700ab41285eafc10--gamut-preview.netlify.app>https://6090137b700ab41285eafc10--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090137b700ab41285eafc10>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 15:56 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/utils.tsx
> +};
I think you could still DRY if you have one function call the other.

2021-05-03 15:59 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Select.tsx
> +    }, [options, id]);
Oh if it causes a functional change that we like then no complaint from me 😄 . My theology with memoizing / general caching additions is that even though there are nearly infinite areas where we _could_ add them, most don't improve application perf meaningfully, so it's not worth the increased code size _until_ we see an issue or know an area is almost certainly going to cause an issue.

2021-05-03 16:02 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/utils.tsx
> +};
Looking at this again: yes, what I'm suggesting is basically:

```ts
export const parseSelectOptions = (props: ParseOptionProps) => {
  return parseDropdownOptions(props).map(formatAsOptions);
};
```

2021-05-03 16:03 UTC, JoshuaKGoldberg approved these changes
I'm sure you'll find a nirvana with the parsing utils, doesn't seem like a blocker to me 😄 

Very nice stuff overall!

2021-05-03 16:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.68-alpha.30f5ab.0<br/>@codecademy/gamut-labs@15.2.8-alpha.30f5ab.0<br/>@codecademy/gamut@32.8.1-alpha.30f5ab.0<br/>@codecademy/styleguide@36.10.1-alpha.30f5ab.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 16:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609027b77e5df9008b3f00a0--gamut-preview.netlify.app>https://609027b77e5df9008b3f00a0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609027b77e5df9008b3f00a0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 16:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.68-alpha.d54af4.0<br/>@codecademy/gamut-labs@15.2.8-alpha.d54af4.0<br/>@codecademy/gamut@32.8.1-alpha.d54af4.0<br/>@codecademy/styleguide@36.10.1-alpha.d54af4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 16:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609029bd41f2b200cb7b06c7--gamut-preview.netlify.app>https://609029bd41f2b200cb7b06c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609029bd41f2b200cb7b06c7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 18:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.69-alpha.28a21d.0<br/>@codecademy/gamut-labs@15.2.9-alpha.28a21d.0<br/>@codecademy/gamut@32.8.2-alpha.28a21d.0<br/>@codecademy/styleguide@36.11.1-alpha.28a21d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 18:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60904496c463a7120e48e8b9--gamut-preview.netlify.app>https://60904496c463a7120e48e8b9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60904496c463a7120e48e8b9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 18:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.70-alpha.a7ee86.0<br/>@codecademy/gamut-labs@15.2.10-alpha.a7ee86.0<br/>@codecademy/gamut@32.8.3-alpha.a7ee86.0<br/>@codecademy/styleguide@36.11.2-alpha.a7ee86.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 19:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090484db9033d1480ab1d02--gamut-preview.netlify.app>https://6090484db9033d1480ab1d02--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090484db9033d1480ab1d02>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 20:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.70-alpha.c5e84a.0<br/>@codecademy/gamut-labs@15.2.10-alpha.c5e84a.0<br/>@codecademy/gamut@32.8.3-alpha.c5e84a.0<br/>@codecademy/styleguide@36.11.2-alpha.c5e84a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 20:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60905d2c1a60541487e4d3ae--gamut-preview.netlify.app>https://60905d2c1a60541487e4d3ae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60905d2c1a60541487e4d3ae>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 20:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.70-alpha.3fd55a.0<br/>@codecademy/gamut-labs@15.2.10-alpha.3fd55a.0<br/>@codecademy/gamut@32.8.3-alpha.3fd55a.0<br/>@codecademy/styleguide@36.11.2-alpha.3fd55a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 20:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090608d702c4b00a50f0752--gamut-preview.netlify.app>https://6090608d702c4b00a50f0752--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090608d702c4b00a50f0752>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 21:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.70-alpha.222335.0<br/>@codecademy/gamut-labs@15.2.10-alpha.222335.0<br/>@codecademy/gamut@32.8.3-alpha.222335.0<br/>@codecademy/styleguide@36.11.2-alpha.222335.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 21:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609065d5bed0230088285331--gamut-preview.netlify.app>https://609065d5bed0230088285331--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609065d5bed0230088285331>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 21:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.70-alpha.0cde88.0<br/>@codecademy/gamut-labs@15.2.10-alpha.0cde88.0<br/>@codecademy/gamut@32.8.3-alpha.0cde88.0<br/>@codecademy/styleguide@36.11.2-alpha.0cde88.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 21:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60906c4dee0d3312900f8f86--gamut-preview.netlify.app>https://60906c4dee0d3312900f8f86--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60906c4dee0d3312900f8f86>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-04 19:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.76-alpha.5358a4.0<br/>@codecademy/gamut-labs@15.4.2-alpha.5358a4.0<br/>@codecademy/gamut@32.10.2-alpha.5358a4.0<br/>@codecademy/styleguide@36.13.2-alpha.5358a4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-04 19:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60919acf0c5dcd0093aa9896--gamut-preview.netlify.app>https://60919acf0c5dcd0093aa9896--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60919acf0c5dcd0093aa9896>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-04 19:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.76-alpha.da6cdf.0<br/>@codecademy/gamut-labs@15.4.2-alpha.da6cdf.0<br/>@codecademy/gamut@32.10.2-alpha.da6cdf.0<br/>@codecademy/styleguide@36.13.2-alpha.da6cdf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-04 19:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60919e6ab275820df1ca1b42--gamut-preview.netlify.app>https://60919e6ab275820df1ca1b42--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60919e6ab275820df1ca1b42>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-04 21:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.76-alpha.4a0c13.0<br/>@codecademy/gamut-labs@15.4.2-alpha.4a0c13.0<br/>@codecademy/gamut@32.10.2-alpha.4a0c13.0<br/>@codecademy/styleguide@36.13.2-alpha.4a0c13.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-04 21:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091b6ed6bcb72009497cd00--gamut-preview.netlify.app>https://6091b6ed6bcb72009497cd00--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091b6ed6bcb72009497cd00>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-04 22:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091c6cc0bb2640d9e0e3ea7--gamut-preview.netlify.app>https://6091c6cc0bb2640d9e0e3ea7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091c6cc0bb2640d9e0e3ea7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-04 22:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.76-alpha.10abdf.0<br/>@codecademy/gamut-labs@15.4.2-alpha.10abdf.0<br/>@codecademy/gamut@32.10.2-alpha.10abdf.0<br/>@codecademy/styleguide@36.13.2-alpha.10abdf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-04 23:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.76-alpha.1d71e0.0<br/>@codecademy/gamut-labs@15.4.2-alpha.1d71e0.0<br/>@codecademy/gamut@32.10.2-alpha.1d71e0.0<br/>@codecademy/styleguide@36.13.2-alpha.1d71e0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-04 23:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6091d6b6a1805f21b320a5fd--gamut-preview.netlify.app>https://6091d6b6a1805f21b320a5fd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6091d6b6a1805f21b320a5fd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 15:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.78-alpha.246fd3.0<br/>@codecademy/gamut-labs@15.5.2-alpha.246fd3.0<br/>@codecademy/gamut@32.11.2-alpha.246fd3.0<br/>@codecademy/styleguide@36.13.4-alpha.246fd3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 15:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092b821f420c300a8f5d020--gamut-preview.netlify.app>https://6092b821f420c300a8f5d020--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092b821f420c300a8f5d020>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 16:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.79-alpha.2df8ca.0<br/>@codecademy/gamut-labs@15.5.3-alpha.2df8ca.0<br/>@codecademy/gamut@32.12.1-alpha.2df8ca.0<br/>@codecademy/styleguide@36.14.1-alpha.2df8ca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 16:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092cb454f486b1c859ece92--gamut-preview.netlify.app>https://6092cb454f486b1c859ece92--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092cb454f486b1c859ece92>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 17:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.80-alpha.9ef8d4.0<br/>@codecademy/gamut-labs@15.5.4-alpha.9ef8d4.0<br/>@codecademy/gamut@32.12.2-alpha.9ef8d4.0<br/>@codecademy/styleguide@36.14.2-alpha.9ef8d4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 17:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092d3364f486b289f9eca2a--gamut-preview.netlify.app>https://6092d3364f486b289f9eca2a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092d3364f486b289f9eca2a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 17:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.80-alpha.51d59c.0<br/>@codecademy/gamut-labs@15.5.4-alpha.51d59c.0<br/>@codecademy/gamut@32.12.2-alpha.51d59c.0<br/>@codecademy/styleguide@36.14.2-alpha.51d59c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 17:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092da3575f94b008c841b19--gamut-preview.netlify.app>https://6092da3575f94b008c841b19--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092da3575f94b008c841b19>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 20:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.80-alpha.a12b1a.0<br/>@codecademy/gamut-labs@15.5.4-alpha.a12b1a.0<br/>@codecademy/gamut@32.12.2-alpha.a12b1a.0<br/>@codecademy/styleguide@36.14.2-alpha.a12b1a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 20:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092fbef3dbcf70f2d045931--gamut-preview.netlify.app>https://6092fbef3dbcf70f2d045931--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092fbef3dbcf70f2d045931>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-06 00:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.81-alpha.78d1bc.0<br/>@codecademy/gamut-labs@15.5.5-alpha.78d1bc.0<br/>@codecademy/gamut@32.12.3-alpha.78d1bc.0<br/>@codecademy/styleguide@36.14.3-alpha.78d1bc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-06 00:08 UTC, merged

2021-05-06 00:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609333721ddd5400b1f7d71e--gamut-preview.netlify.app>https://609333721ddd5400b1f7d71e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609333721ddd5400b1f7d71e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->