feat: List Section
Codecademy/client-modules pull request #1681
Opened 2021-04-27 13:23 UTC by sooinc

### Overview
Adds List Section component.

- Add ListSection molecule

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/PG0kVYDIuLk3hE566beZUV/Profiles-(Concept-Refinement)?node-id=315%3A2374
- [x] Related to JIRA ticket: Egg-1069
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

2021-04-27 13:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.52-alpha.023141.0<br/>@codecademy/gamut-labs@14.4.4-alpha.023141.0<br/>@codecademy/styleguide@36.4.4-alpha.023141.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 13:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://608816dd8ba134699e4ee53f--gamut-preview.netlify.app>https://608816dd8ba134699e4ee53f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/608816dd8ba134699e4ee53f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 17:23 UTC, JoshuaKGoldberg requested changes
Left a few small comments, with the one real blocker IMO being the usage of generic `renderItem` vs. `children`.

From the design perspective, we already have an accordion component set up with animations and everything. Can we start a conversation about expanding that for this kind of vertically flipped scenario?

2021-04-27 17:23 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/ListSection/index.tsx
> +   * Number of items to be initally displayed (note: if the initial display amount matches the number of list items, Show All button will not appear).
Nit: [TSDoc](https://tsdoc.org/) has a think for this:

```suggestion
   * Number of items to be initally displayed
   *
   * @remarks
   * If the initial display amount matches the number of list items, Show All button will not appear.
```

2021-04-27 17:23 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/ListSection/index.tsx
> +  renderItem: (item: T, index?: number) => ReactElement;
The `?` means this component _might_ provide an `index: number` when `renderItem` is called. I see in the code below that it's never provided, so you probably want this:

```suggestion
  renderItem: (item: T) => ReactElement;
```

2021-04-27 17:23 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/ListSection/index.tsx
> +  const renderfooterButton = () => {
Nit: capitalization?

```suggestion
  const renderFooterButton = () => {
```

This is part of why I personally prefer not to use inline `render*` functions; IMO they add a bit of extra overhead. Not a blocker from me, just a side comment.

2021-04-27 17:23 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/ListSection/index.stories.mdx
> +It is built on top of [Page Section](https://gamut.codecademy.com/storybook/?path=/docs/molecules-pagesection--page-section) so you may pass in optional header button and header secondary button.
Err, can you? The props aren't hooked up for that now.

2021-04-27 17:23 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/ListSection/index.tsx
> +export const ListSection = <T extends unknown>({
Is there a reason why this needs to use a `listItems` with its own `renderItem` and `T` generic to render children? If the point is to just make sure things are provided as an array, you could make the `children` prop typed as an array:

```tsx
children: React.ReactNode[];
```

That way consumers would have to provide an array as children, like:

```tsx
<ListSection title="Latest Certificate">
  {titles.map((title) => <Text>{title}</Text>}
</ListSection>
```

https://reactjs.org/docs/react-api.html#reactchildrentoarray is a thing too.

2021-04-27 23:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.c61d97.0<br/>@codecademy/gamut-labs@14.5.2-alpha.c61d97.0<br/>@codecademy/styleguide@36.5.4-alpha.c61d97.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-27 23:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60889a0e28c3d700c1d7e100--gamut-preview.netlify.app>https://60889a0e28c3d700c1d7e100--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60889a0e28c3d700c1d7e100>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-27 23:14 UTC, sooinc commented on packages/gamut-labs/src/ListSection/index.tsx
> +export const ListSection = <T extends unknown>({
I went this route because I thought passing in a raw list of items and composing only the ones needed to show as react nodes was potentially better than composing all react nodes at once. 
But I don't actually know if we end up saving anything by doing that. I'm not opposed to using `children` prop!

2021-04-27 23:14 UTC, sooinc commented on packages/styleguide/stories/Molecules/ListSection/index.stories.mdx
> +It is built on top of [Page Section](https://gamut.codecademy.com/storybook/?path=/docs/molecules-pagesection--page-section) so you may pass in optional header button and header secondary button.
sorry i missed this - i passed the optional props in now :)

2021-04-27 23:19 UTC, sooinc commented
@JoshuaKGoldberg re-requesting review as I addressed your comments.

RE: animation, connected with Timea and Cass and confirmed with Timea that for rendering additional items via "show all" animation is not needed (at least for now).

2021-04-27 23:19 UTC, sooinc commented on packages/gamut-labs/src/ListSection/index.tsx
> +  const renderfooterButton = () => {
Fixed the capitalization! Also agree that they are not always the best and can add extra overhead. I go back and forth but I think it works here

2021-04-28 00:02 UTC, ZackMFleischman commented on packages/gamut-labs/src/ListSection/index.tsx
> +export const ListSection = <T extends unknown>({
@JoshuaKGoldberg The big reason to prefer passing in the items rather than an array of ReactNodes is because the `ListSection` component is in charge of how many of them to render (i.e. it renders only 3 by default, and then all of them if the user clicks "show all").

TIL about `Children.ToArray`. It looks like we could accomplish this via 
```
   renderListItems  = () => {
      if (showAll) return props.children;
      else return React.Children.toArray(children).slice(0, 3);
   }
```
I'm assuming the above will only kick off the useEffects for the first 3 items in the array since the rest aren't actually mounted? If so then this works well.

It would, as you said, rid us of the need for generic list item props and a renderer function.

2021-04-28 00:08 UTC, ZackMFleischman approved these changes
This looks good to me! Let's get webplatform approval before merging though. 

I did have the one question around an empty state though.

2021-04-28 00:08 UTC, ZackMFleischman commented on packages/gamut-labs/src/ListSection/index.tsx
> +    return listItems.slice(0, displayLimit);
nit: if there are a lot of items, this is copying the entire array unnecessarily.

2021-04-28 00:08 UTC, ZackMFleischman commented on packages/gamut-labs/src/ListSection/__tests__/ListSection-test.tsx
> +describe('ListSection', () => {
Does it make sense for us to have a default empty state if it has no items in the children array?

2021-04-28 13:18 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/ListSection/index.tsx
> +export const ListSection = <T extends unknown>({
Yip yip, this looks good to me!

2021-04-28 13:20 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/ListSection/index.tsx
> +   */
This is self-explanatory from the type declaration ✨ 

```suggestion
```

2021-04-28 13:20 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/ListSection/index.tsx
> +export const ListSection = <T extends unknown>({
Yip yip, regardless of what props this node receives as `children` or any other name, if it doesn't return them from the render they won't trigger effectcs.

2021-04-28 13:21 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/ListSection.stories.mdx
> +It is built on top of [Page Section](https://gamut.codecademy.com/storybook/?path=/docs/molecules-pagesection--page-section) so you may pass in optional header button and header secondary button.
Maybe move this below the canvas and show this as a separate story to be extra clear? Up to you.

2021-04-28 13:21 UTC, JoshuaKGoldberg approved these changes
Thanks for being Gamut-first about this stuff! 🌮

2021-04-28 14:46 UTC, dreamwasp approved these changes
beautiful✨

2021-04-28 16:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.eeaece.0<br/>@codecademy/gamut-labs@14.5.2-alpha.eeaece.0<br/>@codecademy/styleguide@36.5.4-alpha.eeaece.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-28 16:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6089884ae1ca262e87e0935b--gamut-preview.netlify.app>https://6089884ae1ca262e87e0935b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6089884ae1ca262e87e0935b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-28 17:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.56-alpha.ea6757.0<br/>@codecademy/gamut-labs@14.5.2-alpha.ea6757.0<br/>@codecademy/styleguide@36.5.4-alpha.ea6757.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-28 17:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6089a1e09d12f40c9db2b120--gamut-preview.netlify.app>https://6089a1e09d12f40c9db2b120--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6089a1e09d12f40c9db2b120>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-04-28 18:57 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/ListSection/__tests__/ListSection-test.tsx
> +describe('ListSection', () => {
This sounds perfect! 💯

2021-04-28 19:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.57-alpha.3940a4.0<br/>@codecademy/gamut-labs@15.0.1-alpha.3940a4.0<br/>@codecademy/styleguide@36.5.5-alpha.3940a4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-04-28 19:14 UTC, merged

2021-04-28 19:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6089b43b9d12f4283db2b1c0--gamut-preview.netlify.app>https://6089b43b9d12f4283db2b1c0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6089b43b9d12f4283db2b1c0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->