adding EmptySection
Codecademy/client-modules pull request #1705
Opened 2021-05-03 14:22 UTC by jcenglish

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-05-03 14:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.67-alpha.eb4d90.0<br/>@codecademy/gamut-labs@15.2.7-alpha.eb4d90.0<br/>@codecademy/styleguide@36.9.4-alpha.eb4d90.0<br/>@codecademy/tracking@0.6.0-alpha.eb4d90.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 14:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090089c13c1c200b77d26b2--gamut-preview.netlify.app>https://6090089c13c1c200b77d26b2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090089c13c1c200b77d26b2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 18:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.67-alpha.98d072.0<br/>@codecademy/gamut-labs@15.2.7-alpha.98d072.0<br/>@codecademy/styleguide@36.9.4-alpha.98d072.0<br/>@codecademy/tracking@0.6.0-alpha.98d072.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 18:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090426cdca51c0f42b35a28--gamut-preview.netlify.app>https://6090426cdca51c0f42b35a28--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090426cdca51c0f42b35a28>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 20:58 UTC, jcenglish commented on packages/gamut-labs/src/EmptySection/index.tsx
> +          <Illustration width={pxRem(100)} />
Is there a way to just use the Illustration, and not have to style a container around it to get the different breakpoint styles?

2021-05-04 13:12 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +          <Illustration width={pxRem(100)} />
We can't... yet :) 👿

2021-05-04 13:24 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +`;
After this is merged https://github.com/Codecademy/client-modules/pull/1658 `calc` will not be stripped out of width etc and you can use the syntax for it.

2021-05-04 13:24 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +  innerBGColor: keyof typeof colors;
```suggestion
  innerBGColor: keyof Theme['colors'];
```

2021-05-04 13:24 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +    <Box position="relative">
It might make sense to try the background component here so everything will still work if the background color ends up being dark :)

```suggestion
import { Background } from '@codecademy/gamut-styles';
        
<Background bg={innerBGColor} position="relative">
```

https://gamut.codecademy.com/storybook/?path=/docs/foundations-colormode--page#background-

2021-05-04 13:24 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +        marginBottom={{ base: pxRem(138) as any }}
In cases like this where you need specific space you can avoid having to set margins like this by creating a spacer element.

```tsx
<FlexBox>
  <!-- Your content here -->
</FlexBox>
<Box width="100%" height="138" />
```

2021-05-04 13:24 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +          </Title>
```suggestion
          <Text as="h2" fontSize={22} mb={8}>
            {headingText}
          </Text>
```

2021-05-04 14:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.67-alpha.89503b.0<br/>@codecademy/gamut-labs@15.2.7-alpha.89503b.0<br/>@codecademy/styleguide@36.9.4-alpha.89503b.0<br/>@codecademy/tracking@0.6.0-alpha.89503b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-04 14:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60915de2402978208e84a3e6--gamut-preview.netlify.app>https://60915de2402978208e84a3e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60915de2402978208e84a3e6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-04 15:54 UTC, jcenglish commented on packages/gamut-labs/src/EmptySection/index.tsx
> +          {children}
I don't like how open to interpretation `children` is, but it really only should accept a link `*Button` or a `*Button` that triggers some kind of onClick action - in particular, the dropdown that will be in the empty Workspaces section.

2021-05-05 16:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.76-alpha.d9d3ba.0<br/>@codecademy/gamut-labs@15.4.2-alpha.d9d3ba.0<br/>@codecademy/styleguide@36.13.2-alpha.d9d3ba.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 16:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092cd775e7891298d10a761--gamut-preview.netlify.app>https://6092cd775e7891298d10a761--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092cd775e7891298d10a761>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 16:53 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/__tests__/EmptySection-test.tsx
> +    expect(view.queryByText(bodyText)).toBeTruthy();
IIRC `view.getByText(bodyText)` works as an assertion on its own :)

2021-05-05 20:36 UTC, dreamwasp approved these changes
have a question but this LGTM as is too ✨

2021-05-05 20:36 UTC, dreamwasp commented on packages/gamut-labs/src/EmptySection/index.tsx
> +          {children}
could we restrict this more if the button was passed down through a prop (or buttonText / buttonOnClick?)? how strict/flexible should this component be?

2021-05-06 02:14 UTC, codecaaron requested changes
Awesome start!!!

The component looks a bit wild on large widths which I left a comment about:
<img width="1525" alt="Screen Shot 2021-05-05 at 9 55 16 PM" src="https://user-images.githubusercontent.com/52927224/117232168-a52ddc80-adee-11eb-905d-18043f69bf93.png">

The other comments are just suggestions if you want to try them out!

2021-05-06 02:14 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +      >
If we make `EmptyContainer` display flex we can make sure we don't stretch the content too much with `justifySelf="center"` and `maxWidth="600px"`.

```tsx
<FlexBox 
    maxWidth="600px"
    justifySelf="center"
    // rest of props
>
 children
</FlexBox>
```

2021-05-06 02:14 UTC, codecaaron commented on packages/styleguide/stories/Molecules/EmptySection.stories.mdx
> +<PropsTable story="Illustration on the left" />
For the props table section check out what we do in Alert in terms of copy :) 
https://github.com/Codecademy/client-modules/blob/main/packages/styleguide/stories/Molecules/Alert/index.stories.mdx

```suggestion
<PropsTable story="Illustration on the left" />
```

2021-05-06 02:14 UTC, codecaaron commented on packages/styleguide/stories/Molecules/EmptySection.stories.mdx
> +    illustration: NumberBlocks,
```suggestion
    illustration: NumberBlocks,
    children: <FillButton>Do something</FillButton>
```

2021-05-06 02:14 UTC, codecaaron commented on packages/styleguide/stories/Molecules/EmptySection.stories.mdx
> +  </Story>
If we use args here we can just set the things we want to change to compared to the args on `Meta` :) 
```suggestion
  <Story name="Illustration on the right" args={{ illustrationPosition: 'right' }}>
    {(args) => (  <EmptySection {...args} />)|
  </Story>
```
```

2021-05-06 02:14 UTC, codecaaron commented on packages/styleguide/stories/Molecules/EmptySection.stories.mdx
> +## Illustration on the right
Could we add stories for Stretch Direction too?

2021-05-06 02:14 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +`;
Want to take a stab at doing this with <Box />?

2021-05-07 17:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.86-alpha.47de4d.0<br/>@codecademy/gamut-labs@15.7.1-alpha.47de4d.0<br/>@codecademy/styleguide@37.1.2-alpha.47de4d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-07 17:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60957d8e93dbeb009d5c3041--gamut-preview.netlify.app>https://60957d8e93dbeb009d5c3041--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60957d8e93dbeb009d5c3041>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-07 18:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.86-alpha.111087.0<br/>@codecademy/gamut-labs@15.7.1-alpha.111087.0<br/>@codecademy/styleguide@37.1.2-alpha.111087.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-07 18:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609582d991a273008c28e188--gamut-preview.netlify.app>https://609582d991a273008c28e188--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609582d991a273008c28e188>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-11 14:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.91-alpha.73d980.0<br/>@codecademy/gamut-labs@15.8.4-alpha.73d980.0<br/>@codecademy/styleguide@37.3.2-alpha.73d980.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-11 15:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609aa503cab2cd1fb4a4d070--gamut-preview.netlify.app>https://609aa503cab2cd1fb4a4d070--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609aa503cab2cd1fb4a4d070>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-11 16:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609ab3b15136db3ed880dbf9--gamut-preview.netlify.app>https://609ab3b15136db3ed880dbf9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609ab3b15136db3ed880dbf9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-11 16:49 UTC, sylvanasantos commented on packages/gamut-labs/src/EmptySection/index.tsx
> +  stretchDirection: 'left' | 'right';
can we add comments/descriptions to these props for more context

2021-05-11 16:49 UTC, sylvanasantos commented on packages/gamut-labs/src/EmptySection/index.tsx
> +          {children}
this is the new dropdown button (already merged): https://github.com/Codecademy/client-modules/pull/1729

2021-05-11 16:49 UTC, sylvanasantos commented on packages/gamut-labs/src/EmptySection/index.tsx
> +      },
hmmm i'm not sure if this is the behavior that we want. i'd need to see it in the pr environment. unfortunately, i'm getting a "Something went wrong" error on the pr environment.

2021-05-11 17:31 UTC, jcenglish commented on packages/gamut-labs/src/EmptySection/index.tsx
> +      },
> hmmm i'm not sure if this is the behavior that we want. i'd need to see it in the pr environment. unfortunately, i'm getting a "Something went wrong" error on the pr environment.

yeah, I'm also having trouble resolving duplicates in the yarn file so I can push the latest version from my monolith PR. :/

2021-05-11 17:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.92-alpha.ba2c25.0<br/>@codecademy/gamut-labs@15.8.5-alpha.ba2c25.0<br/>@codecademy/styleguide@37.4.1-alpha.ba2c25.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-11 17:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609ac0650ddbfd5b359ff66b--gamut-preview.netlify.app>https://609ac0650ddbfd5b359ff66b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609ac0650ddbfd5b359ff66b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-11 21:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609af4f56c18471fbd281c7c--gamut-preview.netlify.app>https://609af4f56c18471fbd281c7c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609af4f56c18471fbd281c7c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-12 15:15 UTC, jcenglish commented on packages/gamut-labs/src/EmptySection/index.tsx
> +          {children}
Okeedoke, I'll update the props to take in either a button or dropdown button. 🙌

2021-05-12 17:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.515a30.0<br/>@codecademy/gamut-labs@16.0.2-alpha.515a30.0<br/>@codecademy/styleguide@37.5.5-alpha.515a30.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-12 18:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c17e5654f7f106db96f92--gamut-preview.netlify.app>https://609c17e5654f7f106db96f92--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c17e5654f7f106db96f92>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-12 20:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.7541d1.0<br/>@codecademy/gamut-labs@16.0.2-alpha.7541d1.0<br/>@codecademy/styleguide@37.5.5-alpha.7541d1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-12 20:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c3a5f5a3f7a1f528e0dfa--gamut-preview.netlify.app>https://609c3a5f5a3f7a1f528e0dfa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c3a5f5a3f7a1f528e0dfa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-13 14:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.62af9e.0<br/>@codecademy/gamut-labs@16.0.2-alpha.62af9e.0<br/>@codecademy/styleguide@37.5.5-alpha.62af9e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-13 14:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609d385ccd7e5903fd389261--gamut-preview.netlify.app>https://609d385ccd7e5903fd389261--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609d385ccd7e5903fd389261>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-14 14:06 UTC, sooinc approved these changes
Checked the profile page and it's looking good!

2021-05-14 14:06 UTC, sooinc commented on packages/gamut-labs/src/EmptySection/index.tsx
> +        maxWidth="822px"
Is this something we should adjust in future PR to work for other pages (ie. dashboard/achievements/workshop)?

2021-05-14 14:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.8d8bf1.0<br/>@codecademy/gamut-labs@16.0.2-alpha.8d8bf1.0<br/>@codecademy/styleguide@37.5.5-alpha.8d8bf1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-14 14:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609e87a461eaecea4e111c1c--gamut-preview.netlify.app>https://609e87a461eaecea4e111c1c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609e87a461eaecea4e111c1c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-14 14:43 UTC, jcenglish commented on packages/gamut-labs/src/EmptySection/index.tsx
> +        maxWidth="822px"
Possssibly, but I think this maxWidth will be fine for those. I went off the width for the section in My Workspaces, where it takes up all the columns and has an inner section width of 822px: https://www.figma.com/file/hPv0Q1QJZa3nfcxsmc8dHV/Build?node-id=122%3A4112

2021-05-14 14:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.740729.0<br/>@codecademy/gamut-labs@16.0.2-alpha.740729.0<br/>@codecademy/styleguide@37.5.5-alpha.740729.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-14 14:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609e9025885a4df410372b36--gamut-preview.netlify.app>https://609e9025885a4df410372b36--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609e9025885a4df410372b36>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-14 15:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.102-alpha.3f10d9.0<br/>@codecademy/gamut-labs@17.0.1-alpha.3f10d9.0<br/>@codecademy/styleguide@38.0.1-alpha.3f10d9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-14 15:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609e93e1949b2230d99ccc51--gamut-preview.netlify.app>https://609e93e1949b2230d99ccc51--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609e93e1949b2230d99ccc51>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-14 15:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.102-alpha.2b73fe.0<br/>@codecademy/gamut-labs@17.0.1-alpha.2b73fe.0<br/>@codecademy/styleguide@38.0.1-alpha.2b73fe.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-14 15:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609e96d6b9337b1e5c666e1c--gamut-preview.netlify.app>https://609e96d6b9337b1e5c666e1c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609e96d6b9337b1e5c666e1c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-14 18:19 UTC, codecaaron approved these changes
Awesome!  Nothing blocking looks great!

Some suggestions if you want to try them out, but no sweat if you wanna shipit!

2021-05-14 18:19 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +});
I think we can remove this if add <Box width={48} height={32}  /> inbetween the content and illustration here:

https://github.com/Codecademy/client-modules/pull/1705/files#diff-2aa502cf3c2e4c2a85b97f6dd1e970c4f2a13020bb0df60b1c88c81417ac2c66R143

2021-05-14 18:19 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +        flexBasis="100%"
```suggestion
```

I don't think we need this anymore :) since the container isn't flex.

2021-05-14 18:19 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +        right: { _: '-100vw', xl: '-96px' },
I think we can safely just make this the -96px for all designs :)

2021-05-14 21:12 UTC, jcenglish commented on packages/gamut-labs/src/EmptySection/index.tsx
> +        flexBasis="100%"
Is it not? Both this FlexBox and its container appear to be flex in dev tools. I put that there so it takes up the full width of its container, up to the maxWidth, so it wasn't too scrunched up.
![Screen Shot 2021-05-14 at 4 08 12 PM](https://user-images.githubusercontent.com/1149386/118326131-85737400-b4d2-11eb-9a56-76e0777999c2.png)

2021-05-14 21:13 UTC, merged

2021-05-14 21:18 UTC, codecaaron commented on packages/gamut-labs/src/EmptySection/index.tsx
> +        flexBasis="100%"
You are totally right :) - misread it!