Hackathon egg for learn page footer
Codecademy/client-modules pull request #1709
Opened 2021-05-03 18:45 UTC by borisonr

### Overview

When learners click on specific words in the footer it'll open cute p5 visualizations

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-05-03 20:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.70-alpha.9edf84.0<br/>@codecademy/gamut-labs@15.2.10-alpha.9edf84.0<br/>@codecademy/styleguide@36.11.2-alpha.9edf84.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 20:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60905ca5a7ea65009d2d9723--gamut-preview.netlify.app>https://60905ca5a7ea65009d2d9723--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60905ca5a7ea65009d2d9723>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 20:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.70-alpha.5db6a4.0<br/>@codecademy/gamut-labs@15.2.10-alpha.5db6a4.0<br/>@codecademy/styleguide@36.11.2-alpha.5db6a4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 20:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090621def5db1008dc2c516--gamut-preview.netlify.app>https://6090621def5db1008dc2c516--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090621def5db1008dc2c516>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-03 21:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.70-alpha.0a1c82.0<br/>@codecademy/gamut-labs@15.2.10-alpha.0a1c82.0<br/>@codecademy/styleguide@36.11.2-alpha.0a1c82.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-03 21:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6090661fa8c59e009f8e762d--gamut-preview.netlify.app>https://6090661fa8c59e009f8e762d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6090661fa8c59e009f8e762d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-04 13:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.71-alpha.85da07.0<br/>@codecademy/gamut-labs@15.2.11-alpha.85da07.0<br/>@codecademy/styleguide@36.11.3-alpha.85da07.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-04 13:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609152fa155aec21a0cc981d--gamut-preview.netlify.app>https://609152fa155aec21a0cc981d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609152fa155aec21a0cc981d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-04 15:43 UTC, JoshuaKGoldberg requested changes
Unit tests please? At least in this level I think it should be unit testable?

2021-05-04 15:43 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalFooter/FooterLegal/MadeIn.tsx
> +`;
Hmm. Is it possible to use one of the new `Anchor` variants for this instead? That's what they're made for.

2021-05-05 12:38 UTC, codecaaron commented on packages/gamut-labs/src/GlobalFooter/FooterLegal/MadeIn.tsx
> +`;
`<Anchor variant="interface" />` should work (orrrr we the new emotion `ButtonBase` might do the trick)

2021-05-05 17:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.79-alpha.c0a644.0<br/>@codecademy/gamut-labs@15.5.3-alpha.c0a644.0<br/>@codecademy/styleguide@36.14.1-alpha.c0a644.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 17:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092d2c3e6d3762a8423bc41--gamut-preview.netlify.app>https://6092d2c3e6d3762a8423bc41--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092d2c3e6d3762a8423bc41>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 17:23 UTC, borisonr commented on packages/gamut-labs/src/GlobalFooter/FooterLegal/__tests__/MadeIn-test.tsx
> +describe('MadeIn', () => {
apologies for being lazy on testing, just wanted to get this through :)
was there anything in particular you wanted tested @JoshuaKGoldberg ?

2021-05-05 17:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.80-alpha.88b104.0<br/>@codecademy/gamut-labs@15.5.4-alpha.88b104.0<br/>@codecademy/styleguide@36.14.2-alpha.88b104.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 17:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092d54d09811a00d116026f--gamut-preview.netlify.app>https://6092d54d09811a00d116026f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092d54d09811a00d116026f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 18:18 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalFooter/FooterLegal/index.tsx
> +  onMadeInClick?: (e: React.MouseEvent | React.KeyboardEvent) => void;
Recapping Slack convo: https://github.com/codecademy-engineering/Codecademy/pull/23488#discussion_r625835878 only reads from the event target, so maybe just pass `"made" | "in" ...`? (or `string` if you don't particularly care what the values are?)

2021-05-05 18:18 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalFooter/FooterLegal/__tests__/MadeIn-test.tsx
> +describe('MadeIn', () => {
LGTM 😄  thanks!

2021-05-05 18:18 UTC, JoshuaKGoldberg approved these changes

2021-05-05 18:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.80-alpha.964bd8.0<br/>@codecademy/gamut-labs@15.5.4-alpha.964bd8.0<br/>@codecademy/styleguide@36.14.2-alpha.964bd8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 18:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092e3f8ddcaf60f1cb125e5--gamut-preview.netlify.app>https://6092e3f8ddcaf60f1cb125e5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092e3f8ddcaf60f1cb125e5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 18:59 UTC, JoshuaKGoldberg approved these changes
Great!

2021-05-05 18:59 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalFooter/FooterLegal/MadeIn.tsx
> +      ©{` ${new Date().getFullYear()} `}{' '}
```suggestion
      ©{` ${new Date().getFullYear()} `}
```

2021-05-05 19:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.80-alpha.1009e4.0<br/>@codecademy/gamut-labs@15.5.4-alpha.1009e4.0<br/>@codecademy/styleguide@36.14.2-alpha.1009e4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 19:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6092f50a940b441307b80867--gamut-preview.netlify.app>https://6092f50a940b441307b80867--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6092f50a940b441307b80867>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-05 21:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.81-alpha.af531c.0<br/>@codecademy/gamut-labs@15.5.5-alpha.af531c.0<br/>@codecademy/styleguide@36.14.3-alpha.af531c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-05 21:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60930aeb0e482e257850bc16--gamut-preview.netlify.app>https://60930aeb0e482e257850bc16--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60930aeb0e482e257850bc16>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-06 14:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.83-alpha.6a0a92.0<br/>@codecademy/gamut-labs@15.5.7-alpha.6a0a92.0<br/>@codecademy/styleguide@37.0.1-alpha.6a0a92.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-06 14:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6093f8e7a111a500cd20c339--gamut-preview.netlify.app>https://6093f8e7a111a500cd20c339--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6093f8e7a111a500cd20c339>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-06 14:24 UTC, merged