feat(Flyout):
Codecademy/client-modules pull request #1740
Opened 2021-05-11 14:07 UTC by dreamwasp

### Overview
**DRAFT PR PLS IGNORE** 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-05-11 14:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.90-alpha.827045.0<br/>@codecademy/gamut-labs@15.8.3-alpha.827045.0<br/>@codecademy/gamut@32.16.1-alpha.827045.0<br/>@codecademy/styleguide@37.3.1-alpha.827045.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-11 14:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609a937acab2cd0b26a4d3c5--gamut-preview.netlify.app>https://609a937acab2cd0b26a4d3c5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609a937acab2cd0b26a4d3c5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-11 19:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.90-alpha.d93d4f.0<br/>@codecademy/gamut-labs@15.8.3-alpha.d93d4f.0<br/>@codecademy/styleguide@37.3.1-alpha.d93d4f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-11 19:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.90-alpha.e4d435.0<br/>@codecademy/gamut-labs@15.8.3-alpha.e4d435.0<br/>@codecademy/styleguide@37.3.1-alpha.e4d435.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-26 15:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.119-alpha.5e0b68.0<br/>@codecademy/gamut-labs@18.2.2-alpha.5e0b68.0<br/>@codecademy/styleguide@40.0.7-alpha.5e0b68.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-26 15:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ae6d912e40f922400213c5--gamut-preview.netlify.app>https://60ae6d912e40f922400213c5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ae6d912e40f922400213c5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-26 21:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.119-alpha.caeb5a.0<br/>@codecademy/gamut-labs@18.2.2-alpha.caeb5a.0<br/>@codecademy/styleguide@40.0.7-alpha.caeb5a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-26 21:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60aec2637d74cd1417cd7d62--gamut-preview.netlify.app>https://60aec2637d74cd1417cd7d62--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60aec2637d74cd1417cd7d62>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-27 19:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.119-alpha.d27305.0<br/>@codecademy/gamut-labs@18.2.2-alpha.d27305.0<br/>@codecademy/styleguide@40.0.7-alpha.d27305.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-27 19:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60aff30984d1c710ab5b1e77--gamut-preview.netlify.app>https://60aff30984d1c710ab5b1e77--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60aff30984d1c710ab5b1e77>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-28 21:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.119-alpha.7a076b.0<br/>@codecademy/gamut-labs@18.2.2-alpha.7a076b.0<br/>@codecademy/styleguide@40.0.7-alpha.7a076b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-28 21:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b162e3be5f6c21ba683da4--gamut-preview.netlify.app>https://60b162e3be5f6c21ba683da4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b162e3be5f6c21ba683da4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-02 20:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.7-alpha.73622e.0<br/>@codecademy/gamut-labs@18.4.1-alpha.73622e.0<br/>@codecademy/styleguide@40.3.5-alpha.73622e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-02 20:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b7edd5ea50f63bcd26e695--gamut-preview.netlify.app>https://60b7edd5ea50f63bcd26e695--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b7edd5ea50f63bcd26e695>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-03 18:32 UTC, MattSchiller reviewed
Code looks great! Just trying to review more PRs so I'm more aware of what's going on so I left some thoughts I had about it. I hope they're useful!

2021-06-03 18:32 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/SidebarCloneButton.tsx
> +}) => {
Is there any danger from keys in `ButtonDeprecatedBaseProps` not being passed into the clone? Would it be more scalable to have this read:
```ts
export const SidebarCloneButton: React.FC<SidebarCloneButtonProps> = ({ 
  children, 
  ...rest
 }) => {
  if (React.isValidElement(children)) {
    return React.cloneElement(children, rest);
  }
```

2021-06-03 18:32 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +    screen.getByTestId('flyout-content');
Is the use of `screen` a preferred testing pattern over `view`? It's surely terser, so I'm interested if maybe we don't want to just move to that style for more of our tests? I'm imagining portal-app as this place where we can use all the latest & greatest patterns, and this looks awesome.

2021-06-03 18:32 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +    });
Just wondering if this test should maybe be wrapped in an `act` or something. If the previous test needs to wait for async activity to finish before we can confirm that the element has closed, shouldn't we also have a similar type of waiting strategy so that we can ensure this test isn't passing just because it's checking before any inner async activity is occuring.

Put another way, would this test pass, as written, if `escapeCloses: true`?

2021-06-03 18:32 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +  });
hyper nit (feel free to ignore): For test pairs like this, I like to group them like:
```ts
describe('clicking outside flyout', () => {
  it('closes flyout if clickOutsideCloses is true', () => { });

  it('does not close flyout if clickOutsideCloses is false', () => { });
});
```
Quite minor, especially in this instance, but I find it helps structure tests for easier addition/editing in the future.

2021-06-03 18:32 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/index.tsx
> +);
Super helpful for other Gamut work for me to see how these patterns are meant to be used 😍

2021-06-03 18:32 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +const renderFlyout = setupRtl(FlyoutContainer);
Not saying this should be changed, just wanted to call out that our `component-test-setup` is set up to handle this kind of use case:
```ts
const renderFlyout = setupRtl(FlyoutContainer, {
  button: <button type="button">Test</button>,
  children: <div data-testid="flyout-content">Howdy!</div>
});

renderFlyout.options({
  wrapper: ({ children }) => <div data-testid="flyout-outside">{children}</div>
})
```

Not sure this is any clearer, though it does offload props-handling to the helper. It also allows us to leverage `component-test-setup`'s required props checking if/as the component changes over time.

2021-06-03 18:32 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/index.tsx
> +  ]);
nit: if you want to save some memory from regenerating this and derivative functions on every toggle, can get the value directly from the `set*`
```ts
const toggleDrawer = useCallback(() => setSidebarOpen(isSidebarOpen => !isSidebarOpen), []);
```

2021-06-03 18:33 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +  ]);
TIL

2021-06-07 17:28 UTC, aresnik11 commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +const renderFlyout = setupRtl(FlyoutContainer);
i think we're doing it like this because we need to have an outside container to be able to click outside of the flyout, this is how `FocusTrap` and `Overlay` tests are set up as well

2021-06-07 17:31 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +const renderFlyout = setupRtl(FlyoutContainer);
I think we're saying the same things =) 

- `wrapper` provides said outside wrapper
- I would posit that those two test suites aren't leveraging our `CTS` library to its fullest

Not a big deal either way though, just wanted to point it out/get ahead of locking into a less-type-inferrable pattern 🙇

2021-06-07 17:37 UTC, aresnik11 commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +const renderFlyout = setupRtl(FlyoutContainer);
ah sorry i didn't read the code close enough. will try this!

2021-06-07 17:47 UTC, aresnik11 commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +    screen.getByTestId('flyout-content');
i need to look into this more. i thought we needed `screen` in some instances where we were clicking/looking at the container holding the flyout but now i'm not so sure. this was also how it was done in `FocusTrap` and `Overlay` tests

2021-06-07 17:52 UTC, aresnik11 commented on packages/gamut-labs/src/Flyout/SidebarCloneButton.tsx
> +}) => {
defer to @dreamwasp who wrote this code

2021-06-07 18:03 UTC, aresnik11 commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +    screen.getByTestId('flyout-content');
relevant https://stackoverflow.com/questions/64792767/what-is-the-difference-between-getbytext-and-screen-getbytext-in-rtl

2021-06-07 21:22 UTC, JoshuaKGoldberg requested changes
Excited to see this come together!

2021-06-07 21:22 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
Well now this is... different from what we normally do 👀

Why do we need so much customization over the button? Can we have people pass in a limited set of props as an object? Or even better, not give them control over it at all?

In addition to being confusing to debug through, `React.cloneElement` is a little difficult for type systems to wrangle with. Sometimes you end up with confusing situations like:

```tsx
interface OnClickRequiredButtonProps {
  onClick: () => void;
}

const OnClickRequiredButton: React.FC<OnClickRequiredButtonProps> = ({ onClick }) => {
  // ...
};

<Flyout button={<OnClickRequiredButton />} ... />;
```

2021-06-07 21:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Flyout.stories.mdx
> +            <TextButton height="5rem" width="5rem">
Nit:

![Screenshot of button focus state overlapping button text](https://user-images.githubusercontent.com/3335181/121088730-2c86bb00-c7b4-11eb-9c74-b4102a99a54a.png)

Maybe:

```suggestion
            <TextButton>
```

2021-06-07 21:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Flyout.stories.mdx
> +    subtitle: 'A good description of the Flyout component',
Ironically, this is a bad description. 😉

2021-06-07 21:22 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Flyout.stories.mdx
> +<Canvas>
So is the intent of this flyout to be a general container, filled with whatever abstract contents go inside it? I'm wondering if we have enough knowledge of all the existing use cases (catalog nav, LE side menus, etc.) that we could specify a bit more: maybe a dark/light mode with a full background...?

Whatever the answer is, could you document it in this story?

2021-06-07 21:29 UTC, aresnik11 commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
defer to @dreamwasp who wrote this code

2021-06-07 21:31 UTC, rogervera commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +  });
I think that's easier to read as well. Neat! Thanks

2021-06-07 21:41 UTC, rogervera commented on packages/styleguide/stories/Molecules/Flyout.stories.mdx
> +    subtitle: 'A good description of the Flyout component',
Hehe will update.

2021-06-07 21:51 UTC, rogervera commented on packages/styleguide/stories/Molecules/Flyout.stories.mdx
> +<Canvas>
Based on existing use cases, the flyout is a general container for mobile/tablet menu navigation. I think the story can be updated to resemble the catalog use case. But I'm comfortable holding off on replicating other cases for now. Thoughts?

2021-06-07 21:53 UTC, rogervera commented on packages/styleguide/stories/Molecules/Flyout.stories.mdx
> +<Canvas>
For what it's worth, we do have a story on this already in the follow up LayoutMenu PR. (The Gamut component for the catalog use case)
https://github.com/Codecademy/client-modules/pull/1784

2021-06-08 14:37 UTC, dreamwasp commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
yeah, this is pretty old code at this point. i can refactor this bit @aresnik11 !

my OG thought behind using clone instead of a more structured button is we use this in a couple of places with Anchors instead of Buttons, but i think we should standardize it more instead of matching old design/code

2021-06-08 16:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.13-alpha.70c31a.0<br/>@codecademy/gamut-labs@19.0.6-alpha.70c31a.0<br/>@codecademy/styleguide@41.2.4-alpha.70c31a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-08 16:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bf9b387cf5100f314a8650--gamut-preview.netlify.app>https://60bf9b387cf5100f314a8650--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bf9b387cf5100f314a8650>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-08 16:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.13-alpha.e5d67b.0<br/>@codecademy/gamut-labs@19.0.6-alpha.e5d67b.0<br/>@codecademy/styleguide@41.2.4-alpha.e5d67b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-08 16:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bf9dffb4b9c30e1912d587--gamut-preview.netlify.app>https://60bf9dffb4b9c30e1912d587--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bf9dffb4b9c30e1912d587>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-08 16:57 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +    screen.getByTestId('flyout-content');
This is exactly what I was looking for, thank you!

My vote is we move to using `screen` where possible. I think the syntax is just cleaner when we don't have to destructure the render result.

It's a little bit magical, but so easy on the eyes 😍

2021-06-08 17:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.13-alpha.04bcce.0<br/>@codecademy/gamut-labs@19.0.6-alpha.04bcce.0<br/>@codecademy/styleguide@41.2.4-alpha.04bcce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-08 17:36 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
Thanks Cass

2021-06-08 17:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60bfaad4663bba1703acfb0b--gamut-preview.netlify.app>https://60bfaad4663bba1703acfb0b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60bfaad4663bba1703acfb0b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-09 21:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.13-alpha.daf3aa.0<br/>@codecademy/gamut-labs@19.0.6-alpha.daf3aa.0<br/>@codecademy/styleguide@41.2.4-alpha.daf3aa.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-09 21:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c1377b83e7990f9b72cea7--gamut-preview.netlify.app>https://60c1377b83e7990f9b72cea7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c1377b83e7990f9b72cea7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-09 22:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.14-alpha.85ff3c.0<br/>@codecademy/gamut-labs@19.1.1-alpha.85ff3c.0<br/>@codecademy/styleguide@41.3.1-alpha.85ff3c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-09 22:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c13baee1f3120db0ef5788--gamut-preview.netlify.app>https://60c13baee1f3120db0ef5788--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c13baee1f3120db0ef5788>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-10 20:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.20-alpha.d663bf.0<br/>@codecademy/gamut-labs@19.4.2-alpha.d663bf.0<br/>@codecademy/styleguide@41.7.2-alpha.d663bf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-10 20:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c274185936e539aeb364e7--gamut-preview.netlify.app>https://60c274185936e539aeb364e7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c274185936e539aeb364e7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-10 21:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.20-alpha.262f8a.0<br/>@codecademy/gamut-labs@19.4.2-alpha.262f8a.0<br/>@codecademy/styleguide@41.7.2-alpha.262f8a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-10 21:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c27f65c5a60e009fb28faa--gamut-preview.netlify.app>https://60c27f65c5a60e009fb28faa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c27f65c5a60e009fb28faa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 16:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.21-alpha.a0457a.0<br/>@codecademy/gamut-labs@19.4.3-alpha.a0457a.0<br/>@codecademy/styleguide@41.7.3-alpha.a0457a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 16:46 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
@rogervera I'm waiting on this to be changed to not use `React.cloneElement` as part of my review

2021-06-11 16:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c393c4d5b08300dbe1dcf7--gamut-preview.netlify.app>https://60c393c4d5b08300dbe1dcf7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c393c4d5b08300dbe1dcf7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 16:51 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
@dreamwasp, I can help out with this if you need. What's the difference between "a button clone" and a "more structured button" here? Can we just replaced the button clone with a Gamut Button?

2021-06-11 17:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.21-alpha.8d3fbf.0<br/>@codecademy/gamut-labs@19.4.3-alpha.8d3fbf.0<br/>@codecademy/styleguide@41.7.3-alpha.8d3fbf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 17:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c396f535a0ab008cad0dc0--gamut-preview.netlify.app>https://60c396f535a0ab008cad0dc0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c396f535a0ab008cad0dc0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 17:33 UTC, rogervera commented
> @rogervera This should be `clickOutsideDoesNotClose` right?

Fixed!

2021-06-11 17:42 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
What are thoughts on this for now? (cc: @aresnik11 since this would affect LayoutMenu)
```ts
buttonText: string
```
And having the button style be fixed.

2021-06-11 17:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.23-alpha.be06a9.0<br/>@codecademy/gamut-labs@19.5.1-alpha.be06a9.0<br/>@codecademy/styleguide@41.7.5-alpha.be06a9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 17:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c3a2802da43d09cff116ea--gamut-preview.netlify.app>https://60c3a2802da43d09cff116ea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c3a2802da43d09cff116ea>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 19:18 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
`renderButton` 4 lyf

2021-06-11 19:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.23-alpha.51d8b6.0<br/>@codecademy/gamut-labs@19.5.1-alpha.51d8b6.0<br/>@codecademy/styleguide@41.7.5-alpha.51d8b6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 19:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c3bf8dcb91b30cb337565c--gamut-preview.netlify.app>https://60c3bf8dcb91b30cb337565c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c3bf8dcb91b30cb337565c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 20:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.23-alpha.62a6c4.0<br/>@codecademy/gamut-labs@19.5.1-alpha.62a6c4.0<br/>@codecademy/styleguide@41.7.5-alpha.62a6c4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 20:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c3c24f62e97e0c879e8c67--gamut-preview.netlify.app>https://60c3c24f62e97e0c879e8c67--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c3c24f62e97e0c879e8c67>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 20:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.23-alpha.b7666a.0<br/>@codecademy/gamut-labs@19.5.1-alpha.b7666a.0<br/>@codecademy/styleguide@41.7.5-alpha.b7666a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 20:20 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +  renderButton: (onClick: () => void) => React.ReactNode;
@JoshuaKGoldberg, @dreamwasp, in response to resolve the concerns brought up in this thread:
https://github.com/Codecademy/client-modules/pull/1740#discussion_r650214707

@MattSchiller put forth this solution that allows customizability, but we no longer need `React.cloneElement`

2021-06-11 20:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c3c5b13836050b52723d0f--gamut-preview.netlify.app>https://60c3c5b13836050b52723d0f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c3c5b13836050b52723d0f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 20:21 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
A solution was put implemented by @MattSchiller that achieves customization, but nixes `React.cloneElement`

2021-06-11 20:22 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
See: https://github.com/Codecademy/client-modules/pull/1740/files#r650244315

2021-06-11 20:25 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +  closeFlyoutRef?: React.MutableRefObject<Function>;
Also big thank you to @MattSchiller for helping us arrive at a solution to:
- wanting to have the Flyout manage it's own state
- allow the parent component to `closeFlyout()` by using a ref.

2021-06-11 20:26 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +      <SidebarCloneButton onClick={onToggle} data-testid="arrow-sidebar-button">
@JoshuaKGoldberg would love your thoughts so we can get this in a good place to unblock https://github.com/Codecademy/client-modules/pull/1784 and https://github.com/codecademy-engineering/portal-app/pull/82! 🙏🏼

2021-06-11 20:29 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/index.tsx
> +  }, [closeFlyoutRef, closeFlyout]);
Ooo, we'll probs wanna change `closeFlyoutRef.current = () => closeFlyout;` to `closeFlyoutRef.current = closeFlyout;`

The woes of programming too fast!

We can also probably write a test for this. Lemme try in a sec

2021-06-11 20:31 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +  }, [closeFlyoutRef, closeFlyout]);
We want to do this because we don't want to use a lambda (`() => closeFlyout`)? We need a reference to closeFlyout?

2021-06-11 20:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.23-alpha.38174d.0<br/>@codecademy/gamut-labs@19.5.1-alpha.38174d.0<br/>@codecademy/styleguide@41.7.6-alpha.38174d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 20:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c3c8f3d0d30d10b89c175f--gamut-preview.netlify.app>https://60c3c8f3d0d30d10b89c175f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c3c8f3d0d30d10b89c175f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 21:13 UTC, rogervera commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +  it('passes the ability to close the flyout to passes ref', async () => {
Small typo in title here?

2021-06-11 21:13 UTC, rogervera commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +  it('passes the ability to close the flyout to passes ref', async () => {
Particularly:

> to passes ref

2021-06-11 21:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.23-alpha.22b237.0<br/>@codecademy/gamut-labs@19.5.1-alpha.22b237.0<br/>@codecademy/styleguide@41.7.6-alpha.22b237.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 21:14 UTC, rogervera commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +  it('passes the ability to close the flyout to passes ref', async () => {
Womp. Ya beat me https://github.com/Codecademy/client-modules/pull/1740/commits/9c45c3a03d52838a841df911e25030e1357d9019

2021-06-11 21:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c3d2a3727910244d44d074--gamut-preview.netlify.app>https://60c3d2a3727910244d44d074--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c3d2a3727910244d44d074>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 21:26 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +  }, [closeFlyoutRef, closeFlyout]);
Ah so we needed to ensure that the type of `() => {}` was upheld?
https://github.com/Codecademy/client-modules/blob/5194e664bc76321d0556eb9da374b3abb117a398/packages/gamut-labs/src/Flyout/index.tsx#L96-L99

2021-06-11 21:35 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
> +  it('passes the ability to close the flyout to passes ref', async () => {
`Gotta go fast!`

2021-06-11 21:37 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/index.tsx
> +  }, [closeFlyoutRef, closeFlyout]);
Not even, you're over thinking it!

`= () => closeFlyout` is just _wrong_ lol
`= () => closeFlyout()` is the correct syntax.

And if we're just running the function, we can pass it directly: `= closeFlyout`

2021-06-11 21:50 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +  }, [closeFlyoutRef, closeFlyout]);
Oh my lolllll.

2021-06-15 15:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.25-alpha.cfe01c.0<br/>@codecademy/gamut-labs@19.5.3-alpha.cfe01c.0<br/>@codecademy/styleguide@41.7.9-alpha.cfe01c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 15:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8c2e0da31740da016e48c--gamut-preview.netlify.app>https://60c8c2e0da31740da016e48c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8c2e0da31740da016e48c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 16:10 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/Flyout/index.tsx
> +        closeFlyoutRef.current = () => {};
Nit: maybe make this `(() => void) | undefined` and make the parent have to `?.()` call it, to be more explicit about it not existing maybe?

```suggestion
        closeFlyoutRef.current = undefined;
```

2021-06-15 16:10 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/Flyout/index.tsx
> +    // Passes the function up to any interested parent component
Heh, this is a clever solution for the case of the parent needing to call a function to close.

But: why do we want that for the parent? Does a `closed` prop not do it for us?

2021-06-15 16:38 UTC, MattSchiller commented on packages/gamut-labs/src/Flyout/index.tsx
> +    // Passes the function up to any interested parent component
Maybe, though I wasn't sure I was able to do that without also managing an equivalent of `isExpanded` in the parent.

Like, I wanted the prop to indicate the initial value, otherwise wouldn't we have to have logic in `Flyout` that would compare whether the previous value of the `closed` prop has changed, and that triggers a state update?

This just felt like a more direct implementation (though I might just not be getting it)

2021-06-15 16:58 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/Flyout/index.tsx
> +    // Passes the function up to any interested parent component
Gotcha - but is there a use case we're thinking of where the parent needs to signal that this should be closed?

2021-06-15 17:15 UTC, aresnik11 commented on packages/gamut-labs/src/Flyout/index.tsx
> +    // Passes the function up to any interested parent component
`LayoutMenu` needs to be able to close the flyout on click of a menu item

2021-06-15 17:21 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/Flyout/index.tsx
> +    // Passes the function up to any interested parent component
My instincts are telling me there should be a way to do this in a state-based manner instead of this imperative ref... but meh, that feels complicated and probably not worth it 😄

2021-06-15 17:21 UTC, JoshuaKGoldberg approved these changes
Cool!

2021-06-15 17:23 UTC, aresnik11 commented on packages/gamut-labs/src/Flyout/index.tsx
> +    // Passes the function up to any interested parent component
we initially had the parent component managing state to open/close the flyout for this scenario but that felt wrong

2021-06-15 18:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.26-alpha.1af8fa.0<br/>@codecademy/gamut-labs@19.6.1-alpha.1af8fa.0<br/>@codecademy/styleguide@41.7.11-alpha.1af8fa.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 18:53 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +        closeFlyoutRef.current = () => {};
Josh did you mean like this?
https://github.com/Codecademy/client-modules/pull/1740/commits/45d088c0af790cbed9d3892ea1532206cdfd1906

2021-06-15 18:54 UTC, rogervera commented on packages/styleguide/stories/Molecules/Flyout.stories.mdx
> +      'Flyout is a general container that is mobile/tablet menu navigation. On button click, a container animates in from the left side of the window. It can be configured to close by pressing the "X
Updated to reference LayoutMenu!

2021-06-15 18:55 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +  testId?: string;
Removed

2021-06-15 18:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.26-alpha.45d088.0<br/>@codecademy/gamut-labs@19.6.1-alpha.45d088.0<br/>@codecademy/styleguide@41.7.11-alpha.45d088.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 18:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8f8624dbb520b47d5218a--gamut-preview.netlify.app>https://60c8f8624dbb520b47d5218a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8f8624dbb520b47d5218a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 18:59 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +        closeFlyoutRef.current = () => {};
CC: @MattSchiller

2021-06-15 19:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8fa4c8adbd40e0debcece--gamut-preview.netlify.app>https://60c8fa4c8adbd40e0debcece--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8fa4c8adbd40e0debcece>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 19:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.27-alpha.611947.0<br/>@codecademy/gamut-labs@19.6.2-alpha.611947.0<br/>@codecademy/styleguide@41.7.12-alpha.611947.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 20:10 UTC, MattSchiller approved these changes
Flyout looks good to me! As long as the layout menu is also accomodating the possibly null function (with `?.()`) we should be good 👍

2021-06-15 20:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.27-alpha.130b84.0<br/>@codecademy/gamut-labs@19.6.2-alpha.130b84.0<br/>@codecademy/styleguide@41.7.12-alpha.130b84.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 20:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c9110c150d652482a17d3d--gamut-preview.netlify.app>https://60c9110c150d652482a17d3d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c9110c150d652482a17d3d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 20:46 UTC, rogervera commented on packages/gamut-labs/src/Flyout/index.tsx
> +        closeFlyoutRef.current = () => {};
Reverted the changes in https://github.com/Codecademy/client-modules/commit/45d088c0af790cbed9d3892ea1532206cdfd1906 to 

https://github.com/Codecademy/client-modules/pull/1740/commits/130b84631e3202547953a21fcdd3a2df66be52ad.

@MattSchiller put it as so:

> before, we could at least ensure that it was always a function
> but now it might be undefined
> so callers need to protect themselves, and without type safety there, too

2021-06-15 20:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.28-alpha.918982.0<br/>@codecademy/gamut-labs@19.6.3-alpha.918982.0<br/>@codecademy/styleguide@41.7.13-alpha.918982.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 20:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c9134165eb662874bb9ac4--gamut-preview.netlify.app>https://60c9134165eb662874bb9ac4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c9134165eb662874bb9ac4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 20:58 UTC, merged