fix(Input): fixed hidden field empty spaces
Codecademy/client-modules pull request #1746
Opened 2021-05-12 18:40 UTC by cstatro

### Overview

### PR Checklist

this PR makes sure our hidden fields don't create empty space inside of the gridform. I have some screenshots of the issue in the ticket below. 

- [ ] Related to designs:
- [x] Related to JIRA ticket: GROW-2350
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-05-12 18:47 UTC, JoshuaKGoldberg requested changes

2021-05-12 18:47 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
>            {...rest}
`rest` no longer includes `type`?

2021-05-12 18:47 UTC, j10sanders approved these changes
makes sense to me! not sure about using undefined though.

2021-05-12 18:47 UTC, j10sanders commented on packages/gamut/src/Form/Input.tsx
> +        display={type === 'hidden' ? 'none' : undefined}
maybe 'inherit' instead of undefined?

2021-05-12 18:58 UTC, cstatro commented on packages/gamut/src/Form/Input.tsx
>            {...rest}
whoops yep unit tests caught this , just pushed up the fix 😅

2021-05-12 19:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.a34f70.0<br/>@codecademy/gamut-labs@16.0.2-alpha.a34f70.0<br/>@codecademy/gamut@32.18.5-alpha.a34f70.0<br/>@codecademy/styleguide@37.5.5-alpha.a34f70.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-12 19:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609c26e94d264d00dcd91a9f--gamut-preview.netlify.app>https://609c26e94d264d00dcd91a9f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609c26e94d264d00dcd91a9f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-12 19:18 UTC, cstatro commented on packages/gamut/src/Form/Input.tsx
> +        display={type === 'hidden' ? 'none' : undefined}
my concern with doing that is that explicitly setting this to something that's normally implicit could have some unintended side effect, @JoshuaKGoldberg  you got any opinions on this?

2021-05-12 19:30 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +        display={type === 'hidden' ? 'none' : undefined}
Yeah my general inclination is to stick with `undefined` (as it is now) to keep things minimally different and not add extra CSS unless we need it.

2021-05-12 19:30 UTC, JoshuaKGoldberg reviewed
Looks reasonable to me, but @dreamwasp and @codecaaron have been working in this area more than me recently.

2021-05-12 20:16 UTC, codecaaron commented on packages/gamut/src/Form/Input.tsx
> +        display={rest?.type === 'hidden' ? 'none' : undefined}
Do bots check for visibility when filling these out? 

I generally see these honeytraps be `position: absolute; left: -10000px;` to preserve their visibility but not within the actual flow.

2021-05-13 18:31 UTC, cstatro commented on packages/gamut/src/Form/Input.tsx
> +        display={rest?.type === 'hidden' ? 'none' : undefined}
this isn't used for honey pots, just hidden inputs

2021-05-14 17:05 UTC, codecaaron approved these changes
LGTM

2021-05-14 22:28 UTC, JoshuaKGoldberg approved these changes
Cool!

2021-05-14 22:28 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/Input.tsx
> +        display={rest?.type === 'hidden' ? 'none' : undefined}
`rest` will always exist:

```suggestion
        display={rest.type === 'hidden' ? 'none' : undefined}
```

2021-05-17 16:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.97-alpha.ec94ec.0<br/>@codecademy/gamut-labs@16.0.2-alpha.ec94ec.0<br/>@codecademy/gamut@32.18.5-alpha.ec94ec.0<br/>@codecademy/styleguide@37.5.5-alpha.ec94ec.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-17 16:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.103-alpha.6a30dc.0<br/>@codecademy/gamut-labs@17.1.1-alpha.6a30dc.0<br/>@codecademy/gamut@32.18.8-alpha.6a30dc.0<br/>@codecademy/styleguide@38.1.1-alpha.6a30dc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-17 16:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60a29f77a2088f00bb12a4ad--gamut-preview.netlify.app>https://60a29f77a2088f00bb12a4ad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60a29f77a2088f00bb12a4ad>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-17 16:53 UTC, merged