fix(Anchor): Allow Cards to be hovered inside Anchors
Codecademy/client-modules pull request #1757
Opened 2021-05-14 15:10 UTC by codecaaron

### Overview

* Fixes a stacking context issue with Anchors that prevented their children from being hovered on their own.
* Adds story

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-05-14 15:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.3.102-alpha.440178.0<br/>@codecademy/gamut-labs@17.0.1-alpha.440178.0<br/>@codecademy/gamut@32.18.8-alpha.440178.0<br/>@codecademy/styleguide@38.0.1-alpha.440178.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-05-14 15:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://609e9508d93f45f4dee4e976--gamut-preview.netlify.app>https://609e9508d93f45f4dee4e976--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/609e9508d93f45f4dee4e976>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-05-14 17:30 UTC, dreamwasp approved these changes

2021-05-14 20:31 UTC, aresnik11 approved these changes
yay!!! thanks for fixing

2021-05-14 22:22 UTC, JoshuaKGoldberg requested changes
In theory I like this approach very much but... Edge support? 😬

2021-05-14 22:22 UTC, JoshuaKGoldberg commented on packages/gamut/src/Anchor/index.tsx
> +      inset: -4,
Not supported by Edge 😞 

https://caniuse.com/?search=inset

2021-05-14 22:30 UTC, codecaaron commented on packages/gamut/src/Anchor/index.tsx
> +      inset: -4,
Should have mentioned / made a comment that this doesn't actually use the inset property and is acting like a polyfill and actually just templates all `top` `left` `bottom` `right` instead.

https://github.com/Codecademy/client-modules/blob/main/packages/gamut-styles/src/variance/config.ts#L154

If properties array is configured property is ignored, and it will template the values for all properties specified (to avoid situations like this where we can't have nice things).

2021-05-15 03:48 UTC, JoshuaKGoldberg commented on packages/gamut/src/Anchor/index.tsx
> +      inset: -4,
Aha! Right! I remember now, yes, great.

2021-05-15 03:48 UTC, JoshuaKGoldberg approved these changes
💯

2021-06-02 13:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.5-alpha.a94a11.0<br/>@codecademy/gamut-labs@18.3.5-alpha.a94a11.0<br/>@codecademy/gamut@33.4.3-alpha.a94a11.0<br/>@codecademy/styleguide@40.3.3-alpha.a94a11.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-02 13:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b78672e964ca2dc5596b5e--gamut-preview.netlify.app>https://60b78672e964ca2dc5596b5e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b78672e964ca2dc5596b5e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-02 20:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.7-alpha.72f38f.0<br/>@codecademy/gamut-labs@18.4.1-alpha.72f38f.0<br/>@codecademy/gamut@33.4.4-alpha.72f38f.0<br/>@codecademy/styleguide@40.3.5-alpha.72f38f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-02 20:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b7f0f90567b84163322356--gamut-preview.netlify.app>https://60b7f0f90567b84163322356--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b7f0f90567b84163322356>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-02 21:14 UTC, merged