feat(icons): Adds LE trophy and certificate filled icons
Codecademy/client-modules pull request #1804
Opened 2021-06-03 15:50 UTC by timjenkins

### Overview
Adds `TropyFilledIcon` to be used in the progress indicator of the new Path Syllabus page. 
![image](https://user-images.githubusercontent.com/2678444/120674041-b3a8fb80-c461-11eb-9334-25c0b85e0a61.png)

Adds `CertificateFilledIcon` to be used on the Path Syllabus page to reflect the achievement that can be earned on completion
![image](https://user-images.githubusercontent.com/2678444/120674262-ed7a0200-c461-11eb-9828-482330f0cdc1.png)

Adds `TrophyFilledIcon` and `CertificateFilledIcon` for Syllabus upgrade

### PR Checklist

- [ ] Related to designs: [Syllabus Upgrade Figma](https://www.figma.com/file/nWkEaTqiV12SGbbZS0Gmr4/Syllabus-Improvements?node-id=573%3A1)
- [ ] Related to JIRA ticket: LX-4800
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-06-03 18:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.0-alpha.a47584.0<br/>@codecademy/gamut-kit@0.4.8-alpha.a47584.0<br/>@codecademy/gamut-labs@19.0.1-alpha.a47584.0<br/>@codecademy/gamut@34.0.1-alpha.a47584.0<br/>@codecademy/styleguide@41.1.0-alpha.a47584.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-03 18:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60b91d5231f0321a75edbab5--gamut-preview.netlify.app>https://60b91d5231f0321a75edbab5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60b91d5231f0321a75edbab5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-03 20:20 UTC, dreamwasp requested changes

2021-06-03 20:20 UTC, dreamwasp commented on packages/gamut-icons/src/svg/regular/certificate-filled-icon.svg
> +    fill="#10162F" />
i think we want fill to be set to `currentColor` -- correct me if i'm wrong @codecaaron !

2021-06-03 20:20 UTC, dreamwasp commented on packages/gamut-icons/src/svg/regular/certificate-filled-icon.svg
> +  <path
pls add a `title` (the other icon is ✨)

2021-06-04 18:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@4.15.0-alpha.d68eb0.0<br/>@codecademy/gamut-kit@0.4.7-alpha.d68eb0.0<br/>@codecademy/gamut-labs@18.4.1-alpha.d68eb0.0<br/>@codecademy/gamut@33.4.4-alpha.d68eb0.0<br/>@codecademy/styleguide@40.4.0-alpha.d68eb0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-04 18:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ba7679c6098400b484976e--gamut-preview.netlify.app>https://60ba7679c6098400b484976e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ba7679c6098400b484976e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-04 18:53 UTC, dreamwasp approved these changes
✨

2021-06-04 18:53 UTC, dreamwasp commented on packages/gamut-icons/src/svg/regular/certificate-filled-icon.svg
> +  <title>certificate star</title>
```suggestion
  <title>certificate-star</title>
```
this is just the naming convention we

2021-06-04 19:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.0-alpha.e4df5e.0<br/>@codecademy/gamut-kit@0.4.8-alpha.e4df5e.0<br/>@codecademy/gamut-labs@19.0.1-alpha.e4df5e.0<br/>@codecademy/gamut@34.0.1-alpha.e4df5e.0<br/>@codecademy/styleguide@41.2.0-alpha.e4df5e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-04 19:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ba7ea325a1b00d4d7c8974--gamut-preview.netlify.app>https://60ba7ea325a1b00d4d7c8974--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ba7ea325a1b00d4d7c8974>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-05 00:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.0-alpha.372ebb.0<br/>@codecademy/gamut-kit@0.4.8-alpha.372ebb.0<br/>@codecademy/gamut-labs@19.0.1-alpha.372ebb.0<br/>@codecademy/gamut@34.0.1-alpha.372ebb.0<br/>@codecademy/styleguide@41.2.0-alpha.372ebb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-05 00:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60babf0f74244f65f9f51646--gamut-preview.netlify.app>https://60babf0f74244f65f9f51646--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60babf0f74244f65f9f51646>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-06 14:20 UTC, codecaaron commented on packages/gamut-icons/src/svg/regular/certificate-filled-icon.svg
> +  <title>certificate-star</title>
These titles actually get stripped out by SVGR and renamed, so I like to keep these as the slug from [streamline](https://app.streamlinehq.com/icons/streamline-bold) `discount-star-premium` as ~some~ source of truth level.

2021-06-07 14:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60be2765c58849a2c0dff778--gamut-preview.netlify.app>https://60be2765c58849a2c0dff778--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60be2765c58849a2c0dff778>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-07 14:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.1.0-alpha.2e36e5.0<br/>@codecademy/gamut-kit@0.4.9-alpha.2e36e5.0<br/>@codecademy/gamut-labs@19.0.2-alpha.2e36e5.0<br/>@codecademy/gamut@34.0.2-alpha.2e36e5.0<br/>@codecademy/styleguide@41.2.0-alpha.2e36e5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-07 14:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60be2d7d515884cf62102707--gamut-preview.netlify.app>https://60be2d7d515884cf62102707--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60be2d7d515884cf62102707>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-07 14:34 UTC, merged