start scaffolding
Codecademy/client-modules pull request #1818
Opened 2021-06-08 21:54 UTC by dreamwasp

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-06-11 19:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.23-alpha.d1c870.0<br/>@codecademy/gamut-labs@19.5.1-alpha.d1c870.0<br/>@codecademy/gamut@34.6.1-alpha.d1c870.0<br/>@codecademy/styleguide@41.7.5-alpha.d1c870.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-14 17:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.23-alpha.b18454.0<br/>@codecademy/gamut-labs@19.5.1-alpha.b18454.0<br/>@codecademy/gamut@34.6.1-alpha.b18454.0<br/>@codecademy/styleguide@41.7.7-alpha.b18454.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-14 17:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c78c0a9fa1d511e08e739b--gamut-preview.netlify.app>https://60c78c0a9fa1d511e08e739b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c78c0a9fa1d511e08e739b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 18:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.26-alpha.3f9145.0<br/>@codecademy/gamut-labs@19.6.1-alpha.3f9145.0<br/>@codecademy/gamut@34.7.1-alpha.3f9145.0<br/>@codecademy/styleguide@41.7.11-alpha.3f9145.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 18:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8eb9f36ae5000d60e99ec--gamut-preview.netlify.app>https://60c8eb9f36ae5000d60e99ec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8eb9f36ae5000d60e99ec>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 18:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.26-alpha.7aafe2.0<br/>@codecademy/gamut-labs@19.6.1-alpha.7aafe2.0<br/>@codecademy/gamut@34.7.1-alpha.7aafe2.0<br/>@codecademy/styleguide@41.7.11-alpha.7aafe2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 18:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8f61083189009a7e53bfa--gamut-preview.netlify.app>https://60c8f61083189009a7e53bfa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8f61083189009a7e53bfa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 19:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.27-alpha.4e6e5a.0<br/>@codecademy/gamut-labs@19.6.2-alpha.4e6e5a.0<br/>@codecademy/gamut@34.7.2-alpha.4e6e5a.0<br/>@codecademy/styleguide@41.7.12-alpha.4e6e5a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 19:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c8fa5d37e04b0b95328173--gamut-preview.netlify.app>https://60c8fa5d37e04b0b95328173--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c8fa5d37e04b0b95328173>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 19:30 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSections/GridFormSectionBreak.tsx
> +};
@codecaaron maybe we can consolidate this + the menu `hr`

2021-06-15 19:32 UTC, dreamwasp commented on packages/gamut/src/GridForm/index.tsx
> +
i moved this to here from types to keep it internal to the pkg - lmk if i should move it back

2021-06-15 19:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.27-alpha.8234e5.0<br/>@codecademy/gamut-labs@19.6.2-alpha.8234e5.0<br/>@codecademy/gamut@34.7.2-alpha.8234e5.0<br/>@codecademy/styleguide@41.7.12-alpha.8234e5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 19:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c900df72003b0ad97081ab--gamut-preview.netlify.app>https://60c900df72003b0ad97081ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c900df72003b0ad97081ab>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 19:51 UTC, JoshuaKGoldberg requested changes
The general structure looks great! Nitpicking a bit around naming and props...

...but also, unit tests please? 😈

2021-06-15 19:51 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/types.ts
> +  as?: any;
```suggestion
  as?: 'h2' | 'h3' | 'h4';
```

2021-06-15 19:51 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/index.tsx
> +  fields?: GridFormFieldsProps[];
`fields` is kind of an odd name to describe something that could be "fields" _or_ "sections"... maybe, `sections` as the name?

2021-06-15 19:51 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormSections/GridFormQuestion.tsx
> +export type GridFormQuestionProps = {
"Question" is not a word I was expecting to apply here, and I got confused by it at first 😅 . 

I'm a little loathe to add to the already big `GridFormInputGroup` component, so maybe... `GridFormSectionContents`?

2021-06-15 19:51 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/types.ts
> +export type GridFormSectionType = GridFormSectionTitleBaseProps & {
Nit: this is a "type", no need to include that in the name.

```suggestion
export type GridFormSection = GridFormSectionTitleBaseProps & {
```

2021-06-15 19:51 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/types.ts
> +  layout?: 'center' | 'left';
Do we already have designs that call for the centered alignment?

2021-06-15 19:52 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Organisms/GridForm.stories.mdx
> +Each sections should have a title that correctly follows (heading ranks)[https://usability.yale.edu/web-accessibility/articles/headings]. You can set the text type of this title though the `as` prop
oop

![Screenshot of an invalid Storybook link](https://user-images.githubusercontent.com/3335181/122114801-b4db1080-cdf1-11eb-994e-75016702f8f6.png)

2021-06-15 20:48 UTC, dreamwasp commented on packages/gamut/src/GridForm/types.ts
> +  as?: any;
word - i'm swapping this over over to h1 through h6 -- theoretically i think a form could take up the whole page + need the h1 tag.

2021-06-15 20:51 UTC, dreamwasp commented on packages/gamut/src/GridForm/index.tsx
> +  fields?: GridFormFieldsProps[];
i wanted to make this change _not_ breaking so kept the naming convention and clean things up a bit more when i do more of this work. theoretically i think it's just as weird to have a prop called `sections` that sometimes renders just `fields` but pretty ambivalent either way 🙂

2021-06-15 20:52 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSections/GridFormQuestion.tsx
> +export type GridFormQuestionProps = {
yeah i was somewhat at a loss with what to name these... these aren't _always_ section contents and are sometime just the field. will noodle on a better name!

2021-06-15 20:53 UTC, dreamwasp commented on packages/gamut/src/GridForm/types.ts
> +export type GridFormSectionType = GridFormSectionTitleBaseProps & {
It goofs with the name of the GridFormSection component. swapping it over to GridFormSectionProps

2021-06-15 20:54 UTC, dreamwasp commented on packages/gamut/src/GridForm/types.ts
> +  layout?: 'center' | 'left';
eh, i figured it was just standard-ish looking

2021-06-15 20:55 UTC, dreamwasp commented on packages/styleguide/stories/Organisms/GridForm.stories.mdx
> +Each sections should have a title that correctly follows (heading ranks)[https://usability.yale.edu/web-accessibility/articles/headings]. You can set the text type of this title though the `as` prop
oop

2021-06-15 20:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.27-alpha.35aff6.0<br/>@codecademy/gamut-labs@19.6.2-alpha.35aff6.0<br/>@codecademy/gamut@34.7.2-alpha.35aff6.0<br/>@codecademy/styleguide@41.7.12-alpha.35aff6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 21:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c9153502b23c2bb83fe0e2--gamut-preview.netlify.app>https://60c9153502b23c2bb83fe0e2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c9153502b23c2bb83fe0e2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-15 21:24 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/index.tsx
> +  fields?: GridFormFieldsProps[];
Oh right I'd meant to say `content`? 😄 

But yeah that makes sense. Whatever you prefer!

2021-06-15 21:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.30-alpha.7897d7.0<br/>@codecademy/gamut-labs@19.8.1-alpha.7897d7.0<br/>@codecademy/gamut@34.7.2-alpha.7897d7.0<br/>@codecademy/styleguide@41.9.1-alpha.7897d7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 21:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c9205937e04b36ff328128--gamut-preview.netlify.app>https://60c9205937e04b36ff328128--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c9205937e04b36ff328128>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-16 21:39 UTC, songstephen commented on packages/gamut/src/GridForm/GridFormSections/GridFormSectionBreak.tsx
> +        width="90%"
Where did we get the `width="90%"` property from? Was wondering if we should bump it up to 100% to align the dividers to the grid more

2021-06-16 21:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.30-alpha.d91700.0<br/>@codecademy/gamut-labs@19.8.1-alpha.d91700.0<br/>@codecademy/gamut@34.7.2-alpha.d91700.0<br/>@codecademy/styleguide@41.9.1-alpha.d91700.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-16 21:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca724d9179a300cb8810bf--gamut-preview.netlify.app>https://60ca724d9179a300cb8810bf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca724d9179a300cb8810bf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-16 22:48 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/types.ts
> +  layout?: 'center' | 'left';
I'll defer to @songstephen but my preference would be that we don't add feature complexity unless we need it

2021-06-16 22:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.30-alpha.69cf9e.0<br/>@codecademy/gamut-labs@19.8.1-alpha.69cf9e.0<br/>@codecademy/gamut@34.7.2-alpha.69cf9e.0<br/>@codecademy/styleguide@41.9.1-alpha.69cf9e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-16 22:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca80ab9179a30b798811f5--gamut-preview.netlify.app>https://60ca80ab9179a30b798811f5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca80ab9179a30b798811f5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 13:49 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSections/GridFormSectionBreak.tsx
> +        width="90%"
it comes from me incorrectly eyeballing [these designs](https://www.figma.com/file/PG0kVYDIuLk3hE566beZUV/Profiles-(Concept-Refinement-V0.1%2BV0.2)?node-id=998%3A0), i'll change it to `100%`!

2021-06-17 15:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.30-alpha.cc19b1.0<br/>@codecademy/gamut-labs@19.8.1-alpha.cc19b1.0<br/>@codecademy/gamut@34.7.2-alpha.cc19b1.0<br/>@codecademy/styleguide@41.9.1-alpha.cc19b1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 15:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cb70577087db178195c406--gamut-preview.netlify.app>https://60cb70577087db178195c406--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cb70577087db178195c406>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 21:38 UTC, sooinc approved these changes
This looks great, thank you for rejiggering gridform to add in this feature. Also for adding all the unit tests!!

2021-06-17 21:44 UTC, dreamwasp commented on packages/gamut/src/GridForm/types.ts
> +  layout?: 'center' | 'left';
thought about this a bit today - will defer to @songstephen but i think we need something like `center` for mobile/zoom accessibility anyway (and have set up `GridFormSectionTitle` to be zoom/mobile friendly!)

2021-06-22 21:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.1930ce.0<br/>@codecademy/gamut-labs@19.11.1-alpha.1930ce.0<br/>@codecademy/gamut@34.10.8-alpha.1930ce.0<br/>@codecademy/styleguide@41.10.15-alpha.1930ce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-22 22:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d25d912ab7220089c98322--gamut-preview.netlify.app>https://60d25d912ab7220089c98322--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d25d912ab7220089c98322>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-23 20:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.41317d.0<br/>@codecademy/gamut-labs@19.11.2-alpha.41317d.0<br/>@codecademy/gamut@34.10.9-alpha.41317d.0<br/>@codecademy/styleguide@41.10.16-alpha.41317d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-23 20:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d39ea894ebdc18debf27f2--gamut-preview.netlify.app>https://60d39ea894ebdc18debf27f2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d39ea894ebdc18debf27f2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 20:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.2d0742.0<br/>@codecademy/gamut-labs@19.12.2-alpha.2d0742.0<br/>@codecademy/gamut@34.11.1-alpha.2d0742.0<br/>@codecademy/styleguide@41.10.22-alpha.2d0742.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 20:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d636bf2b36990a900d770d--gamut-preview.netlify.app>https://60d636bf2b36990a900d770d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d636bf2b36990a900d770d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 20:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.ec8826.0<br/>@codecademy/gamut-labs@19.12.2-alpha.ec8826.0<br/>@codecademy/gamut@34.11.1-alpha.ec8826.0<br/>@codecademy/styleguide@41.10.22-alpha.ec8826.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 20:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d63c18630d471643144429--gamut-preview.netlify.app>https://60d63c18630d471643144429--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d63c18630d471643144429>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 20:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.f34a98.0<br/>@codecademy/gamut-labs@19.12.2-alpha.f34a98.0<br/>@codecademy/gamut@34.11.1-alpha.f34a98.0<br/>@codecademy/styleguide@41.10.22-alpha.f34a98.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 20:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d6412fe865f01a92d58422--gamut-preview.netlify.app>https://60d6412fe865f01a92d58422--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d6412fe865f01a92d58422>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 21:57 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Organisms/GridForm.stories.mdx
> +We call it a "sweet container" so that bots do not immediately detect it as a honeypot input. test
oop

```suggestion
We call it a "sweet container" so that bots do not immediately detect it as a honeypot input.
```

2021-06-25 21:58 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormSections/GridFormContent.tsx
> +        error={errorMessage as string}
Nit: saw this in another PR

```suggestion
        error={errorMessage}
```

2021-06-25 21:59 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormSections/__tests__/GridFormSection-test.tsx
> +    expect(await view.findByText('not enough updog')).toBeTruthy();
RTL rejects if the element isn't found:

```suggestion
   await view.findByText('what is it?');
   await view.findByText('not enough updog');
```

2021-06-25 22:00 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/GridFormSections/__tests__/GridFormSectionTitle-test.tsx
> +    expect(gridRowEnd).toEqual({ _: 'span 1', md: 'span 3' });
Nit / food for thought: you could combine this into one assertion if you wanted...

```suggestion
    expect({ gridRowEnd, size }).toEqual({
      gridRowEnd: { _: 'span 1', md: 'span 3' },
      size: { _: 12, md: 3 },
    });
```

...I'm not sure how I feel about this 😂

2021-06-25 22:00 UTC, JoshuaKGoldberg approved these changes
Awesome!

2021-06-25 22:02 UTC, dreamwasp commented on packages/gamut/src/GridForm/GridFormSections/__tests__/GridFormSectionTitle-test.tsx
> +    expect(gridRowEnd).toEqual({ _: 'span 1', md: 'span 3' });
😎

2021-06-25 22:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.e2b197.0<br/>@codecademy/gamut-labs@19.12.2-alpha.e2b197.0<br/>@codecademy/gamut@34.11.1-alpha.e2b197.0<br/>@codecademy/styleguide@41.10.22-alpha.e2b197.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 22:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d653f0a924f400ab1455b6--gamut-preview.netlify.app>https://60d653f0a924f400ab1455b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d653f0a924f400ab1455b6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 22:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.704d8f.0<br/>@codecademy/gamut-labs@19.12.2-alpha.704d8f.0<br/>@codecademy/gamut@34.11.1-alpha.704d8f.0<br/>@codecademy/styleguide@41.10.22-alpha.704d8f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 22:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d655845f01f00ae7f7f8f1--gamut-preview.netlify.app>https://60d655845f01f00ae7f7f8f1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d655845f01f00ae7f7f8f1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 22:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.90b3ff.0<br/>@codecademy/gamut-labs@19.12.2-alpha.90b3ff.0<br/>@codecademy/gamut@34.11.1-alpha.90b3ff.0<br/>@codecademy/styleguide@41.10.22-alpha.90b3ff.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 22:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d65aba5f01f00a35f7f739--gamut-preview.netlify.app>https://60d65aba5f01f00a35f7f739--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d65aba5f01f00a35f7f739>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 22:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.d326fc.0<br/>@codecademy/gamut-labs@19.12.2-alpha.d326fc.0<br/>@codecademy/gamut@34.11.1-alpha.d326fc.0<br/>@codecademy/styleguide@41.10.22-alpha.d326fc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 22:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d65d3d5f01f018a6f7f5c3--gamut-preview.netlify.app>https://60d65d3d5f01f018a6f7f5c3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d65d3d5f01f018a6f7f5c3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 23:45 UTC, jakemhiller commented on packages/gamut/src/GridForm/GridFormSections/GridFormContent.tsx
> +  const { register, errors, setValue } = useFormContext();
Yassss

2021-06-28 14:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.53-alpha.31c40b.0<br/>@codecademy/gamut-labs@19.12.3-alpha.31c40b.0<br/>@codecademy/gamut@34.12.1-alpha.31c40b.0<br/>@codecademy/styleguide@41.10.23-alpha.31c40b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-28 14:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d9e2d21fc98caaf13594c7--gamut-preview.netlify.app>https://60d9e2d21fc98caaf13594c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d9e2d21fc98caaf13594c7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-28 15:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.54-alpha.e73d9c.0<br/>@codecademy/gamut-labs@19.12.4-alpha.e73d9c.0<br/>@codecademy/gamut@34.12.1-alpha.e73d9c.0<br/>@codecademy/styleguide@41.10.24-alpha.e73d9c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-28 15:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d9e8f199dd7c9b40065c79--gamut-preview.netlify.app>https://60d9e8f199dd7c9b40065c79--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d9e8f199dd7c9b40065c79>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-28 15:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.54-alpha.ee20cd.0<br/>@codecademy/gamut-labs@19.13.0-alpha.ee20cd.0<br/>@codecademy/gamut@34.12.1-alpha.ee20cd.0<br/>@codecademy/styleguide@41.10.24-alpha.ee20cd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-28 15:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d9eb5899dd7c9cb0065cc1--gamut-preview.netlify.app>https://60d9eb5899dd7c9cb0065cc1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d9eb5899dd7c9cb0065cc1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-28 19:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60da29a30886383c630452f5--gamut-preview.netlify.app>https://60da29a30886383c630452f5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60da29a30886383c630452f5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-28 21:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.56-alpha.8e9f09.0<br/>@codecademy/gamut-labs@19.14.1-alpha.8e9f09.0<br/>@codecademy/gamut@34.12.1-alpha.8e9f09.0<br/>@codecademy/styleguide@41.10.26-alpha.8e9f09.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-28 21:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60da38c5f290cd0af7ee2097--gamut-preview.netlify.app>https://60da38c5f290cd0af7ee2097--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60da38c5f290cd0af7ee2097>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-28 21:03 UTC, merged