fix(GlobalHeader): fix transparent header when refreshing scrolled SSR'd page
Codecademy/client-modules pull request #1822
Opened 2021-06-10 21:54 UTC by christian-dinh

### Overview

seems that `react-use/useWindowScroll` is not isomorphic enough, but this is!

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-1048](https://codecademy.atlassian.net/browse/REACH-1048)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

Testing (sort of a pain)
1. pull this down, run `yarn build-all` from the root (not 100% this is necessary)
2. `cd` to `portal-app` and run `npx npm-link-better --copy <path/to/gamut-labs>`
3. `yarn start` in `portal-app` and go to `localhost:3100/catalog` or some other page with a GlobalHeader
4. ensure the header background fades in when scrolled to the top of the page and fades out when scrolled down
5. refresh while at the top of the page and ensure the GlobalHeader renders with a background
6. scroll down and refresh the page and ensure the GlobalHeader renders without a background

2021-06-10 22:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.20-alpha.3ef995.0<br/>@codecademy/gamut-labs@19.4.2-alpha.3ef995.0<br/>@codecademy/styleguide@41.7.2-alpha.3ef995.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-10 22:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c28bfbad403811d06ac87f--gamut-preview.netlify.app>https://60c28bfbad403811d06ac87f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c28bfbad403811d06ac87f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-10 22:33 UTC, MattSchiller approved these changes
😭 Absolutely beautiful 😭

2021-06-11 14:28 UTC, rogervera reviewed
Noticing some funky behavior on deploy preview builds on Portal App with this update. Not sure if it's because of our preview env or css loading related issues in Portal App

2021-06-11 14:28 UTC, rogervera commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +  const [isInHeaderRegion, setIsInHeaderRegion] = useState(false);
Made a test branch with v`0.4.20-alpha.3ef995.0` on [portal-app](https://github.com/codecademy-engineering/portal-app/pull/118/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17) and [monolith](url) and deployed a preview build.

I see a black screen on load when in the middle of the page. Can anyone else reproduce this? Not sure yet of the cause, but wanted to highlight this first. I can't reproduce on the monolith, so could it be how our preview env is setup for portal app. I can also reproduce locally with yarn build & serve.

Portal: https://portal-app-pr-118.dev-eks.codecademy.com/catalog
Monolith: https://pr-25164.dev-eks.codecademy.com/catalog


![8f5417c4-3b3d-43ea-8943-00b3038ad685](https://user-images.githubusercontent.com/17210163/121701962-6fd87680-ca9f-11eb-8ced-9e0fdbcaaad3.gif)

2021-06-11 14:39 UTC, MattSchiller commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +  const [isInHeaderRegion, setIsInHeaderRegion] = useState(false);
I can't repro with the portal-app link you shared?

2021-06-11 14:47 UTC, rogervera commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +  const [isInHeaderRegion, setIsInHeaderRegion] = useState(false);
Strange :/
It's also not consistent in how it's firing for me. Another set of eyes confirming it's not reproducible and I'll feel comfortable ✅. The fix itself LGTM

2021-06-11 15:19 UTC, christian-dinh commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +  const [isInHeaderRegion, setIsInHeaderRegion] = useState(false);
This is what I'm seeing:
![Untitled](https://user-images.githubusercontent.com/19958143/121708936-09a32200-caa6-11eb-879f-7059734b2a05.gif)

If the page loads while scrolled to the top the header loads with a background which fades out immediately. I'm not sure if there's a clean way around this type of thing since it has to start in one state or the other, but it probably makes more sense for it to start in the transparent state and fade in if the page is scrolled

2021-06-11 15:23 UTC, christian-dinh commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +  const [isInHeaderRegion, setIsInHeaderRegion] = useState(false);
seeing the same thing on the monolith btw, interesting that it didn't happen in local dev

2021-06-11 15:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.20-alpha.3bf7f2.0<br/>@codecademy/gamut-labs@19.4.2-alpha.3bf7f2.0<br/>@codecademy/styleguide@41.7.2-alpha.3bf7f2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-11 15:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c380dc93c91c5a5ba84b4a--gamut-preview.netlify.app>https://60c380dc93c91c5a5ba84b4a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c380dc93c91c5a5ba84b4a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-11 15:28 UTC, christian-dinh commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +  const [isInHeaderRegion, setIsInHeaderRegion] = useState(false);
preview getting built off this branch: https://github.com/codecademy-engineering/portal-app/pull/122

2021-06-11 15:57 UTC, christian-dinh commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +  const [isInHeaderRegion, setIsInHeaderRegion] = useState(false);
ok as seen on https://portal-app-pr-122.dev-eks.codecademy.com/catalog

![Untitled](https://user-images.githubusercontent.com/19958143/121714833-39edbf00-caac-11eb-95b1-a960f9578388.gif)

2021-06-11 15:59 UTC, christian-dinh commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +  const [isInHeaderRegion, setIsInHeaderRegion] = useState(false);
weirdly the css transition isn't working now 🤷

2021-06-11 16:36 UTC, JoshuaKGoldberg commented
+ Egg folks who worked on this for their visibility :)

2021-06-11 16:38 UTC, JoshuaKGoldberg requested changes
Behavior looks good, but I don't think we're the ones who need to fix this 😉

2021-06-11 16:38 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +    return () => document.removeEventListener('scroll', checkScroll);
🤔  this seems like a lot of continuous work for what is likely a bug in an external library. Have you tried taking in the changes post-https://github.com/streamich/react-use/issues/1699?

Instead of writing our own scroll handler _(which we'd have to do every time this logic is needed)_ I think it'd be better to fix it upstream.

2021-06-14 22:14 UTC, christian-dinh commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +    return () => document.removeEventListener('scroll', checkScroll);
problem still exists with `react-use` upgraded to latest unfortunately. Looking through the source code, I'm a little surprised it doesn't work because they're doing exactly what I'm doing here:

https://github.com/streamich/react-use/blob/master/src/useWindowScroll.ts

Actually to be more specific, I'm a little surprised the change I made here works. `useWindowScroll` is actually working fine, the issue is that the page statically renders with the `transitionFadeOut` css class applied which then does not get removed on the client (my best guess is because the client renders the page without that class on rehydration and therefore doesn't keep track of it internally). At first I thought maybe this was a sass issue but the same thing happens when converting to emotion, and I'm not quite sure how what I'm doing dodges the issue better than what they're doing 🤷

2021-06-15 15:18 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +    return () => document.removeEventListener('scroll', checkScroll);
@codecaaron think this might be a hydration thing?

2021-06-15 15:30 UTC, christian-dinh commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +    return () => document.removeEventListener('scroll', checkScroll);
Well this PR does defer the class application. I think the main difference between this and `useWindowScroll` is the [useState initialization](https://github.com/streamich/react-use/blob/master/src/useWindowScroll.ts#L13-L14), and I don't know if they would consider this behavior a bug or not

2021-06-15 19:27 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +    return () => document.removeEventListener('scroll', checkScroll);
Okie. Do you two think this is well defined (and not specific to our rendering) enough where you could file a bug on their repo?

Either way, we should at least have a comment in code here. Otherwise I'd probably forget about this conversation if I see this in a few months and switch back to `useWindowScroll` 😄

2021-06-15 19:28 UTC, JoshuaKGoldberg approved these changes
Approving to unblock :)

2021-06-15 19:30 UTC, christian-dinh commented on packages/gamut-labs/src/GlobalHeader/index.tsx
> +    return () => document.removeEventListener('scroll', checkScroll);
yeah I can add a comment and file a bug I think

2021-06-15 20:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.27-alpha.42ba4c.0<br/>@codecademy/gamut-labs@19.6.2-alpha.42ba4c.0<br/>@codecademy/styleguide@41.7.12-alpha.42ba4c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-15 20:20 UTC, merged

2021-06-15 20:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60c90bf65e513b1bda8dfeb2--gamut-preview.netlify.app>https://60c90bf65e513b1bda8dfeb2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60c90bf65e513b1bda8dfeb2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->