Ajr layoutmenu update focus states reach 1058
Codecademy/client-modules pull request #1840
Opened 2021-06-16 19:41 UTC by aresnik11

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-06-16 19:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.30-alpha.74a2da.0<br/>@codecademy/gamut-labs@19.8.1-alpha.74a2da.0<br/>@codecademy/styleguide@41.9.1-alpha.74a2da.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-16 19:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca553d4355f83db6cae311--gamut-preview.netlify.app>https://60ca553d4355f83db6cae311--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca553d4355f83db6cae311>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-16 20:26 UTC, MattSchiller commented on packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
> +        <Box key={item.slug} py={8} pl={3 as any}>
To avoid the `as any` & keep the `3` colocated, you may want to consider:
```ts
const leftPaddingForItem = 3;

const StyledAccordionArea = styled(AccordionArea)`
  padding-bottom: ${({ theme }) => theme.spacing[32]};
  position: relative;  left: -${leftPaddingForItem}px;
`;

const StyledAccordionSection = styled(Box)`
  padding: 8px 0 8px ${leftPaddingForItem}px;
`
```

2021-06-16 20:46 UTC, JoshuaKGoldberg approved these changes
Assuming Matt's review is addressed, yes 😄

2021-06-16 20:47 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
> +        <Box key={item.slug} py={8} pl={3 as any}>
done!

2021-06-16 20:50 UTC, codecaaron commented on packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
> +        </StyledAccordionSection>
Honestly I wonder if we should just update Accordion button to have a prop like `padded?: boolean` so we don't have to do any overrides here.

2021-06-16 20:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.30-alpha.5a9a48.0<br/>@codecademy/gamut-labs@19.8.1-alpha.5a9a48.0<br/>@codecademy/styleguide@41.9.1-alpha.5a9a48.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-16 20:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca64b90e863a009e7db7bc--gamut-preview.netlify.app>https://60ca64b90e863a009e7db7bc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca64b90e863a009e7db7bc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-16 21:20 UTC, rogervera requested changes
Testing the preview for the portal app:
https://portal-app-pr-146.dev-eks.codecademy.com/catalog

<img width="486" alt="Screen Shot 2021-06-16 at 5 18 44 PM" src="https://user-images.githubusercontent.com/17210163/122295300-0903f480-cec7-11eb-9707-f1fb827e0bf1.png">

Also, the left side of the outline is cropped a bit.
<img width="179" alt="Screen Shot 2021-06-16 at 5 19 49 PM" src="https://user-images.githubusercontent.com/17210163/122295346-13be8980-cec7-11eb-8f83-1ffe86f1318a.png">

2021-06-16 21:28 UTC, rogervera approved these changes
LGTM now!

2021-06-16 21:31 UTC, rogervera commented on packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
> +        </StyledAccordionSection>
Left a comment in this ticket:

https://codecademy.atlassian.net/browse/REACH-1061?focusedCommentId=59761

2021-06-16 21:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.30-alpha.f5d956.0<br/>@codecademy/gamut-labs@19.8.1-alpha.f5d956.0<br/>@codecademy/styleguide@41.9.1-alpha.f5d956.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-16 21:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca6e6820bfc80976780df6--gamut-preview.netlify.app>https://60ca6e6820bfc80976780df6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca6e6820bfc80976780df6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-16 21:37 UTC, christian-dinh approved these changes
idk if I'm allowed to ship this one but you already have 2 other ships so yoler 🙌

2021-06-16 21:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.30-alpha.6e9f6c.0<br/>@codecademy/gamut-labs@19.8.1-alpha.6e9f6c.0<br/>@codecademy/styleguide@41.9.1-alpha.6e9f6c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-16 21:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ca742e38b8c000ce9bf528--gamut-preview.netlify.app>https://60ca742e38b8c000ce9bf528--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ca742e38b8c000ce9bf528>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 14:22 UTC, dreamwasp commented on packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
> +        </StyledAccordionSection>
+1 to Aaron's comment above!

2021-06-17 17:30 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
> +        </StyledAccordionSection>
that makes sense but we would also still need overrides to set `justify-content` and `width`. i'm going to keep as is for now since we're trying to get this out asap

2021-06-17 17:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.34-alpha.6c878a.0<br/>@codecademy/gamut-labs@19.9.3-alpha.6c878a.0<br/>@codecademy/styleguide@41.10.4-alpha.6c878a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 17:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cb8d3e7bf01e00aefbb003--gamut-preview.netlify.app>https://60cb8d3e7bf01e00aefbb003--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cb8d3e7bf01e00aefbb003>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 19:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.35-alpha.17dd16.0<br/>@codecademy/gamut-labs@19.10.1-alpha.17dd16.0<br/>@codecademy/styleguide@41.10.5-alpha.17dd16.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 19:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cb9f6b402a581a18975a0b--gamut-preview.netlify.app>https://60cb9f6b402a581a18975a0b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cb9f6b402a581a18975a0b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 19:16 UTC, merged