fix(SelectDropdown): Fix axe accessibility input issue
Codecademy/client-modules pull request #1846
Opened 2021-06-17 18:42 UTC by dreamwasp

### Overview
Basically have restructured this to only have one <input> that we can optionally spread custom props onto as the other way was messier + causing axe test failures. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: GM-239
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-06-17 18:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.34-alpha.5fc709.0<br/>@codecademy/gamut-labs@19.9.3-alpha.5fc709.0<br/>@codecademy/gamut@34.10.2-alpha.5fc709.0<br/>@codecademy/styleguide@41.10.4-alpha.5fc709.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 18:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cb9925e51915151cd1a55d--gamut-preview.netlify.app>https://60cb9925e51915151cd1a55d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cb9925e51915151cd1a55d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 18:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.34-alpha.1c27bc.0<br/>@codecademy/gamut-labs@19.10.0-alpha.1c27bc.0<br/>@codecademy/gamut@34.10.2-alpha.1c27bc.0<br/>@codecademy/styleguide@41.10.4-alpha.1c27bc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 18:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cb9b4a92aa8213f7e1969b--gamut-preview.netlify.app>https://60cb9b4a92aa8213f7e1969b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cb9b4a92aa8213f7e1969b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 19:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cb9d069df35014a29d4e73--gamut-preview.netlify.app>https://60cb9d069df35014a29d4e73--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cb9d069df35014a29d4e73>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 19:18 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  }),
i *normally* wouldn't do this, but this mimics the [DummyInput](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/internal/DummyInput.tsx) react-select uses (but doesn't expose for us to use, or apply value + props to, of course  🙃)

2021-06-17 19:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.36-alpha.9e65a8.0<br/>@codecademy/gamut-labs@19.10.2-alpha.9e65a8.0<br/>@codecademy/gamut@34.10.2-alpha.9e65a8.0<br/>@codecademy/styleguide@41.10.6-alpha.9e65a8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 19:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cba2578b4a161a8ff59d3e--gamut-preview.netlify.app>https://60cba2578b4a161a8ff59d3e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cba2578b4a161a8ff59d3e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 19:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.36-alpha.40b07b.0<br/>@codecademy/gamut-labs@19.10.2-alpha.40b07b.0<br/>@codecademy/gamut@34.10.2-alpha.40b07b.0<br/>@codecademy/styleguide@41.10.6-alpha.40b07b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 19:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cba5bced6e9f19fa49d2dd--gamut-preview.netlify.app>https://60cba5bced6e9f19fa49d2dd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cba5bced6e9f19fa49d2dd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-17 22:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.38-alpha.7ed26b.0<br/>@codecademy/gamut-labs@19.10.4-alpha.7ed26b.0<br/>@codecademy/gamut@34.10.3-alpha.7ed26b.0<br/>@codecademy/styleguide@41.10.8-alpha.7ed26b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 22:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cbc69dbac88412433ed074--gamut-preview.netlify.app>https://60cbc69dbac88412433ed074--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cbc69dbac88412433ed074>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-21 19:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.40-alpha.6d05aa.0<br/>@codecademy/gamut-labs@19.10.6-alpha.6d05aa.0<br/>@codecademy/gamut@34.10.4-alpha.6d05aa.0<br/>@codecademy/styleguide@41.10.10-alpha.6d05aa.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-21 19:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0e37410070138d44c9cd2--gamut-preview.netlify.app>https://60d0e37410070138d44c9cd2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0e37410070138d44c9cd2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-21 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.40-alpha.0cb760.0<br/>@codecademy/gamut-labs@19.10.6-alpha.0cb760.0<br/>@codecademy/gamut@34.10.4-alpha.0cb760.0<br/>@codecademy/styleguide@41.10.10-alpha.0cb760.0<br/>@codecademy/tracking@0.10.0-alpha.0cb760.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-21 19:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0edfa1007014b6b4c99c5--gamut-preview.netlify.app>https://60d0edfa1007014b6b4c99c5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0edfa1007014b6b4c99c5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-21 20:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.40-alpha.938eab.0<br/>@codecademy/gamut-labs@19.10.6-alpha.938eab.0<br/>@codecademy/gamut@34.10.4-alpha.938eab.0<br/>@codecademy/styleguide@41.10.10-alpha.938eab.0<br/>@codecademy/tracking@0.10.0-alpha.938eab.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-21 20:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0f6516d9df7ea25b92739--gamut-preview.netlify.app>https://60d0f6516d9df7ea25b92739--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0f6516d9df7ea25b92739>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-21 20:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.41-alpha.2f3208.0<br/>@codecademy/gamut-labs@19.10.7-alpha.2f3208.0<br/>@codecademy/gamut@34.10.5-alpha.2f3208.0<br/>@codecademy/styleguide@41.10.11-alpha.2f3208.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-21 20:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0f97110070153fd4c9c82--gamut-preview.netlify.app>https://60d0f97110070153fd4c9c82--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0f97110070153fd4c9c82>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-21 20:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.41-alpha.c23adf.0<br/>@codecademy/gamut-labs@19.10.7-alpha.c23adf.0<br/>@codecademy/gamut@34.10.5-alpha.c23adf.0<br/>@codecademy/styleguide@41.10.11-alpha.c23adf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-21 20:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d0fb5dd668d854e9044d5f--gamut-preview.netlify.app>https://60d0fb5dd668d854e9044d5f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d0fb5dd668d854e9044d5f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-22 20:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.dd0223.0<br/>@codecademy/gamut-labs@19.11.1-alpha.dd0223.0<br/>@codecademy/gamut@34.10.8-alpha.dd0223.0<br/>@codecademy/styleguide@41.10.15-alpha.dd0223.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-22 20:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d247d7cff8a900a4bec86a--gamut-preview.netlify.app>https://60d247d7cff8a900a4bec86a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d247d7cff8a900a4bec86a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-23 21:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.76af37.0<br/>@codecademy/gamut-labs@19.11.2-alpha.76af37.0<br/>@codecademy/gamut@34.10.9-alpha.76af37.0<br/>@codecademy/styleguide@41.10.16-alpha.76af37.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-23 21:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d3a42bc46ca31dcd2258e1--gamut-preview.netlify.app>https://60d3a42bc46ca31dcd2258e1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d3a42bc46ca31dcd2258e1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-23 22:25 UTC, JoshuaKGoldberg requested changes
Feels good in general! Just the `isSearchable` thing is a blocker for me _(unintended inclusion?)_.

2021-06-23 22:25 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  input: (provided, state) => ({
Nit: 

```suggestion
  input: () => ({
```

2021-06-23 22:25 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  isSearchable: true,
I tried this in Storybook and searchability is borked: the functionality works but you can't see what you're inputting.

![Searching select dropdown with no input visibility](https://user-images.githubusercontent.com/3335181/123175767-51d02600-d450-11eb-8805-94af1c5e12f3.png)

2021-06-23 22:25 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  }),
Lol, of course.

Since this is all open source code and we have a legitimate need for it, could you please file an issue on their repo requesting it be made public, and comment a link to it in code? That way once that's resolved, we'll know to either remove this or do whatever alternative fix they might suggest.

2021-06-24 14:59 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  isSearchable: true,
yeah, i know lol - i'll put some time on your calendar to walk through this PR + my react-select findings because some of my choices here may seem weird without context

2021-06-24 15:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.edf8da.0<br/>@codecademy/gamut-labs@19.11.2-alpha.edf8da.0<br/>@codecademy/gamut@34.10.9-alpha.edf8da.0<br/>@codecademy/styleguide@41.10.16-alpha.edf8da.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-24 15:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d49e684aa32318feb214fc--gamut-preview.netlify.app>https://60d49e684aa32318feb214fc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d49e684aa32318feb214fc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-24 15:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.5f507a.0<br/>@codecademy/gamut-labs@19.11.2-alpha.5f507a.0<br/>@codecademy/gamut@34.10.9-alpha.5f507a.0<br/>@codecademy/styleguide@41.10.16-alpha.5f507a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-24 15:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d4a59544d8ec253ae67b99--gamut-preview.netlify.app>https://60d4a59544d8ec253ae67b99--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d4a59544d8ec253ae67b99>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 14:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.49-alpha.157f69.0<br/>@codecademy/gamut-labs@19.11.5-alpha.157f69.0<br/>@codecademy/gamut@34.10.12-alpha.157f69.0<br/>@codecademy/styleguide@41.10.19-alpha.157f69.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 14:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d5ead1b7fb485553542b97--gamut-preview.netlify.app>https://60d5ead1b7fb485553542b97--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d5ead1b7fb485553542b97>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-02 21:45 UTC, closed without merging