truncating curriculum card title
Codecademy/client-modules pull request #1848
Opened 2021-06-17 19:41 UTC by aionate0812

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-06-17 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.36-alpha.624ae3.0<br/>@codecademy/gamut-labs@19.10.2-alpha.624ae3.0<br/>@codecademy/styleguide@41.10.6-alpha.624ae3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-17 19:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60cba7901408bd00b784bf33--gamut-preview.netlify.app>https://60cba7901408bd00b784bf33--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60cba7901408bd00b784bf33>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-22 15:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.267c83.0<br/>@codecademy/gamut-labs@19.11.1-alpha.267c83.0<br/>@codecademy/styleguide@41.10.15-alpha.267c83.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-22 15:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d202602d18a10c4d85bedb--gamut-preview.netlify.app>https://60d202602d18a10c4d85bedb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d202602d18a10c4d85bedb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-22 16:33 UTC, christian-dinh approved these changes
🔪

2021-06-22 16:46 UTC, aresnik11 reviewed
copying my slack message here for visibility:
i'm not sure we want to truncate the titles here. i think we instead may want to just stretch the other cards in that row so the row is even, or at least thats what it looks like we were doing in the old catalog (top) vs portal app (bottom)
<img width="1211" alt="Screen Shot 2021-06-22 at 11 33 11 AM" src="https://user-images.githubusercontent.com/8761638/122966750-ae9be580-d357-11eb-8ccf-d55b6cd720a8.png">
<img width="1213" alt="Screen Shot 2021-06-22 at 11 33 27 AM" src="https://user-images.githubusercontent.com/8761638/122966755-b065a900-d357-11eb-8303-4fe079fa09bc.png">

2021-06-22 17:40 UTC, JoshuaKGoldberg requested changes
+1, what Amy said :)

2021-06-22 19:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.52fb74.0<br/>@codecademy/gamut-labs@19.11.1-alpha.52fb74.0<br/>@codecademy/styleguide@41.10.15-alpha.52fb74.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-22 19:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d23e68ee3325120412bb6b--gamut-preview.netlify.app>https://60d23e68ee3325120412bb6b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d23e68ee3325120412bb6b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-22 20:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.54b8ac.0<br/>@codecademy/gamut-labs@19.11.1-alpha.54b8ac.0<br/>@codecademy/styleguide@41.10.15-alpha.54b8ac.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-22 20:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d24904d28bda00aac9c0f3--gamut-preview.netlify.app>https://60d24904d28bda00aac9c0f3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d24904d28bda00aac9c0f3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-22 20:44 UTC, JoshuaKGoldberg requested changes

2021-06-22 20:44 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/CurriculumCard/index.tsx
> +      height={isFullHeight ? '100%' : ''}
I'm averse to adding assorted sizing props to shared components. Their complexity can get pretty intense.

Instead, have you tried using CSS properties in the consuming app to make things stretch? Like `align-items: stretch` / `justify-content: stretch` type of thing?

2021-06-23 14:39 UTC, aionate0812 commented on packages/gamut-labs/src/CurriculumCard/index.tsx
> +      height={isFullHeight ? '100%' : ''}
Trying that [here](https://github.com/codecademy-engineering/portal-app/pull/170)

2021-06-23 14:56 UTC, closed without merging