feat(AppHeader types): Updating AppHeaderItem types
Codecademy/client-modules pull request #1865
Opened 2021-06-22 18:12 UTC by MattSchiller

### Overview

- Adding the helper `appHeaderItemIsLink` so that parent components have better insight into the `item` that's passed into the `props.header.action` method
- Also consolidated some of the shared keys in the various types

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-06-22 18:13 UTC, MattSchiller commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
>  };
My goal with this generic is to:
- Communicate to the compiler that these shared `type` keys are actually the same key with different specific values across the different extensions of the Base type
- Enforce that any new header items must implement this key (via the generic)

2021-06-22 18:14 UTC, MattSchiller commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithLink => !!(item as AppHeaderItemWithLink).href;
This is the primary purpose of the PR. `portal-app` would like to know if a given header item is a link or not to know if it should `preventDefault` and `router.push` to enforce SPA navigation where it can (without forcing `client-modules` to be NextJS-aware)

2021-06-22 18:22 UTC, MattSchiller commented
Tagging some more Engagement people since they own this code 👍

2021-06-23 15:31 UTC, aionate0812 approved these changes
🚀

2021-06-23 19:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.aeae72.0<br/>@codecademy/gamut-labs@19.11.1-alpha.aeae72.0<br/>@codecademy/styleguide@41.10.15-alpha.aeae72.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-23 19:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d38fea49f59e0dbdc84abe--gamut-preview.netlify.app>https://60d38fea49f59e0dbdc84abe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d38fea49f59e0dbdc84abe>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-23 22:13 UTC, saghdaey commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithLink => !!(item as AppHeaderItemWithLink).href;
ooooo gotchya i was wondering where this came from :) 
ps love when folks comment on their own prs

2021-06-23 22:14 UTC, saghdaey commented
Looks good to me! Thanks for implementing the rename. Will take another look tomorrow and test in story book + in the partner PR!

2021-06-23 22:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.acb496.0<br/>@codecademy/gamut-labs@19.11.1-alpha.acb496.0<br/>@codecademy/styleguide@41.10.15-alpha.acb496.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-23 22:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d3b346079a002e402eb41d--gamut-preview.netlify.app>https://60d3b346079a002e402eb41d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d3b346079a002e402eb41d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-23 22:19 UTC, JoshuaKGoldberg requested changes
I dig the type improvements!

2021-06-23 22:19 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +type AppHeaderBaseItem<T extends string> = {
Nit: for readability, since this variable has semantic meaning:

```suggestion
type AppHeaderBaseItem<Type extends string> = {
```

2021-06-23 22:19 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithHref => !!(item as AppHeaderItemWithHref).href;
I'm not jazzed about this approach where clients have to piece together the core functionality of the header individually. What do you think about having an `onLinkAction`/`onLinkClick` prop that is called after `action`, where clients can put logic like `event.preventDefault();` and `router.push(item.href)`?

```ts
onClick={(event) => {
  props.action(event, item);
  props.linkAction?.(event, item);
}}
```

_(personally I think we should rename the `action` prop to `onAction` and make `event, item` an object, but I haven't gotten around to taking action on that yet -- for another time!)_

2021-06-24 00:46 UTC, jakemhiller commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithHref => !!(item as AppHeaderItemWithHref).href;
+1 to what @JoshuaKGoldberg said, this seems like it should be exposed as top-level functionality for the header. If the current action prop (+1 on the eventual rename) is too generic or mainly meant for tracking then adding a separate `onLinkAction` prop makes sense to me!

2021-06-24 18:00 UTC, MattSchiller commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithHref => !!(item as AppHeaderItemWithHref).href;
Sure thing, these API tweaks make sense to me. On it!

2021-06-24 18:36 UTC, MattSchiller commented on jest.config.js
> +  clearMocks: true,
Found this to be a missing helper. Should I be adding this on a suite by suite basis?

2021-06-24 18:36 UTC, MattSchiller commented on packages/gamut-labs/src/DropdownButton/__tests__/DropdownList-test.tsx
> +    expect(items[1].clickHandler).toHaveBeenCalledTimes(1);
Discovered this "broken" test by adding the mock clear between tests.

2021-06-24 18:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.45-alpha.f9ecaf.0<br/>@codecademy/gamut-labs@19.11.1-alpha.f9ecaf.0<br/>@codecademy/styleguide@41.10.15-alpha.f9ecaf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-24 18:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d4d1b64589a952b3251b58--gamut-preview.netlify.app>https://60d4d1b64589a952b3251b58--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d4d1b64589a952b3251b58>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-24 19:48 UTC, saghdaey commented on packages/gamut-labs/src/AppHeader/__tests__/AppHeader-test.tsx
> +    expect(onLinkAction).not.toHaveBeenCalled();
nice ty for these tests

2021-06-24 20:19 UTC, saghdaey approved these changes

2021-06-24 20:33 UTC, saghdaey commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithHref => !!(item as AppHeaderItemWithHref).href;
with your new changes, I think we may be missing adding the onLinkAction to the base header type 
https://github.com/Codecademy/client-modules/blob/main/packages/gamut-labs/src/GlobalHeader/types.tsx#L12

2021-06-24 20:33 UTC, saghdaey commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithHref => !!(item as AppHeaderItemWithHref).href;
not seeing how the client can actually pass this through without updating that

2021-06-24 21:18 UTC, MattSchiller commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithHref => !!(item as AppHeaderItemWithHref).href;
@JoshuaKGoldberg So after looking into this, and seeing how the header is constructed (GlobalHeader => AppHeader/AppMobileHeader, props drilling and multiple implementations), I think we'd probably prefer the "old way" where portal-app was augmenting `action` instead.

Otherwise we're not only marshaling this prop everywhere, but also re-implementing the augmentation in desktop/mobile headers.

Thoughts?

2021-06-24 22:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.49-alpha.7c9037.0<br/>@codecademy/gamut-labs@19.11.5-alpha.7c9037.0<br/>@codecademy/styleguide@41.10.19-alpha.7c9037.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-24 22:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d507300327528d0dc6fd58--gamut-preview.netlify.app>https://60d507300327528d0dc6fd58--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d507300327528d0dc6fd58>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 15:37 UTC, MattSchiller commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
> +): item is AppHeaderItemWithHref => !!(item as AppHeaderItemWithHref).href;
Alriiiight! Yeah, I was just thinking with blinders on. Moving the logic all up to `GlobalHeader` is where this should go (and not just `AppHeader`).

Lemme know what you think!

2021-06-25 15:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.49-alpha.0b44c9.0<br/>@codecademy/gamut-labs@19.11.5-alpha.0b44c9.0<br/>@codecademy/styleguide@41.10.19-alpha.0b44c9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 16:09 UTC, JoshuaKGoldberg approved these changes
🌮 , thanks for the combined action change! This looks great to me.

2021-06-25 16:09 UTC, JoshuaKGoldberg commented on jest.config.js
> +  clearMocks: true,
Ooh +1 to having it in `jest.config.js`. People tend to forget otherwise!

2021-06-25 17:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.50-alpha.7d472a.0<br/>@codecademy/gamut-labs@19.11.6-alpha.7d472a.0<br/>@codecademy/styleguide@41.10.20-alpha.7d472a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 17:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d60f38647659784827c9df--gamut-preview.netlify.app>https://60d60f38647659784827c9df--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d60f38647659784827c9df>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 17:22 UTC, merged

2021-06-25 18:17 UTC, saghdaey commented on packages/gamut-labs/src/GlobalHeader/types.tsx
> +  onLinkAction?: AppHeaderClickHandler;
nice. thanks for adding comments too :)