New Tabs (WIP)
Codecademy/client-modules pull request #1867
Opened 2021-06-23 17:54 UTC by tchryssos

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-06-23 17:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/client-modules?pullRequest=1867) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/client-modules?pullRequest=1867) it.</sub>

2021-06-23 17:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.34-alpha.47fc2d.0<br/>@codecademy/gamut-labs@19.9.3-alpha.47fc2d.0<br/>@codecademy/styleguide@41.10.4-alpha.47fc2d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-23 18:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d376b639185b1b13402c7b--gamut-preview.netlify.app>https://60d376b639185b1b13402c7b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d376b639185b1b13402c7b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-24 13:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.34-alpha.eb2d24.0<br/>@codecademy/gamut-labs@19.9.3-alpha.eb2d24.0<br/>@codecademy/styleguide@41.10.4-alpha.eb2d24.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-24 13:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d4877978faef00a0fae723--gamut-preview.netlify.app>https://60d4877978faef00a0fae723--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d4877978faef00a0fae723>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-24 14:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.043bcf.0<br/>@codecademy/gamut-labs@19.11.2-alpha.043bcf.0<br/>@codecademy/styleguide@41.10.16-alpha.043bcf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-24 14:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d4978d456cbe115e616940--gamut-preview.netlify.app>https://60d4978d456cbe115e616940--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d4978d456cbe115e616940>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-24 14:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.b99d6c.0<br/>@codecademy/gamut-labs@19.11.2-alpha.b99d6c.0<br/>@codecademy/styleguide@41.10.16-alpha.b99d6c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-24 14:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d49d084589a91a07251caf--gamut-preview.netlify.app>https://60d49d084589a91a07251caf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d49d084589a91a07251caf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-24 16:29 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
>  <Meta
A couple of requests to make sure people don't build on this and turn it into the same pain as the old tabs:

* Rename to `TabsExperimental` or something like that
* Explicitly say in the story that consumers should talk to #gamut-team before using

2021-06-24 16:29 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
> +            quote="You know Dad, the kids playing soccer don't have any lumps or bruises and Coach Lucas gives them orange slices at half time."
<3 I just watched this episode for the first time!!

2021-06-24 16:32 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
> +## Tabs with custom active color
Do we... need this? Or the predefined width?

I'm getting lost in the Jira/Figma and can't tell what's actually necessary to implement _now_.

2021-06-24 16:37 UTC, JoshuaKGoldberg requested changes
Sorry to do this again 😄 but I can review a bit more thoroughly once this is pared down a bit _(or you indicate that's not the right thing to do)_.

2021-06-24 16:39 UTC, tchryssos commented
wow @JoshuaKGoldberg I gotta say I am not sure how you keep getting tagged on this stuff. Maybe moving from draft -> ready to review auto tags people? 

Either way, your early feedback is helpful ty

2021-06-24 16:49 UTC, tchryssos commented on packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
> +## Tabs with custom active color
Sure, I'm happy to pull this stuff out and just make it fixed to exactly what I need. I did start hearing from @antoniablair that she might need this component in the very near future as well, so some of this stuff was to make it flexible for her needs, but if you think you'll have a "real" version out soon, then maybe that point is moot (or if tonia decides she doesn't need this after all).

The only thing I need for sure is `160px` tab width, everything else I did for flexibility.

2021-06-24 17:24 UTC, JoshuaKGoldberg commented
@tchryssos I'm going to be owning tabs work after this goes in so it's a good thing I got tagged 😄 

And yeah, we have a codeowners file set up.

2021-06-24 17:25 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
> +## Tabs with custom active color
Ooh good to know, thank you!

fyi @codecaaron for when we kick off soon

2021-06-25 17:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.c54423.0<br/>@codecademy/gamut-labs@19.11.2-alpha.c54423.0<br/>@codecademy/styleguide@41.10.16-alpha.c54423.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 17:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d611e76a81fa77196a8098--gamut-preview.netlify.app>https://60d611e76a81fa77196a8098--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d611e76a81fa77196a8098>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 17:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.e2d28d.0<br/>@codecademy/gamut-labs@19.11.2-alpha.e2d28d.0<br/>@codecademy/styleguide@41.10.16-alpha.e2d28d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 17:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d615f16a81fa7f846a7179--gamut-preview.netlify.app>https://60d615f16a81fa7f846a7179--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d615f16a81fa7f846a7179>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 17:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.46-alpha.1754ae.0<br/>@codecademy/gamut-labs@19.11.2-alpha.1754ae.0<br/>@codecademy/styleguide@41.10.16-alpha.1754ae.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 17:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d6181a8653ab83120e3cc7--gamut-preview.netlify.app>https://60d6181a8653ab83120e3cc7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d6181a8653ab83120e3cc7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 18:02 UTC, tchryssos commented
@JoshuaKGoldberg / @codecaaron I think this sufficiently stripped down. Still waiting on a final color from design, but that should be a pretty trivial addition. I did _not_ rename the other component to `SegmentedControlDeprecated`, or whatever we decided we wanted it to be because I wasn't 100% sure I would catch every place it needed to be updated

2021-06-25 18:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.51-alpha.f10fa6.0<br/>@codecademy/gamut-labs@19.12.1-alpha.f10fa6.0<br/>@codecademy/styleguide@41.10.21-alpha.f10fa6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 18:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d61b9578468781d2ac9bf3--gamut-preview.netlify.app>https://60d61b9578468781d2ac9bf3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d61b9578468781d2ac9bf3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 18:39 UTC, JoshuaKGoldberg requested changes
Close and very 🔥!

2021-06-25 18:39 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +`;
@codecaaron is there a menu button this should be using instead?

If not, I'll defer to you on using variance / whatnot.

2021-06-25 18:39 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/TabsExperimental/ExampleCard.tsx
> +export default ExampleCard;
Nit: named please 😄 

```suggestion
```

2021-06-25 18:39 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/TabsDeprecated/index.stories.mdx
> +import {
Commenting here because I can't on the other file: is it intentional that you left in a `SegmentedControlDeprecated/index.stories.mdx`?

2021-06-25 18:39 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/TabsExperimental/__tests__/Tabs-test.tsx
> +    expect(view.getByText(herculeText)).toBeTruthy();
`view.getByText` throws an error if no element is found. The `.toBeTruthy` is redundant.

```suggestion
    view.getByText('Hercule');
    view.getByText('Goku');
    view.getByText(gokuText);
    view.getByText(herculeText);
```

2021-06-25 18:39 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/index.ts
> +export { Tabs as TabsExperimental, TabPanel } from './TabsExperimental';
Could you directly have the components be named as `TabsExperimental` and `TabPanelExperimental`? Component renames are confusing and don't always show up in a lot of dev tools, such as the React dev tools.

2021-06-25 18:39 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/TabsExperimental/TabList.tsx
> +};
For your reading pleasure:

* The current code might crash if `undefined` or `null` are passed
* You `ReactElement` is a generic type with the first type parameter representing the component props (go-to-definition on it in an editor)
* Returning an `is` is how TypeScript lets us say _"this function tells us not just a boolean, but also whether something is a specific type"_: a user-defined type guard

```tsx
      {React.Children.toArray(children)
        .filter(
          (child): child is ReactElement<TabPanelProps> =>
            typeof child === 'object' &&
            'type' in child &&
            child.type === TabPanel
        )
        .map((child, i) => {
          const { children, className, title } = child.props;

          return (
            <DerivedTabPanel
              isActiveTab={i === activeTabIndex}
              className={className}
              key={`panel-${title}`}
            >
              {children}
            </DerivedTabPanel>
          );
        })}
```

2021-06-25 18:39 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/TabsDeprecated/index.stories.mdx
> +## Controlled
This is no longer the case. A section to remove?

2021-06-25 19:23 UTC, tchryssos commented on packages/styleguide/stories/Molecules/TabsDeprecated/index.stories.mdx
> +import {
Oh weird, no. I  stashed those changes, but I guess that folder creation didn't stash nicely

2021-06-25 19:24 UTC, tchryssos commented on packages/styleguide/stories/Molecules/TabsDeprecated/index.stories.mdx
> +## Controlled
This is on `TabsDeprecated`, not the new `TabsExperimental`

2021-06-25 19:24 UTC, tchryssos commented on packages/styleguide/stories/Molecules/TabsDeprecated/index.stories.mdx
> +## Controlled
Which I guess I should just leave as tabs for now and let y'all handle the full conversion

2021-06-25 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.68f1e2.0<br/>@codecademy/gamut-labs@19.12.2-alpha.68f1e2.0<br/>@codecademy/styleguide@41.10.22-alpha.68f1e2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 19:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d633bc9b0a880d10d2e118--gamut-preview.netlify.app>https://60d633bc9b0a880d10d2e118--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d633bc9b0a880d10d2e118>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-25 19:59 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/TabsDeprecated/index.stories.mdx
> +## Controlled
Oh sorry I got confused haha. But yeah if you're going to rename it you might as well go with the "Segmented" name; otherwise we'll just rename directly there next.

2021-06-25 20:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.3a23b8.0<br/>@codecademy/gamut-labs@19.12.2-alpha.3a23b8.0<br/>@codecademy/styleguide@41.10.22-alpha.3a23b8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-25 20:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d6365243e89512a296a922--gamut-preview.netlify.app>https://60d6365243e89512a296a922--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d6365243e89512a296a922>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-28 14:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.52-alpha.9c4f21.0<br/>@codecademy/gamut-labs@19.12.2-alpha.9c4f21.0<br/>@codecademy/styleguide@41.10.22-alpha.9c4f21.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-28 14:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d9ddbcabf1b009e2a0da6d--gamut-preview.netlify.app>https://60d9ddbcabf1b009e2a0da6d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d9ddbcabf1b009e2a0da6d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-28 14:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.53-alpha.0f14e6.0<br/>@codecademy/gamut-labs@19.12.3-alpha.0f14e6.0<br/>@codecademy/styleguide@41.10.23-alpha.0f14e6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-28 14:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60d9e009d8eda915e9b4d2fe--gamut-preview.netlify.app>https://60d9e009d8eda915e9b4d2fe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60d9e009d8eda915e9b4d2fe>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-29 13:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.58-alpha.b920dc.0<br/>@codecademy/gamut-labs@19.15.1-alpha.b920dc.0<br/>@codecademy/styleguide@41.12.1-alpha.b920dc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-29 13:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60db1da2684b69c891d93efd--gamut-preview.netlify.app>https://60db1da2684b69c891d93efd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60db1da2684b69c891d93efd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-29 18:28 UTC, tchryssos commented
@JoshuaKGoldberg this is hopefully ready for the ol' 👍

2021-06-29 18:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.59-alpha.0cb6e0.0<br/>@codecademy/gamut-labs@19.15.2-alpha.0cb6e0.0<br/>@codecademy/styleguide@41.12.2-alpha.0cb6e0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-29 18:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60db6777aa690c2c9d88e00e--gamut-preview.netlify.app>https://60db6777aa690c2c9d88e00e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60db6777aa690c2c9d88e00e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-29 22:14 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +`;
@dreamwasp now ✨

2021-06-30 17:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.59-alpha.2fc95b.0<br/>@codecademy/gamut-labs@19.15.2-alpha.2fc95b.0<br/>@codecademy/styleguide@41.12.2-alpha.2fc95b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-30 17:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60dcae94e6dad5681d1b7142--gamut-preview.netlify.app>https://60dcae94e6dad5681d1b7142--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60dcae94e6dad5681d1b7142>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-30 20:27 UTC, JoshuaKGoldberg approved these changes
Awesome, thanks for taking this on!

I'll defer to @dreamwasp on the styling stuff but in general it looks good to me!

2021-06-30 20:27 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +    let textColor: string = theme.colors.text;
Nit: TypeScript is smort

```suggestion
    let textColor = theme.colors.text;
```

2021-06-30 20:27 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +    }
Nit: a bit of duplicate code in the `isActiveTab` logic... I don't mind WET code if you prefer, but a suggestion to DRY 😄

2021-07-01 13:53 UTC, dreamwasp approved these changes
this looks great! would love to see it using states for isActiveTab, but non-blocking 🚀

2021-07-01 13:53 UTC, dreamwasp commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +    if (isActiveTab) {
i think you could dry this up if you some of the isActiveTab stuff with [states](https://gamut.codecademy.com/storybook/?path=/docs/foundations-system-variants--page#states)

2021-07-01 13:53 UTC, dreamwasp commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +`;
yupp, i think [states](https://gamut.codecademy.com/storybook/?path=/docs/foundations-system-variants--page#states) would work well for this !

2021-07-01 13:53 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/TabsExperimental/index.stories.mdx
> +          speaker="Piccolo"
star-studded example, we love to see it

2021-07-01 16:02 UTC, tchryssos commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +    let textColor: string = theme.colors.text;
I actually get a ts warning if I don't do this: `Type '"var(--color-blue)"' is not assignable to type '"var(--colors-text)"'.`

2021-07-01 16:03 UTC, tchryssos commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +    }
I had these extracted into a different function, but I started to get a lot of ts errors about theme type clashes when I tried to re-assign things in a more generic way. I can take another look

2021-07-01 19:33 UTC, tchryssos commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +    let textColor: string = theme.colors.text;
This doesn't matter anymore because I got `states` to work

2021-07-01 19:33 UTC, tchryssos commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +    }
Same as above

2021-07-01 20:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.60-alpha.483046.0<br/>@codecademy/gamut-labs@19.15.3-alpha.483046.0<br/>@codecademy/styleguide@41.12.3-alpha.483046.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-01 20:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60de21163b6c1626dee13348--gamut-preview.netlify.app>https://60de21163b6c1626dee13348--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60de21163b6c1626dee13348>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-02 15:27 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/TabsExperimental/Tab.tsx
> +    let textColor: string = theme.colors.text;
Ooh yay!

2021-07-02 15:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.61-alpha.914f8c.0<br/>@codecademy/gamut-labs@19.15.4-alpha.914f8c.0<br/>@codecademy/styleguide@41.12.4-alpha.914f8c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-02 15:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60df321b37f1120a9d18ff67--gamut-preview.netlify.app>https://60df321b37f1120a9d18ff67--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60df321b37f1120a9d18ff67>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-12 15:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.62-alpha.b45187.0<br/>@codecademy/gamut-labs@19.15.5-alpha.b45187.0<br/>@codecademy/styleguide@41.13.1-alpha.b45187.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-12 15:31 UTC, merged

2021-07-12 15:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60ec602e455b4749de08b6d8--gamut-preview.netlify.app>https://60ec602e455b4749de08b6d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60ec602e455b4749de08b6d8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->