feat(GridFormSectionTitle): Add configurable Text props to GridFormSection
Codecademy/client-modules pull request #1879
Opened 2021-06-29 19:51 UTC by dreamwasp

### Overview
Adds (most) Text props to GridFormSection to make GridFormTitle configurable.\

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-06-29 20:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.58-alpha.081494.0<br/>@codecademy/gamut-labs@19.15.1-alpha.081494.0<br/>@codecademy/gamut@34.13.1-alpha.081494.0<br/>@codecademy/styleguide@41.12.1-alpha.081494.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-29 20:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.59-alpha.c9e41f.0<br/>@codecademy/gamut-labs@19.15.2-alpha.c9e41f.0<br/>@codecademy/gamut@34.13.2-alpha.c9e41f.0<br/>@codecademy/styleguide@41.12.2-alpha.c9e41f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-29 20:41 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Organisms/GridForm.stories.mdx
> +You can set the rest of the [Text](https://gamut.codecademy.com/storybook/?path=/docs/typography-text--text) props for the section title the same way. Please check if your styling can be achieved wit
What's the use case here? I'm super duper wary of giving people so much control over them... can it be a `Pick` of some allowed ones?

2021-06-29 20:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60db85957e7098072f5055c7--gamut-preview.netlify.app>https://60db85957e7098072f5055c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60db85957e7098072f5055c7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-29 20:49 UTC, katiezutter approved these changes
Thank you thank you for getting this up so quickly!! ⚡️ Looks great on the Profile Edit page - here's the branch (preview environment with changes is not up yet): https://github.com/codecademy-engineering/Codecademy/pull/25557

2021-06-29 20:51 UTC, dreamwasp commented on packages/styleguide/stories/Organisms/GridForm.stories.mdx
> +You can set the rest of the [Text](https://gamut.codecademy.com/storybook/?path=/docs/typography-text--text) props for the section title the same way. Please check if your styling can be achieved wit
@katiezutter's current PR is the best use-case -- I will experiment in restricting this to just `variants`. Does that make more sense ya think?

2021-06-29 20:59 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Organisms/GridForm.stories.mdx
> +You can set the rest of the [Text](https://gamut.codecademy.com/storybook/?path=/docs/typography-text--text) props for the section title the same way. Please check if your styling can be achieved wit
Yeah that makes sense to me, thanks!

If you wanted to be _really_ snazzy you could restrict it to just the title variants. Unless that's an explicit list somewhere, you could probably write some fancy complex TypeScript type to restrict the string literal types... up to you 😄

2021-06-29 21:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.59-alpha.477d88.0<br/>@codecademy/gamut-labs@19.15.2-alpha.477d88.0<br/>@codecademy/gamut@34.13.2-alpha.477d88.0<br/>@codecademy/styleguide@41.12.2-alpha.477d88.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-29 21:00 UTC, JoshuaKGoldberg requested changes
What you suggested 😄

2021-06-29 21:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60db8a57e1c17f0bfab8bb8a--gamut-preview.netlify.app>https://60db8a57e1c17f0bfab8bb8a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60db8a57e1c17f0bfab8bb8a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-30 15:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.59-alpha.02cb12.0<br/>@codecademy/gamut-labs@19.15.2-alpha.02cb12.0<br/>@codecademy/gamut@34.13.2-alpha.02cb12.0<br/>@codecademy/styleguide@41.12.2-alpha.02cb12.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-30 15:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60dc873b9e46d1374a72d639--gamut-preview.netlify.app>https://60dc873b9e46d1374a72d639--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60dc873b9e46d1374a72d639>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-06-30 16:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.59-alpha.f7139f.0<br/>@codecademy/gamut-labs@19.15.2-alpha.f7139f.0<br/>@codecademy/gamut@34.13.2-alpha.f7139f.0<br/>@codecademy/styleguide@41.12.2-alpha.f7139f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-06-30 16:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60dca155397c6b58b60e000f--gamut-preview.netlify.app>https://60dca155397c6b58b60e000f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60dca155397c6b58b60e000f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-02 18:25 UTC, sooinc approved these changes
This is awesome!! Thank you for adding this. Tested in Katie's branch that it indeed throws a TS error if you aren't using title-size.

2021-07-02 19:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.61-alpha.248ede.0<br/>@codecademy/gamut-labs@19.15.4-alpha.248ede.0<br/>@codecademy/gamut@34.13.3-alpha.248ede.0<br/>@codecademy/styleguide@41.12.4-alpha.248ede.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-02 19:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60df66c674fefb4ac2200556--gamut-preview.netlify.app>https://60df66c674fefb4ac2200556--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60df66c674fefb4ac2200556>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-12 14:05 UTC, merged