initial setup
Codecademy/client-modules pull request #1894
Opened 2021-07-13 19:46 UTC by aionate0812

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-07-13 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.7f1321.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-13 19:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60edeefb38d4f94bb33ed792--gamut-preview.netlify.app>https://60edeefb38d4f94bb33ed792--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60edeefb38d4f94bb33ed792>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-21 15:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.5e560d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-21 15:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f8413de6863a211f6bf43a--gamut-preview.netlify.app>https://60f8413de6863a211f6bf43a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f8413de6863a211f6bf43a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-22 13:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.fac0ef.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-22 13:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f97969c8e523ff112eee03--gamut-preview.netlify.app>https://60f97969c8e523ff112eee03--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f97969c8e523ff112eee03>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-22 14:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f982e3c8e5230de52eef54--gamut-preview.netlify.app>https://60f982e3c8e5230de52eef54--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f982e3c8e5230de52eef54>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-22 14:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.a429ca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-22 17:19 UTC, MattSchiller reviewed
I'm a bit wary of how we're determining when a component updates, but I think this is ultimately just a port from monolith, so it's not any worse than what we have already.

Just wanted to flag that one. Also, are tests coming over, too?

Nice job!

2021-07-22 17:19 UTC, MattSchiller commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/index.tsx
> +  }
Perhaps I'm just unfamiliar with the other use-cases, but why would we need this? I'm assuming it's because upstream components aren't passing referentially stable functions/`options`?

This method may end up causing issues down the line. Like, if a caller changes just `onChange` or something, this wouldn't update.

Would it make sense to memoize them in this component and then have shouldComponentUpdate be able to check if anything changes? Could we enforce passing referentially stable props?

2021-07-22 17:19 UTC, MattSchiller commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/index.tsx
> +        onResize={(width: any, height: any) => {
nit: are these really `any` or `number`? Is this just a function of the underlying monaco types?

2021-07-22 17:19 UTC, MattSchiller commented on packages/monaco/src/MonacoEditor/index.tsx
> +  readOnly,
Nit: Are these unused props here for future use cases or can we remove them?

2021-07-22 18:08 UTC, aionate0812 commented on packages/monaco/src/MonacoEditor/index.tsx
> +  readOnly,
they are there for future cases but i removed them for now

2021-07-22 18:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.f7bdd2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-22 18:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60f9b55ab2b47123779a8cae--gamut-preview.netlify.app>https://60f9b55ab2b47123779a8cae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60f9b55ab2b47123779a8cae>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-22 20:31 UTC, aionate0812 commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/index.tsx
> +  }
This will probably be more clear when I import hooks that configure the language settings for the editor. [This PR](https://github.com/Codecademy/client-modules/pull/1913) has some of those hooks. From looking at the monolith I think this is needed to update the language config of the editor when switching between files in the LE or if a file is renamed with a different extension

2021-07-22 22:05 UTC, JoshuaKGoldberg requested changes
A lovely start!

2021-07-22 22:05 UTC, JoshuaKGoldberg commented on packages/monaco/package.json
> +    "@loadable/component": "5.10.1",
We don't want to add `@loadable/component` as a dependency in a shared client-modules package. Some consuming apps have different lazy-loading techniques, such as portal-app's [built-in `import()` support](https://nextjs.org/docs/advanced-features/dynamic-import).

_This_ package would be the one we'd want to lazy-import/load.

2021-07-22 22:05 UTC, JoshuaKGoldberg commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/styles.module.scss
> +@import "~styles/cc";
Ha, let's not start off a new package with old styles!

Can you use Gamut's `Box` for this, or failing that `emotion`?

2021-07-23 20:24 UTC, aionate0812 commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/styles.module.scss
> +@import "~styles/cc";
I swapped this for a `Box` component but encountered this weird bug, the editor's height starts to decrease, so I decided to use `emotion` instead

![Jul-23-2021 14-54-48](https://user-images.githubusercontent.com/22219812/126837596-1505ea7a-bd68-48b6-a014-eceb92d23803.gif)

2021-07-23 20:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.69ae63.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-23 20:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fb263fd6a9dc2d4a578846--gamut-preview.netlify.app>https://60fb263fd6a9dc2d4a578846--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fb263fd6a9dc2d4a578846>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-23 20:34 UTC, JoshuaKGoldberg commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/index.tsx
> +  }
Yeah the context here is that I _wanted_ to use a function component but kept having bad updates come in from the `ReactMonacoEditor` inside 😞 . This was quite a while ago so it's possible that's no longer necessary, or maybe I just wasn't experienced enough with hooks & persistent enough to figure it out.

Anyway, it seems reasonable that we might want to check more of the props for equality, but beware that requiring consumers to provide referentially equal props might require changing upstream code a good bit!

2021-07-23 20:34 UTC, JoshuaKGoldberg approved these changes
🚀

2021-07-23 20:35 UTC, JoshuaKGoldberg commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/styles.module.scss
> +@import "~styles/cc";
Huh, weird. Ok! 

fyi @codecaaron

2021-07-23 20:47 UTC, codecaaron commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/styles.module.scss
> +@import "~styles/cc";
is this reproduced somewhere I could gander at?

2021-07-23 21:09 UTC, aionate0812 commented on packages/monaco/src/MonacoEditor/SimpleMonacoEditor/styles.module.scss
> +@import "~styles/cc";
no but I can spin off a branch

2021-07-26 20:36 UTC, casey-speer approved these changes
Looks good, though as mentioned if we can convert to a functional component all the better.

2021-07-27 18:56 UTC, christian-dinh approved these changes
sorry for the delay, looks great to me as long as `node_modules` can't get pulled in!

2021-07-27 18:56 UTC, christian-dinh commented on packages/monaco/.gitignore
> +dist
is `node_modules` getting ignored by default?

2021-07-28 16:27 UTC, aionate0812 commented on packages/monaco/.gitignore
> +dist
yes it is

2021-07-28 16:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.1017ba.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-28 16:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6101862df455f33b96f27887--gamut-preview.netlify.app>https://6101862df455f33b96f27887--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6101862df455f33b96f27887>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-28 16:31 UTC, merged