feat: ProvidedForms
Codecademy/client-modules pull request #1918
Opened 2021-07-23 22:10 UTC by dreamwasp

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-07-23 22:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.4.72-alpha.f90743.0<br/>@codecademy/gamut-labs@19.16.10-alpha.f90743.0<br/>@codecademy/gamut@35.2.1-alpha.f90743.0<br/>@codecademy/styleguide@42.1.4-alpha.f90743.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-23 22:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fb3f9828539400ba7f24b5--gamut-preview.netlify.app>https://60fb3f9828539400ba7f24b5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fb3f9828539400ba7f24b5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-29 16:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.3-alpha.228645.0<br/>@codecademy/gamut-labs@19.16.15-alpha.228645.0<br/>@codecademy/gamut@35.4.3-alpha.228645.0<br/>@codecademy/styleguide@42.3.3-alpha.228645.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-29 16:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6102da564a903a541df02e8e--gamut-preview.netlify.app>https://6102da564a903a541df02e8e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6102da564a903a541df02e8e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-29 16:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.3-alpha.077402.0<br/>@codecademy/gamut-labs@19.16.15-alpha.077402.0<br/>@codecademy/gamut@35.4.3-alpha.077402.0<br/>@codecademy/styleguide@42.3.3-alpha.077402.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-29 16:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6102ddc5fe905145c0cfbb60--gamut-preview.netlify.app>https://6102ddc5fe905145c0cfbb60--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6102ddc5fe905145c0cfbb60>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-30 13:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.4-alpha.2e097c.0<br/>@codecademy/gamut-labs@19.16.16-alpha.2e097c.0<br/>@codecademy/gamut@35.4.4-alpha.2e097c.0<br/>@codecademy/styleguide@42.3.5-alpha.2e097c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-30 13:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61040169d522946450394ba3--gamut-preview.netlify.app>https://61040169d522946450394ba3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61040169d522946450394ba3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-30 17:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.4-alpha.869362.0<br/>@codecademy/gamut-labs@19.16.16-alpha.869362.0<br/>@codecademy/gamut@35.4.4-alpha.869362.0<br/>@codecademy/styleguide@42.3.5-alpha.869362.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-30 17:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61043573c6f1b7082153a679--gamut-preview.netlify.app>https://61043573c6f1b7082153a679--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61043573c6f1b7082153a679>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-30 17:53 UTC, codecaaron commented on packages/gamut/src/GridForm/GridForm.tsx
> +  Values extends Record<string, boolean | string | undefined | FileList>
We may want to make an intermediate type for `FormValues` or something now that this is shared in other places.
```suggestion
  Values extends FormValues
```

2021-07-30 17:53 UTC, codecaaron commented on packages/gamut/src/Form/FormWrapper.tsx
> +  validation?: Exclude<Mode, 'onBlur'>;
I know this is copied from somewhere else but just wondering why we can't / don't want to support on blur?

2021-08-02 13:42 UTC, dreamwasp commented on packages/gamut/src/Form/FormWrapper.tsx
> +  validation?: Exclude<Mode, 'onBlur'>;
yeah, i'm not sure! assumed it was a long ago design decision. i'll swap it over here since i can't foresee an issue with supporting it here?

2021-08-02 20:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.6-alpha.619b4f.0<br/>@codecademy/gamut-labs@19.16.18-alpha.619b4f.0<br/>@codecademy/gamut@35.5.1-alpha.619b4f.0<br/>@codecademy/styleguide@42.3.9-alpha.619b4f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-02 20:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6108568ce990ee26be7a59c4--gamut-preview.netlify.app>https://6108568ce990ee26be7a59c4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6108568ce990ee26be7a59c4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-02 21:06 UTC, codecaaron approved these changes
✅ 🥂

2021-08-02 21:06 UTC, codecaaron commented on packages/gamut/src/Form/FormWrapper.tsx
> +  const { handleSubmit, formState, ...methods } = useForm({ mode: validation });
Do we want to allow defaultValues here too?  IIRC the Controller defaultValue ended up causing some weird bugs if we allow both - but since GridForm does this it might make sense to do the same here.

2021-08-02 21:06 UTC, codecaaron commented on packages/gamut/src/GridForm/index.tsx
> +export { GridFormContent } from './GridFormSections/GridFormContent';
Is GridFormContent specific to a single field?

Content makes me think there is some polymorphic behavior here like sections and separators - but IIRC its just the Column and the Field right?

2021-08-02 21:18 UTC, dreamwasp commented on packages/gamut/src/Form/FormWrapper.tsx
> +  const { handleSubmit, formState, ...methods } = useForm({ mode: validation });
that requires passing the entire fields array into this FormWrapper which i'm slightly against, right now they're just hooking into formState and setting their values within the individual field components.... i'm sure there's a more ergonomic + DRY way to do this but i think it's a bridge i wanna cross when i incorporate FormWrapper into GridForm

2021-08-02 21:23 UTC, dreamwasp commented on packages/gamut/src/GridForm/index.tsx
> +export { GridFormContent } from './GridFormSections/GridFormContent';
it basically is just a component that hands the FormContext + error logic to `GridFormInputGroup`, which is where the Field + Column come from. naming things is hard, very open to better ideas! i think before i had named it something atrocious like `GridFormFieldContextProvider` or something ghastly.  eventually i will break this out of GridForm and it can just be `FormFieldWrapper` 😅

2021-08-02 21:28 UTC, codecaaron commented on packages/gamut/src/Form/FormWrapper.tsx
> +  const { handleSubmit, formState, ...methods } = useForm({ mode: validation });
I think it would have be typed to `Values` which we have right now.

So not the fields array just the object that we generate from the fields array right?  This way GridForm could consume this component after generating the defaultValues

2021-08-02 21:28 UTC, codecaaron commented on packages/gamut/src/GridForm/index.tsx
> +export { GridFormContent } from './GridFormSections/GridFormContent';
It is extremely hard!  That sounds like a good plan we can wait till then :)

2021-08-02 22:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.7-alpha.d21a6b.0<br/>@codecademy/gamut-labs@19.16.19-alpha.d21a6b.0<br/>@codecademy/gamut@35.6.1-alpha.d21a6b.0<br/>@codecademy/styleguide@42.4.1-alpha.d21a6b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-02 22:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61086f1821527d2a1ffb3f39--gamut-preview.netlify.app>https://61086f1821527d2a1ffb3f39--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61086f1821527d2a1ffb3f39>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-02 23:09 UTC, JoshuaKGoldberg requested changes
Without cheating and looking at the portal-app PR I cannot figure out how to use this. Docs please?

_(but also very excited about the form wrapper!)_

2021-08-03 12:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.12-alpha.0c8575.0<br/>@codecademy/gamut-labs@19.18.4-alpha.0c8575.0<br/>@codecademy/gamut@35.9.1-alpha.0c8575.0<br/>@codecademy/styleguide@42.6.4-alpha.0c8575.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-03 12:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61093c2842afb776fea251c4--gamut-preview.netlify.app>https://61093c2842afb776fea251c4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61093c2842afb776fea251c4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-03 13:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.12-alpha.96e83a.0<br/>@codecademy/gamut-labs@19.18.4-alpha.96e83a.0<br/>@codecademy/gamut@35.9.1-alpha.96e83a.0<br/>@codecademy/styleguide@42.6.4-alpha.96e83a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-03 13:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610941bba18b5b5000c82a36--gamut-preview.netlify.app>https://610941bba18b5b5000c82a36--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610941bba18b5b5000c82a36>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-03 13:23 UTC, JoshuaKGoldberg approved these changes
Thanks for the clarification!

Stoked to see form progress 🚀

2021-08-03 13:23 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/FormWrapper.tsx
> +
This way the doc gets nicely attached in IDEs:

```suggestion
/**
 * This is an in progress API! please reach out to the web-plat team if you're interested in using it.
 */
```

If you want to be _really_ aggressive about it you can add `@deprecated` to give it a strikethrough... might be too aggressive though, hehe

2021-08-03 13:23 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/index.tsx
> +// this is being exported as a piece of an in progress API. if you think you have a use-case for it, please reach out to the web-plat team.
```suggestion
/**
 * This is being exported as a piece of an in progress API. if you think you have a use-case for it, please reach out to the web-plat team.
 */
```

2021-08-03 13:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.13-alpha.a243f2.0<br/>@codecademy/gamut-labs@19.18.5-alpha.a243f2.0<br/>@codecademy/gamut@35.9.1-alpha.a243f2.0<br/>@codecademy/styleguide@42.6.5-alpha.a243f2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-03 13:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610946eb5cf4355bfce86abf--gamut-preview.netlify.app>https://610946eb5cf4355bfce86abf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610946eb5cf4355bfce86abf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-03 14:26 UTC, merged