feat: small SelectDropdown
Codecademy/client-modules pull request #1954
Opened 2021-08-05 20:51 UTC by dreamwasp

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-08-05 20:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.17-alpha.318f20.0<br/>@codecademy/gamut-labs@19.19.3-alpha.318f20.0<br/>@codecademy/gamut@35.12.1-alpha.318f20.0<br/>@codecademy/styleguide@42.7.1-alpha.318f20.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-05 21:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.18-alpha.0b87fa.0<br/>@codecademy/gamut-labs@19.19.4-alpha.0b87fa.0<br/>@codecademy/gamut@35.12.2-alpha.0b87fa.0<br/>@codecademy/styleguide@42.7.2-alpha.0b87fa.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-05 21:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610c521a12a5d800c942a0fc--gamut-preview.netlify.app>https://610c521a12a5d800c942a0fc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610c521a12a5d800c942a0fc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-05 21:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.18-alpha.508eb0.0<br/>@codecademy/gamut-labs@19.19.4-alpha.508eb0.0<br/>@codecademy/gamut@35.12.2-alpha.508eb0.0<br/>@codecademy/styleguide@42.7.2-alpha.508eb0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-05 21:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610c5d521ccf2f071517d9e6--gamut-preview.netlify.app>https://610c5d521ccf2f071517d9e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610c5d521ccf2f071517d9e6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-06 15:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.19-alpha.494882.0<br/>@codecademy/gamut-labs@19.19.5-alpha.494882.0<br/>@codecademy/gamut@35.12.3-alpha.494882.0<br/>@codecademy/styleguide@42.7.3-alpha.494882.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 18:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.19-alpha.1340d6.0<br/>@codecademy/gamut-labs@19.19.5-alpha.1340d6.0<br/>@codecademy/gamut@35.12.3-alpha.1340d6.0<br/>@codecademy/styleguide@42.7.3-alpha.1340d6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 18:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d8007fd210eed7064e1c3--gamut-preview.netlify.app>https://610d8007fd210eed7064e1c3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d8007fd210eed7064e1c3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-06 19:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.19-alpha.d5178c.0<br/>@codecademy/gamut-labs@19.19.5-alpha.d5178c.0<br/>@codecademy/gamut@35.12.3-alpha.d5178c.0<br/>@codecademy/styleguide@42.7.3-alpha.d5178c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 20:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d95108e155c21dcfb187b--gamut-preview.netlify.app>https://610d95108e155c21dcfb187b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d95108e155c21dcfb187b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-06 20:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.19-alpha.fa9f21.0<br/>@codecademy/gamut-labs@19.19.5-alpha.fa9f21.0<br/>@codecademy/gamut@35.12.3-alpha.fa9f21.0<br/>@codecademy/styleguide@42.7.3-alpha.fa9f21.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 20:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d98a714cf62045ab6b461--gamut-preview.netlify.app>https://610d98a714cf62045ab6b461--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d98a714cf62045ab6b461>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-06 20:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.19-alpha.93e759.0<br/>@codecademy/gamut-labs@19.19.5-alpha.93e759.0<br/>@codecademy/gamut@35.12.3-alpha.93e759.0<br/>@codecademy/styleguide@42.7.3-alpha.93e759.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 20:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d9a6d14cf620ac4b6b341--gamut-preview.netlify.app>https://610d9a6d14cf620ac4b6b341--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d9a6d14cf620ac4b6b341>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-06 20:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.922851.0<br/>@codecademy/gamut-labs@19.19.6-alpha.922851.0<br/>@codecademy/gamut@35.12.4-alpha.922851.0<br/>@codecademy/styleguide@42.7.4-alpha.922851.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 20:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d9f9f21756329c06a0210--gamut-preview.netlify.app>https://610d9f9f21756329c06a0210--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d9f9f21756329c06a0210>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-06 21:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.33875a.0<br/>@codecademy/gamut-labs@19.19.6-alpha.33875a.0<br/>@codecademy/gamut@35.12.4-alpha.33875a.0<br/>@codecademy/styleguide@42.7.4-alpha.33875a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 21:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610da3494f319f2bd8fcea1f--gamut-preview.netlify.app>https://610da3494f319f2bd8fcea1f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610da3494f319f2bd8fcea1f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-09 19:05 UTC, JoshuaKGoldberg requested changes
Unit test please?

2021-08-10 16:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.816a71.0<br/>@codecademy/gamut-labs@19.19.6-alpha.816a71.0<br/>@codecademy/gamut@35.12.4-alpha.816a71.0<br/>@codecademy/styleguide@42.7.4-alpha.816a71.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-10 16:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6112ad63fec24e63e257585b--gamut-preview.netlify.app>https://6112ad63fec24e63e257585b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6112ad63fec24e63e257585b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-11 20:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611433259803f5123becbb9d--gamut-preview.netlify.app>https://611433259803f5123becbb9d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611433259803f5123becbb9d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-11 21:13 UTC, codecaaron approved these changes

2021-08-11 21:13 UTC, codecaaron commented on packages/gamut/src/Form/styles/SelectDropdown-styles.ts
> +    base: formFieldPaddingStyles,
Nittiest of nits: Maybe `medium`, `normal` or `regular` here?

For whatever reason when I see `base` on variants I think of `base` shared styles - but might just be me.

2021-08-11 21:13 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +      )}
Might be overkill here but if there are multiple things we need to pass to these components it might make sense to figure out the component prior to calling them, that way we are sure each icon is getting the right props (IE color or other things)

```tsx
const indicatorSizes = {
  small:  {
    size: 12,
    icon: MiniChevronDownIcon,
  },
  base: {
     size: 16,
     icon: ArrowChevronDownIcon,
   }
}
```

Icon calls stay in sync 
```tsx
const { icon: IndicatorIcon, ...iconProps } = indicatorSizes[size];

return <IndicatorIcon {...iconProps} color={color} />
```

2021-08-12 16:58 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
> +        'i am small',
pls?

```suggestion
        'i am smol',
```

(not blocking lol)

2021-08-12 17:36 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +        padding: state.selectProps.size === 'small' ? '3px 14px' : '11px 14px',
ahhh, caused by a merge, will fix!!

2021-08-12 17:36 UTC, dreamwasp commented on packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
> +        'i am small',
yes

2021-08-12 17:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.25-alpha.715e5c.0<br/>@codecademy/gamut-labs@19.19.11-alpha.715e5c.0<br/>@codecademy/gamut@36.1.1-alpha.715e5c.0<br/>@codecademy/styleguide@43.1.1-alpha.715e5c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-12 17:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61155da474fd000096f7355a--gamut-preview.netlify.app>https://61155da474fd000096f7355a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61155da474fd000096f7355a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-12 18:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61156334d4ebe607b6de8a1a--gamut-preview.netlify.app>https://61156334d4ebe607b6de8a1a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61156334d4ebe607b6de8a1a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-12 18:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6115651bdcb64a0f2ebe31d9--gamut-preview.netlify.app>https://6115651bdcb64a0f2ebe31d9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6115651bdcb64a0f2ebe31d9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-12 20:17 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  ];
Ooh even cleaner than what I was thinking of! I like this a lot.

One lil nit:

```suggestion
  const { icon: IndicatorIcon, ...iconProps } = indicatorSizes[size ?? 'small'];
```

2021-08-12 20:24 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  ];
🙏

2021-08-12 21:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.26-alpha.636389.0<br/>@codecademy/gamut-labs@19.20.1-alpha.636389.0<br/>@codecademy/gamut@36.1.1-alpha.636389.0<br/>@codecademy/styleguide@43.2.1-alpha.636389.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-12 21:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611595efd4ebe63ccdde864d--gamut-preview.netlify.app>https://611595efd4ebe63ccdde864d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611595efd4ebe63ccdde864d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-12 21:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.27-alpha.21d403.0<br/>@codecademy/gamut-labs@19.20.2-alpha.21d403.0<br/>@codecademy/gamut@36.1.2-alpha.21d403.0<br/>@codecademy/styleguide@43.2.2-alpha.21d403.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-12 21:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611597f7e204ad3d1b85634c--gamut-preview.netlify.app>https://611597f7e204ad3d1b85634c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611597f7e204ad3d1b85634c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 14:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.28-alpha.4f82c2.0<br/>@codecademy/gamut-labs@19.20.3-alpha.4f82c2.0<br/>@codecademy/gamut@36.1.3-alpha.4f82c2.0<br/>@codecademy/styleguide@43.2.3-alpha.4f82c2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 14:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61168084adc6fb32dfb78d0a--gamut-preview.netlify.app>https://61168084adc6fb32dfb78d0a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61168084adc6fb32dfb78d0a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 14:58 UTC, JoshuaKGoldberg approved these changes
💖

2021-08-13 17:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.28-alpha.c3bc49.0<br/>@codecademy/gamut-labs@19.20.3-alpha.c3bc49.0<br/>@codecademy/gamut@36.1.3-alpha.c3bc49.0<br/>@codecademy/styleguide@43.3.1-alpha.c3bc49.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 17:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116ad03eb82ed2378c1a13c--gamut-preview.netlify.app>https://6116ad03eb82ed2378c1a13c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116ad03eb82ed2378c1a13c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 17:42 UTC, merged