feat: SelectDropdown shownOptions
Codecademy/client-modules pull request #1957
Opened 2021-08-06 17:52 UTC by dreamwasp

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-08-06 17:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.19-alpha.bbc872.0<br/>@codecademy/gamut-labs@19.19.5-alpha.bbc872.0<br/>@codecademy/gamut@35.12.3-alpha.bbc872.0<br/>@codecademy/styleguide@42.7.3-alpha.bbc872.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 17:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610d7878fef152e6d4b644f8--gamut-preview.netlify.app>https://610d7878fef152e6d4b644f8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610d7878fef152e6d4b644f8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-06 20:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.92575c.0<br/>@codecademy/gamut-labs@19.19.6-alpha.92575c.0<br/>@codecademy/gamut@35.12.4-alpha.92575c.0<br/>@codecademy/styleguide@42.7.4-alpha.92575c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 20:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610da0f4b5d12c1f385f5bb5--gamut-preview.netlify.app>https://610da0f4b5d12c1f385f5bb5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610da0f4b5d12c1f385f5bb5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-06 21:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.91b801.0<br/>@codecademy/gamut-labs@19.19.6-alpha.91b801.0<br/>@codecademy/gamut@35.12.4-alpha.91b801.0<br/>@codecademy/styleguide@42.7.4-alpha.91b801.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-06 21:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://610da4801ec7264863b9ca41--gamut-preview.netlify.app>https://610da4801ec7264863b9ca41--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/610da4801ec7264863b9ca41>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-09 19:04 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
> +      placeholder: 'no its three actually',
Little UI bug here, is this known?

![Screenshot of placeholder text overlapping](https://user-images.githubusercontent.com/3335181/128760147-cdbbdd34-b8d8-4a7e-9686-76ac6a41fe15.png)

2021-08-09 19:04 UTC, JoshuaKGoldberg requested changes
LGTM!

Unit test please?

2021-08-09 19:04 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  shownOptions?: 1 | 2 | 3 | 4 | 5 | 6;
Just confirming: we _never_ want to show > 6?

2021-08-10 16:34 UTC, dreamwasp commented on packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
> +      placeholder: 'no its three actually',
eh, i goofed up the width. fixed now!

2021-08-10 16:35 UTC, dreamwasp commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  shownOptions?: 1 | 2 | 3 | 4 | 5 | 6;
yupp! confirmed with @songstephen

2021-08-10 16:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.458b2f.0<br/>@codecademy/gamut-labs@19.19.6-alpha.458b2f.0<br/>@codecademy/gamut@35.12.4-alpha.458b2f.0<br/>@codecademy/styleguide@42.7.4-alpha.458b2f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-10 16:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.20-alpha.01f61f.0<br/>@codecademy/gamut-labs@19.19.6-alpha.01f61f.0<br/>@codecademy/gamut@35.12.4-alpha.01f61f.0<br/>@codecademy/styleguide@42.7.4-alpha.01f61f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-10 16:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6112accb21764b52734fce22--gamut-preview.netlify.app>https://6112accb21764b52734fce22--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6112accb21764b52734fce22>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-11 21:04 UTC, codecaaron approved these changes

2021-08-11 21:04 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +      shownOptions={shownOptions}
At a glance shownOptions makes me feel like this is a subset of the passed options (like a sort thing) didn't think it would be a number.  I've generally seen this with some variation of `limit` in as a prop - but I can't think of anything idiomatic :shrug:

2021-08-11 21:04 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +        const numberOfShown = state.selectProps.shownOptions ?? 6;
Is there any possibility that `state.showOptions` and `showOptions` from props are get decoupled?  (Assuming this avoiding having to add it as a dep to the useMemo.

2021-08-11 21:04 UTC, codecaaron commented on packages/gamut/src/Form/SelectDropdown.tsx
> +  shownOptions,
Can replace this https://github.com/Codecademy/client-modules/pull/1957/files#diff-fcaeb7ab98af88e2ffbd7eee363c51f3a0b9e77ae092caf53c94037e16a8c424R169

```suggestion
  shownOptions = 6,
```

2021-08-12 17:17 UTC, JoshuaKGoldberg approved these changes
Nothing beyond what @codecaaron is saying so ✅  from me otherwise! Sweet!

2021-08-12 17:17 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
> +You can chose how options will be shown in the dropdown, with 6 being the default and the max.
> 6 being the default and the max

A little confusing to read this: is it.. both the default _and_ always the max? Like if I pass 7 will it be capped to 6?

2021-08-12 19:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.26-alpha.fb1c4c.0<br/>@codecademy/gamut-labs@19.20.1-alpha.fb1c4c.0<br/>@codecademy/gamut@36.1.1-alpha.fb1c4c.0<br/>@codecademy/styleguide@43.2.1-alpha.fb1c4c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-12 19:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61157697bed0321febca4166--gamut-preview.netlify.app>https://61157697bed0321febca4166--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61157697bed0321febca4166>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 17:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.28-alpha.947db2.0<br/>@codecademy/gamut-labs@19.20.3-alpha.947db2.0<br/>@codecademy/gamut@36.2.0-alpha.947db2.0<br/>@codecademy/styleguide@43.4.0-alpha.947db2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 17:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116b2299b5576337785c68c--gamut-preview.netlify.app>https://6116b2299b5576337785c68c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116b2299b5576337785c68c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 18:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.29-alpha.3c685a.0<br/>@codecademy/gamut-labs@19.20.4-alpha.3c685a.0<br/>@codecademy/gamut@36.2.1-alpha.3c685a.0<br/>@codecademy/styleguide@43.4.1-alpha.3c685a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 18:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116b421fc2e762ce03bf280--gamut-preview.netlify.app>https://6116b421fc2e762ce03bf280--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116b421fc2e762ce03bf280>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 18:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.29-alpha.b06c62.0<br/>@codecademy/gamut-labs@19.20.4-alpha.b06c62.0<br/>@codecademy/gamut@36.2.1-alpha.b06c62.0<br/>@codecademy/styleguide@43.4.1-alpha.b06c62.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 18:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116b66e8f229d008ee4882f--gamut-preview.netlify.app>https://6116b66e8f229d008ee4882f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116b66e8f229d008ee4882f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 18:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.29-alpha.15fb37.0<br/>@codecademy/gamut-labs@19.20.4-alpha.15fb37.0<br/>@codecademy/gamut@36.2.1-alpha.15fb37.0<br/>@codecademy/styleguide@43.4.1-alpha.15fb37.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 18:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116bc21092b170096c0adc9--gamut-preview.netlify.app>https://6116bc21092b170096c0adc9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116bc21092b170096c0adc9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 19:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.29-alpha.53f4dd.0<br/>@codecademy/gamut-labs@19.20.4-alpha.53f4dd.0<br/>@codecademy/gamut@36.2.1-alpha.53f4dd.0<br/>@codecademy/styleguide@43.4.1-alpha.53f4dd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 19:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116c4f0ee19a40c1c143b45--gamut-preview.netlify.app>https://6116c4f0ee19a40c1c143b45--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116c4f0ee19a40c1c143b45>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 19:19 UTC, merged