Split out modal components
Codecademy/client-modules pull request #1964
Opened 2021-08-09 20:47 UTC by codecaaron

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-08-09 22:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.22-alpha.cea900.0<br/>@codecademy/gamut-labs@19.19.8-alpha.cea900.0<br/>@codecademy/gamut@35.14.1-alpha.cea900.0<br/>@codecademy/styleguide@42.7.8-alpha.cea900.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-09 22:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6111affa1612e155a76f2832--gamut-preview.netlify.app>https://6111affa1612e155a76f2832--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6111affa1612e155a76f2832>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-09 22:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.22-alpha.6b6d23.0<br/>@codecademy/gamut-labs@19.19.8-alpha.6b6d23.0<br/>@codecademy/gamut@35.14.1-alpha.6b6d23.0<br/>@codecademy/styleguide@42.7.8-alpha.6b6d23.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-09 22:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6111b1a11bf4865273e6def9--gamut-preview.netlify.app>https://6111b1a11bf4865273e6def9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6111b1a11bf4865273e6def9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-10 14:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.22-alpha.7dcd16.0<br/>@codecademy/gamut-labs@19.19.8-alpha.7dcd16.0<br/>@codecademy/gamut@35.14.1-alpha.7dcd16.0<br/>@codecademy/styleguide@42.7.8-alpha.7dcd16.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-10 14:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6112905c801cb98e6e5cee78--gamut-preview.netlify.app>https://6112905c801cb98e6e5cee78--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6112905c801cb98e6e5cee78>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-10 18:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.22-alpha.ce9852.0<br/>@codecademy/gamut-labs@19.19.8-alpha.ce9852.0<br/>@codecademy/gamut@35.14.1-alpha.ce9852.0<br/>@codecademy/styleguide@42.7.8-alpha.ce9852.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-10 18:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6112c91a148ef57f1e4196bb--gamut-preview.netlify.app>https://6112c91a148ef57f1e4196bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6112c91a148ef57f1e4196bb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-10 19:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.22-alpha.bb4bd8.0<br/>@codecademy/gamut-labs@19.19.8-alpha.bb4bd8.0<br/>@codecademy/gamut@35.14.1-alpha.bb4bd8.0<br/>@codecademy/styleguide@42.7.8-alpha.bb4bd8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-10 19:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6112d74b044c78d7fdff5f0c--gamut-preview.netlify.app>https://6112d74b044c78d7fdff5f0c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6112d74b044c78d7fdff5f0c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-10 20:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.22-alpha.da7b6f.0<br/>@codecademy/gamut-labs@19.19.8-alpha.da7b6f.0<br/>@codecademy/gamut@35.14.1-alpha.da7b6f.0<br/>@codecademy/styleguide@42.7.8-alpha.da7b6f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-10 20:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6112e622044c78eac0ff5e2e--gamut-preview.netlify.app>https://6112e622044c78eac0ff5e2e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6112e622044c78eac0ff5e2e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-10 21:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.23-alpha.3dc772.0<br/>@codecademy/gamut-labs@19.19.9-alpha.3dc772.0<br/>@codecademy/gamut@36.0.1-alpha.3dc772.0<br/>@codecademy/styleguide@43.0.1-alpha.3dc772.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-10 21:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6112eca25b77c6878e0009f8--gamut-preview.netlify.app>https://6112eca25b77c6878e0009f8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6112eca25b77c6878e0009f8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-10 21:57 UTC, dreamwasp approved these changes
🧇  wonderful

2021-08-10 21:57 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx
> +- `Alert`: Actionable direct user feedback.
🔥🔥🔥

2021-08-11 14:30 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx
> +- `Alert`: Actionable direct user feedback.
urgfh yes

2021-08-11 17:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.23-alpha.9f4b80.0<br/>@codecademy/gamut-labs@19.19.9-alpha.9f4b80.0<br/>@codecademy/gamut@36.0.1-alpha.9f4b80.0<br/>@codecademy/styleguide@43.0.1-alpha.9f4b80.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-11 17:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61140fcda7bc070091568629--gamut-preview.netlify.app>https://61140fcda7bc070091568629--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61140fcda7bc070091568629>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-11 18:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.24-alpha.b8d1ec.0<br/>@codecademy/gamut-labs@19.19.10-alpha.b8d1ec.0<br/>@codecademy/gamut@36.0.2-alpha.b8d1ec.0<br/>@codecademy/styleguide@43.0.2-alpha.b8d1ec.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-11 18:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61141bf28036cb00992f0e51--gamut-preview.netlify.app>https://61141bf28036cb00992f0e51--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61141bf28036cb00992f0e51>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-11 19:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.24-alpha.fe746f.0<br/>@codecademy/gamut-labs@19.19.10-alpha.fe746f.0<br/>@codecademy/gamut@36.0.2-alpha.fe746f.0<br/>@codecademy/styleguide@43.0.2-alpha.fe746f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-11 20:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611437cc6c4fa51621f0bd6d--gamut-preview.netlify.app>https://611437cc6c4fa51621f0bd6d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611437cc6c4fa51621f0bd6d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-11 21:33 UTC, songstephen commented on packages/styleguide/stories/Molecules/Modals/Overlay.stories.mdx
> +          <FillButton onClick={() => setOpen(true)}>Open Overlay</FillButton>
Might be good to enable the shroud for the example overlays so the overlay is more visible when folks are exploring this!

2021-08-11 21:35 UTC, songstephen commented on packages/styleguide/stories/Molecules/Modals/Overlay.stories.mdx
>              <Overlay
Might be good to enable the shroud in this example so the Overlay is more visible when folks are exploring this!

2021-08-12 16:46 UTC, JoshuaKGoldberg requested changes
Lovely overall - just a few things!

2021-08-12 16:46 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx
> +- `Alert`: Actionable direct user feedback.
Can these be links please? (here and below)

2021-08-12 16:46 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx
> +### Related Components
I was actually looking for something like this in the root `Modals/About` page haha. Can you move this there with a bit of an introduction please?

2021-08-12 16:46 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Modals/Overlay.stories.mdx
> +Edit attributes and see what’s possible to do with this component or get the exact output you want.
I wonder if, long term, we should standardize this for all code playgrounds...

2021-08-12 22:00 UTC, saghdaey commented
Looks great so far -- I tested in the monolith! 

I'm having trouble viewing the code for some of the stories -- example for the modal size variants; and when I try to switch to "canvas" view the page breaks

https://611437cc6c4fa51621f0bd6d--gamut-preview.netlify.app/storybook/?path=/docs/molecules-modals-modal--medium

2021-08-13 18:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.29-alpha.00b952.0<br/>@codecademy/gamut-labs@19.20.4-alpha.00b952.0<br/>@codecademy/gamut@36.2.1-alpha.00b952.0<br/>@codecademy/styleguide@43.4.1-alpha.00b952.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 18:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116b77ff3ac540096a96cdf--gamut-preview.netlify.app>https://6116b77ff3ac540096a96cdf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116b77ff3ac540096a96cdf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 18:50 UTC, JoshuaKGoldberg commented on packages/gamut/src/Modals/__tests__/Modal-test.tsx
> +      showCloseButton: false,
🤔

2021-08-13 18:50 UTC, JoshuaKGoldberg commented on packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx
> +### Related Components
bump @codecaaron - yay or nay?

2021-08-13 18:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.29-alpha.3de45d.0<br/>@codecademy/gamut-labs@19.20.4-alpha.3de45d.0<br/>@codecademy/gamut@36.2.1-alpha.3de45d.0<br/>@codecademy/styleguide@43.4.1-alpha.3de45d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 18:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116c0e543bd000a3a58e4aa--gamut-preview.netlify.app>https://6116c0e543bd000a3a58e4aa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116c0e543bd000a3a58e4aa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 19:10 UTC, codecaaron commented on packages/gamut/src/Modals/__tests__/Modal-test.tsx
> +      showCloseButton: false,
@JoshuaKGoldberg I forgot to update the tests lol

2021-08-13 19:37 UTC, JoshuaKGoldberg approved these changes
Super!

2021-08-13 19:44 UTC, codecaaron commented on packages/styleguide/stories/Molecules/Modals/Overlay.stories.mdx
> +Edit attributes and see what’s possible to do with this component or get the exact output you want.
👍  I'd like to but I think we can only do it with a snippet rather than using the Docs container due to the way storybook handles story registration during the build (it might be possible with the storybook legacy API).

2021-08-13 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.30-alpha.86930f.0<br/>@codecademy/gamut-labs@19.20.5-alpha.86930f.0<br/>@codecademy/gamut@36.3.1-alpha.86930f.0<br/>@codecademy/styleguide@43.5.1-alpha.86930f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 19:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116cd0ed7f79400915cb2e5--gamut-preview.netlify.app>https://6116cd0ed7f79400915cb2e5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116cd0ed7f79400915cb2e5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 19:54 UTC, merged