fix: Performance boost for <Truncate />
Codecademy/client-modules pull request #1968
Opened 2021-08-11 17:30 UTC by MattSchiller

### Overview

Small performance boost for expanded text within truncation component

Just noticed that we were always generating the truncated text content, even when the truncated text was in an expanded state. This should provide a bit more performance when we're actually in the expanded state.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-08-11 17:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61140a55de05aa00e5ee1fcc--gamut-preview.netlify.app>https://61140a55de05aa00e5ee1fcc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61140a55de05aa00e5ee1fcc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-11 17:58 UTC, codecaaron requested changes

2021-08-11 17:58 UTC, codecaaron commented on packages/gamut/src/Truncate/index.tsx
> +  ) : (
👍  to the perf increase but we need to  also wrap `TuncateMarkup` with a container `<Box display="inline-block" width="100%" className={className}>` in all cases or it will break as it won't know to untruncate something when more space is available.

2021-08-13 14:31 UTC, MattSchiller commented on packages/gamut/src/Truncate/index.tsx
> +  ) : (
Is that a bug from earlier? I didn't change the effective markup at all here 🤔

2021-08-13 20:02 UTC, codecaaron approved these changes

2021-08-13 20:02 UTC, codecaaron commented on packages/gamut/src/Truncate/index.tsx
> +  ) : (
Oh I misread - apologies!

2021-08-13 20:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.31-alpha.7267bc.0<br/>@codecademy/gamut-labs@19.20.6-alpha.7267bc.0<br/>@codecademy/gamut@36.4.1-alpha.7267bc.0<br/>@codecademy/styleguide@43.6.1-alpha.7267bc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 20:24 UTC, merged

2021-08-13 20:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6116d511db9a380c7c2a54b3--gamut-preview.netlify.app>https://6116d511db9a380c7c2a54b3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6116d511db9a380c7c2a54b3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->