feat(icon): hyper link 3 icon
Codecademy/client-modules pull request #1972
Opened 2021-08-13 13:11 UTC by saghdaey

### Overview

Added the hyperlink 3 icon

### PR Checklist

- [ ] Related to designs: https://www.figma.com/file/plUAVokatDi5L3zexvlkY8/Build?node-id=2%3A838
- [ ] Related to JIRA ticket: EGG-1688
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-08-13 13:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.3-alpha.14dc3a.0<br/>@codecademy/gamut-kit@0.5.27-alpha.14dc3a.0<br/>@codecademy/gamut-labs@19.20.2-alpha.14dc3a.0<br/>@codecademy/gamut@36.1.2-alpha.14dc3a.0<br/>@codecademy/styleguide@43.2.2-alpha.14dc3a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 16:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.4-alpha.22b47b.0<br/>@codecademy/gamut-kit@0.5.28-alpha.22b47b.0<br/>@codecademy/gamut-labs@19.20.3-alpha.22b47b.0<br/>@codecademy/gamut@36.1.3-alpha.22b47b.0<br/>@codecademy/styleguide@43.2.3-alpha.22b47b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-13 16:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61169f9b0a8d87157c0f128a--gamut-preview.netlify.app>https://61169f9b0a8d87157c0f128a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61169f9b0a8d87157c0f128a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-13 17:02 UTC, mstykmshy approved these changes
LGTM! :)

2021-08-13 19:39 UTC, codecaaron requested changes

2021-08-13 19:39 UTC, codecaaron commented on packages/gamut-icons/src/svg/regular/hyperlink-3-icon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>hyperlink-3</title><path d="M10.458,18.374,7.721,21.11a2.853,2.853,0,0,1-3.942,0l-.892-.891a2.787,2.787,0,0,1,0-3.941l5.8-5.8a2.789,
Let's rename this to just `hyperlink-icon` (@songstephen thoughts on naming?) and add the slug as a title here.

2021-08-16 12:54 UTC, saghdaey commented on packages/gamut-icons/src/svg/regular/hyperlink-3-icon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>hyperlink-3</title><path d="M10.458,18.374,7.721,21.11a2.853,2.853,0,0,1-3.942,0l-.892-.891a2.787,2.787,0,0,1,0-3.941l5.8-5.8a2.789,
renamed the file and left the title as "hyperlink-3" to match the streamline slug! is that correct?

2021-08-16 12:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.4-alpha.c88cdd.0<br/>@codecademy/gamut-kit@0.5.32-alpha.c88cdd.0<br/>@codecademy/gamut-labs@19.20.7-alpha.c88cdd.0<br/>@codecademy/gamut@36.4.2-alpha.c88cdd.0<br/>@codecademy/styleguide@43.6.2-alpha.c88cdd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-16 13:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611a61a84a137e3cd077a75e--gamut-preview.netlify.app>https://611a61a84a137e3cd077a75e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611a61a84a137e3cd077a75e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-16 14:27 UTC, codecaaron approved these changes

2021-08-16 15:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.8.5-alpha.7985f2.0<br/>@codecademy/gamut-kit@0.5.33-alpha.7985f2.0<br/>@codecademy/gamut-labs@19.21.1-alpha.7985f2.0<br/>@codecademy/gamut@36.4.3-alpha.7985f2.0<br/>@codecademy/styleguide@43.7.1-alpha.7985f2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-16 15:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611a8094fed150b8861f906a--gamut-preview.netlify.app>https://611a8094fed150b8861f906a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611a8094fed150b8861f906a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-16 15:17 UTC, merged