feat: Toaster
Codecademy/client-modules pull request #2008
Opened 2021-08-30 14:54 UTC by sooinc

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-09-09 23:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.64-alpha.ef2ca7.0<br/>@codecademy/gamut-labs@19.24.8-alpha.ef2ca7.0<br/>@codecademy/gamut@37.1.1-alpha.ef2ca7.0<br/>@codecademy/monaco@0.3.13-alpha.ef2ca7.0<br/>@codecademy/styleguide@44.1.4-alpha.ef2ca7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-09 23:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613a9d6dff28a1426e2a05a1--gamut-preview.netlify.app>https://613a9d6dff28a1426e2a05a1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613a9d6dff28a1426e2a05a1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-10 00:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.64-alpha.7765b6.0<br/>@codecademy/gamut-labs@19.24.8-alpha.7765b6.0<br/>@codecademy/gamut@37.1.1-alpha.7765b6.0<br/>@codecademy/monaco@0.3.13-alpha.7765b6.0<br/>@codecademy/styleguide@44.1.4-alpha.7765b6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-10 00:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613aa1b99a608b453f6b4138--gamut-preview.netlify.app>https://613aa1b99a608b453f6b4138--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613aa1b99a608b453f6b4138>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-10 12:05 UTC, codecaaron reviewed
Looking great!!! Just a few small questions on types and prop naming :)

2021-09-10 12:05 UTC, codecaaron commented on packages/gamut/src/Toaster/index.tsx
> +};
Any reason we wouldn't want to import the props type from https://github.com/Codecademy/client-modules/blob/main/packages/gamut/src/Toast/Toast.tsx#L54

And extend it with an id?

```tsx
interface ToasterItem extends ToastProps {
  id: string;
}
```

2021-09-10 12:05 UTC, codecaaron commented on packages/gamut/src/Toaster/index.tsx
> +  const closeToast = (id: string) => onClose(id);
I think we don't need to declare a new fn here since `onClose` has the same signature.

```tsx
<Toast {...toast}  onClose={() => onClose(toast.id)} />
```

2021-09-10 13:28 UTC, sooinc commented on packages/gamut/src/Toaster/index.tsx
> +};
ah yes, good point!

2021-09-10 14:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.64-alpha.564632.0<br/>@codecademy/gamut-labs@19.24.8-alpha.564632.0<br/>@codecademy/gamut@37.1.1-alpha.564632.0<br/>@codecademy/monaco@0.3.13-alpha.564632.0<br/>@codecademy/styleguide@44.1.4-alpha.564632.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-10 14:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b6a326a6eeaeca61c28ad--gamut-preview.netlify.app>https://613b6a326a6eeaeca61c28ad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b6a326a6eeaeca61c28ad>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-10 14:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.73-alpha.c5b34b.0<br/>@codecademy/gamut-labs@19.26.2-alpha.c5b34b.0<br/>@codecademy/gamut@37.3.2-alpha.c5b34b.0<br/>@codecademy/monaco@0.4.2-alpha.c5b34b.0<br/>@codecademy/styleguide@44.3.2-alpha.c5b34b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-10 14:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b706ab8661b2c516f0a98--gamut-preview.netlify.app>https://613b706ab8661b2c516f0a98--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b706ab8661b2c516f0a98>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-10 15:04 UTC, JoshuaKGoldberg requested changes
Unit tests please? :)

2021-09-10 15:04 UTC, JoshuaKGoldberg commented on packages/gamut/src/Toaster/index.tsx
> +export const Toaster: React.FC<ToasterProps> = ({ toasts = [], onClose }) => {
Hmm, how is this going to work with `aria-live`? https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

2021-09-10 17:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.10.1-alpha.46efe8.0<br/>@codecademy/gamut-illustrations@0.18.1-alpha.46efe8.0<br/>@codecademy/gamut-kit@0.5.73-alpha.46efe8.0<br/>@codecademy/gamut-labs@19.26.2-alpha.46efe8.0<br/>@codecademy/gamut-patterns@0.6.1-alpha.46efe8.0<br/>@codecademy/gamut-styles@11.10.1-alpha.46efe8.0<br/>@codecademy/gamut-tests@2.6.1-alpha.46efe8.0<br/>@codecademy/gamut@37.3.2-alpha.46efe8.0<br/>@codecademy/konamimojisplosion@0.3.1-alpha.46efe8.0<br/>@codecademy/markdown-overrides@0.6.1-alpha.46efe8.0<br/>@codecademy/monaco@0.4.2-alpha.46efe8.0<br/>@codecademy/styleguide@44.3.2-alpha.46efe8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-10 17:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://613b929b33442614e4da5f62--gamut-preview.netlify.app>https://613b929b33442614e4da5f62--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/613b929b33442614e4da5f62>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-10 17:22 UTC, sooinc commented on packages/styleguide/.storybook/getStories.ts
> +  'Toaster',
note: excluding this as we can't use hooks in stories and I'm utilizing hook for Toaster story.

But yes, will be adding unit tests!

2021-09-29 21:47 UTC, melaniemohn commented
Hey @sooinc, are you still working on adding this Toaster component? We'd love to use it for success messages on save in Author! I'm happy to help out with unit tests or anything else. Just lmk! 🍞

2021-09-30 17:30 UTC, sooinc commented
> Hey @sooinc, are you still working on adding this Toaster component? We'd love to use it for success messages on save in Author! I'm happy to help out with unit tests or anything else. Just lmk! 🍞

Hi @melaniemohn, yes! sorry for the delay. I pushed up the unit tests but i'm working out some kinks with making it a11y. pairing with someone in the afternoon so hopefully can have this ready by review again by EOD.

2021-09-30 19:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@5.12.1-alpha.e66b91.0<br/>@codecademy/gamut-illustrations@0.18.3-alpha.e66b91.0<br/>@codecademy/gamut-kit@0.5.98-alpha.e66b91.0<br/>@codecademy/gamut-labs@24.1.2-alpha.e66b91.0<br/>@codecademy/gamut-patterns@0.6.2-alpha.e66b91.0<br/>@codecademy/gamut-styles@11.10.2-alpha.e66b91.0<br/>@codecademy/gamut-tests@2.6.2-alpha.e66b91.0<br/>@codecademy/gamut@37.7.2-alpha.e66b91.0<br/>@codecademy/konamimojisplosion@0.3.2-alpha.e66b91.0<br/>@codecademy/markdown-overrides@0.6.2-alpha.e66b91.0<br/>@codecademy/monaco@0.4.14-alpha.e66b91.0<br/>@codecademy/styleguide@47.1.2-alpha.e66b91.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-30 19:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6156101c3790459654fcf866--gamut-preview.netlify.app>https://6156101c3790459654fcf866--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6156101c3790459654fcf866>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-30 19:42 UTC, sooinc commented on packages/gamut/src/Toaster/index.tsx
> +export const Toaster: React.FC<ToasterProps> = ({ toasts = [], onClose }) => {
I was referring to [this](https://getbootstrap.com/docs/4.3/components/toasts/#accessibility) and saw that both the toaster and the toasts need to have an aria-live region and that the live region needs to be present in the markup before the toast is generated or updated. It seems to work - announces the toasts when they appear but does not announce again if you refresh.

https://user-images.githubusercontent.com/58445391/135519998-19034cd3-d78b-4ade-8b62-41d7cf448e7e.mp4 

I thinking using aria-live="polite" makes more sense for toasts as they're not as urgent as alerts. Please let me know if you have additional thoughts around this!

2021-09-30 21:10 UTC, JoshuaKGoldberg requested changes
This look *GREAT* - code looks great & thanks for the tests! 🌮 

Just the one bug? If that's only a Storybook thing then I'm good to ✅

2021-09-30 21:10 UTC, JoshuaKGoldberg commented on packages/gamut-styles/src/variables/timing.ts
> +  toastExitDuration: 0.175,
Any reason not to use `fast` here? They're so close..

Failing that, I'll echo Aaron's message on my PR 😄 : https://github.com/Codecademy/client-modules/pull/2083#discussion_r718935816

2021-09-30 21:10 UTC, JoshuaKGoldberg commented on packages/gamut/src/Motion/FadeInSlideOut.tsx
> +  <motion.div
If you use `motion.custom(Box)` you should be able to combine the `motion.div` and `Box py={8}`.

https://github.com/Codecademy/client-modules/pull/2083/files#diff-4f1cf25cbdc61e1e2bf35c97a2a67e4858d4264378104d8201334b8e4e3fef52R7

2021-09-30 21:10 UTC, JoshuaKGoldberg commented on packages/gamut/src/Toaster/index.tsx
> +export const Toaster: React.FC<ToasterProps> = ({ toasts = [], onClose }) => {
Aha super that sounds right, thanks!

2021-09-30 21:10 UTC, JoshuaKGoldberg commented on packages/gamut/src/Toaster/index.tsx
> +        <Box right={16} bottom={88} position="fixed" aria-live="polite">
This is happening both on the docs view and when I view the [iframe directly](https://6156101c3790459654fcf866--gamut-preview.netlify.app/iframe.html?id=molecules-toaster--toaster&viewMode=story). Some kind of bug with animations?

https://user-images.githubusercontent.com/3335181/135530485-3595cdf7-aeb3-46ff-b966-c066916946ef.mov

2021-09-30 21:27 UTC, sooinc commented on packages/gamut/src/Motion/FadeInSlideOut.tsx
> +  <motion.div
ooh TIL! will try that

2021-09-30 21:28 UTC, sooinc commented on packages/gamut-styles/src/variables/timing.ts
> +  toastExitDuration: 0.175,
i wanted to maintain the same speed we were using in monolith but yea it really is so close. if there are no objections, i can switch to using fast :)

2021-09-30 21:40 UTC, sooinc commented on packages/gamut/src/Toaster/index.tsx
> +        <Box right={16} bottom={88} position="fixed" aria-live="polite">
ah yes, this is a storybook bug. I noticed it happens when I add too soon after removing all - sorry forgot to mention it. i can try using setTimeout() to delay it.

2021-10-01 01:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.99-alpha.f2606c.0<br/>@codecademy/gamut-labs@24.2.1-alpha.f2606c.0<br/>@codecademy/gamut@37.8.1-alpha.f2606c.0<br/>@codecademy/monaco@0.4.15-alpha.f2606c.0<br/>@codecademy/styleguide@47.2.1-alpha.f2606c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-10-01 01:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61565ffa395c6a26242cacfd--gamut-preview.netlify.app>https://61565ffa395c6a26242cacfd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61565ffa395c6a26242cacfd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-10-01 14:30 UTC, JoshuaKGoldberg approved these changes
Awesome, thanks Sooin!

2021-10-01 14:50 UTC, merged