feat(LayoutMenu): additional links section above accordions
Codecademy/client-modules pull request #2063
Opened 2021-09-16 16:19 UTC by amabarr

### Overview

An additional section above accordions in the LayoutMenu.

### PR Checklist

- [x] Related to designs: [External Organization Catalog](https://www.figma.com/file/YR6abM4OmOq0Q8YrifzOpn/Self-Service-Course-%26-Path-Release?node-id=492%3A5861)
- [x] Related to JIRA ticket: [CONPLAT-1134](https://codecademy.atlassian.net/secure/RapidBoard.jspa?rapidView=156&modal=detail&selectedIssue=CONPLAT-1134)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-09-16 16:27 UTC, JoshuaKGoldberg requested changes
👋  hi jumping on here because I also happen to be working on this component elsewhere 😄

2021-09-16 16:27 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
> +  topLinkSection?: React.ReactNode;
Allowing any `React.ReactNode` means any sort of button/text/whatnot could be added in. IMO we'd generally want to be a bit more restrictive in the designs and only allow the specific kinds of things this area is intended to include: in this case, button links. 

How about making this a `Section` or `SectionItem` the way the other sections are set up?

```suggestion
  topLinkSection?: SectionItem[];
```

2021-09-16 17:33 UTC, amabarr commented on packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
> +  topLinkSection?: React.ReactNode;
I see your point. I was following the way children act here, since we'd want to conditionally render some top links based on if you belong to an organization + your organization has its own content and making a component do that and pass it into this just seemed so nice.

If your organization has content, we want that link on top of all the links and the full catalog link below it. If not, we just want just the full catalog link on top. I'll edit this to make it a SectionItem[], and just do some calculations in portal after we fetch everything.

2021-09-16 17:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.81-alpha.181ab7.0<br/>@codecademy/gamut-labs@20.0.2-alpha.181ab7.0<br/>@codecademy/styleguide@44.6.3-alpha.181ab7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-16 17:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614385be556de509499225cb--gamut-preview.netlify.app>https://614385be556de509499225cb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614385be556de509499225cb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-16 18:03 UTC, JoshuaKGoldberg requested changes
Getting closer!

2021-09-16 18:03 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
> +   * An array of section items containing the title, slug, href, and onClick, each of which become an additional link on top of the accordion section.
Nit: you can skip describing what TypeScript already indicates. Not a blocker 😄 

```suggestion
   * An array of section items, each of which become an additional link on top of the accordion section.
```

2021-09-16 18:03 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/LayoutMenu/TopLinkSection.tsx
> +);
Could you unit test this please?

2021-09-16 18:03 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/LayoutMenu/TopLinkSection.tsx
> +export const TopLinkSection: React.FC<TopLinkSectionProps> = ({
Hmm, this is almost exactly copy & pasted from `AccordionMenu`. Can you extract out the shared stuff from inside there for a shared component?

2021-09-16 19:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.81-alpha.df85e8.0<br/>@codecademy/gamut-labs@20.0.2-alpha.df85e8.0<br/>@codecademy/styleguide@44.6.3-alpha.df85e8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-16 19:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61439a37b3ceec0a5d8d1d80--gamut-preview.netlify.app>https://61439a37b3ceec0a5d8d1d80--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61439a37b3ceec0a5d8d1d80>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-16 19:26 UTC, JoshuaKGoldberg approved these changes
Cool!

2021-09-16 19:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.83-alpha.539e42.0<br/>@codecademy/gamut-labs@20.0.4-alpha.539e42.0<br/>@codecademy/styleguide@44.6.6-alpha.539e42.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-16 19:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61439e9c4118f808bff8e986--gamut-preview.netlify.app>https://61439e9c4118f808bff8e986--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61439e9c4118f808bff8e986>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-16 21:33 UTC, aresnik11 requested changes
Nice! Left a few small change requests regarding the padding but otherwise this is looking great. Also sets us up nicely in the future to refactor the below links as children into a separate prop using the new `LayoutMenuSection` component

2021-09-16 21:33 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
>  // this is needed to add a few pixels of extra space for the left side of the focus-visible outline
i think this is an old extraneous comment, mind removing it while you're already in here?

2021-09-16 21:33 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/LayoutMenuSection.tsx
> +      <Box key={item.slug} py={8} px={4} pb={16}>
we don't want to always add `pb={16}` here, this is adding extra space between every item. if you're looking to have 16px of space between each item that should already be covered here since each item has top and bottom padding of 8

2021-09-16 21:33 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/TopLinkSection.tsx
> +`;
this isn't working, i don't believe you can style a gamut component unless it takes a className prop, which this does not

2021-09-16 21:33 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/LayoutMenuSection.tsx
> +  <Box>
i think instead of `styled(LayoutMenuSection)` below you probably want to add that padding here perhaps as a prop. or looks like we are adding 32px of padding bottom to the accordion area above (https://github.com/Codecademy/client-modules/pull/2063/files#diff-6b8208b20b9f5a74ed2fa1f4d750764b993b64751f4511371152d9c8aef6649fR11) that could probably be moved here instead

2021-09-16 22:07 UTC, amabarr commented on packages/gamut-labs/src/LayoutMenu/LayoutMenuSection.tsx
> +  <Box>
I ended up adding styleprops to the `LayoutMenuSection` I left the pb on the accordion areas since removing them caused weirdness when the accordions were closed!

2021-09-17 13:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.83-alpha.4203a6.0<br/>@codecademy/gamut-labs@20.0.4-alpha.4203a6.0<br/>@codecademy/styleguide@44.6.6-alpha.4203a6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-17 13:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614493bc0f59fa70bd699a76--gamut-preview.netlify.app>https://614493bc0f59fa70bd699a76--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614493bc0f59fa70bd699a76>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-17 14:54 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/LayoutMenuSection.tsx
> +  <Box>
ahh yeah good call, thanks for catching that!

2021-09-17 15:30 UTC, aresnik11 approved these changes
Awesome!

2021-09-17 15:30 UTC, aresnik11 commented on packages/styleguide/stories/Organisms/LayoutMenu.stories.mdx
> +Additional links outside of an accordion can be added to the bottom as `children`. Another way to add additional links outside of the accordion section is to pass an array of items that each contain
nit: 
```suggestion
Another way to add additional links outside of the accordion section is to pass an array of items that each contain a `title`, `slug`, and `onClick` to `topLinkSections`. Each of these items will become a link on top of the accordion section.
```
and can you also update the above section title to be `With Additional Links on Bottom` and the first sentence to specifically say `added to the bottom` so its super clear that is for links on the bottom now that you have options

2021-09-17 16:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.83-alpha.a31bd4.0<br/>@codecademy/gamut-labs@20.0.4-alpha.a31bd4.0<br/>@codecademy/styleguide@44.6.6-alpha.a31bd4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-17 16:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6144bce38f7fc66ecf93fca3--gamut-preview.netlify.app>https://6144bce38f7fc66ecf93fca3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6144bce38f7fc66ecf93fca3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-17 16:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.84-alpha.bda3f0.0<br/>@codecademy/gamut-labs@20.1.1-alpha.bda3f0.0<br/>@codecademy/styleguide@44.6.7-alpha.bda3f0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-17 16:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6144c485f132674cbe4ac25d--gamut-preview.netlify.app>https://6144c485f132674cbe4ac25d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6144c485f132674cbe4ac25d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-20 20:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.86-alpha.6a0898.0<br/>@codecademy/gamut-labs@20.1.3-alpha.6a0898.0<br/>@codecademy/styleguide@44.7.2-alpha.6a0898.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-20 20:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6148efa3362bc62f369ef523--gamut-preview.netlify.app>https://6148efa3362bc62f369ef523--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6148efa3362bc62f369ef523>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-20 20:33 UTC, merged