feat(PageHero): add optional eyebrow text
Codecademy/client-modules pull request #2072
Opened 2021-09-20 21:55 UTC by aresnik11

### Overview

Adds optional eyebrow text to the `PageHero` component used in the landing page builder

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/J5yB1jyELiNt3Vb47T9GcE/Job-Readiness?node-id=57%3A600
- [x] Related to JIRA ticket: [REACH-1324]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

2021-09-20 21:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.87-alpha.dfdecf.0<br/>@codecademy/gamut-labs@20.2.1-alpha.dfdecf.0<br/>@codecademy/styleguide@44.8.1-alpha.dfdecf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-20 22:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.87-alpha.4d9a19.0<br/>@codecademy/gamut-labs@20.2.1-alpha.4d9a19.0<br/>@codecademy/styleguide@44.8.1-alpha.4d9a19.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-20 22:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6149062e227ea742da66b1e7--gamut-preview.netlify.app>https://6149062e227ea742da66b1e7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6149062e227ea742da66b1e7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-21 15:07 UTC, JoshuaKGoldberg requested changes
Otherwise looks great, just checking in on accessibility!

2021-09-21 15:07 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/LandingPage/PageHero.tsx
> +          <Text fontSize={{ _: 20, sm: 22 }} fontFamily="accent" mb={16}>
cc @Codecademy/accessibility - I think this will need to be _inside_ the `Title`. Especially if this is used as an `h1` then there shouldn't be main body text before the heading.

2021-09-21 15:43 UTC, christian-dinh commented on packages/gamut-labs/src/LandingPage/PageHero.tsx
> +          <Text fontSize={{ _: 20, sm: 22 }} fontFamily="accent" mb={16}>
> there shouldn't be main body text before the heading


this makes intuitive sense to me but I haven't been able to find any WCAG resources that call this out as a problem (I've been looking around [here](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=246%2C2410&currentsidebar=%23col_overview#section-headings))

2021-09-21 16:03 UTC, christian-dinh commented on packages/gamut-labs/src/LandingPage/PageHero.tsx
> +          <Text fontSize={{ _: 20, sm: 22 }} fontFamily="accent" mb={16}>
good news is that based on [this slack thread](https://codecademy.slack.com/archives/CGQPTPR27/p1632238252038600) it looks like the eyebrow should be the `h1` anyway!

2021-09-21 18:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.87-alpha.50e3f8.0<br/>@codecademy/gamut-labs@20.2.1-alpha.50e3f8.0<br/>@codecademy/styleguide@44.8.1-alpha.50e3f8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-21 18:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614a1eaa896ab508ac601f5b--gamut-preview.netlify.app>https://614a1eaa896ab508ac601f5b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614a1eaa896ab508ac601f5b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-21 18:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.87-alpha.4e505f.0<br/>@codecademy/gamut-labs@20.2.1-alpha.4e505f.0<br/>@codecademy/styleguide@44.8.1-alpha.4e505f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-21 18:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614a23ae470cbd00c9a8522d--gamut-preview.netlify.app>https://614a23ae470cbd00c9a8522d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614a23ae470cbd00c9a8522d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-22 14:07 UTC, dreamwasp approved these changes
this looks great! especially love the doc improvements 🙏

2021-09-22 15:08 UTC, JoshuaKGoldberg approved these changes
🔥

2021-09-22 15:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.91-alpha.4b4a82.0<br/>@codecademy/gamut-labs@23.0.2-alpha.4b4a82.0<br/>@codecademy/styleguide@46.0.2-alpha.4b4a82.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-22 15:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614b4c407db18808e99106a9--gamut-preview.netlify.app>https://614b4c407db18808e99106a9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614b4c407db18808e99106a9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-24 18:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.91-alpha.1ae64a.0<br/>@codecademy/gamut-labs@23.0.2-alpha.1ae64a.0<br/>@codecademy/styleguide@46.1.1-alpha.1ae64a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-24 18:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614e13656d258a1a3b8b39c9--gamut-preview.netlify.app>https://614e13656d258a1a3b8b39c9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614e13656d258a1a3b8b39c9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-24 18:09 UTC, merged