feat(CurriculumCard): updated footer text variant
Codecademy/client-modules pull request #2076
Opened 2021-09-21 19:55 UTC by amabarr

### Overview

Teams+ users want to see the copy "In Progress..." instead of "Enrolled..." for their own organization's content. 

So, I made an optional variable called `footerTextVariant` that either takes in `inProgress` or `enrolled`, and displays the corresponding text.  

### PR Checklist

- [x] Related to designs: [figma](https://www.figma.com/file/YR6abM4OmOq0Q8YrifzOpn/Self-Service-Course-%26-Path-Release?node-id=492%3A5861)
- [x] Related to JIRA ticket: [CONPLAT-1121](https://codecademy.atlassian.net/secure/RapidBoard.jspa?rapidView=156&modal=detail&selectedIssue=CONPLAT-1121)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-09-22 15:12 UTC, JoshuaKGoldberg requested changes
LGTM! Unit test please? 🕺

2021-09-22 16:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.90-alpha.a79975.0<br/>@codecademy/gamut-labs@23.0.1-alpha.a79975.0<br/>@codecademy/styleguide@46.0.1-alpha.a79975.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-22 16:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614b5884fb9b01013c74d1a7--gamut-preview.netlify.app>https://614b5884fb9b01013c74d1a7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614b5884fb9b01013c74d1a7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-22 18:07 UTC, JoshuaKGoldberg approved these changes
🌮

2021-09-22 18:07 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/CurriculumCard/Footer/__tests__/Footer-test.tsx
> +    expect(view.queryByText('Enrolled...')).toBeTruthy();
⛳ ✨ 

```suggestion
    view.getByText('Enrolled...'));
```

2021-09-24 16:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.91-alpha.75f8e9.0<br/>@codecademy/gamut-labs@23.0.2-alpha.75f8e9.0<br/>@codecademy/styleguide@46.1.1-alpha.75f8e9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-24 16:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://614e02e2b91f890a0467665e--gamut-preview.netlify.app>https://614e02e2b91f890a0467665e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/614e02e2b91f890a0467665e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-27 17:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.93-alpha.fe602f.0<br/>@codecademy/gamut-labs@23.2.1-alpha.fe602f.0<br/>@codecademy/styleguide@46.3.1-alpha.fe602f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-27 17:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6152059f8b8ed49efcae37a5--gamut-preview.netlify.app>https://6152059f8b8ed49efcae37a5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6152059f8b8ed49efcae37a5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-27 20:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.5.93-alpha.94035c.0<br/>@codecademy/gamut-labs@23.2.1-alpha.94035c.0<br/>@codecademy/styleguide@46.3.2-alpha.94035c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-09-27 20:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61522b1e79d2cf2f6ead89f6--gamut-preview.netlify.app>https://61522b1e79d2cf2f6ead89f6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61522b1e79d2cf2f6ead89f6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-09-28 17:50 UTC, merged