feat(TSyled): It begins
Codecademy/client-modules pull request #953
Opened 2020-09-09 15:00 UTC by codecaaron

## Overview
The beginnings

### PR Checklist

- [ ] Related to Abstract designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description

2020-09-09 16:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@2.0.6-alpha.ac2513.0<br/>@codecademy/gamut-styles@5.1.3-alpha.ac2513.0<br/>@codecademy/gamut@14.0.6-alpha.ac2513.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-09 16:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.0.3-alpha.195b0e.0<br/>@codecademy/gamut-styles@7.0.1-alpha.195b0e.0<br/>@codecademy/gamut@16.0.5-alpha.195b0e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-09 16:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5905f39fbfdd6b8ffe04cf--gamut-preview.netlify.app>https://5f5905f39fbfdd6b8ffe04cf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5905f39fbfdd6b8ffe04cf>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-09 16:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.0.3-alpha.0b2db7.0<br/>@codecademy/gamut-styles@7.0.1-alpha.0b2db7.0<br/>@codecademy/gamut@16.0.5-alpha.0b2db7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-09 16:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f590742dbc86d57398a5a3e--gamut-preview.netlify.app>https://5f590742dbc86d57398a5a3e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f590742dbc86d57398a5a3e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-09 20:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.abef3e.0<br/>@codecademy/gamut-labs@4.0.3-alpha.abef3e.0<br/>@codecademy/gamut-styles@7.0.1-alpha.abef3e.0<br/>@codecademy/gamut@16.0.5-alpha.abef3e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-09 21:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.e796f0.0<br/>@codecademy/gamut-labs@4.0.3-alpha.e796f0.0<br/>@codecademy/gamut-styles@7.0.1-alpha.e796f0.0<br/>@codecademy/gamut@16.0.5-alpha.e796f0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 14:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.5b77fc.0<br/>@codecademy/gamut-labs@4.0.3-alpha.5b77fc.0<br/>@codecademy/gamut-styles@7.0.1-alpha.5b77fc.0<br/>@codecademy/gamut@16.0.5-alpha.5b77fc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 15:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.2a5257.0<br/>@codecademy/gamut-labs@4.0.3-alpha.2a5257.0<br/>@codecademy/gamut-styles@7.0.1-alpha.2a5257.0<br/>@codecademy/gamut@16.0.5-alpha.2a5257.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 16:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.1640d6.0<br/>@codecademy/gamut-labs@4.0.3-alpha.1640d6.0<br/>@codecademy/gamut-styles@7.0.1-alpha.1640d6.0<br/>@codecademy/gamut@16.0.5-alpha.1640d6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 16:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.57448a.0<br/>@codecademy/gamut-labs@4.0.3-alpha.57448a.0<br/>@codecademy/gamut-styles@7.0.1-alpha.57448a.0<br/>@codecademy/gamut@16.0.5-alpha.57448a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 17:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.d7389b.0<br/>@codecademy/gamut-labs@4.0.3-alpha.d7389b.0<br/>@codecademy/gamut-styles@7.0.1-alpha.d7389b.0<br/>@codecademy/gamut@16.0.5-alpha.d7389b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 18:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.ff28fe.0<br/>@codecademy/gamut-labs@4.0.3-alpha.ff28fe.0<br/>@codecademy/gamut-styles@7.0.1-alpha.ff28fe.0<br/>@codecademy/gamut@16.0.5-alpha.ff28fe.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 18:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5a74abab978b0962457620--gamut-preview.netlify.app>https://5f5a74abab978b0962457620--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5a74abab978b0962457620>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-10 19:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.765234.0<br/>@codecademy/gamut-labs@4.0.3-alpha.765234.0<br/>@codecademy/gamut-styles@7.0.1-alpha.765234.0<br/>@codecademy/gamut@16.0.5-alpha.765234.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 19:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5a85a42cf866008bc2449f--gamut-preview.netlify.app>https://5f5a85a42cf866008bc2449f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5a85a42cf866008bc2449f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-10 22:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.bf6052.0<br/>@codecademy/gamut-labs@4.0.3-alpha.bf6052.0<br/>@codecademy/gamut-styles@7.0.1-alpha.bf6052.0<br/>@codecademy/gamut@16.0.5-alpha.bf6052.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-11 04:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.6707f3.0<br/>@codecademy/gamut-labs@4.0.3-alpha.6707f3.0<br/>@codecademy/gamut-styles@7.0.1-alpha.6707f3.0<br/>@codecademy/gamut@16.0.5-alpha.6707f3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-11 05:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.6997c0.0<br/>@codecademy/gamut-labs@4.0.3-alpha.6997c0.0<br/>@codecademy/gamut-styles@7.0.1-alpha.6997c0.0<br/>@codecademy/gamut@16.0.5-alpha.6997c0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-11 05:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.04509e.0<br/>@codecademy/gamut-labs@4.0.3-alpha.04509e.0<br/>@codecademy/gamut-styles@7.0.1-alpha.04509e.0<br/>@codecademy/gamut@16.0.5-alpha.04509e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-11 14:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5b8dbf556a1556b0c0510e--gamut-preview.netlify.app>https://5f5b8dbf556a1556b0c0510e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5b8dbf556a1556b0c0510e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-11 15:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.5c996a.0<br/>@codecademy/gamut-labs@4.0.3-alpha.5c996a.0<br/>@codecademy/gamut-styles@7.0.1-alpha.5c996a.0<br/>@codecademy/gamut@16.0.5-alpha.5c996a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-11 15:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5b97529ab1a75cff66984f--gamut-preview.netlify.app>https://5f5b97529ab1a75cff66984f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5b97529ab1a75cff66984f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-14 02:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.dcee1e.0<br/>@codecademy/gamut-labs@4.0.3-alpha.dcee1e.0<br/>@codecademy/gamut-styles@7.0.1-alpha.dcee1e.0<br/>@codecademy/gamut@16.0.5-alpha.dcee1e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-14 03:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5edcfdda13e32824ccc1c7--gamut-preview.netlify.app>https://5f5edcfdda13e32824ccc1c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5edcfdda13e32824ccc1c7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-14 05:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.613834.0<br/>@codecademy/gamut-labs@4.0.3-alpha.613834.0<br/>@codecademy/gamut-styles@7.0.1-alpha.613834.0<br/>@codecademy/gamut@16.0.5-alpha.613834.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-14 16:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.88b248.0<br/>@codecademy/gamut-labs@4.0.3-alpha.88b248.0<br/>@codecademy/gamut-styles@7.0.1-alpha.88b248.0<br/>@codecademy/gamut@16.0.5-alpha.88b248.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-14 17:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5faf5e13fd862975282c22--gamut-preview.netlify.app>https://5f5faf5e13fd862975282c22--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5faf5e13fd862975282c22>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-16 12:48 UTC, kipprice commented on packages/gamut-labs/package.json
> +    "polished": ">=3.0.0"
why does polished need to be a peer dependency?

2020-09-16 12:50 UTC, kipprice commented on packages/gamut-styles/src/variables/typography.ts
> +  '1.5': 1.5,
is anything using the old keys for lineHeight?

2020-09-16 12:51 UTC, kipprice commented on packages/gamut-styles/src/variables/typography.ts
> +  light: 300,
same question as above; is anything using the old keys here?

2020-09-16 12:51 UTC, kipprice commented on packages/gamut-styles/src/variables/typography.ts
> +  light: 300,
also, do our new fonts include all three weight variants?

2020-09-16 12:52 UTC, kipprice commented on packages/gamut-styles/src/variables/typography.ts
> +  1: pxRem(0.85 * base),
this is really nice 🤩

2020-09-16 12:53 UTC, kipprice commented on packages/gamut-styles/src/variables/typography.ts
> +} as const;
I know you call this out in the description, but why do we need the `as const` part of this? I've found that starting with `const` has been enough for `keyof typeof` to work.

2020-09-16 12:54 UTC, kipprice commented on packages/gamut-styles/src/variables/typography.ts
>  export const fontColor = {
this is an area where I'd expect a light / dark mode distinction

2020-09-16 12:56 UTC, kipprice commented on packages/gamut-styles/src/variables/display.ts
> +export const displayValues = [
is there any CSS / react type lib we can use to get these values?

2020-09-16 12:58 UTC, kipprice commented on packages/gamut-styles/src/variables/display.ts
> +export type DisplayTypes = typeof displayValues[number];
when do we use the array version of `displayValues` over the `DisplayTypes` type? If we're only ever really using the latter, this could be a union type instead of an array (`export type DisplayTypes = 'block' | 'inline-block' ...`)

2020-09-16 12:59 UTC, kipprice commented on packages/gamut-styles/src/variables/border.ts
> +  base: colors.navy,
another one that I'd expect to need a light v. dark mode potentially

2020-09-16 13:00 UTC, kipprice commented on packages/gamut-styles/src/system/transforms/percentageOrAbsolute/index.ts
> +  if (coordinate <= 1 && coordinate >= -1) {
why `<=` here instead of `<`? will we never end up in a spot where we'll be adjusting by 1 absolute px?

2020-09-16 13:05 UTC, kipprice commented on packages/gamut-styles/src/system/constants.ts
> +export const propMap = {
I would slightly prefer this being an array of the accepted values and a function to transform the js-friendly name to the CSS-friendly name. The advantage there is in avoiding typos in the CSS property names, and we can use `CSSStyleDeclaration[]` to type the array to recognized JS-friendly CSS props.

2020-09-16 13:06 UTC, kipprice commented on packages/gamut-styles/src/system/constants.ts
> +  textShadow: 'text-shadow',
where do we use `textShadow`? 🤔

2020-09-16 13:13 UTC, kipprice commented on packages/gamut-styles/src/system/propTemplates/responsiveProperty/__tests__/responsiveProperty-test.ts
> +  xit('creates a property function', () => {
typo? or is there a jest func for `xit`?

2020-09-16 13:23 UTC, kipprice commented on packages/gamut-styles/src/system/types.ts
> +  | [T | undefined, T | undefined, T | undefined, T | undefined, T | undefined];
I think this could be simplified to the following:
```suggestion
export type MediaQueryArray<T> = [T?, T?, T?, T?, T?];
```

2020-09-16 13:25 UTC, kipprice commented on packages/gamut-styles/src/system/types.ts
> +export type MediaQueryMap<T> = {
I think we should probably type `T` to be something tied to the styles shape we will accept

2020-09-16 13:29 UTC, kipprice commented on packages/gamut-styles/src/system/props/typography.ts
> +export const typography = {
this is really elegant :D

2020-09-16 13:32 UTC, kipprice commented on packages/gamut-styles/src/system/props/spacing.ts
> +    computeValue: (value: unknown) => spaceScale[value as SpaceSizes],
could this be more strongly typed as `value: SpaceSizes`?

2020-09-16 13:36 UTC, kipprice commented on packages/gamut-styles/src/system/props/grid.ts
> +      | 'baseline'
this is probably worth pulling out into a type so you can reuse it with `align`

2020-09-16 13:37 UTC, kipprice commented on packages/gamut-styles/src/system/props/flex.ts
> +      | 'baseline'
as mentioned below with `grid`, we should pull this out into its own type to share between `scale` and `align`  + overlap with `grid`

2020-09-16 14:02 UTC, kipprice commented on packages/gamut-styles/src/system/propTemplates/standardProperty/index.ts
> +import { propMap, PropAlias } from '../../constants';
if you don't end up going the fun rename JS -> CSS route, `propMap` could do with a more semantic name (e.g.`jsToCssPropMap`)

2020-09-16 14:03 UTC, kipprice commented on packages/gamut-styles/src/system/propTemplates/standardProperty/index.ts
> +      return `${propMap[propKey]}: ${computeValue!(props[propKey])};`;
do you need to assert that computeValue is non-null?

2020-09-16 14:04 UTC, kipprice commented on packages/gamut-styles/src/system/propTemplates/responsiveProperty/__tests__/responsiveProperty-test.ts
> +import { ResponiveProp } from '../../../types';
typo: should be `ResponsiveProp`

2020-09-16 14:05 UTC, kipprice commented on packages/gamut-styles/src/system/types.ts
> +export type ResponiveProp<T> = MediaQueryArray<T> | MediaQueryMap<T>;
typo: should be `ResponsiveProp`

2020-09-16 14:06 UTC, kipprice commented on packages/gamut-styles/src/system/props/background.ts
> +} as const;
no `backgroundColor` in this?

2020-09-16 14:08 UTC, kipprice commented on packages/gamut-labs/src/experimental/Box/index.tsx
> +export type BoxProps = SpaceProps & LayoutProps & BorderProps;
this needs a BG color option too right?

2020-09-16 17:48 UTC, codecaaron commented on packages/gamut-styles/src/system/types.ts
> +  | [T | undefined, T | undefined, T | undefined, T | undefined, T | undefined];
Amazing, thank you :)

2020-09-16 17:50 UTC, codecaaron commented on packages/gamut-styles/src/system/constants.ts
> +export const propMap = {
Completely agree, as per our earlier discussion, I think switching this to CSSProperty will be higher value and DRYer for sure.

2020-09-16 17:52 UTC, codecaaron commented on packages/gamut-styles/src/system/propTemplates/responsiveProperty/__tests__/responsiveProperty-test.ts
> +  xit('creates a property function', () => {
This just disables the block, xdescribe and xit I think skip the blocks.

The test is currently broken but wanted to save the progress.

2020-09-17 02:07 UTC, JoshuaKGoldberg reviewed
I waited until I was dead tired after work to post on what I don't understand, in an effort to simulate what a relative newcomer to the architecture here would think (yes, this is a legit strategy, it works well!). So please consider my basic questions to be more requests for documentation/comments than anything else. 😉

(Don't review code or do work stuff out of work hours at home, people! Work life balance is important!)

Another thought: I'd really like to be able to get rid of the `as` needs in config definitions: both `[] as` and `as const`. I suspect we could get away with them by using a well crafted user API. Let's set some time up to mob/pair on it soon? 😁

2020-09-17 15:45 UTC, codecaaron commented on packages/gamut-styles/src/system/propTemplates/directionalProperty/index.ts
> +  K extends AbstractSystemConfig
Of course, I guess I wasn't sure about what these naming conventions are supposed to be for generics.  I guess we should put this in our styleguide?

2020-09-17 15:46 UTC, codecaaron commented on packages/gamut-styles/src/system/props/spacing.ts
> +    computeValue: (value: unknown) => spaceScale[value as SpaceSizes],
Unfortunately, not currently.  Though I think I could potentially get the type forwarding to work, I think value needs to always be unknown here :(

2020-09-17 15:48 UTC, codecaaron commented on packages/gamut-styles/src/system/transforms/percentageOrAbsolute/index.ts
> +  if (coordinate <= 1 && coordinate >= -1) {
So this is really only reachable if you've called `parseSize` with a number.  If you've specified `1px` it will always be 1px.  However if you've done `1` it will be 100%.  It's a bit of a weird behavior but I wanted to make .01 - 1 consistently %'s.  Though I could see cases where that is not very intuitive and that we would need to go larger than that.

2020-09-17 15:49 UTC, codecaaron commented on packages/gamut-styles/src/variables/display.ts
> +export const displayValues = [
Yea, these will be replaced by `csstype` ideally.

2020-09-17 15:49 UTC, codecaaron commented on packages/gamut-styles/src/variables/display.ts
> +export type DisplayTypes = typeof displayValues[number];
I'm going to remove a lot of these in favor of `csstype`

2020-09-17 15:51 UTC, codecaaron commented on packages/gamut-styles/src/variables/typography.ts
> +  light: 300,
This file is pretty much unused, currently so these are safe updates.

It's unclear, I need to get locked down type standards from design to truly specify.

2020-09-17 15:53 UTC, codecaaron commented on packages/gamut-styles/src/system/props/grid.ts
> +      | 'baseline'
Agree + `csstype`'s  responsibility.

2020-09-17 15:55 UTC, codecaaron commented on packages/gamut-styles/src/system/props/background.ts
> +} as const;
`backgroundColor` and `color` are still up in the air, I'm not really sure how to handle them yet RE: theming.

2020-09-17 18:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.47e9c6.0<br/>@codecademy/gamut-labs@4.0.3-alpha.47e9c6.0<br/>@codecademy/gamut-styles@7.0.1-alpha.47e9c6.0<br/>@codecademy/gamut@16.0.5-alpha.47e9c6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-17 18:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.c5c524.0<br/>@codecademy/gamut-labs@4.0.3-alpha.c5c524.0<br/>@codecademy/gamut-styles@7.0.1-alpha.c5c524.0<br/>@codecademy/gamut@16.0.5-alpha.c5c524.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-17 19:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.4.2-alpha.a8287d.0<br/>@codecademy/gamut-labs@4.0.3-alpha.a8287d.0<br/>@codecademy/gamut-styles@7.0.1-alpha.a8287d.0<br/>@codecademy/gamut@16.0.5-alpha.a8287d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-18 15:16 UTC, codecaaron commented on packages/gamut-styles/src/system/propTemplates/standardProperty/index.ts
> +      return `${propMap[propKey]}: ${computeValue!(props[propKey])};`;
Bleh, sure don't :)

Basically there are 2 steps to a config: 
1. Base configuration, no defaults.
2. Defaults initialized and used within the functions.

Used the same type for both of these which caused the assertion.  I'll add a second type to represent a fully initialized configuration.

2020-09-18 15:16 UTC, codecaaron commented on packages/gamut-styles/src/system/props/shadow.ts
> +    scale: [] as string[],
Yeah that's what I am thinking here :)

Many of these values are just placeholders :D

2020-09-18 22:21 UTC, JoshuaKGoldberg commented on packages/gamut-styles/src/system/props/layout.ts
> +  },
Capturing Zoom convo into here, this is roughly/vaguely what I was thinking about for creating these...

```suggestion
  display: createScaleProp<DisplayTypes>('display'),
```

More complex ones might use a {} object like:

```ts
createScaleProp<number | string>({
  propName: ['width', 'minWidth', /* ... */],
  computeValue: parseSize
});
```

...where `computeValue` is known to take in a `value: (number | string)` somehow _(is that a doable thing to type in?)_.

What do you think? :smile:

2020-09-21 14:19 UTC, codecaaron commented on packages/gamut-styles/src/system/props/layout.ts
> +  },
Yeah, I've been trying to get something like this to work, but I've been struggling.

I think my grasp on the rules of how TS resolves `unknown` to more defined types is a bit vague, I've got it to work in some cases but others have been more tricky.

2020-09-23 19:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.0ca334.0<br/>@codecademy/gamut-icons@3.4.2-alpha.0ca334.0<br/>@codecademy/gamut-labs@4.1.0-alpha.0ca334.0<br/>@codecademy/gamut-styles@7.1.0-alpha.0ca334.0<br/>@codecademy/gamut@16.1.0-alpha.0ca334.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-23 19:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6ba2549e294b1f0e764703--gamut-preview.netlify.app>https://5f6ba2549e294b1f0e764703--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6ba2549e294b1f0e764703>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-24 12:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.8fc034.0<br/>@codecademy/gamut-icons@3.4.2-alpha.8fc034.0<br/>@codecademy/gamut-labs@4.1.0-alpha.8fc034.0<br/>@codecademy/gamut-styles@7.1.0-alpha.8fc034.0<br/>@codecademy/gamut@16.1.0-alpha.8fc034.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-24 12:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6c97052a85a43ec90ed5c5--gamut-preview.netlify.app>https://5f6c97052a85a43ec90ed5c5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6c97052a85a43ec90ed5c5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-24 14:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.928f49.0<br/>@codecademy/gamut-labs@4.2.0-alpha.928f49.0<br/>@codecademy/gamut-styles@7.1.0-alpha.928f49.0<br/>@codecademy/gamut@16.1.0-alpha.928f49.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-24 14:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6cb3f1710508010cce3747--gamut-preview.netlify.app>https://5f6cb3f1710508010cce3747--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6cb3f1710508010cce3747>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-24 15:02 UTC, JoshuaKGoldberg commented on packages/eslint-config/index.js
> +    // <3.x.x
Nit: I wouldn't bother including these comments, we'd end up with a whole bunch of them if we kept up the system.

2020-09-24 15:02 UTC, JoshuaKGoldberg commented on packages/eslint-config/index.js
> +    // >3.x.x
Would you mind taking these additions into a separate PR? I'd like to play with them to try to figure out the things blocking Hasan from turning on the import sorting with `~` aliases.

2020-09-24 15:04 UTC, codecaaron commented on packages/eslint-config/index.js
> +    // >3.x.x
Yep :)

2020-09-24 21:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.06f407.0<br/>@codecademy/gamut-labs@4.2.0-alpha.06f407.0<br/>@codecademy/gamut-styles@7.1.0-alpha.06f407.0<br/>@codecademy/gamut-system@0.0.1-alpha.06f407.0<br/>@codecademy/gamut@16.1.0-alpha.06f407.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-24 21:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6d0ff072f0ba5a6675a584--gamut-preview.netlify.app>https://5f6d0ff072f0ba5a6675a584--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6d0ff072f0ba5a6675a584>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-24 21:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.85ab70.0<br/>@codecademy/gamut-labs@4.2.0-alpha.85ab70.0<br/>@codecademy/gamut-styles@7.1.0-alpha.85ab70.0<br/>@codecademy/gamut-system@0.0.1-alpha.85ab70.0<br/>@codecademy/gamut@16.1.0-alpha.85ab70.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-24 21:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6d16a97b1916665819d55d--gamut-preview.netlify.app>https://5f6d16a97b1916665819d55d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6d16a97b1916665819d55d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-24 23:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.873064.0<br/>@codecademy/gamut-labs@4.2.0-alpha.873064.0<br/>@codecademy/gamut-styles@7.1.0-alpha.873064.0<br/>@codecademy/gamut-system@0.0.1-alpha.873064.0<br/>@codecademy/gamut@16.1.0-alpha.873064.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-24 23:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6d31c37b191690d019d235--gamut-preview.netlify.app>https://5f6d31c37b191690d019d235--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6d31c37b191690d019d235>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-25 00:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.93471b.0<br/>@codecademy/gamut-labs@4.2.0-alpha.93471b.0<br/>@codecademy/gamut-styles@7.1.0-alpha.93471b.0<br/>@codecademy/gamut-system@0.0.1-alpha.93471b.0<br/>@codecademy/gamut@16.1.0-alpha.93471b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-25 00:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6d3cdad0677ac9155d49ea--gamut-preview.netlify.app>https://5f6d3cdad0677ac9155d49ea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6d3cdad0677ac9155d49ea>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-25 01:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.3aae9e.0<br/>@codecademy/gamut-labs@4.2.0-alpha.3aae9e.0<br/>@codecademy/gamut-styles@7.1.0-alpha.3aae9e.0<br/>@codecademy/gamut-system@0.0.1-alpha.3aae9e.0<br/>@codecademy/gamut@16.1.0-alpha.3aae9e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-25 01:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6d4495d0677ad6cd5d4ab9--gamut-preview.netlify.app>https://5f6d4495d0677ad6cd5d4ab9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6d4495d0677ad6cd5d4ab9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-25 01:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/eslint-config@3.1.0-alpha.f1b0bf.0<br/>@codecademy/gamut-labs@4.2.0-alpha.f1b0bf.0<br/>@codecademy/gamut-styles@7.1.0-alpha.f1b0bf.0<br/>@codecademy/gamut-system@0.0.1-alpha.f1b0bf.0<br/>@codecademy/gamut@16.1.0-alpha.f1b0bf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-25 01:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6d48d9d0677ad5b65d549a--gamut-preview.netlify.app>https://5f6d48d9d0677ad5b65d549a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6d48d9d0677ad5b65d549a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-25 17:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6e24ecaef79a00ddbeb03f--gamut-preview.netlify.app>https://5f6e24ecaef79a00ddbeb03f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6e24ecaef79a00ddbeb03f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-25 17:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.2d5f20.0<br/>@codecademy/gamut-styles@7.1.0-alpha.2d5f20.0<br/>@codecademy/gamut-system@0.0.1-alpha.2d5f20.0<br/>@codecademy/gamut@16.0.12-alpha.2d5f20.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-25 20:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.915cf7.0<br/>@codecademy/gamut-styles@7.1.0-alpha.915cf7.0<br/>@codecademy/gamut-system@0.0.1-alpha.915cf7.0<br/>@codecademy/gamut@16.0.12-alpha.915cf7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-25 20:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6e54439fcc723f9a7341b5--gamut-preview.netlify.app>https://5f6e54439fcc723f9a7341b5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6e54439fcc723f9a7341b5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-28 03:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7153f55973e200f0815a32--gamut-preview.netlify.app>https://5f7153f55973e200f0815a32--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7153f55973e200f0815a32>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-28 03:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.fc9147.0<br/>@codecademy/gamut-styles@7.1.0-alpha.fc9147.0<br/>@codecademy/gamut-system@0.0.1-alpha.fc9147.0<br/>@codecademy/gamut@16.0.12-alpha.fc9147.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-28 18:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.9c6a52.0<br/>@codecademy/gamut-styles@7.1.0-alpha.9c6a52.0<br/>@codecademy/gamut-system@0.0.1-alpha.9c6a52.0<br/>@codecademy/gamut@16.0.12-alpha.9c6a52.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-28 18:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f722a7316199176968eb281--gamut-preview.netlify.app>https://5f722a7316199176968eb281--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f722a7316199176968eb281>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-29 20:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.e6ccf3.0<br/>@codecademy/gamut-styles@7.1.0-alpha.e6ccf3.0<br/>@codecademy/gamut-system@0.0.1-alpha.e6ccf3.0<br/>@codecademy/gamut@16.0.12-alpha.e6ccf3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-29 20:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f739a2f3a107201186d91cd--gamut-preview.netlify.app>https://5f739a2f3a107201186d91cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f739a2f3a107201186d91cd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-29 20:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.c8388a.0<br/>@codecademy/gamut-styles@7.1.0-alpha.c8388a.0<br/>@codecademy/gamut-system@0.0.1-alpha.c8388a.0<br/>@codecademy/gamut@16.0.12-alpha.c8388a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-29 20:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f739bf9873f2c0089d7350d--gamut-preview.netlify.app>https://5f739bf9873f2c0089d7350d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f739bf9873f2c0089d7350d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-29 20:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.56f2a2.0<br/>@codecademy/gamut-styles@7.1.0-alpha.56f2a2.0<br/>@codecademy/gamut-system@0.0.1-alpha.56f2a2.0<br/>@codecademy/gamut@16.0.12-alpha.56f2a2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-29 20:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f739d044b97e9013b278c65--gamut-preview.netlify.app>https://5f739d044b97e9013b278c65--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f739d044b97e9013b278c65>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-30 21:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f74f3d2d3c9a40cf763d235--gamut-preview.netlify.app>https://5f74f3d2d3c9a40cf763d235--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f74f3d2d3c9a40cf763d235>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-30 21:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.1b12ac.0<br/>@codecademy/gamut-styles@7.1.0-alpha.1b12ac.0<br/>@codecademy/gamut-system@0.0.1-alpha.1b12ac.0<br/>@codecademy/gamut@16.0.12-alpha.1b12ac.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-30 21:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.4013d8.0<br/>@codecademy/gamut-styles@7.1.0-alpha.4013d8.0<br/>@codecademy/gamut-system@0.0.1-alpha.4013d8.0<br/>@codecademy/gamut@16.0.12-alpha.4013d8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-30 21:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f74faf0e0acdd0ff6bbad8c--gamut-preview.netlify.app>https://5f74faf0e0acdd0ff6bbad8c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f74faf0e0acdd0ff6bbad8c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-30 21:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.4924c1.0<br/>@codecademy/gamut-styles@7.1.0-alpha.4924c1.0<br/>@codecademy/gamut-system@0.0.1-alpha.4924c1.0<br/>@codecademy/gamut@16.0.12-alpha.4924c1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-30 21:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f74fc03ab8cdb10b8a9a447--gamut-preview.netlify.app>https://5f74fc03ab8cdb10b8a9a447--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f74fc03ab8cdb10b8a9a447>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-01 16:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.7a1d0f.0<br/>@codecademy/gamut-styles@7.1.0-alpha.7a1d0f.0<br/>@codecademy/gamut-system@0.0.1-alpha.7a1d0f.0<br/>@codecademy/gamut@16.0.12-alpha.7a1d0f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-01 16:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7604cb198613d2946db848--gamut-preview.netlify.app>https://5f7604cb198613d2946db848--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7604cb198613d2946db848>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-01 18:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.6c0caf.0<br/>@codecademy/gamut-styles@7.1.0-alpha.6c0caf.0<br/>@codecademy/gamut-system@0.0.1-alpha.6c0caf.0<br/>@codecademy/gamut@16.0.12-alpha.6c0caf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-01 18:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f761a3527760ceca4df0057--gamut-preview.netlify.app>https://5f761a3527760ceca4df0057--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f761a3527760ceca4df0057>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-01 18:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.bd957a.0<br/>@codecademy/gamut-styles@7.1.0-alpha.bd957a.0<br/>@codecademy/gamut-system@0.0.1-alpha.bd957a.0<br/>@codecademy/gamut@16.0.12-alpha.bd957a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-01 18:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f761aa4d3c9a4922163da6f--gamut-preview.netlify.app>https://5f761aa4d3c9a4922163da6f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f761aa4d3c9a4922163da6f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-01 22:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.1e0b1f.0<br/>@codecademy/gamut-styles@7.1.0-alpha.1e0b1f.0<br/>@codecademy/gamut-system@0.0.1-alpha.1e0b1f.0<br/>@codecademy/gamut@16.0.12-alpha.1e0b1f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-01 22:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7656e39ea61312b00df6b8--gamut-preview.netlify.app>https://5f7656e39ea61312b00df6b8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7656e39ea61312b00df6b8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-01 22:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.d08d7f.0<br/>@codecademy/gamut-styles@7.1.0-alpha.d08d7f.0<br/>@codecademy/gamut-system@0.0.1-alpha.d08d7f.0<br/>@codecademy/gamut@16.0.12-alpha.d08d7f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-01 22:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f765d2bc22cce0107d843d6--gamut-preview.netlify.app>https://5f765d2bc22cce0107d843d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f765d2bc22cce0107d843d6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 14:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.b05ed0.0<br/>@codecademy/gamut-styles@7.1.0-alpha.b05ed0.0<br/>@codecademy/gamut-system@0.0.1-alpha.b05ed0.0<br/>@codecademy/gamut@16.0.12-alpha.b05ed0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 14:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f773f01422a4d4803406d4a--gamut-preview.netlify.app>https://5f773f01422a4d4803406d4a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f773f01422a4d4803406d4a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 16:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.4531e3.0<br/>@codecademy/gamut-styles@7.1.0-alpha.4531e3.0<br/>@codecademy/gamut-system@0.0.1-alpha.4531e3.0<br/>@codecademy/gamut@16.0.12-alpha.4531e3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 16:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f774f12b480eb560c2abb8a--gamut-preview.netlify.app>https://5f774f12b480eb560c2abb8a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f774f12b480eb560c2abb8a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 16:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.95544c.0<br/>@codecademy/gamut-styles@7.1.0-alpha.95544c.0<br/>@codecademy/gamut-system@0.0.1-alpha.95544c.0<br/>@codecademy/gamut@16.0.12-alpha.95544c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 16:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7751ee9ffa4546b027f933--gamut-preview.netlify.app>https://5f7751ee9ffa4546b027f933--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7751ee9ffa4546b027f933>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 16:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.dae8f2.0<br/>@codecademy/gamut-styles@7.1.0-alpha.dae8f2.0<br/>@codecademy/gamut-system@0.0.1-alpha.dae8f2.0<br/>@codecademy/gamut@16.0.12-alpha.dae8f2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 16:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7752d2c656894cc49aee6b--gamut-preview.netlify.app>https://5f7752d2c656894cc49aee6b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7752d2c656894cc49aee6b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 16:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.490754.0<br/>@codecademy/gamut-styles@7.1.0-alpha.490754.0<br/>@codecademy/gamut-system@0.0.1-alpha.490754.0<br/>@codecademy/gamut@16.0.12-alpha.490754.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 16:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7753d4aa2e984987cdf9b1--gamut-preview.netlify.app>https://5f7753d4aa2e984987cdf9b1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7753d4aa2e984987cdf9b1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 17:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.161f8c.0<br/>@codecademy/gamut-styles@7.1.0-alpha.161f8c.0<br/>@codecademy/gamut-system@0.0.1-alpha.161f8c.0<br/>@codecademy/gamut@16.0.12-alpha.161f8c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 17:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f775f8eaa2e98532fcde97b--gamut-preview.netlify.app>https://5f775f8eaa2e98532fcde97b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f775f8eaa2e98532fcde97b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 17:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.c12095.0<br/>@codecademy/gamut-styles@7.1.0-alpha.c12095.0<br/>@codecademy/gamut-system@0.0.1-alpha.c12095.0<br/>@codecademy/gamut@16.0.12-alpha.c12095.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 17:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7760c8115f525bab8eb681--gamut-preview.netlify.app>https://5f7760c8115f525bab8eb681--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7760c8115f525bab8eb681>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 18:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.788517.0<br/>@codecademy/gamut-styles@7.1.0-alpha.788517.0<br/>@codecademy/gamut-system@0.0.1-alpha.788517.0<br/>@codecademy/gamut@16.0.12-alpha.788517.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 18:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7770559ffa4564d827f874--gamut-preview.netlify.app>https://5f7770559ffa4564d827f874--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7770559ffa4564d827f874>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 20:04 UTC, kipprice commented on packages/gamut-system/.npmignore
> +node_modules
why npm ignore instead of the `files` property in package.json?

Ref: https://docs.npmjs.com/files/package.json#files

2020-10-02 20:06 UTC, kipprice commented on packages/gamut-system/README.md
> +export const {
Can we add comments detailing what these example blocks are actually doing? I find that to be a best practice with public modules

2020-10-02 20:08 UTC, kipprice commented on packages/gamut-system/docs/getting-started.md
> +    typography,
are these each optional? would be good to flag if so

2020-10-02 20:10 UTC, kipprice commented on packages/gamut-system/docs/properties.md
> +| verticalAign | vertical-align |                  |
typo

```suggestion
| verticalAlign | vertical-align |                  |
```

2020-10-02 20:11 UTC, kipprice commented on packages/gamut-system/docs/properties.md
> +- [Properties](#properties)
can you add context on whether these are the only supported properties?

2020-10-02 20:12 UTC, kipprice commented on packages/gamut-system/docs/responsive.md
> +```tsx
nit: technically could just be `ts` / `typescript`

2020-10-02 20:14 UTC, kipprice commented on packages/gamut-system/docs/variants.md
> +Using the variant API to a group and share specific configurations.
Not sure how this is supposed to be interpreted...is there an extra or missing word?

2020-10-02 20:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.6a7b6e.0<br/>@codecademy/gamut-styles@7.1.0-alpha.6a7b6e.0<br/>@codecademy/gamut-system@0.0.1-alpha.6a7b6e.0<br/>@codecademy/gamut@16.0.12-alpha.6a7b6e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 20:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f778b8928e9468ec5fa4fc7--gamut-preview.netlify.app>https://5f778b8928e9468ec5fa4fc7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f778b8928e9468ec5fa4fc7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 20:24 UTC, kipprice commented on packages/gamut-system/package.json
> +    "csstype": "3.0.3"
i think this should include typescript, unless Lerna handles it

2020-10-02 20:43 UTC, kipprice commented on packages/gamut-system/src/core/system/__tests__/system-test.ts
> +  xdescribe('base system', () => {
do we want to enable this before shipping?

2020-10-02 21:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.8f3a31.0<br/>@codecademy/gamut-styles@7.1.0-alpha.8f3a31.0<br/>@codecademy/gamut-system@0.0.1-alpha.8f3a31.0<br/>@codecademy/gamut@16.0.12-alpha.8f3a31.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 21:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7799010944b10eea586b6b--gamut-preview.netlify.app>https://5f7799010944b10eea586b6b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7799010944b10eea586b6b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-02 21:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.3d56dc.0<br/>@codecademy/gamut-styles@7.1.0-alpha.3d56dc.0<br/>@codecademy/gamut-system@0.0.1-alpha.3d56dc.0<br/>@codecademy/gamut@16.0.12-alpha.3d56dc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-02 21:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f779ef4d4a3c1115a7737a3--gamut-preview.netlify.app>https://5f779ef4d4a3c1115a7737a3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f779ef4d4a3c1115a7737a3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-04 19:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.9c90e2.0<br/>@codecademy/gamut-styles@7.1.0-alpha.9c90e2.0<br/>@codecademy/gamut-system@0.0.1-alpha.9c90e2.0<br/>@codecademy/gamut@16.0.12-alpha.9c90e2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-04 19:07 UTC, codecaaron commented on packages/gamut-system/docs/variants.md
> +Using the variant API to a group and share specific configurations.
Yeah, whoops brain died while writing this I think :)

2020-10-04 19:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7a1d5b340e1d952562744c--gamut-preview.netlify.app>https://5f7a1d5b340e1d952562744c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7a1d5b340e1d952562744c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-04 19:08 UTC, codecaaron commented on packages/gamut-system/package.json
> +    "csstype": "3.0.3"
Yeah, I'll move up CSS type to the main one since I think we'll probably want it as a dev / peer in other repos.  Sometimes its useful to isolate them so conflicts don't happen IIRC.

2020-10-04 19:11 UTC, codecaaron commented on packages/gamut-system/.npmignore
> +node_modules
Oh, hmm no reason other than the rest of our packages use npmignore.  I guess we could switch the future :)

2020-10-04 19:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7a1f973a09c2013c37b07a--gamut-preview.netlify.app>https://5f7a1f973a09c2013c37b07a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7a1f973a09c2013c37b07a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-04 19:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.f53082.0<br/>@codecademy/gamut-styles@7.1.0-alpha.f53082.0<br/>@codecademy/gamut-system@0.0.1-alpha.f53082.0<br/>@codecademy/gamut@16.0.12-alpha.f53082.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-05 14:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.fb1247.0<br/>@codecademy/gamut-styles@7.1.0-alpha.fb1247.0<br/>@codecademy/gamut-system@0.0.1-alpha.fb1247.0<br/>@codecademy/gamut@16.0.12-alpha.fb1247.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-05 14:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7b2b3bdd19731a09f351a4--gamut-preview.netlify.app>https://5f7b2b3bdd19731a09f351a4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7b2b3bdd19731a09f351a4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-05 14:45 UTC, JoshuaKGoldberg commented on packages/gamut-system/README.md
> +import { system } from '@codecademy/gamut-system';
For reference later:

```suggestion
import { HandlerProps, system } from '@codecademy/gamut-system';
```

2020-10-05 14:46 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/getting-started.md
> +Gamut system is a styled-system inpsired utility toolkit that focuses on making your design system
```suggestion
Gamut system is a styled-system inspired utility toolkit that focuses on making your design system
typesafe.
```

2020-10-05 14:46 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/getting-started.md
> +  propertyGroups: {
This was `propGroups` in the readme.

2020-10-05 14:48 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/getting-started.md
> +the correct types for your properties.
Todo for later: since this doc file is the first we look at as consumers, it'd be good to explain what these property groups are. Maybe a sentence or two with links to the more detailed docs pages?

2020-10-05 14:48 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/getting-started.md
> +Now you can use both `spacing` and `layout` props on your `<Box/>` with all of the typesafety that entails.
Todo for later: what, exactly, do you mean by that? :smile:

2020-10-05 14:50 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/properties.md
> +# Properties
I think someone reading this page as the second recommended one in the readme would most likely want to know _what a property even is_ before getting a list of the defailt ones.

* What's a property?
* How does defining it work? _(I guess maybe not this one just yet, per lack of support?)_
* How would you use it in a basic component?
* What does it mean to map from the Prop column to CSS Property?
* What's a transform?
    * What's `parseSize`?

2020-10-05 14:51 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/properties.md
> +## Spacing
You know, maybe as a followup, it'd be good to auto-generate these tables from code? Props to you for getting them set up :smile:

2020-10-05 14:54 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/responsive.md
> +export const { properties, propertyGroups } = system<{}, typeof MyTheme>();
This part of the usage confuses me. Wouldn't we want to provide the breakpoints to the `system` itself in runtime land?

2020-10-05 14:54 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/responsive.md
> +export const Apps = ({ children }) => <ThemeProvider theme={MyTheme}>{chidlren}</ThemeProvider>
```suggestion
export const Apps = ({ children }) => <ThemeProvider theme={MyTheme}>{children}</ThemeProvider>
```

2020-10-05 14:58 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/variants.md
> +const colorVariant = variants({
First of all, I love this. I think the `variants` explanation solidified in my mind _"oh yes this is a great step forward"_ a second time after the props descriptions...

Second, what do you think about making `variants` take in an API like:

```
export function variants<T extends Record<string, Variant>>(things: T): ...;
export function variants<T extends Record<string, Variant>>(key: string, things: T): ...;
```

...that way we don't get this seeming redundant `{ variants: ... }` nesting?

2020-10-05 15:00 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/customization.md
> +const config = {
Nit: Is it reasonable suggest people directly pass this object like `system({ ... });`, so they don't have to understand or use `as const`?

2020-10-05 15:01 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/customization.md
> +export const { properties }  = system<ThemeShape, typeof config>(config);
Nit: will TypeScript let us we get away with not specifying the `typeof config` manually? 

```suggestion
export const { properties } = system<ThemeShape>(config);
```

2020-10-05 15:02 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/customization.md
> +export const { properties }  = system<ThemeShape, typeof config>(config);
Same comment as the other file though: can we specify all theming information in the `system(...)` call itself, so we don't have to manually specify redundant types?

2020-10-05 15:06 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/compose.md
> +```
Would you be up for fleshing this example out and including usage examples too? I think I only understand this because you walked me through it over Zoom once or twice 😅

2020-10-05 15:07 UTC, JoshuaKGoldberg commented on packages/gamut-system/src/types/system.ts
> +};
These first two types hardcode clients into using the same amounts of breakpoints as us (base + 5). That won't be desirable for most clients, especially getting-started style users who would want only one or two on top of the base at first. Can we make these more generic, and provide defaults in our default config?

2020-10-05 15:08 UTC, JoshuaKGoldberg commented on packages/gamut-system/src/types/system.ts
> +export type ThematicScaleValue<
You know, I think we can probably simplify this if we remove some of the really strict type system guarantees.. might be worth it to make this whole shebang readable to a first-timer.

2020-10-05 15:10 UTC, JoshuaKGoldberg commented on packages/gamut-system/src/core/system/index.ts
> +  };
Are you still planning on extracting & simplifying all these? Might be a fun mob programming exercise for all of us :smile:

2020-10-05 15:13 UTC, JoshuaKGoldberg commented on packages/gamut-system/src/core/createHandler/index.ts
> +export const createHandler = <
I know you explained this to me a small number of business days ago but I've lost track of what a handler actually is... Since these aren't (yet?) documented in the markdown docs, maybe a good exercise would be to have Kip or me lead the generation of those docs? I'm still hopeful we can come to a more clear name than "handler".

2020-10-05 15:14 UTC, JoshuaKGoldberg commented on packages/gamut-system/docs/responsive.md
> +```tsx
IIRC those don't support React code by default 💩

2020-10-05 15:16 UTC, JoshuaKGoldberg commented on packages/gamut-system/src/propTemplates/directionalProperty/index.ts
> +type DirectionalProps = typeof DIRECTIONAL_PROPS;
I think it'd be good to keep the default props objects and types separated (above) from the handling logic (below). People might want to override these with their own values and it's a little confusing seeing them lumped into the same file & hardcoded.

2020-10-05 15:18 UTC, JoshuaKGoldberg commented on packages/gamut-system/README.md
> +  propGroups: { typography, spacing, layout },
I wonder, maybe it'd be easier to refer to these as `groups`? It's a little catchier and doesn't have an abbreviation. 

Maybe `groups` isn't the right word to go with, but I do really like the idea of not exporting any abbreviations in the top-level common use case API, for cleanliness & clarity...

2020-10-05 15:21 UTC, JoshuaKGoldberg requested changes
This is shaping up to be a _really_ nice, clean library. It's kind of mind blowing how after all the implementation and type system shenanigans, the end result is a clean, pure example of declaring prop groups, variants, and responsiveness. _Heck yeah_.

Left some comments around the public API (more relevant) and how it's documented (probably less relevant so far). I kinda want to set up Kip or myself to do a pairing exercise to simplify some of the `system.ts` logic and send the result as a PR against this branch... should be fun & useful!

2020-10-05 16:10 UTC, codecaaron commented on packages/gamut-system/src/types/system.ts
> +};
100% agree.  Should have left a note here that I tried to make it dynamic, but couldn't figure out a non-yuck way to make it work with the absolute length array syntax.

EG:
```ts
type ResponsiveProperty<T> = T | [T?, T?] | { base?: T, sm?: T };
type ResponsiveProperty<T> = T | [T?, T?, T?] | { base?: T, sm?: T, md?: T };
```

2020-10-05 16:15 UTC, codecaaron commented on packages/gamut-system/README.md
> +  propGroups: { typography, spacing, layout },
I waffled on the naming on this a lot, and agree it's still not perfect.  It might be worth it just to remove the `group` key altogether and have them all exist on the base object (`properties` would remain its own key to reduce destructure spam)

2020-10-05 16:16 UTC, codecaaron commented on packages/gamut-system/src/core/system/index.ts
> +  };
Yes :) and 👍  to mob session, as I've tried and failed at extracting them a couple of times.

2020-10-05 16:22 UTC, codecaaron commented on packages/gamut-system/src/types/system.ts
> +export type ThematicScaleValue<
I'm thinking of only using theme keys for `scale` configuration which should reduce the unions here by about half.  And potentially remove the ability to use arrays on the themes.

Should make this significantly lighter.

2020-10-05 17:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.495572.0<br/>@codecademy/gamut-styles@7.1.0-alpha.495572.0<br/>@codecademy/gamut-system@0.0.1-alpha.495572.0<br/>@codecademy/gamut@16.0.12-alpha.495572.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-05 17:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7b52963e2aa90b7205a3ef--gamut-preview.netlify.app>https://5f7b52963e2aa90b7205a3ef--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7b52963e2aa90b7205a3ef>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-05 18:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.185a31.0<br/>@codecademy/gamut-styles@7.1.0-alpha.185a31.0<br/>@codecademy/gamut-system@0.0.1-alpha.185a31.0<br/>@codecademy/gamut@16.0.12-alpha.185a31.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-05 18:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.cf7681.0<br/>@codecademy/gamut-styles@7.1.0-alpha.cf7681.0<br/>@codecademy/gamut-system@0.0.1-alpha.cf7681.0<br/>@codecademy/gamut@16.0.12-alpha.cf7681.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-05 18:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7b65d7fe77cf3096e88e99--gamut-preview.netlify.app>https://5f7b65d7fe77cf3096e88e99--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7b65d7fe77cf3096e88e99>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-05 18:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7b660e23e1f024293cf415--gamut-preview.netlify.app>https://5f7b660e23e1f024293cf415--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7b660e23e1f024293cf415>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-06 00:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.2469bd.0<br/>@codecademy/gamut-styles@7.1.0-alpha.2469bd.0<br/>@codecademy/gamut-system@0.0.1-alpha.2469bd.0<br/>@codecademy/gamut@16.0.12-alpha.2469bd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-06 00:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7bb4fbd97c6c75bf44f144--gamut-preview.netlify.app>https://5f7bb4fbd97c6c75bf44f144--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7bb4fbd97c6c75bf44f144>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-06 15:33 UTC, codecaaron commented on packages/gamut-system/docs/customization.md
> +const config = {
Seems reasonable to me.  This applies to `variant` as well, so I'll update all the docs to reflect that.  I'll provide a note to say you must use const in the event that you don't use it in a literal.

2020-10-06 15:48 UTC, codecaaron commented on packages/gamut-system/docs/properties.md
> +## Spacing
💯 to that, I definitely want to make the docs here more dynamic.  Having a gatsby site where we use this to help document itself would be fun.

Love it:
> _Props_ to you for getting them set up 😄

2020-10-06 15:59 UTC, codecaaron commented on packages/gamut-system/docs/responsive.md
> +export const { properties, propertyGroups } = system<{}, typeof MyTheme>();
Spoke on this yesterday in person.  The context for posterity:

Currently, the only way to configure your own breakpoints is through the theme.  These will get looked up during runtime like other scale values.

However, if you do not use a theme there is no way to change them from the defaults, which is decidedly unideal.  So we should make it possible to do this without requiring a theme.

2020-10-08 15:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.20750b.0<br/>@codecademy/gamut-styles@7.1.0-alpha.20750b.0<br/>@codecademy/gamut-system@0.0.1-alpha.20750b.0<br/>@codecademy/gamut@16.0.12-alpha.20750b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-08 15:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7f2d1c2dc97300cf788ee7--gamut-preview.netlify.app>https://5f7f2d1c2dc97300cf788ee7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7f2d1c2dc97300cf788ee7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-08 20:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f7f78d16253410dcc84de9d--gamut-preview.netlify.app>https://5f7f78d16253410dcc84de9d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f7f78d16253410dcc84de9d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-09 17:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.8ec7d3.0<br/>@codecademy/gamut-styles@7.1.0-alpha.8ec7d3.0<br/>@codecademy/gamut-system@0.0.1-alpha.8ec7d3.0<br/>@codecademy/gamut@16.0.12-alpha.8ec7d3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-09 17:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f809e64b126c34391166eb2--gamut-preview.netlify.app>https://5f809e64b126c34391166eb2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f809e64b126c34391166eb2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-09 19:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.6b1f86.0<br/>@codecademy/gamut-styles@7.1.0-alpha.6b1f86.0<br/>@codecademy/gamut-system@0.0.1-alpha.6b1f86.0<br/>@codecademy/gamut@16.0.12-alpha.6b1f86.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-09 19:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f80bb445e52c95944873ef2--gamut-preview.netlify.app>https://5f80bb445e52c95944873ef2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f80bb445e52c95944873ef2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-09 22:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f80e71ad1e6202613c0c6d9--gamut-preview.netlify.app>https://5f80e71ad1e6202613c0c6d9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f80e71ad1e6202613c0c6d9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-09 22:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.778c34.0<br/>@codecademy/gamut-styles@7.1.0-alpha.778c34.0<br/>@codecademy/gamut-system@0.0.1-alpha.778c34.0<br/>@codecademy/gamut@16.0.12-alpha.778c34.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-09 22:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.959814.0<br/>@codecademy/gamut-styles@7.1.0-alpha.959814.0<br/>@codecademy/gamut-system@0.0.1-alpha.959814.0<br/>@codecademy/gamut@16.0.12-alpha.959814.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-09 22:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f80ea9fd8f8af2ca1e2e515--gamut-preview.netlify.app>https://5f80ea9fd8f8af2ca1e2e515--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f80ea9fd8f8af2ca1e2e515>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-13 19:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f86056f4faec88c627e78e8--gamut-preview.netlify.app>https://5f86056f4faec88c627e78e8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f86056f4faec88c627e78e8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-13 19:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.61cf24.0<br/>@codecademy/gamut-styles@7.1.0-alpha.61cf24.0<br/>@codecademy/gamut-system@0.0.1-alpha.61cf24.0<br/>@codecademy/gamut@16.0.12-alpha.61cf24.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-14 16:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.118aed.0<br/>@codecademy/gamut-styles@7.1.0-alpha.118aed.0<br/>@codecademy/gamut-system@0.0.1-alpha.118aed.0<br/>@codecademy/gamut@16.0.12-alpha.118aed.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-14 16:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.fdf9ac.0<br/>@codecademy/gamut-styles@7.1.0-alpha.fdf9ac.0<br/>@codecademy/gamut-system@0.0.1-alpha.fdf9ac.0<br/>@codecademy/gamut@16.0.12-alpha.fdf9ac.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-14 16:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f872de6b747131c1ebfbd89--gamut-preview.netlify.app>https://5f872de6b747131c1ebfbd89--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f872de6b747131c1ebfbd89>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-14 16:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f872e49b747131cd3bfbb53--gamut-preview.netlify.app>https://5f872e49b747131cd3bfbb53--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f872e49b747131cd3bfbb53>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-14 17:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.ca8aca.0<br/>@codecademy/gamut-styles@7.1.0-alpha.ca8aca.0<br/>@codecademy/gamut-system@0.0.1-alpha.ca8aca.0<br/>@codecademy/gamut@16.0.12-alpha.ca8aca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-14 17:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8730883074b52feedb6de1--gamut-preview.netlify.app>https://5f8730883074b52feedb6de1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8730883074b52feedb6de1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-14 19:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.4ba43f.0<br/>@codecademy/gamut-styles@7.1.0-alpha.4ba43f.0<br/>@codecademy/gamut-system@0.0.1-alpha.4ba43f.0<br/>@codecademy/gamut@16.0.12-alpha.4ba43f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-14 19:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f874cc75515264afcc4d350--gamut-preview.netlify.app>https://5f874cc75515264afcc4d350--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f874cc75515264afcc4d350>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-15 17:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.aa837e.0<br/>@codecademy/gamut-styles@7.1.0-alpha.aa837e.0<br/>@codecademy/gamut-system@0.0.1-alpha.aa837e.0<br/>@codecademy/gamut@16.0.12-alpha.aa837e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-15 17:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8886a10eb21300e8aad67a--gamut-preview.netlify.app>https://5f8886a10eb21300e8aad67a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8886a10eb21300e8aad67a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-15 17:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.3ed38d.0<br/>@codecademy/gamut-styles@7.1.0-alpha.3ed38d.0<br/>@codecademy/gamut-system@0.0.1-alpha.3ed38d.0<br/>@codecademy/gamut@16.0.12-alpha.3ed38d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-15 17:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f888a35e3d3dd00db006878--gamut-preview.netlify.app>https://5f888a35e3d3dd00db006878--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f888a35e3d3dd00db006878>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 17:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.b95615.0<br/>@codecademy/gamut-styles@7.1.0-alpha.b95615.0<br/>@codecademy/gamut-system@0.0.1-alpha.b95615.0<br/>@codecademy/gamut@16.0.12-alpha.b95615.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 17:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8dc88655faeb0bc681fc16--gamut-preview.netlify.app>https://5f8dc88655faeb0bc681fc16--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8dc88655faeb0bc681fc16>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 20:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.c848be.0<br/>@codecademy/gamut-styles@7.1.0-alpha.c848be.0<br/>@codecademy/gamut-system@0.0.1-alpha.c848be.0<br/>@codecademy/gamut@16.0.12-alpha.c848be.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 20:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8df25f3eede52059070ba4--gamut-preview.netlify.app>https://5f8df25f3eede52059070ba4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8df25f3eede52059070ba4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 20:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.2.2-alpha.38bc07.0<br/>@codecademy/gamut-styles@7.1.0-alpha.38bc07.0<br/>@codecademy/gamut-system@0.0.1-alpha.38bc07.0<br/>@codecademy/gamut@16.0.12-alpha.38bc07.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 20:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8df5f39702bb244f693a1f--gamut-preview.netlify.app>https://5f8df5f39702bb244f693a1f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8df5f39702bb244f693a1f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 20:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.2-alpha.4d2915.0<br/>@codecademy/gamut-styles@7.1.0-alpha.4d2915.0<br/>@codecademy/gamut-system@0.0.1-alpha.4d2915.0<br/>@codecademy/gamut@16.2.4-alpha.4d2915.0<br/>@codecademy/markdown-overrides@0.3.4-alpha.4d2915.0<br/>@codecademy/styleguide@17.7.4-alpha.4d2915.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 20:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8df765486197242acbdeac--gamut-preview.netlify.app>https://5f8df765486197242acbdeac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8df765486197242acbdeac>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 21:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.2-alpha.ab005d.0<br/>@codecademy/gamut-styles@7.1.0-alpha.ab005d.0<br/>@codecademy/gamut-system@0.0.1-alpha.ab005d.0<br/>@codecademy/gamut@16.2.4-alpha.ab005d.0<br/>@codecademy/markdown-overrides@0.3.4-alpha.ab005d.0<br/>@codecademy/styleguide@17.7.4-alpha.ab005d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 21:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8e036d29b8173a314aa7ff--gamut-preview.netlify.app>https://5f8e036d29b8173a314aa7ff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8e036d29b8173a314aa7ff>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-20 22:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.4.2-alpha.8634ce.0<br/>@codecademy/gamut-styles@7.1.0-alpha.8634ce.0<br/>@codecademy/gamut-system@0.0.1-alpha.8634ce.0<br/>@codecademy/gamut@16.2.4-alpha.8634ce.0<br/>@codecademy/markdown-overrides@0.3.4-alpha.8634ce.0<br/>@codecademy/styleguide@17.7.4-alpha.8634ce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-20 22:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8f5ee6ff0dfc2fc3380b6e--gamut-preview.netlify.app>https://5f8f5ee6ff0dfc2fc3380b6e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8f5ee6ff0dfc2fc3380b6e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-26 21:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.5.0-alpha.e5e743.0<br/>@codecademy/gamut-styles@7.1.0-alpha.e5e743.0<br/>@codecademy/gamut-system@0.1.0-alpha.e5e743.0<br/>@codecademy/gamut@16.3.0-alpha.e5e743.0<br/>@codecademy/markdown-overrides@0.3.4-alpha.e5e743.0<br/>@codecademy/styleguide@17.8.0-alpha.e5e743.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-26 21:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f97409bd2f759210c843cad--gamut-preview.netlify.app>https://5f97409bd2f759210c843cad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f97409bd2f759210c843cad>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-27 20:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.7.0-alpha.dc47ef.0<br/>@codecademy/gamut-styles@7.2.0-alpha.dc47ef.0<br/>@codecademy/gamut-system@0.1.0-alpha.dc47ef.0<br/>@codecademy/gamut@16.4.0-alpha.dc47ef.0<br/>@codecademy/markdown-overrides@0.3.6-alpha.dc47ef.0<br/>@codecademy/styleguide@17.11.0-alpha.dc47ef.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-27 20:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f988371518f320088fb5af0--gamut-preview.netlify.app>https://5f988371518f320088fb5af0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f988371518f320088fb5af0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-28 14:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f997c9108f7aea47eea0090--gamut-preview.netlify.app>https://5f997c9108f7aea47eea0090--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f997c9108f7aea47eea0090>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-28 14:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.7.0-alpha.a469ca.0<br/>@codecademy/gamut-styles@7.2.0-alpha.a469ca.0<br/>@codecademy/gamut-system@0.1.0-alpha.a469ca.0<br/>@codecademy/gamut@16.4.0-alpha.a469ca.0<br/>@codecademy/markdown-overrides@0.3.6-alpha.a469ca.0<br/>@codecademy/styleguide@17.11.0-alpha.a469ca.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-28 14:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f99859a77b6d7c2cf404f45--gamut-preview.netlify.app>https://5f99859a77b6d7c2cf404f45--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f99859a77b6d7c2cf404f45>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-28 15:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.7.0-alpha.f666d7.0<br/>@codecademy/gamut-styles@7.2.0-alpha.f666d7.0<br/>@codecademy/gamut-system@0.1.0-alpha.f666d7.0<br/>@codecademy/gamut@16.4.0-alpha.f666d7.0<br/>@codecademy/markdown-overrides@0.3.6-alpha.f666d7.0<br/>@codecademy/styleguide@17.11.0-alpha.f666d7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-28 15:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f998e4b1feb6e008602eee0--gamut-preview.netlify.app>https://5f998e4b1feb6e008602eee0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f998e4b1feb6e008602eee0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-28 19:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.7.0-alpha.b4d30c.0<br/>@codecademy/gamut-styles@7.2.0-alpha.b4d30c.0<br/>@codecademy/gamut-system@0.1.0-alpha.b4d30c.0<br/>@codecademy/gamut@16.4.0-alpha.b4d30c.0<br/>@codecademy/markdown-overrides@0.3.6-alpha.b4d30c.0<br/>@codecademy/styleguide@17.11.0-alpha.b4d30c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-28 19:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f99c98e7df84436044f3c68--gamut-preview.netlify.app>https://5f99c98e7df84436044f3c68--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f99c98e7df84436044f3c68>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-29 20:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.7.0-alpha.be49e6.0<br/>@codecademy/gamut-styles@7.2.0-alpha.be49e6.0<br/>@codecademy/gamut-system@0.1.0-alpha.be49e6.0<br/>@codecademy/gamut@16.4.0-alpha.be49e6.0<br/>@codecademy/markdown-overrides@0.3.6-alpha.be49e6.0<br/>@codecademy/styleguide@17.11.0-alpha.be49e6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-29 20:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f9b23e26b325d00a22a95ce--gamut-preview.netlify.app>https://5f9b23e26b325d00a22a95ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f9b23e26b325d00a22a95ce>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-02 23:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.8.0-alpha.15f691.0<br/>@codecademy/gamut-styles@7.3.0-alpha.15f691.0<br/>@codecademy/gamut-system@0.1.0-alpha.15f691.0<br/>@codecademy/gamut@16.5.0-alpha.15f691.0<br/>@codecademy/markdown-overrides@0.3.7-alpha.15f691.0<br/>@codecademy/styleguide@17.12.0-alpha.15f691.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-02 23:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa0903c84596d0b1a4ffe03--gamut-preview.netlify.app>https://5fa0903c84596d0b1a4ffe03--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa0903c84596d0b1a4ffe03>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-02 23:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.8.0-alpha.06178f.0<br/>@codecademy/gamut-styles@7.3.0-alpha.06178f.0<br/>@codecademy/gamut-system@0.1.0-alpha.06178f.0<br/>@codecademy/gamut@16.5.0-alpha.06178f.0<br/>@codecademy/markdown-overrides@0.3.7-alpha.06178f.0<br/>@codecademy/styleguide@17.12.0-alpha.06178f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-02 23:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa0915430ca4116b3e455d5--gamut-preview.netlify.app>https://5fa0915430ca4116b3e455d5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa0915430ca4116b3e455d5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-05 17:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.8.0-alpha.2c3586.0<br/>@codecademy/gamut-styles@7.3.0-alpha.2c3586.0<br/>@codecademy/gamut-system@0.1.0-alpha.2c3586.0<br/>@codecademy/gamut@16.5.0-alpha.2c3586.0<br/>@codecademy/markdown-overrides@0.3.7-alpha.2c3586.0<br/>@codecademy/styleguide@17.12.0-alpha.2c3586.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-05 17:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa43900334be4012a6e3846--gamut-preview.netlify.app>https://5fa43900334be4012a6e3846--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa43900334be4012a6e3846>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-05 18:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.8.0-alpha.da1327.0<br/>@codecademy/gamut-styles@7.3.0-alpha.da1327.0<br/>@codecademy/gamut-system@0.1.0-alpha.da1327.0<br/>@codecademy/gamut@16.5.0-alpha.da1327.0<br/>@codecademy/markdown-overrides@0.3.7-alpha.da1327.0<br/>@codecademy/styleguide@17.12.0-alpha.da1327.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-05 18:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa4460d23b8390c398dec47--gamut-preview.netlify.app>https://5fa4460d23b8390c398dec47--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa4460d23b8390c398dec47>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-06 15:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@5.1.0-alpha.dc1bc6.0<br/>@codecademy/gamut-styles@7.3.0-alpha.dc1bc6.0<br/>@codecademy/gamut-system@0.1.0-alpha.dc1bc6.0<br/>@codecademy/gamut@17.1.0-alpha.dc1bc6.0<br/>@codecademy/markdown-overrides@0.3.7-alpha.dc1bc6.0<br/>@codecademy/styleguide@18.1.0-alpha.dc1bc6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-11-06 15:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5fa56bd41f73ab014051b106--gamut-preview.netlify.app>https://5fa56bd41f73ab014051b106--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5fa56bd41f73ab014051b106>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-11-10 18:39 UTC, closed without merging