fix: Byline aria-label a11y bug
Codecademy/client-modules pull request #955
Opened 2020-09-10 19:45 UTC by rogervera

## Overview
There's an a11y bug with the Byline (used within the Testimonial) discovered during a Test.IO A11y test that was run on the Back to School Campaign Page.

### The Bug: https://codecademy.test.io/products/9763/test_cycles/68462/bugs

> **Steps**
> 
> 1. Open https://codecademy.com/student-center
> 2. Tab to Tyler V. quote

> - Expected result: I expect to hear the "Tyler V. Student.... "
> - Actual result:  I hear "First name Last name Occupation..."

> The screen reader read the aria-label in this
> `<span aria-label="First Name">Tyler</span>`
> 

**Video of Bug:** https://uploads.test.io/uploads/bug_attachment/file/3732204/cc1cde2f-eabf-40b6-a610-0bb5db697286.mp4

<img width="500" alt="Screen Shot 2020-09-10 at 3 37 22 PM" src="https://user-images.githubusercontent.com/17210163/92792846-e400b500-f37b-11ea-9229-230928e09d5e.png">

### My fix:
Append the value of `firstName`, `lastName`, `occupation`, and `company` to their respective `aria-labels`.

### PR Checklist

- [ ] Related to Abstract designs:
- [ ] Related to JIRA ticket: [REACH-247](https://codecademy.atlassian.net/browse/REACH-247)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2020-09-10 19:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.0.3-alpha.22e394.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 19:59 UTC, rogervera commented
Confirmed to work locally. See updated voice over details now:
<img width="716" alt="Screen Shot 2020-09-10 at 3 57 56 PM" src="https://user-images.githubusercontent.com/17210163/92795697-933e8b80-f37e-11ea-81e6-3f40e77af30b.png">

2020-09-10 20:38 UTC, JoshuaKGoldberg requested changes

2020-09-10 20:38 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/brand/Byline/index.tsx
> +      <span aria-label={`First Name: ${firstName}`}>{firstName}</span>
We talked briefly over Slack: I've seen reports where the _opposite_ of what the ticket requested happened; some screenreaders narrated _both_ the label _and_ the text.

How about getting rid of the label altogether? It's not really necessary for understanding the page, right?

cc @jcenglish who might know more.

2020-09-10 20:40 UTC, dougyd92 reviewed
Do we need aria-labels at all here? i.e. if we get rid of them altogether, would the screen reader correctly read out "John Smith, Engineer at E Corp"?

My understanding is that aria-labels are used to describe visual context that is otherwise unlabelled, such as an 'X' button to close a dialog box. But in this case, we already have the labels in the text itself.

https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html

2020-09-10 21:08 UTC, rogervera commented on packages/gamut-labs/src/brand/Byline/index.tsx
> +      <span aria-label={`First Name: ${firstName}`}>{firstName}</span>
@JoshuaKGoldberg, @dougyd92

Thanks for comments. Based off [ARIA14: Using aria-label to provide an invisible label where a visible label cannot be used](https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html) and looking at https://www.w3.org/TR/wai-aria-1.1/#aria-label:
> It provides the user with a recognizable name of the object. 

I agree that given the context it's in, the labels are redundant. Will go with no aria labels

2020-09-10 21:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.0.3-alpha.1cb61e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-10 21:32 UTC, rogervera commented
Update: With no aria-labels quotes read as such:


**Reads:** 
> Lacey Bathala Data Anaylst at Mircosoft
<img width="928" alt="Screen Shot 2020-09-10 at 5 30 08 PM" src="https://user-images.githubusercontent.com/17210163/92810276-693f9600-f38b-11ea-92a4-039e695647c4.png">

**Reads:**
> Tyler V. Student
<img width="1270" alt="Screen Shot 2020-09-10 at 5 28 46 PM" src="https://user-images.githubusercontent.com/17210163/92810280-69d82c80-f38b-11ea-8a57-135bff8a44a1.png">

2020-09-10 22:04 UTC, JoshuaKGoldberg approved these changes
Swell, thanks!

2020-09-11 12:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f5b66e6556a151f06c06c10--gamut-preview.netlify.app>https://5f5b66e6556a151f06c06c10--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f5b66e6556a151f06c06c10>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-11 12:03 UTC, merged