fix(GridForm): only set aria-live on first error component
Codecademy/client-modules pull request #960
Opened 2020-09-18 17:43 UTC by ahmed-abdallah

## Overview

### PR Checklist

- [ ] Related to Abstract designs:
- [ ] Related to JIRA ticket: A11Y-434
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description

2020-09-18 17:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/client-modules?pullRequest=960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/client-modules?pullRequest=960) before we can accept your contribution.<br/><hr/>**Ahmed Abdallah** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/client-modules?pullRequest=960) it.</sub>

2020-09-18 18:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.0.4-alpha.551a06.0<br/>@codecademy/gamut@16.0.5-alpha.551a06.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-18 18:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.1.1-alpha.392f78.0<br/>@codecademy/gamut@16.0.5-alpha.392f78.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-18 18:50 UTC, ahmed-abdallah commented on packages/gamut/src/GridForm/index.tsx
> +          hasFirstError = hasFirstError || isFirstError;
I'm not wild about this implementation as it seems a little roundabout to keep track of error states this way. Open to suggestions on a better way to make `FormError` aware of errors in other `GridFormInputGroup` blocks.

2020-09-18 19:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f650adc44c5b724688a9b52--gamut-preview.netlify.app>https://5f650adc44c5b724688a9b52--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f650adc44c5b724688a9b52>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-18 22:29 UTC, JoshuaKGoldberg requested changes
Generally I think the approach is pretty good, and the added tests are a nice tough 😄. Just requesting changes on the `FormError`/`aria-live` bits.

👏 yay, your first client-modules PR!

2020-09-18 22:29 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/FormError.tsx
> +  isFirstError?: boolean;
It's not really the responsibility of this `FormError` component to know that it's a particular first error; that logic really just lives in the parent (in this case, `GridFormInputGroup`). Can this be passed an `aria-live` by its parent instead?

2020-09-18 22:29 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/index.tsx
> +          hasFirstError = hasFirstError || isFirstError;
Heh, I think it's reasonable to keep the `hasFirstError` as a `let` here. Maybe semantically this isn't _precisely_ a super duper perfect application of functional programming paradigms, but it's readable and really the logic we need. 😄 

Perhaps a slightly more clear variable name would be `pastFirstError`? Definitely not a blocker IMO.

2020-09-18 22:29 UTC, JoshuaKGoldberg commented on packages/gamut/src/GridForm/index.tsx
> +          hasFirstError = hasFirstError || isFirstError;
Nit: I think you could get rid of the comments added. The code is pretty self-explanatory.

2020-09-18 22:58 UTC, ahmed-abdallah commented on packages/gamut/src/Form/FormError.tsx
> +  isFirstError?: boolean;
Yeah that makes way more sense! Easy to change

2020-09-18 23:08 UTC, JoshuaKGoldberg commented on packages/gamut/src/Form/__tests__/FormError-test.tsx
> +import { shallow } from 'enzyme';
Oh I almost missed this -- just a heads up, we've been moving to `mount` instead of `shallow` for a bit. We had a whole discussion at https://www.notion.so/codecademy/Updated-React-Redux-and-Jest-Preferences-207154440e25476b93d4f41ad48728e6 but the tl;dr is that Enzyme is getting more and more stale over time -particularly `shallow` mounting-, so `mount` will make it easier to move to RTL. (and also the general philosophical preference of more accurately simulating the component)

2020-09-18 23:27 UTC, ahmed-abdallah commented on packages/gamut/src/Form/__tests__/FormError-test.tsx
> +import { shallow } from 'enzyme';
Interesting! The `FormError` tests are going away but this is good to know!

2020-09-18 23:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.1.1-alpha.bf16a7.0<br/>@codecademy/gamut@16.0.5-alpha.bf16a7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-21 14:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f68bbae3920b8189b704173--gamut-preview.netlify.app>https://5f68bbae3920b8189b704173--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f68bbae3920b8189b704173>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-21 23:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-labs@4.1.2-alpha.3a3c9f.0<br/>@codecademy/gamut@16.0.5-alpha.3a3c9f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-22 13:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f69fbea451630332cfcec37--gamut-preview.netlify.app>https://5f69fbea451630332cfcec37--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f69fbea451630332cfcec37>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-22 15:43 UTC, JoshuaKGoldberg approved these changes
Looks great, thanks! Yay accessibility!

2020-09-22 16:04 UTC, merged