[REACH-217] Enable tracking in the blog using a generalized, shared library.
Codecademy/client-modules pull request #974
Opened 2020-09-25 17:32 UTC by judahtanthony

## Overview

### PR Checklist

- [ ] Related to Abstract designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### Description

2020-09-25 17:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/client-modules?pullRequest=974) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/client-modules?pullRequest=974) before we can accept your contribution.<br/><hr/>**Judah Anthony** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/client-modules?pullRequest=974) it.</sub>

2020-09-25 17:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.0.2-alpha.746cae.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-09-25 17:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f6e2a877d2f140127d13e05--gamut-preview.netlify.app>https://5f6e2a877d2f140127d13e05--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f6e2a877d2f140127d13e05>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-09-25 19:50 UTC, JoshuaKGoldberg requested changes
Love the drive to get this in! But I think we should be intentional about how it looks.

2020-09-25 19:50 UTC, JoshuaKGoldberg commented on packages/tracking/src/beacon.ts
> +import request from 'superagent';
@judahtanthony I have a strong professional dislike for superagent:

* It spams our NewRelic prod JS errors log with non-actionable _"the client disconnected"_ style errors
* I _very_ strongly disagree with its assumption that non-success status codes should throw

Can we have a larger discussion on what we want the standard requests to look like across our web apps, if there is to be a consensus? The monolith's code now is very much a production of years-gone-by, not any intentional big decisions the last couple years at least.

2020-09-25 19:54 UTC, JoshuaKGoldberg commented on packages/tracking/src/beacon.ts
> +import request from 'superagent';
(this is a general feedback for all the APIs here; superagent is just my most pressing emotional response 😄 )

2020-09-25 21:09 UTC, hmafzal commented on packages/tracking/src/types.ts
> +export type EventDataTypes = {
I don't think these types should go into something public facing like client-modules.

Also, i think they're very specific to the monolith. Other consumers will define their own types for what they are sending to our event libraries

2020-09-25 21:24 UTC, dougyd92 commented on packages/tracking/src/types.ts
> +export type EventDataTypes = {
I disagree. Some of these may be specific to the monolith, but others like User Visit are going to be the same everywhere. It would be better to have one source of truth so if we add a new field to the event we can just change it here.

2020-09-25 21:26 UTC, neilzo commented on packages/tracking/src/beacon.ts
> +import request from 'superagent';
One other downside I found while working with superagent on Codecademy-Go: it uses `XHR` under the hood and not `fetch`. This makes it incompatible with our commonly used `fetchMock` [library](https://github.com/wheresrhys/fetch-mock) and is difficult to test/mock in general.

2020-09-25 21:40 UTC, neilzo commented on packages/tracking/src/api.ts
> +    Accept: 'application/json',
Common request string (`'application/json'`, `'same-origin'`) could be more maintainable as constants.

2020-09-25 21:40 UTC, neilzo commented on packages/tracking/src/api.ts
> +import Uri from 'jsuri';
Is the `jsuri` library necessary here? I see some niceties like `setPath` and `setQuery` but I'm doubting if those convenience methods are worth adding an additional specialized package.

`jsuri` isn't too big but could save 1.8kb minified + gzipped: https://bundlephobia.com/result?p=jsuri@1.3.1

2020-09-28 19:22 UTC, judahtanthony commented on packages/tracking/src/types.ts
> +export type EventDataTypes = {
I gotta agree with Doug on this.  I agree this is definitely not useful for open source, but our tracking api is not useful for open source, we just happen to be leveraging our client_modules repo.  The primary goal of this unification is to keep our various systems in alignment, and I think events and their properties should be included in that.

2020-09-28 19:27 UTC, judahtanthony commented on packages/tracking/src/api.ts
> +import Uri from 'jsuri';
This is also used in the superagent-auth file.  I can just reimplment URL parsing, but it would open us up to bugs and maintenance.  I'm open to you insisting that is worth it, but I didn't deem it worth it when I was porting this.

2020-09-28 19:32 UTC, judahtanthony commented on packages/tracking/src/api.ts
> +    Accept: 'application/json',
I don't see any precedence for turning `application/json` into a constant.  I'm not sure where that constant would belong and how it should be referenced.  I would think abstracting API access, so clients don't have to think about setting Accept headers, would be re-use enough.

2020-09-28 19:34 UTC, judahtanthony commented on packages/tracking/src/beacon.ts
> +import request from 'superagent';
I can port this to fetch.  When you are talking about this larger conversation, are you talking about API design, or just the client library API?  Should this conversation happen here or in an RFC?

2020-09-29 13:47 UTC, hmafzal commented on packages/tracking/src/types.ts
> +export type EventDataTypes = {
The types here map directly to the tables we have in redshift. I really don't think we should be exposing those in a public repo. Are we meaning to open source the logic to send events to our specific endpoints? When would an external consumer of something like client-modules (which really anyone could install) need or care about this specific library?

I do agree that they can belong in an external library from the monolith so that the types can be shared for tables which are utilized by multiple clients.

I think a better avenue for this would be creating a private TS repo within the codecademy-engineering org, which publishes a private npm package. In the future, we'll likely want to set up a monorepo similar to client-modules but for private business logic.

I think this change could also benefit from an RFC to work out some of the things we want to do and come to a consensus on how we want to share this code. I think others may have opinions here but to me, an RFC is a better avenue for discussion on those than an implementation through a PR

2020-09-29 13:59 UTC, neilzo commented on packages/tracking/src/api.ts
> +    Accept: 'application/json',
Yeah, good point. It might not be too useful, especially since this is already abstracting away the API access.

2020-09-29 14:18 UTC, neilzo commented on packages/tracking/src/types.ts
> +export type EventDataTypes = {
While I agree the current types are not as useful for open source, there is precedence in Client Modules for Codecademy specific use cases (Gamut Labs). If someone wanted to fork this repo for event tracking, they could use the EventDataTypes as templates/examples.

2020-09-30 18:24 UTC, judahtanthony commented on packages/tracking/src/api.ts
> +import Uri from 'jsuri';
That's a good idea.  And others have already objected to our use of superagent, so this section of code will have to be rewritten anyway.

2020-09-30 18:58 UTC, JoshuaKGoldberg commented on packages/tracking/src/beacon.ts
> +import request from 'superagent';
Both 😄 . RFC?

2020-10-07 17:26 UTC, judahtanthony commented
We have ready 100% support for beacon in our supported browsers, so we can simplify the port.

2020-10-07 17:34 UTC, judahtanthony commented
Remove superagent

2020-10-15 21:13 UTC, jakemhiller commented on packages/tracking/src/api.ts
> +import Uri from 'jsuri';
just to add to this, a lot of the features in JSURI are now possible natively using the `URL` interface https://developer.mozilla.org/en-US/docs/Web/API/URL

2020-10-16 14:21 UTC, judahtanthony commented on packages/tracking/src/api.ts
> +import Uri from 'jsuri';
Yeah, that with https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams should be all I need.

2020-10-19 19:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.0.2-alpha.4d84a9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 20:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8df0d04861972773cbd8a5--gamut-preview.netlify.app>https://5f8df0d04861972773cbd8a5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8df0d04861972773cbd8a5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 20:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.0.2-alpha.2651d7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 20:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8df1f73eede52059070ad6--gamut-preview.netlify.app>https://5f8df1f73eede52059070ad6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8df1f73eede52059070ad6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 20:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.0.2-alpha.0e344d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 20:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8df2c8a799d7297726d25e--gamut-preview.netlify.app>https://5f8df2c8a799d7297726d25e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8df2c8a799d7297726d25e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 20:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.0.2-alpha.0d56d6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 20:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8df3ce29b81728b74aa603--gamut-preview.netlify.app>https://5f8df3ce29b81728b74aa603--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8df3ce29b81728b74aa603>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 22:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.0.2-alpha.b4ea6f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-19 22:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f8e13fde65245010e01f790--gamut-preview.netlify.app>https://5f8e13fde65245010e01f790--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f8e13fde65245010e01f790>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-19 22:58 UTC, judahtanthony commented
@JoshuaKGoldberg  & @dougyd92  I think I have addressed all your concerns.  Let me know if I missed anything.

2020-10-21 15:12 UTC, jakemhiller commented on packages/tracking/package.json
> +  "dependencies": {
these look like `devdependencies`

2020-10-21 15:17 UTC, judahtanthony commented on packages/tracking/package.json
> +  "dependencies": {
I'll try moving them, and see if it works.

2020-10-21 15:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.1.0-alpha.0668a1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-21 15:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f90557daf85dc0cd03640dc--gamut-preview.netlify.app>https://5f90557daf85dc0cd03640dc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f90557daf85dc0cd03640dc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-21 15:44 UTC, JoshuaKGoldberg requested changes
I think we might still have some discussion around what the API looks like, if you want?

2020-10-21 15:44 UTC, JoshuaKGoldberg commented on yarn.lock
> +  version "2.3.0"
We should probably not have duplicate `babel-preset-codecademy`s floating around the codebase... are you up for bumping everyone's version? LMK if you don't or need help, I can assist!

Ideally, there would be basically no `yarn.lock` changes for things from Babel, Webpack, etc., as we should be using the same versions everywhere.

2020-10-21 15:44 UTC, JoshuaKGoldberg commented on packages/tracking/src/track.ts
> +  constructor(api: API, verbose = false) {
Surfacing what we talked about on Slack: I'm not against classes in general, but this kind of API seems extra:

```js
new Track(...).event(...)
```

IMO something smaller would be more ideal:

```js
event(..., ...)
```

Errata: I love the idea of injecting an `api.beacon` kind of deal, such as though constructor dependency injection, but since we don't have DI set up through the app, it won't be too useful.

2020-10-21 15:44 UTC, JoshuaKGoldberg commented on packages/tracking/src/track.ts
> +  async event<
Is there a reason these are `async`? Ideally I think they'd be fire-and-forget to not block anything on them, right?

2020-10-21 15:44 UTC, JoshuaKGoldberg commented on packages/tracking/src/track.ts
> +    if (!userData) (userData as any) = {};
This line should no longer be necessary, now that TypeScript enforces `userData` existing.

```suggestion
```

2020-10-21 15:53 UTC, JoshuaKGoldberg commented on packages/tracking/src/api.ts
> +export class API {
Oh this wasn't in the RFC; I'm surprised to see it here. I thought from the RFC that the shared library wouldn't have the responsibility for fetching user data. Should we talk about this?

2020-10-21 17:44 UTC, judahtanthony commented on packages/tracking/src/api.ts
> +export class API {
The RFC didn't explicitly discuss this, but the example code had a call to fetchUser.  Ultimately, the tracking needs an auth code, so I see this as the beginning of a user library or a monolith api client.  I'm open to talking about it.  Do you want to have that discussion here or in "person"?

2020-10-21 17:53 UTC, judahtanthony commented on packages/tracking/src/track.ts
> +  async event<
You can still "fire-and-forget" async functions as long as you don't "await" on them.  async is just nice syntactic sugar because there could be a chain of async calls that need to resolve (get the user, then track the event).

2020-10-21 17:56 UTC, judahtanthony commented on yarn.lock
> +  version "2.3.0"
Yeah,  I would love your help.  Wanna pair on it?

2020-10-21 18:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.1.0-alpha.8ceb37.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-21 18:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f9077d9b4acb6010d2465c7--gamut-preview.netlify.app>https://5f9077d9b4acb6010d2465c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f9077d9b4acb6010d2465c7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-21 20:11 UTC, JoshuaKGoldberg commented on packages/tracking/src/api.ts
> +export class API {
We should probably set up a Zoom meeting yeah :)

2020-10-21 20:11 UTC, JoshuaKGoldberg commented on packages/tracking/src/track.ts
> +  async event<
Indeed, this will just be problematic when we enable https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/no-floating-promises.ts

2020-10-21 22:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.1.0-alpha.c078c6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-21 23:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f90bd75d6399600a5db759f--gamut-preview.netlify.app>https://5f90bd75d6399600a5db759f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f90bd75d6399600a5db759f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-22 18:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.1.0-alpha.fb2694.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-22 18:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f91cb758f280417f0118dd8--gamut-preview.netlify.app>https://5f91cb758f280417f0118dd8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f91cb758f280417f0118dd8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-22 20:13 UTC, JoshuaKGoldberg commented on packages/tracking/package.json
> +    "babel-preset-codecademy": "^2.3.0",
Recapping comments from our pairing: these are the versions that are causing seismic `yarn.lock` shifts. If you set them to the same as the other packages and `yarn`, `yarn.lock` should go back to being less increased.

If this gives you pain / you don't have time for these trivial pursuits, it's already in my medium-term goals to get automatic dependency bumps going more smoothly so I can take this off your plate. 😄

2020-10-22 20:14 UTC, JoshuaKGoldberg commented on packages/tracking/src/api.ts
> +export class API {
Recapping from pairing today in web plat office hours: `get` and `post` are nice but we don't quite need them yet. We came up with a much more trimmed down architecture proposal that doesn't have the kinds of semaphores making this a little bigger:

<details>
<summary>code snippet</summary>
<pre>
<code>
// monolith/author
// beacon
  // take in api base url
  // and user auth
  // formalize the data sent there (Record<string, BasicStringable>)

// createTracker(baseUrl, user.authToken)
export const createTracker = (baseUrl: string, authToken: string) => {
  const endpoint = `${baseUrl}/events/blah`; // createEndpoint(baseUrl)
  
  const beacon = async (data: any /* your thing */) => {
      // ...move into track? prob keep separate
  }

  return {
    event: <
      Category extends keyof EventDataTypes,
      Event extends keyof EventDataTypes[Category],
      Data extends EventDataTypes[Category][Event]
    >(data: Data) => {
      // ...
      beacon(/* ... */)
    }
  };
}

// static-sites/blog
// getcurrentuser (fetch)
  // takes in auth token  / cookie details

export const getUser = async (baseUrl: string, cookie: string) => {
  // ...send fetch to users/web
  const response = await fetch(`${baseUrl}/users/web`, { cookie });
  return await response.json();
}

//

const wat = () => {
  let dataPromise;

  return async () => {
    if (!dataPromise) {
      dataPromise = fetchData();
    }

    return await dataPromise;
  }
}
</code>
</pre>
</details>

2020-10-23 14:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/tracking@0.1.0-alpha.c57d82.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 14:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f92e5ccc5976b014f2adb2c--gamut-preview.netlify.app>https://5f92e5ccc5976b014f2adb2c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f92e5ccc5976b014f2adb2c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 14:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.7.3-alpha.05b465.0<br/>@codecademy/tracking@0.1.0-alpha.05b465.0<br/>@codecademy/webpack-config@5.0.7-alpha.05b465.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 14:44 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f92ec34a084eabe7baecdac--gamut-preview.netlify.app>https://5f92ec34a084eabe7baecdac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f92ec34a084eabe7baecdac>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 14:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.7.3-alpha.8bc045.0<br/>@codecademy/tracking@0.1.0-alpha.8bc045.0<br/>@codecademy/webpack-config@5.0.7-alpha.8bc045.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 14:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f92edf8ed336600f1cdb7ae--gamut-preview.netlify.app>https://5f92edf8ed336600f1cdb7ae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f92edf8ed336600f1cdb7ae>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 15:08 UTC, JoshuaKGoldberg commented on packages/styleguide/package.json
> +    "@babel/cli": "^7.11.6",
@jakemhiller did you have opinions on using or not using `^` for these? I personally don't mind either way since we have lockfiles.

2020-10-23 15:24 UTC, JoshuaKGoldberg approved these changes
@judahtanthony this is looking wonderful! Thanks for taking the time to work with me & follow up on getting this nice and lean.

I left a bunch of fun comments but IMO none are blocking (unless someone else has a preference on allowing `^` versions). You probably will want someone from Conversion to sign off too, I'd guess?

2020-10-23 15:24 UTC, JoshuaKGoldberg commented on packages/tracking/src/user.spec.ts
> +    expect(fetch.mock.calls[0][1]!.credentials).toBe('include');
Nit: you're testing very precisely here, which is nice, but I don't think we need to worry too much about it making a lot of extra calls. What do you think about switching to something like this?

```suggestion
    expect(fetch).toHaveBeenLastCalledWith(`${apiBaseUrl}/users/web`, {
      credentials: 'include',
      method: 'GET',
    });
```

2020-10-23 15:24 UTC, JoshuaKGoldberg commented on packages/tracking/src/user.spec.ts
> +import fetch from 'jest-fetch-mock';
We use `fetch-mock` in the monolith. Is there an advantage to using this new one?

I'd err towards standardizing if possible, but it's not a blocker IMO.

2020-10-23 15:24 UTC, JoshuaKGoldberg commented on packages/tracking/src/user.spec.ts
> +afterAll(() => fetch.disableMocks());
Each file is its own little Jest world, so you shouldn't need to do this, I think?

```suggestion
```

2020-10-23 15:24 UTC, JoshuaKGoldberg commented on packages/tracking/src/user.spec.ts
> +};
Nit: you could probably get rid of a bunch of these fields if you wanted to 😄 .

2020-10-23 15:24 UTC, JoshuaKGoldberg commented on packages/tracking/src/track.ts
> +      event: event as string,
Aha! I was wondering if you were going to hit this wall 😄  how irritating was this "event isn't assignable to string" error to get in dev?

```
Type 'Event' is not assignable to type 'string'.
  Type 'keyof EventDataTypes[Category]' is not assignable to type 'string'.
    Type 'string | number | symbol' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.ts(2322)
```

For visibility, the reason why this is coming up is that the `keyof` operator used above in `Event extends keyof EventDataTypes[Category]` returns a `string | number | symbol`. You can tell TypeScript you _only_ want the string keys of the object _(which is technically more correct & true)_:

```ts
Event extends string & keyof EventDataTypes[Category],
```

...and then you won't need the cast 😄 

```suggestion
      event,
```

🧙 ✨

2020-10-23 15:29 UTC, jakemhiller commented on packages/styleguide/package.json
> +    "@babel/cli": "^7.11.6",
probably prefer the `^` with babel stuff actually, since the changes are rarely breaking and we're going to be upgrading everything for the webpack 5 update

2020-10-23 15:42 UTC, JoshuaKGoldberg commented on yarn.lock
> +"@babel/cli@^7.11.6":
I can tackle these next if this is giving you pain - I don't want to keep blocking on something silly like this...

2020-10-23 17:07 UTC, judahtanthony commented on packages/tracking/src/user.spec.ts
> +    expect(fetch.mock.calls[0][1]!.credentials).toBe('include');
There are some internal things like the headers, that I don't really want to check for.  In a way, I'm actually trying to make this a looser check.  Is there a way to test for a partial object (like `{ credentials, method }`?

2020-10-23 17:12 UTC, judahtanthony commented on packages/tracking/src/user.spec.ts
> +import fetch from 'jest-fetch-mock';
On https://www.npmjs.com/package/fetch-mock it recommended `fetch-mock-jest`; however, that was not TS compatible, so I found a similar package that had TS support and a decent number of downloads.

2020-10-23 17:18 UTC, judahtanthony commented on packages/tracking/src/user.spec.ts
> +afterAll(() => fetch.disableMocks());
I remove the disable one, but I found that I needed `afterEach(() => jest.resetAllMocks());` in the other test, so I think I would like to keep the resetMocks just in case.

2020-10-23 17:21 UTC, judahtanthony commented on packages/tracking/src/user.spec.ts
> +};
Good call.  Probably best to not make any implicit promises to our future selves.

2020-10-23 17:24 UTC, judahtanthony commented on packages/tracking/src/track.ts
> +      event: event as string,
OMG.  Thank you.

2020-10-23 17:31 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.7.3-alpha.2f0b22.0<br/>@codecademy/tracking@0.1.0-alpha.2f0b22.0<br/>@codecademy/webpack-config@5.0.7-alpha.2f0b22.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 17:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f9313a172e1520d18c9a1b1--gamut-preview.netlify.app>https://5f9313a172e1520d18c9a1b1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f9313a172e1520d18c9a1b1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 17:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.8.0-alpha.cbbc9e.0<br/>@codecademy/tracking@0.1.0-alpha.cbbc9e.0<br/>@codecademy/webpack-config@5.1.0-alpha.cbbc9e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 17:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f93155a85b2891fbce5220a--gamut-preview.netlify.app>https://5f93155a85b2891fbce5220a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f93155a85b2891fbce5220a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 17:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.8.0-alpha.472eab.0<br/>@codecademy/tracking@0.1.0-alpha.472eab.0<br/>@codecademy/webpack-config@5.1.0-alpha.472eab.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 17:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f93195285b289285ee51fa9--gamut-preview.netlify.app>https://5f93195285b289285ee51fa9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f93195285b289285ee51fa9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 18:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.8.0-alpha.bce4cb.0<br/>@codecademy/tracking@0.1.0-alpha.bce4cb.0<br/>@codecademy/webpack-config@5.1.0-alpha.bce4cb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 18:10 UTC, JoshuaKGoldberg commented on packages/tracking/src/user.spec.ts
> +    expect(fetch.mock.calls[0][1]!.credentials).toBe('include');
`toMatchObject`, maybe? https://jestjs.io/docs/en/expect

2020-10-23 18:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f931ca94b834717e198a9e6--gamut-preview.netlify.app>https://5f931ca94b834717e198a9e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f931ca94b834717e198a9e6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 18:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.8.0-alpha.3695f2.0<br/>@codecademy/tracking@0.1.0-alpha.3695f2.0<br/>@codecademy/webpack-config@5.1.0-alpha.3695f2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 18:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f9322d70e058d2c8e8b23fc--gamut-preview.netlify.app>https://5f9322d70e058d2c8e8b23fc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f9322d70e058d2c8e8b23fc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 18:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.8.0-alpha.3a8b9e.0<br/>@codecademy/tracking@0.1.0-alpha.3a8b9e.0<br/>@codecademy/webpack-config@5.1.0-alpha.3a8b9e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 18:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://5f932570c7fa31253011a79f--gamut-preview.netlify.app>https://5f932570c7fa31253011a79f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/5f932570c7fa31253011a79f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2020-10-23 18:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@17.8.0-alpha.cd5f3c.0<br/>@codecademy/tracking@0.1.0-alpha.cd5f3c.0<br/>@codecademy/webpack-config@5.1.0-alpha.cd5f3c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-23 18:57 UTC, merged