feat(Icon) Add Gripper and Expand icons for Portfolio project UI
Codecademy/client-modules pull request #978
Opened 2020-10-01 14:32 UTC by Kooshaba

Ticket: [LX-4196](https://codecademy.atlassian.net/browse/LX-4196)
Design: https://www.figma.com/file/Mmoo9FiPHdfGbfODDr0Ydh/Portfolio-Projects?node-id=1732%3A1374

2020-10-01 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/client-modules?pullRequest=978) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/client-modules?pullRequest=978) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/client-modules?pullRequest=978) it.</sub>

2020-10-01 14:49 UTC, JoshuaKGoldberg requested changes
All of our existing icons have `viewBox="0 0 24 24"`. These should also be, I think.

2020-10-01 15:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@3.8.1-alpha.010a77.0<br/>@codecademy/gamut-labs@4.2.5-alpha.010a77.0<br/>@codecademy/gamut@16.0.15-alpha.010a77.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2020-10-01 15:28 UTC, JoshuaKGoldberg requested changes
We chatted a bit on Slack: the Expand icon should be scaled a bit so it fits its icon area. The Gripper really isn't a square so let's try out a non-square viewport for it? I couldn't find any breakages in a `yarn start` locally. 🚀 

fyi @codecaaron

2020-10-01 18:00 UTC, casey-speer commented on packages/gamut-icons/src/svg/gripper-icon.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Curious if the gripper glyph is something we'll be reusing or if it's more of a one-off that could live alongside the kanban board — what do you think @JoshuaKGoldberg @Kooshaba ?

2020-10-01 18:57 UTC, JoshuaKGoldberg commented on packages/gamut-icons/src/svg/gripper-icon.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
I'll defer to design on this one.

2020-10-02 19:28 UTC, codecaaron commented
Is there a reason we are not using `FullscreenIcon` for the expand?

2020-10-02 19:35 UTC, codecaaron commented on packages/gamut-icons/src/svg/expand-icon.svg
> +</svg>
Isn't this covered by `FullscreenIcon`?

2020-10-19 17:01 UTC, codecaaron commented
@Kooshaba are we good to close this per our conversation about the other icons available?

2020-10-28 19:12 UTC, codecaaron commented
@Kooshaba closing this in favor of current solution.

2020-10-28 19:12 UTC, closed without merging